:PROPERTIES:
:ID:       D18EFC22-62B7-47D0-9167-32DA204B845C
:END:
#+title: Pivot Announcement
* A Modest But Real Pivot For The Book In Question

Apparently This Whole Talk To Customers Thing Is a Good Idea?

tl;dr -- I'm changing the name of my book!

The (new) provisional title is:

<insert photo>

How To
+Survive+
+Manage+
+Ignore+
Partner With Stakeholders:
A Guidebook For Engineers

The old (provisional) title was:

Tech Investments, Not Tech Debt

How To Make Time For Engineering Work That Matters

** Why The Change?

Since the moment I started writing, I've been talking about how to establish a high-trust, effective partnership with stakeholders, including all of:

 - Tactics for building trust and rapport

 - Understanding how value is created in a business

 - Breaking work down to offer meaningful increments

 - How to advocate effectively

 - How to push back without creating bad will

I've just been getting into all those topics through the *lens* of technical investments.

But the more that I wrote, the more that it felt like the overall story I was telling was broader.

I also realized, as I talked with more engineers, and dug into early beta reading feedback, that I was hearing engineers name "working with stakeholders" as a core challenge of their jobs -- and that "tech debt" was (rightfully!) a more minor concern.

(To be clear, I still believe that *Technical Investments* are a central responsibility of an engineering team... but the *problem* that they help solve is a part of working effectively with stakeholders)

This change will necessitate some restructuring of what I've written so far.

In order to fully focus on that restructuring, I'm *not* going to be sharing a full-sized post this week.

But I expect to be back very soon, sharing sprawlingly long mixtures of abstract thinking, dramatic reenactments of everyday engineering life and cheerful abuse of footnotes.

Until then, I will add a pair of teasers.

** Teaser 1: What Are These "Stakeholder Challenges" You Speak Of, Dan?

Stakeholder friends in the audience, cover your ears for a sec.

First off, I firmly believe that most stakeholders -- be they product managers, or a CEO, or the head of sales, or some powerful internal user -- well and truly want the overall business to succeed.[fn:: I mean, they *also* want to personally succeed, I'm not naive or something, duh. But their fondest hope is that engineers will offer them a way to achieve *both* overall business success and their own personal goals. The wise engineer will therefore ensure that they understand both of those aspirations, it's almost like someone should write a book or something.]

*And* they want to be, well, *reasonable* in what they ask of engineering.

In fact, I'll go further. They deeply believe they *are* being reasonable in what they ask of engineering.

And yet... *somehow*, engineers end up experiencing:

  - Demands for commitment to long-term estimates

  - Constant interruptions with new feature requests

  - A painful refusal to engage in tradeoff discussions

  - An unwillingness to face looming technical problems

If those challengs sound at all familiar, stay tuned!

I do, in fact, have a battle-tested plan for handling these challenges, and getting to a place of true, rewarding partnership.

** Teaser 2: Launching Early Is Super Valuable, Film At Eleven

For years and years, I've strongly recommended / forced my teams to ship new products to customers at an *uncomfortably early* stage in their development.

"If you're not embarrassed by your product, you've waited too long" (I think that's Reid Hoffman, should I look up his politics now, or am I gonna be horrified, and feel like when we all quote Donald Rumsfeld about unknown unknowns, sigh)

Fortunately, I've done this enough with my teams, that I was able to force myself to do it.

Once I had anything even vaguely resembling a potentially useful draft, I made myself ship it, in the form of sharing a very rough draft with beta readers.

It was, as is always the case, *genuinely* uncomfortable.

It's not fun being embarrassed.

"Wait," said the voice inside my head, "you can make it so much better! Just take a bit more time to clean up the intro, and fix the links, and review some transitions one more time."

Luckily, I've learned to not trust that voice, so I sort of closed my eyes and hit send on the beta invites.

And, lo, as has happened for my teams over and over, I learned something that I wasn't expecting, which was *insanely* valuable.

Specifically, it was through the process of reaching out for beta readers, and talking to people, that I came to realize that, by linking my book to "tech debt", I was talking about a vitamin, not a painkiller.

Even though, within the book, I was in fact, speaking to some of the most fundamental challenges engineers struggle with.

Since I very much want people to *buy* and then *read* the book, I should maybe name those challenges on the cover or something?

As with most product discoveries, this feels blindingly obvious... after the fact.

Everyone, I have this awesome new idea!

Ship early and learn from reality!

Trademark coming soon!
