* Engineering & The Creation of Value, Part III
** Intro

In our previous posts in this series, (Link, Link), we developed a model for how engineers can *create value* for the companies at which they work.

We dug deeply into how investors determine what a company is *worth*---also known as how they *value* a company. Because an investor's valuation of a company is, fundamentally, based on some estimate of future profits, we established that the work an engineer does *creates value* for their company if that work:

 - Increases the probabilistic estimate of future profits...

 - made by an economically rational investor...

 - who possesses information known both inside and outside the company.

We named a specific, economically rational investor *Bertha*.

Armed with this fuller understanding of how value is created (and our made-up person!), we're ready to explore various kinds of engineering work.

In particular, we're ready to analyze [explore, dig into] a wide variety of different *demands* that are frequently made of engineering teams, by people across the company who believe that solving problems in their area will certainly absolutely for sure no questions asked create value for the company.

We will develop the key questions to ask, to determine if those people are correct or misguided in their beliefs about what engineering should work on.

# XXX Make Above Suck Less (MASL)

We'll start by digging into how value can be created *incrementally*.

This is absolutely key. Our understanding of how value is created is of essentially no use to us if it can only be applied in bulk, at the scale of a full project. We need a way to, at a specific moment in time, look at a variety of potential increments our team could take, select an increment that will create the most incremental value, execute for a chunk, then pause, see how much value was created, and select a new increment.

That is what will let us steer, day-to-day.

In order to understand that, we'll dig into how Bertha might evaluate the actions of a team doing two kinds of work.

** Acquiring Evidence Creates Incremental Value

# The Acquisition of Evidence

# Let's start with a classic tension:

# Stop me if you've heard this one before:

Let me sketch in a situation that is utterly unique, that you've definitely never heard of before or experienced personally.

 - The company desperately needs a new product, it's all the CEO can talk about

 - The engineering team desperately needs to stop clawing their eyes out every time they deploy to production

How should the team decide what to do with their next increment of work? What will create the most value?

One common way to frame the question is: should the team work on the *business* problem (building a new product, asap), or the *engineering* problem (smoothing out the path to production)?

Hold it right there, Mr Common Way: these are *both* business problems. Because gthey are *both* opportunities to create value.

It's depressingly common for people, even engineers, to consider the new product opportunity *more valuable* because it creates "immediate" value (being able to acquire new customers), whereas a reduction in deploy pain is *less valuable*, because it will take a long time for such an improvement to either generate revenue or reduce costs for the business.

That perspective is *profoundly wrong*. Company value is not simply current revenue. Company value is a rational investor's probabilistic estimate of *future profits*.

Therefore, crucially, value can accrue *immediately*, even if the actual increase in profits will take a long time to land.

Let's see how this could happen.

It's a Tuesday morning. Something suddenly causes Bertha, our rational investor, to *double* her estimate of future profits for our company. In that moment, the company as a whole will *immediately* double in value. In the moment she changes her rational mind. If a team somehow gets her to change her mind this way, that team creates an enormous amount of value for their company. *Immediately*.

And therefore there's an *incremental* creation of value.

Why would Bertha suddenly change her mind about expected future profits?

For exactly one and only one reason: beause she sees a new piece of *evidence*.

Bertha *only* ever changes her estimate of future profits if she sees evidence.

Let's see how that plays out for our two potential investment opportunities.

For the new product, evidence might be customers purchasing the new product. But it could also be a series of extremely positive customer pre-sales conversations, with clear signals of intent to later buy. It could even simply be discovering that customers are already spending money to try to solve the problem the product focuses on.

Each of these outcomes would provide Bertha with a different form of evidence that this new product will allow the company to keep growing revenues, and therefore profits, over time. Each of those pieces of evidence would therefore, in the moment they were acquired, immediately increase the value of the company (by different amounts, to be clear)[fn:: Current revenue *is* a powerful predictor of future revenue. Which is why investors short-hand valuation by simply picking revenue multiples. But, inside a company, as we're evaluating fine-grained activities, we need a more nuanced model].

A team that *acquires* that evidence therefore immediately creates value for the company.

How could incremental value creation work on the deploy side?

Let's say that, because Bertha is rational, she has read Accelerate [link]. She therefore understands that frequency of deploy is predictive of an increase in future profits.

Thus, evidence could be: a direct increase in deploy frequency. But it could also be: identifying a bottleneck in the deploy process -- Bertha would see the identification of the bottlenck as evidence that the team has just improved their odds of increasing deploy frequency. It could even simply be the team *measuring* deploy frequency, if it wasn't measured before. Again, a rational investor would see that as improving the odds that the team can later increase the frequency of deploys, and therefore, in the moment the team was able to start measuring, would immediately increase their estimate of future profits (by a small amount, to be clear).

This may sound a bit abstract or hard to believe, but, in extreme cases, almost all engineers already intuitively understand this.

# Name the engineer? Jorja?

Say an engineer joins a B2B SaaS company, and knows that they were hired because the company urgently wants to build a new product over the succeeding year. However, on their first day, that engineer discovers to their horror that the company only ships to production *once per quarter*. In such a situation, just about every engineer I know would tell their leadership that improving deploy processes should be their top priority.

That engineer would not make that case because smoother deploys "feel good" to them. They'd advocate for that work because they believe (correctly!) that their new company has essentially zero chance of successfully developing a new product in a year if they can only ship to production four times during that period.

Say that, after their first two months of work, the new engineer has cleaned up a variety of issues, and now, when they look at their little deploy frequency graph, they see that, for the most recent three week period, deploys were happening once per week. A fully economically ration investor who understands the impact of deploy frequency on product development would look at that graph as *evidence*, and based on that evidence, would *immediately* ascribe a higher likelihood of the company successfully developing a new product and thus increasing profits.

The moment that graph exists, and could be shared with a rational investor, the company *immediately* becomes more valuable. Even if the actual revenue comes in much later.

The acquiring of evidence is one of the most powerful ways to understand the incremental creation of value.

Of course, there's every chance that your key stakeholders neither understand nor believe this. That's okay! By having this understanding yourself, you'll be able to advocate for work which, over time, pays off.

You might be thinking: but we can't quantify this! And if we can't quantify it, how can we possible use it to make decisions? This is a fair concern. As we dig into the various ways evidence creates value I think you'll find that there are often continuous tradeoffs happening, so you don't need much in the way of precision. But I'm super curious about exploring quanitification as a means to unlock rapid decision-making. If you've taken a shot at making that work, please let me know what you've learned! Or if you *want* to take a shot at making that work, ooooh, please reach out!

To understand how to apply this model for understanding engineering work, we're going to dig into a variety of situations, and illustrate the key questions you can ask, if you want to maximize the value you and your team can create, with the hours of work you're spending, right now, by asking: "What evidence would Bertha need, to increase her estimate of future profits?"

The evidence/estimate frame will cast a light into many murky areas.

** How Do People Make Demands Of Engineering? Let Me Count The Ways

To think about the kinds of work engineers can do, I'm going to speak to the kinds of requests made of engineering. Except, to match up more fully with my lived experience, I'll name them as "Demands", not "Requests".

# We're going to start each one from the perspective of a "problem" that someone might want an engineering team to solve. We'll characterize those as "demands".

I'm going to break the demands made of engineering into a few buckets, based on where, in the organization, I've typically seen such demands come from. Why do this? People rarely come to engineering teams with truly clear thinking about overall company value creation and their place within it. Rather, they're just about always worried about some local problem for their function, which they then try to dress up in impressive and/or moralizing terms (e.g. "This is a huge opportunity!", or "Don't you care about the customer?!")

So, by looking at the different buckets, we can develop means to map from the "local" concerns of those functions to overall company value. Which is what we need to do, if we're going to make good decisions about which problems to solve, aka, how to spend our time.

*** Sales & Marketing

Typical demands:

 - Develop new products

 - Add features to existing products

 - Fix bugs in existing products

*** Internal Operations

E.g. the customer support desk, the data ingestion team, a business intelligence group, the warehousing and fulfillment teams.

Typical demands:

 - Automate repetitive work

 - Handle exceptional/severe problems

 - Add support for a new operation

*** Engineering

Typical demands:

 - Clean up or replace "bad" code

 - Upgrade or retire old infrastructure

 - Make it easier to deploy changes to production

 - Address system performance issues

*** Product

Haha!

The product team is the people of whom demands are made! They have the awesome power of saying no to people (aka prioritization), and with it the attendant awesome power of everyone being kind of mad at them, all the time!

This is the "product function" at its heart---disappointing people by saying no.

If you don't have a product team, or if your product team seems to be kind of a project management team in disguise, you can figure out who is serving the product function by asking: Who gets to/has to disappoint other people? Who decides which problems are important enough to solve? Who continually updates their understanding of reality to adjust the answers to those questions as you go?

There are plenty of situations [cases, times] where the person doing the "product funtion" is actually an engineering leader.

One sign that this might be the case is that various IC engineers on the team are frustrated with that leader for "not allowing them to deal with tech debt".

Engineers are, to a first approximation, *always* frustrated with someone for not letting them deal with tech debt. if the engineers focus that frustration on an engineering lead instead of a nearby product manager, that could be a clue about who is serving the product function.

** Who Evaluates Demands of the Engineering Team?

Company value is created by acquiring *evidence* that will increase Bertha's probablistic *estimate* of future profits.

How can an engineering team create value, when confronted with the kinds of demands we've just sketched in?

What questions should they ask, to orient?

What answers might they hear that could make them push back?

"Wait", you might be saying, "isn't this the product manager's job?"

"In fact," you might further say, "didn't you just tell me, Dan, that the product team is the one of whom demands are made? Shouldn't *they* be digging in, on these questions?"

Look, I'm going to be blurring the line between engineering and product here, and *I make no apologies for this*.

I have *never* seen a high-functioning engineering team where the engineering lead wasn't able to think like a product manager. So, if you're an engineering leader, even if your product peer will ultimately make the prioritization calls, I *highly* recommend that you understand how your team's work could ultimately turn into value for the company. To excel at your job, you need to be an *active partner* in that prioritization decision.

Note: if your product peer doesn't currently seem interested in that kind of partnership, being able to speak to potential value can be a very powerful way to gradually change the dynamic between you. Unsurprisingly, this is a common topic of my coaching practice: helping engineering leaders earn their way into a greater degree of influence and partnership. I wrote about a form of this in <Fixing the Engineering/Stakeholder API>.

On the other hand, if you're a product manager, I think I'm describing a core function of your job? Hopefully that's kind of useful?

"But wait, Dan", you might still be saying, "my team doesn't have a PM."

I have seen... some... high-functioning engineering teams that didn't have a PM.

But, honestly, not that many. There's simply too much to do, across the two functions, to have one person have both the skills and the capacity to handle both. If you get rid of your PM's, your "product-minded" engineering lead can easily find that that they're spending all their time talking with stakeholders and/or trying to triage concerns from the help desk, and/or preparing for meetings with the exec team, and/or trying to quickly learn customer interview or presentation design skills, etc. Aka, they're just being a PM. And, every day, they're feeling like they're doing an increasingly bad job of staying on top of the evolving architecture of their systems, or mentoring promising early-career engineers, or steadily flushing out key risks and opportunities, etc. Aka, they're not being effective as an engineering leader. There's a conversation I find myself in, not infrequently, with young engineering leads who have found themselves in this situation and are thinking about leaving their jobs.

In short: I believe Product Managers can be *extremely* valuable! Don't get rid of them lightly!

Yes, at a somewhat painfully wide variety of places, the PM's may be doing a poor job (though I'm always suspicious of structural reasons as well as weak performance). In my in-no-way humble opinion, the optimal answer is just about *never* to simply get rid of product. I believe this passionately. (again unsurprisingly, this is very much the kind of thing I help my coaching clients wrestle with).

Okay, I'll get off my soapbox now.

** Sales & Marketing Demands

First off: Sales & Marketing-sourced problems are somewhat distressingly often seen as the only economically valuable problems for the engineering team to work on.

Of course, company leaders won't say it in those flowery academic words. They'll instead talk about adding new products or fixing bugs as addressing "actual business problems", or "being customer-centric". By which they're demonstrating that they consider problems identified by other parts of the business as *not* real business problems, or as not serving the morally pure purpose of centering customers[fn:: Look, if you've managed to work at a company where a push to be be "more customer-centric" *didn't* immediately become a means for powerful people to sabotage the prioritization process by elevating their evidence-free opinions about customers into moral imperatives, I'll be thrilled to hear about it. But I am batting negative one thousand on that one.].

We're going to avoid falling into that trap.

*** Develop New Products

This one feels obvious, right? If the engineering team can build a new product that customers will pay for, then Bertha, our economically rational investor, will happily increase her estimate of the future stream of profits, and thus the value of the company will increase.

Great, we can move on---

Waitwaitwait.

Understanding value creation *during* new product development is a total cesspit of confusion. In particular, there are a couple of extremely common anti-patterns to watch out for.

Here is the absolute key to understanding the *incremental* creation of value, as you work on developing a new product:

Bertha, being economically rational, *doesn't think you're going to succeed*.

Most new product development efforts *fail*.

Most new product ideas *fail* (especially as they are initially conceived of).

# Everyone at your company are sort of joining hands and agreeing to pretend this isn't true. Because it would be depressing to go to work every day on something you thought was likely to fail, right? Trick: turn failure into success. How, by adopting a portfolio/pipeline view, and celebrating evidence that lets you winnow bets out of your portfolio. Most sales calls do not turn into conversations. Does the sales team spend an incredibly long time debating about who to call? Or staying on the line with someone who is clearly not going to buy? No, they put in their hours, they "build pipeline", and they spend their time wisely.

An economically rational investor will look *extremely suspiciously* at your CEO's optimistic PowerPoint deck, the one that explains how the new product your team is going to develop will double revenue over the next three years. Bertha has seen *plenty* of such decks. Very few of those companies actually achieved the promised increase in revenue (and, essentially *none* achieved that increase in revenue without significantly changing their original plan).

To understand value creation in new product development, you should think of your company as considering a *set* of product ideas it could potentially invest in. At any moment, your company doesn't actually know which product ideas (if any) in that set will turn out to be both valuable for customers and feasible to build.

A rational investor will therefore assign a weighted average across all of them -- and, unless you have evidence, that weight average will be quite low (because so few product ideas work out)

# If, say, on average one out of ten of product ideas turn into a modest increase in profits, then Bertha's *current* estimate of future profits will be one tenth of that modest increase.

Given this context, value is created during new product development by two activities:

 - *Learning* which product idea, if any, are potentially valuable

 - Actually *building* those product, aka, learning which are feasible to build

The best teams *interleave* these two activities, so that they iteratively hone in on a product customers will pay for, steadily learning and adapting as they go.

There are two classic failure modes companies fall into, here:

 1. They try to do all the learning before they start building

Aka, conduct full market research before a team can start, try to analyize it all up front, and then fully commit to a single bet.

 2. They try to do the building, "as fast as possible", by not slowing down to learn as they go

Just go with what some executive is "certain customers want", and don't do anything to learn from customers and/or reality as you build.

Given that evidence creates value, a team building a new product should be eagerly pursuing evidence. They should bias towards building to learn -- building their product in a smart sequence that lets them test their biggest risks at every moment.

For more on this idea, see my talk Risk, Information, Time & Money

*** Add Features To Existing Products

*** Fix Bugs In Existing Products
* Scraps/Thinking
** Morning Walk Thinking <2025-09-28 Sun>
I've got a tiger by the tail.

I do like that I'm speaking to the "immediacy" of value creation.

Could maybe back up and frame the entire thing around increments, around the incremental creation of value.

Why are increments important?

So you can stay on track -- building a big piece of software in increments is important because it allows you to learn and adapt.

The exact same thing is true of all software work -- you need to see if you're creating value, and if you're not, adapt.

But the increments are tricky.

Maybe, show the classic Agile skateboard picture -- this is profoundly wrong (even though it's usefully right, at the same time). Yes, you should hook your software up all the time, but you shouldn't always have a thing that is useful to a user.

The first picture is asking someone about where they need to go every day

The second one is building 5 different engines and testing them.

The third one is experimenting with different sales models.

Could I show that with arrows going off in different directions, so it's finding a path through decision space? Visually? That's an interesting idea.

And that does maybe give me a way to make clear that each moment, each key milestone, is a *decision*, not a deliverable.

I still want to find a way to give the reader that sort of actionable, useful when/not useful when.

Definitely frame the portfolio/pipeline thing as a way to make the economics manifest, and enable better decisions. And to unlock good bits of human nature, and point stakeholders at useful decisions.

Also, this is clearly exploding into something between a series and a book, embrace that.

Key Q: if I want to touch both on the immediacy of value creation (the incremental creation of value), *and* some specific tactics for new product dev, should I make that one post or two.

It could be two, as long as the first is grounded enough in reality to not be purely abstract.
** Random Thinking
The "this is valuable when/not valuable when" thing worked super well.

I do really like the idea of unifying across product/engineering/operations, showing them all with a common, true view.

What if I make a central point about the unification, so I can show both top-down and bottom-up concerns through a common lens?


** Good/Bad Engineering Activities
*** Rapidly Banging Out Prototypes
*** Building Complex Data Pipelines
*** Cleaning Up Horrible Code
*** Investing in "DevOps" or "Dev Experience"
*** Retiring/Upgrading Old Infrastructure
*** Developing New Products to Expand TAM or $/Customer
*** Adding Features for Big Customers
*** Making It Possible to Sell to Smaller Customers
*** Making Internal Operations Easier
*** Making Onboarding Easier
*** Writing Lots and Lots and Lots of New Code, Super Fast

** Contextual Situations
Can I run that through. What are my four forms of value so far?

Existing Forms of Value:

 - "This Code Is a Nightmare From The Black Depths of Hell"

 - "Deploying To Production Saps My Will To Live"

 - "I Can't Find a Moment to Think"

 - "The Database Is On the Verge of Death And No One Cares"


** Possible Titles
Turn "Engineering Concerns" Into Potential Value, I

The Landscape of Potential Value

The Unifying Force of Potential Value

Seeing Engineering Work Through the Lens of Value

Engineering & The Creation of Value, Part III


** Scrap
It covers both "simple" situations, like closing new customers who add to this year's top-line revenue, but also more nuanced ones, like, a team that rapidly chews through three different product hypotheses, invalidates two of them and makes a critical discovery about a third. That key discovery creates *evidence* that the company is on the verge of building a valuable new product. Bertha, in reviewing that, may even consider that action as having created a greater probabilistic increase in future profits than closing a few new customers (though, note, closing those new customers can create evidence that the company can keep growing, which, in some situations, might be the most important evidence of all).

* Old Turn "Engineering Concerns" Into Potential Value, I
** Intro
# Getting a Handle on Interruptions

# Hmm, When You Put It That Way, That Does Sound Pretty Important

# Can Bertha Help Tame Interruptions?

Now, armed with a fuller understanding of value [link], we're ready to look at issues engineers tend to be concerned about.

We'll look for ways to turn those from vague worries into potentially valuable *investment opportunities*.

We'll ask: What Would Bertha (our economically rational investor) Say?

Then, we'll share ideas on how you to make the potential value *visible* to stakeholders.

Today, we'll dig into one such challenge, which engineers might experience as:

** "I Can't Find a Moment to Think"

Wouldn't it be great if your engineers had time to, say, *do software engineering*?

But instead, every day they face a relentless stream of *interruptions* from people across your company:

 - *People who work directly with customers pinging them about bugs and feature requests (and bugs that are actually feature requests)*

   Every one naturally at the highest priority!

 - *Follow ups and status checks and nudges about those bugs and feature requests (and bugs that are actualy feature requests)*

   And I have some bad news.

   People who work in sales are often very good at advocating for issues that affect "their" customers.

   I mean, look, they didn't get into sales because they're *bad* at persuading people to do things![fn:: I once asked my friend Marion, who was running sales at Ellevation, what it's like to interview sales people, who are, by their very nature, skilled at presenting themselves optimally, and she rolled her eyes and said "Oh my god it's the worst".]

 - *Weird bits of operational work only engineering can do*

   The still-largely-manual work to set up data integrations for new customers, or the monthly data pull for the BI reports.

Worse yet, the interruptive requests often fall most heavily on your most experienced engineers (because they're the ones who know how to solve all the wonkiest problems)

And that's *especially* true if those engineers suffer from the misfortune of *being nice*.

(I have vivid memories of standing by Tom Hare's desk at Wayfair, watching just a parade of people from the operations teams "wander by", each asking for Tom's help to fix some weird edge case. Tom was such a good engineer! And so nice!).

# That said, he did end up marrying one of those ops stakeholders -- hi Lauren! -- so I guess that worked out okay in the end?

*** Potential Value: Reduce Opportunity Cost *And/Or* Improve Operational Outcomes

This situation isn't just *unpleasant* for the engineers.

It may represent a serious *opportunity cost* for the company as a whole.

As in, there might be something else, that the engineers *could* be doing, which would create *more* overall company value than their current work.

But, and this is important, just because the current work is interruptive and not much fun, *doesn't mean it's not creating value*.

So we're going to dig in, with Bertha at our side, to understand the situation in more detail -- and then be ready to advocate.

Let's imagine the engineers on the team spend, among them, a few dozen hours each month doing the following two "distracting" things:

 1) Fixing edge case bugs for a small set of extremely vocal customers

 2) Setting up data integrations for the customers who onboard in that month

What is the value being created by each of these activities?

aka, what is the effect on Bertha's probabilistic estimate of future profits?

That is what we'll have to understand if we want to make a case for the engineers doing *something else*.

Let's take them each in turn.

*** 1) Fixing Edge Case Bugs

Aka, Sometimes We Should Just Let the Wheel Squeak

Let's imagine that the engineers and/or their PM's do some investigation and discover the following things are true:

 - These customers represent a tiny fraction of the company's revenue

 - They're not particularly *representative* customers

   A common case for this is that they were acquired *early* in the company's history, but they're not actually in the key segment. But they have high expectations of responsiveness.

 - They are very unlikely to cancel -- although they're *always* complaining about bugs, but none of the customers have left in a long time.

In this case, it ;

# Likely nearly purely opp cost, key is how to make this visible, answer = a) lightweight tracking of time, then use that to b) set up triage to bring it out in the open, and c) force a one-time budget or cost.


*** 2) Setting Up Data Integrations for New Customers

aka, Enabling Customers To Use The Product They Paid For

Let's imagine that the investigation led to finding that there genuinely is no other way.

If they *didn't* do this, there would be some likelihood

Say that decreases the likelihood of those customers churning by some amount. Then we can look at the value of the

If, instead, theywhen they could have been developing a product that opens up a new segment for the whole business... that might represent a loss of overall company value (where, again, value is a probabilistic estimate of future profits).

But, of course, that tends to be completely invisible to stakeholder and decision-makers.

There are two distinct ways that Bertha understands the potential for value here, and thus two distinct forms of visibility.

First, Bertha suspects there might well be value for the company if the engineers could spend *less time* on all this interruptive work.

In this belief, she is likely heartily joined by both the engineers *and* their immediate stakeholders.

Spending less time on reactive work could free the engineers up to work on things that would be more valuable (hopefully) and more fun (definitely).

# more fun for them and more in keeping with the product team's immediate goals.

If that "other" work were likely to lead to greater profits in the future, Bertha will happily ascribe real value to replacing the reactive work with that "something else".

Visibility on this "engineering capacity" front is fairly straightforward: you want to simply make it clear *how much time* the engineers are spending on operational work (with some multiplier for interruptions, since they blow up focus).

Just viewing the capacity consumed by reactive work can sometimes motivate a real investment to speed up or fully eliminate interruptive tasks the engineers are currently responsible for.

You can build visibility into the "capacity spent on reactive work" by some combo of:

 - Surveying engineers on a regular basis as to how much time they're spending on the reactive work

 - Tagging and tracking tickets

 - Shadowing an engineer for a day or two

 - Setting up a formal triage process to bring reactive work out into the open

All of that can help create enough visibility to make a case for investment, in particular if there's a way to *reduce* the reactive work.

However, that's not the whole story.

The reactive work, thankless though it may be, is very likely creating *some* form of value for the business.

Bad news: *Bertha cares about that value, too.*

If fixing bugs, or restoring the site from outages, or correcting data issues in production keep customers renewing, then Bertha will not be happy if your team simply stops doing that work.

The trick here is to spend a bit of time understanding the *positive* value of what your team perceives as reactive work.

If you can really dig in on that side, you might be able to find creative ways to restructure how much work gets to your team, or make a real investment to eliminate a whole class of issues at a deeper level, or even, propose moving the work *off your team* altogether and finding a home for it somewhere else in the organization.

Those kind of major investments or shifts can be economically rational, but those aren't easy pitches to make, unless you can show the *positive* value to the business, *beyond* just saving time for the engineers.

E.g. say your engineers spend time every sprint helping set up data import configurations for new customers.

Even if they were to invest in better tooling, they can't automate it all away, because setting up each new customer requires carefully reviewing sample data files, testing out imports and diagnosing failures, helping the customers fix subtle issues on *their* end, etc.

Imagine you were go to an Important Person at your company and say, "We'd like create a dedicated Data Operations team"

And the Important Person looks august, and says, "Okay, why?"

And you say, "So my engineers can spend less time on new customer onboarding."

Here's a problem: there is a risk that Important People will hear that as a form of *complaining*.

Everyone's job has certain unpleasant and/or boring parts. Most Important People have developed the skill of ignoring complaints that they hear as: "Part of my job isn't fun, can I stop doing that part?"

You really don't want them to hear this suggestion in that light.

You might be able to make a more effective case by saying something like:

/"It currently takes three weeks to onboard new customers. Delays in the back and forth to setup data imports are the main driver./

/That work is currently being handled by the engineers, but:/
  /a) Engineers are expensive, and/
  /b) it often takes a few days for an engineer to find time to review a question from customers, which adds a lot of delays and frustrates customers./

/We'd like to talk about finding a better home for that work, so we can both improve onboarding times and reduce costs./

/Our early estimate is that 70% of the work can be done by the more technical members of the help desk, if we can carve out time for them, and the engineers can build some basic tooling."/

That's speaking to potential benefits -- both a better customer experience, but also lower costs and better outcomes *for the operation itself*.

There's a decent chance you can (and should) loop in your product team to help build this kind of case. It's usually not too hard to get their help, because they would love to have more of "their" engineers time devoted to "their" work.

There are other variations on this game plan you can run, be it setting up a regular collaborative triage process, or breaking off a separate platform team that owns a particularly troublesome bit of functionality (e.g. authentication and authorization is a classic), etc. We'll touch on a couple in the Case Book of Tech Investments later.
