* New Post
** Intro

In our previous posts in this series, (Link, Link), we developed a model for how engineers can *create value* for the companies at which they work.

We dug deeply into how investors determine what a company is *worth*, aka what it is *valued* at.  We established that the work an engineer does *creates value* if that work:

 - Increases the probabilistic estimate of future profits...

 - made by an economically rational investor...

 - who possesses information known both inside and outside the company.

We named our economically rational investor *Bertha*.

Armed with this fuller understanding of how value is created, we're ready to explore various kinds of engineering work.

In particular, we're ready to analyze [explore, dig into] a wide variety of different *demands* that can be made of engineering teams, and undertand when the engineer teams should agree to those demands, and when they should push back.

# XXX Make above Suck Less

** Acquiring Evidence Drives The Creation Of Value

Let's start with a classic tension:

 - The company desperately needs a new product, it's all the CEO can talk about

 - The engineering team desperately needs to stop clawing their eyes out every time they deploy to production

Should the team work on the "business" problem (building a new product, asap), or the "engineering" problem (smoothing out the path to production)?

First off, these are *both business problems*. They are *both* opportunities to create value.

Now, it's easy (and maybe even typical) to think of the new product opportunity as more important because it creates "immediate" value (being able to acquire new customers), whereas an improvement in deploys is less important, because it will take a long time for such an improvement to either generate revenue or reduce costs for the business.

But that perspective is *profoundly wrong*. It falls into the trap of equating company value with present revenue.

Value is not current revenue, value is a rational investor's probabilistic estimate of *future* profits. Therefore, value can accrue *immediately*, even if the actual increase in profits will take a long time to land. If Bertha, our rational investor, suddenly decides that expected future profits are now twice as large as she had previously believed, the company will *immediately* double in value.

Why would Bertha change her mind about expected future profits?

Beause she saw *evidence*.

For *both* of our potential investment opportunities, Bertha will *only* change her estimate of future profits if she sees *evidence*.

That evidence could be some customers who have purchased the new product---which will provide Bertha with evidence that the company can keep growing revenues, and therefore profits, over time.

Or the evidence could be an increase in the frequency of deploys---which, because Bertha has read Accelerate [link], she understands as predictive of an increase in profits over time.

In the extreme cases, almost all engineers already understand this.

Say an engineer joins a company, with an express mandate to build a new product. On their first day, that engineer discovers to their horror that the company only ships to production once per quarter. In such a situation, just about every engineer I know would feel *extremely confident* in telling their leadership that improving deploy frequency is their absolute top priority.

They would just do that because it "felt good" to them. They'd do that because, at some level, they believe that their new company has essentially zero chance of successfully developing a new product if it takes up to twelve weeks to get anything new to production.

Let's further dig into this scenario. Say that, after their first two months of work, the new engineer has cleaned up a variety of issues, and now, when they look at their little deploy frequency graph, they see that, for the most recent three week period, deploys were happening once per week. A rational investor, who understands the impact of infrequent deploys on product development,  would look at that graph as *evidence*, and based on that evidence, would *immediately* ascribe a higher likelihood of the company successfully developing a new product and thus increasing profits.

The moment that graph exists, and could be shared with a rational investor, the company *immediately* becomes more valuable. Even if the actual revenue comes in much later.

The acquiring of evidence is one of the most powerful ways to understand the creation of value.

This is critical to both understand and, well, *believe*.

Of course, there's every chance that your key stakeholders neither understand nor believe this. That's okay! By having this understanding yourself, you'll be able to advocate for work which, over time, pays off.

# It covers both "simple" situations, like closing new customers who add to this year's top-line revenue, but also more nuanced ones, like, a team that rapidly chews through three different product hypotheses, invalidates two of them and makes a critical discovery about a third. That key discovery creates *evidence* that the company is on the verge of building a valuable new product. Bertha, in reviewing that, may even consider that action as having created a greater probabilistic increase in future profits than closing a few new customers (though, note, closing those new customers can create evidence that the company can keep growing, which, in some situations, might be the most important evidence of all).

To understand how to apply this model for understanding engineering work, we're going to dig into a variety of situations, and illustrate the key questions you can ask, if you want to maximize the value you and your team can create, with the hours of work you're spending, right now.

For each, we'll ask: "What evidence would Bertha need, to increase her estimate of future profits?"

The evidence/estimate frame will cast a light into many murky areas.

** How Do People Make Demands Of Engineering? Let Me Count The Ways

# We're going to start each one from the perspective of a "problem" that someone might want an engineering team to solve. We'll characterize those as "demands".

I'm going to break "demands of engineering" into three buckets, based on where, in the organization, I've typically seen the demands come from. People rarely come to engineering teams with truly clear thinking about overall company value creation and their place within it. Rather, they're just about always worried about some local problem for their function, which they then try to dress up in impressive and/or moralizing terms (e.g. "This is a huge opportunity!", or "Don't you care about the customer?!")

The whole point of this post is to show that all of these problems can be compared against each other, on a common ground.

*** Sales & Marketing

Typical demands:

 - Develop new products

 - Add features to existing products

 - Fix bugs in existing products

*** Internal Operations

E.g. the customer support desk, the data ingestion team, a business intelligence group, the warehousing and fulfillment teams.

Typical demands:

 - Automate repetitive work

 - Handle exceptional/severe problems

 - Add support for a new operation

*** Engineering

Typical demands (of... themselves):

 - Clean up or replace "bad" code

 - Upgrade or retire old infrastructure

 - Make it easier to deploy changes to production

 - Address system performance issues

*** Product

Haha!

The product team is the people of whom demands are made! They have the awesome power of saying no to people (aka prioritization), and with it the attendant awesome power of everyone being kind of mad at them, all the time!

This is the "product function" at its heart---disappointing people by saying no.

If you don't have a product team, or if your product team seems to be kind of a project management team in disguise, you can figure out who is serving the product function by asking: Who gets to/has to disappoint other people? Who decides which problems are important enough to solve? Who continually updates their understanding of reality to adjust the answers to those questions as you go?

There are plenty of situations [cases, times] where the person doing the "product funtion" is actually an engineering leader.

One sign that this might be the case is that various IC engineers on the team are frustrated with that leader for "not allowing them to deal with tech debt".

Engineers are, to a first approximation, *always* frustrated with someone for not letting them deal with tech debt. if the engineers focus that frustration on an engineering lead instead of a nearby product manager, that could be a clue about who is serving the product function.

** Evaluating Demands of the Engineering Teams

Company value is created by acquiring *evidence* that will increase Bertha's probablistic *estimate* of future profits.

How can an engineering team create value, when confronted with the kinds of demands we've just sketched in?

What questions should they ask, to orient?

What answers might they hear that could make them push back?

"Wait", you might be saying, "isn't this the product manager's job?"

"Didn't you just say, Dan, that the product team is the one of whom demands are made? Shouldn't they be digging in, on these questions?"

Look, I'm going to be blurring the line between engineering and product here, and *I make no apologies for this*.

I have *never* seen a high-functioning engineering team where the engineering lead wasn't able to think like a product manager. So, if you're an engineering leader, even if your product peer will ultimately make the prioritization calls, I *highly* recommend that you understand how your team's work could ultimately turn into value for the company. To excel at your job, you need to be an *active partner* in that prioritization decision.

Note: if your product peer doesn't currently seem interested in that kind of partnership, being able to speak to potential value can be a very powerful way to gradually change the dynamic between you. Unsurprisingly, this is a common topic of my coaching practice: helping engineering leaders "earn their way" into a greater degree of influence and partnership. I wrote about a form of this in <Fixing the Engineering/Stakeholder API>.

On the other hand, if you're a product manager, I think I'm describing a core function of your job? Hopefully that's kind of useful?

"But wait, Dan", you might still be saying, "my team doesn't have a PM."

I have seen... some... high-functioning engineering teams that didn't have a PM.

But, honestly, not that many. There's simply too much to do, across the two functions, to have one person have both the skills and the capacity to handle both. If you get rid of your PM's, your "product-minded" engineering lead can easily find that that they're spending all their time talking with stakeholders and/or trying to triage concerns from the help desk, and/or preparing for meetings with the exec team, and/or trying to quickly learn customer interview or presentation design skills, etc. Aka, they're just being a PM. And, every day, they're feeling like they're doing an increasingly bad job of staying on top of the evolving architecture of their systems, or mentoring promising early-career engineers, or steadily flushing out key risks and opportunities, etc. Aka, they're not being effective as an engineering leader. There's a conversation I find myself in, not infrequently, with young engineering leads who have found themselves in this situation and are thinking about leaving their jobs.

In short: I believe Product Managers can be *extremely* valuable! Don't get rid of them lightly!

Yes, at a somewhat painfully wide variety of places, the PM's may be doing a poor job (though I'm always suspicious of structural reasons as well as weak performance). In my in-no-way humble opinion, the optimal answer is just about *never* to simply get rid of product. I believe this passionately. (again unsurprisingly, this is very much the kind of thing I help my coaching clients wrestle with).

Okay, I'll get off my soapbox now.

** Sales & Marketing Demands

First off: Sales & Marketing-sourced problems are somewhat distressingly often seen as the only economically valuable problems for the engineering team to work on.

Of course, company leaders won't say it in those flowery academic words. They'll instead talk about adding new products or fixing bugs as addressing "actual business problems", or "being customer-centric". By which they're demonstrating that they consider problems identified by other parts of the business as *not* real business problems, or as not serving the morally pure purpose of centring customers[fn:: Look, if you've managed to work at a company where a push to be be "more customer-centric" *didn't* immediately become a means for powerful people to sabotage the prioritization process by elevating their evidence-free opinions about customers into moral imperatives, I'll be thrilled to hear about it. But I am batting negative one thousand on that one. At this point, I've decided to just go immediately to the mat when someone self-importantly announces we should all be more customer-centric.].

We're going to avoid falling into that trap.

*** Develop New Products

This one feels obvious, right? If the engineering team can build a new product that customers will pay for, then Bertha, our economically rational investor, will happily increase her estimate of the future stream of profits, and thus the value of the company will increase.

Great, we can move on---

Waitwaitwait.

Understanding value creation *during* new product development is a total cesspit of confusion. In particular, there are a couple of extremely common anti-patterns to watch out for.

Here is the absolute key to understanding the *incremental* creation of value, as you work on developing a new product:

Bertha, being economically rational, *doesn't think you're going to succeed*.

Most new product development efforts *fail*.

Most new product ideas *fail* (especially as they are initially conceived of).

An economically rational investor will look *extremely suspiciously* at your CEO's optimistic PowerPoint deck, the one that explains how the new product your team is going to develop will double revenue over the next three years. Bertha has seen *plenty* of such decks, and very few companies who actually achieved the promised increase in revenue (and, essentially *none* who achieved that increase in revenue without significantly changing their original plan).

To properly understand value creation in new product development, you should think of your company as considering a *set* of product ideas it could potentially invest in. At any moment, your company doesn't actually know which product ideas (if any) in that set will turn out to be both valuable to customers and feasible to build.

A rational investor will therefore assign a weighted average across all of them -- and, unless you have evidence, that expected return from any one new product idea is quite low.

# If, say, on average one out of ten of product ideas turn into a modest increase in profits, then Bertha's *current* estimate of future profits will be one tenth of that modest increase.

Given this context, value is created during new product development by two activities:

 - *Learning* which products idea, if any, are potentially valuable

 - Actually *building* those product

The best teams *interleave* these two activities, so that they iteratively hone in on a product customers will pay for, steadily learning and adapting as they go.

There are two classic failure modes companies fall into, here:

 1. They try to do all the learning before they start building

Aka, conduct full market research before a team can start, try to analyize it all up front, and then fully commit to a single bet.

 2. They try to do the building, "as fast as possible", by not slowing down to learn as they go

Just go with what some executive is "certain customers want", and don't do anything to test that with customers and/or reality as you build.







*** Add Features To Existing Products

*** Fix Bugs In Existing Products
* Scraps/Thinking

** Random Thinking
The "this is valuable when/not valuable when" thing worked super well.

I do really like the idea of unifying across product/engineering/operations, showing them all with a common, true view.

What if I make a central point about the unification, so I can show both top-down and bottom-up concerns through a common lens?


** Good/Bad Engineering Activities
*** Rapidly Banging Out Prototypes
*** Building Complex Data Pipelines
*** Cleaning Up Horrible Code
*** Investing in "DevOps" or "Dev Experience"
*** Retiring/Upgrading Old Infrastructure
*** Developing New Products to Expand TAM or $/Customer
*** Adding Features for Big Customers
*** Making It Possible to Sell to Smaller Customers
*** Making Internal Operations Easier
*** Making Onboarding Easier
*** Writing Lots and Lots and Lots of New Code, Super Fast

** Contextual Situations
Can I run that through. What are my four forms of value so far?

Existing Forms of Value:

 - "This Code Is a Nightmare From The Black Depths of Hell"

 - "Deploying To Production Saps My Will To Live"

 - "I Can't Find a Moment to Think"

 - "The Database Is On the Verge of Death And No One Cares"


** Possible Titles
Turn "Engineering Concerns" Into Potential Value, I

The Landscape of Potential Value

The Unifying Force of Potential Value

Seeing Engineering Work Through the Lens of Value

Engineering & The Creation of Value, Part III


* Old Turn "Engineering Concerns" Into Potential Value, I
** Intro
# Getting a Handle on Interruptions

# Hmm, When You Put It That Way, That Does Sound Pretty Important

# Can Bertha Help Tame Interruptions?

Now, armed with a fuller understanding of value [link], we're ready to look at issues engineers tend to be concerned about.

We'll look for ways to turn those from vague worries into potentially valuable *investment opportunities*.

We'll ask: What Would Bertha (our economically rational investor) Say?

Then, we'll share ideas on how you to make the potential value *visible* to stakeholders.

Today, we'll dig into one such challenge, which engineers might experience as:

** "I Can't Find a Moment to Think"

Wouldn't it be great if your engineers had time to, say, *do software engineering*?

But instead, every day they face a relentless stream of *interruptions* from people across your company:

 - *People who work directly with customers pinging them about bugs and feature requests (and bugs that are actually feature requests)*

   Every one naturally at the highest priority!

 - *Follow ups and status checks and nudges about those bugs and feature requests (and bugs that are actualy feature requests)*

   And I have some bad news.

   People who work in sales are often very good at advocating for issues that affect "their" customers.

   I mean, look, they didn't get into sales because they're *bad* at persuading people to do things![fn:: I once asked my friend Marion, who was running sales at Ellevation, what it's like to interview sales people, who are, by their very nature, skilled at presenting themselves optimally, and she rolled her eyes and said "Oh my god it's the worst".]

 - *Weird bits of operational work only engineering can do*

   The still-largely-manual work to set up data integrations for new customers, or the monthly data pull for the BI reports.

Worse yet, the interruptive requests often fall most heavily on your most experienced engineers (because they're the ones who know how to solve all the wonkiest problems)

And that's *especially* true if those engineers suffer from the misfortune of *being nice*.

(I have vivid memories of standing by Tom Hare's desk at Wayfair, watching just a parade of people from the operations teams "wander by", each asking for Tom's help to fix some weird edge case. Tom was such a good engineer! And so nice!).

# That said, he did end up marrying one of those ops stakeholders -- hi Lauren! -- so I guess that worked out okay in the end?

*** Potential Value: Reduce Opportunity Cost *And/Or* Improve Operational Outcomes

This situation isn't just *unpleasant* for the engineers.

It may represent a serious *opportunity cost* for the company as a whole.

As in, there might be something else, that the engineers *could* be doing, which would create *more* overall company value than their current work.

But, and this is important, just because the current work is interruptive and not much fun, *doesn't mean it's not creating value*.

So we're going to dig in, with Bertha at our side, to understand the situation in more detail -- and then be ready to advocate.

Let's imagine the engineers on the team spend, among them, a few dozen hours each month doing the following two "distracting" things:

 1) Fixing edge case bugs for a small set of extremely vocal customers

 2) Setting up data integrations for the customers who onboard in that month

What is the value being created by each of these activities?

aka, what is the effect on Bertha's probabilistic estimate of future profits?

That is what we'll have to understand if we want to make a case for the engineers doing *something else*.

Let's take them each in turn.

*** 1) Fixing Edge Case Bugs

Aka, Sometimes We Should Just Let the Wheel Squeak

Let's imagine that the engineers and/or their PM's do some investigation and discover the following things are true:

 - These customers represent a tiny fraction of the company's revenue

 - They're not particularly *representative* customers

   A common case for this is that they were acquired *early* in the company's history, but they're not actually in the key segment. But they have high expectations of responsiveness.

 - They are very unlikely to cancel -- although they're *always* complaining about bugs, but none of the customers have left in a long time.

In this case, it ;

# Likely nearly purely opp cost, key is how to make this visible, answer = a) lightweight tracking of time, then use that to b) set up triage to bring it out in the open, and c) force a one-time budget or cost.


*** 2) Setting Up Data Integrations for New Customers

aka, Enabling Customers To Use The Product They Paid For

Let's imagine that the investigation led to finding that there genuinely is no other way.

If they *didn't* do this, there would be some likelihood

Say that decreases the likelihood of those customers churning by some amount. Then we can look at the value of the

If, instead, theywhen they could have been developing a product that opens up a new segment for the whole business... that might represent a loss of overall company value (where, again, value is a probabilistic estimate of future profits).

But, of course, that tends to be completely invisible to stakeholder and decision-makers.

There are two distinct ways that Bertha understands the potential for value here, and thus two distinct forms of visibility.

First, Bertha suspects there might well be value for the company if the engineers could spend *less time* on all this interruptive work.

In this belief, she is likely heartily joined by both the engineers *and* their immediate stakeholders.

Spending less time on reactive work could free the engineers up to work on things that would be more valuable (hopefully) and more fun (definitely).

# more fun for them and more in keeping with the product team's immediate goals.

If that "other" work were likely to lead to greater profits in the future, Bertha will happily ascribe real value to replacing the reactive work with that "something else".

Visibility on this "engineering capacity" front is fairly straightforward: you want to simply make it clear *how much time* the engineers are spending on operational work (with some multiplier for interruptions, since they blow up focus).

Just viewing the capacity consumed by reactive work can sometimes motivate a real investment to speed up or fully eliminate interruptive tasks the engineers are currently responsible for.

You can build visibility into the "capacity spent on reactive work" by some combo of:

 - Surveying engineers on a regular basis as to how much time they're spending on the reactive work

 - Tagging and tracking tickets

 - Shadowing an engineer for a day or two

 - Setting up a formal triage process to bring reactive work out into the open

All of that can help create enough visibility to make a case for investment, in particular if there's a way to *reduce* the reactive work.

However, that's not the whole story.

The reactive work, thankless though it may be, is very likely creating *some* form of value for the business.

Bad news: *Bertha cares about that value, too.*

If fixing bugs, or restoring the site from outages, or correcting data issues in production keep customers renewing, then Bertha will not be happy if your team simply stops doing that work.

The trick here is to spend a bit of time understanding the *positive* value of what your team perceives as reactive work.

If you can really dig in on that side, you might be able to find creative ways to restructure how much work gets to your team, or make a real investment to eliminate a whole class of issues at a deeper level, or even, propose moving the work *off your team* altogether and finding a home for it somewhere else in the organization.

Those kind of major investments or shifts can be economically rational, but those aren't easy pitches to make, unless you can show the *positive* value to the business, *beyond* just saving time for the engineers.

E.g. say your engineers spend time every sprint helping set up data import configurations for new customers.

Even if they were to invest in better tooling, they can't automate it all away, because setting up each new customer requires carefully reviewing sample data files, testing out imports and diagnosing failures, helping the customers fix subtle issues on *their* end, etc.

Imagine you were go to an Important Person at your company and say, "We'd like create a dedicated Data Operations team"

And the Important Person looks august, and says, "Okay, why?"

And you say, "So my engineers can spend less time on new customer onboarding."

Here's a problem: there is a risk that Important People will hear that as a form of *complaining*.

Everyone's job has certain unpleasant and/or boring parts. Most Important People have developed the skill of ignoring complaints that they hear as: "Part of my job isn't fun, can I stop doing that part?"

You really don't want them to hear this suggestion in that light.

You might be able to make a more effective case by saying something like:

/"It currently takes three weeks to onboard new customers. Delays in the back and forth to setup data imports are the main driver./

/That work is currently being handled by the engineers, but:/
  /a) Engineers are expensive, and/
  /b) it often takes a few days for an engineer to find time to review a question from customers, which adds a lot of delays and frustrates customers./

/We'd like to talk about finding a better home for that work, so we can both improve onboarding times and reduce costs./

/Our early estimate is that 70% of the work can be done by the more technical members of the help desk, if we can carve out time for them, and the engineers can build some basic tooling."/

That's speaking to potential benefits -- both a better customer experience, but also lower costs and better outcomes *for the operation itself*.

There's a decent chance you can (and should) loop in your product team to help build this kind of case. It's usually not too hard to get their help, because they would love to have more of "their" engineers time devoted to "their" work.

There are other variations on this game plan you can run, be it setting up a regular collaborative triage process, or breaking off a separate platform team that owns a particularly troublesome bit of functionality (e.g. authentication and authorization is a classic), etc. We'll touch on a couple in the Case Book of Tech Investments later.
