:PROPERTIES:
:ID:       5903AFE7-4B1E-422C-8537-2C56BBFBA643
:END:
#+title: Mine for Frustrations, Fears & Dreams
#+filetags: :Chapter:
* Mine for Fears & Dreams
** Humans Have Feelings, Ignore At Your Own Risk

I'm going to go out on a limb here and guess: you probably work with humans.

That's great! Except, of course, for when it's not.

If you want one of those humans to change their behavior, it's absolutely critical for you to understand their *feelings*.

This may sound a bit odd. Perhaps you work with a CEO whose only outward expression of emotion is a series of variations on the tightly clenched jaw. You might have legitimate debates with coworkers about whether or not this CEO even *has* feelings.

Look. Understanding feelings doesn't mean gathering in a drum circle and getting in touch with our inner child. All humans, in whatever positions of power they may find themselves, have things they deeply want, and things they are deeply afraid of. I don't care what role they're in, your stakeholder's current behavior patterns are driven by some combination of what they want and what they're afraid of.

When you advocate for change, you want to be able to speak with authentic connection to both the fears that are keeping them up at night, as well as the things that they desperately wish were happening.

But there's a problem.

Many leaders do their best to *hide* their feelings. If you haven't had positions of serious responsibility over large groups of other humans, I encourage you to have some empathy for people in these roles. It can feel incredibly important to "project confidence". And that can very easily turn into "pretend to have no fears or desires". In fact, many leaders unconsciously feel some desperate fear of their emotions being found out. They feel, without realizing it, that they must *hide* their emotions to retain control.  That is why it's so common to feel like you're banging up against an unyielding, inhuman, unemotional wall.

However, even if your key stakeholder seems to be working very hard to present as a goal-driven business automaton, you *must* find a way to get past that.

To persuade your stakeholder to risk making a change, you need to to develop an *empathetic understanding* of their fears and dreams.

That empathy will allow you to productively challenge them to change their current behavior, by speaking *authentically* to their *underlying concerns*. Even if they've been actively trying to hide those from you.

Persuading humans to change their behavior works roughly a thousand [zillion] times better if you can find a way to speak to their hearts as well as their minds.

Let's talk about how to map your stakeholder's feelings.

** The Four Key Emotions

You're not going to worry about every facet of your stakeholder's inner life. Instead, you're going to develop a picture of just four key emotions, by coming up with answers to four questions:

 - *Frustrations*

   What happens, day-to-day, that frustrates your stakeholder?

 - *Fears*

   What are they afraid might happen at some point in the future?

 - *Delights*

   What happens, day-to-day, that makes your stakeholder feel good?

 - *Dreams*

   What do they most fondly hope happens at some point in the future?

These form an extremely powerful core for persuasion. Two focus on day-to-day experiences (frustrations and delights), two on longer-term motivations (fears and dreams).

If you can come up with answers to these four questions, you can build an *extremely* compelling request to try something new. A request that the stakeholder will both *hear* and *feel* as worth listening to.

We'll spend real time on how to craft such a request in the "Make a Compelling Offer" chapter.

But first we need to talk about how to come up with answers to these questions.

You're going to use a mix of two techniques:

 - Making an Educated Guess

 - Mining For Emotions

If your stakeholder is in some position of authority within your company, you should be able to *guess* at answers to the four questions by simply spending some time talking with people you trust. Of course, that's only true if you work at a company where people consider it important to understand what the hell the people in power are doing and *why* they're doing those things, but that's every company I've ever worked at?

Educated guesses are a good way to start, but they aren't always enough, especially if your stakeholder seems committed to showing as little vulnerability as possible.

In that case, you'll need to do a bit of detective work, which we'll call "mining for emotions".

** Tactical Empathy Skill #3: Repeat Trailing Three Words

If you want to understand your stakeholder's fears and dreams, you're going to, well, need them to *talk to you*.[fn:: At least that's true... now? If this book is invalidated by mind-reading technologies, ALL BETS ARE OFF]

Unfortunately, it often requires some work to *get people talking at all*.

Luckily, there's a surprising simple tactic that helps a great deal on this front.

Let's see it in action:

Say you notice that your stakeholder seems frustrated after a customer call.

Eager to build up your picture, you say, "I noticed that that call seemed a little frustrating. Can I ask what was going on?"

Your stakeholder says briefly, "It's nothing. I'd just like to advance the deal."

They show no interest in explaining more. That hasn't shown you much useful about their feelings. In fact, they seem to be shutting the conversation down.

What can you do?

You're going to employ a simple and, honestly, somewhat *bizarrely* effective tactic, "Repeat Trailing Three Words".

Here's how it works.

First, you ask someone a question.

They respond with an answer.

You then calmly and curiously repeat the last three words they said, back to them, inflected as a question.

And then you stop talking and wait.

*That's it*.

If you can achieve any form of genuine curiosity as you speak, and if you can stop yourself from saying anything other than those three words...

...the person will then start talking again, telling you more and more.

And they'll *feel* like you're hearing and understanding them.

It shouldn't be this simple. But it totally works.[fn:: If you happen to like romantic comedies, you might catch this *exact tactic* from Never Split the Difference being referenced in episode <something> of Nobody Wants This (in the very fun B storyline of the two "loser" siblings, which honestly, I maybe liked more than the main storyline?)]

In our scenario, your stakeholder said, "It's nothing. I'd just like to advance the deal."

You calmly say back to them, with genuine curiosity, "Advance the deal...?"

The stakeholder says nothing for a moment, but then, once the silence has opened up, suddenly continues with, "Yeah, they just keep talking and talking."

You try the tactic once more. "They're talking and talking...?"

A slightly shorter pause, and then the stakeholder says "Yeah. I honestly don't know if they're *ever* going to convert. Of if they just like *talking* about their problems."

A final time, "About their problems...?"

The stakeholder is now talking more smoothly, there's barely a pause. "Yes. It's almost like these aren't *real* problems. We might be talking about a vitamin, not a pain-killer."

And, lo, you've turned up one of your stakeholder's biggest fears---that you may be offering something which customers don't urgently *need*.

Those may look like dry words on the page, but the tactic is remarkably effective in person. It's honestly kind of bonkers that you can get so far with such a simple approach. You may have to experience it to fully believe it.

If you're able to deploy this tactic well, you'll achieve two *super* important things:

 - *First, you'll build rapport*

   You're demonstrating, simply by listening, that you want to work *with* the stakeholder to solve their problems.

   # Eduardo started the above conversation in a bit of a haze, half-listening, half-distracted.

   # By the end, he had a sort of cautious hope that maybe Janine understands his problems.

 - *Second, you'll acquire context*

   # Janine learned: how he thinks about the team's overall goal; which segment of customers Eduardo is focused on; and some tricky internal company dynamics he's wrestling with.

   Which you can put those use in making your case.

Let's see what Quin finds out when she uses the Repeat Trailing Three Words tactic.

#  We'll demonstrate how to do so, but first, we'll talk about a second core skill of Tactical Empathy.

** Our Story: Quin Mines for Feelings
** Tactical Empathy Skill #4: Offer Labeled Feelings
** Exercises
*** Repeat Trailing Three Words

Because it's so simple, there are two good ways to practice the Repeat Trailing Three Words tactic.

1) Experiment In Random Parts of Your Life

Whenever you can, in whatever conversations you find yourself in, try repeating the last few words someone says to you, inflected as a question. Try it in both professional and personal contexts, try it with your boss, try it with your peers, with your spouse, kids, neighbors, whoever.

Do it over and over, and you'll find your own authentic way in, and it'll start to feel and more more natural.

If you start by using it just once in a given conversation, then, as that feels comfortable, see how long you can keep someone talking and opening up by just repeating those last three words of each thing they say to you.[fn:: "Dan, this whole active listening thing has helped my relationship with [insert spouse's name]", is something I've heard let's just say, a bunch of times.])

As above, take a bit of time to explicitly reflect on how it feels to do it, and use that reflection to tweak your personal approach.

For an initial, focused period of practice to rewire yourself, aim to do this 2-3 times/day for a week, and see where that lands you.

2) Explicitly Test With a Trusted Friend

Tell a friend you want to work on active listening, and then ask them a series of questions to dig into some issue -- maybe specifically something close to the kind of conversations you might have with a stakeholder.

E.g. you could say "I want to practice some active listening sikills I'm working on. Would it be okay if I ask you some questions about your work?"

And then see if you can dig for information about what they're most worried about, and what they most hope to achieve, using the repeat trailing three words tactic as you go.

At the end, pause and ask for feedback from them on how it felt for them.

During a period of focused practice, do this 3-4 separate times, and again, make sure you make time to reflect.

* Structure Ideas
** What are my learning outcomes?
Have I sold the idea enough in the previous chapter, of the value?
*** Humans Have Feelings
*** The Key Questions To Answer
**** Frustrations
**** Fears
**** Delights
**** Dreams
*** Tactical Empathy Skill #3: Repeat Trailing 3 Words
*** Tactical Empathy Skill #4: Offering "Labeled" Feelings
*** Our Story: Quin Mines for Feelings
*** Exercises

* Title Ideas

** Mine for Context, Fears & Dreams
** Mine for Strategy, Fears & Dreams
** Mine for Frustrations, Fears, Delights & Dreams
** Mine for Intent & Feelings
* Scraps
** Afford to Ignore

One useful frame is: someone is one of your stakeholders if you *can't afford to ignore them*. That may sound a bit brutally transactional, but if there's too large a set of people who you can't ignore, then there's almost no chance your team can move quickly and create meaningful value.  Asking who you can ignore will sometimes shine a light on the implicit power structures of your company--and can reveal fundamental conflicts that are making it impossible for you to win. E.g. maybe your CEO talks night and day about how critical it is for your team to stay on track for the big new product launch they've promised to the board. However, your team is *also* expected to handle a stream of feature requests from existing customers, which that CEO doesn't pay any attention to. If, one day, the Head of Customer Success comes banging on your door, demanding you immediately add a new feature for enterprise customers, can you *afford* to ignore them? Or if you do, will you receive an unpleasant lecture from the CEO and then acquire a reputation as "not being a team player"?

If not, the CEO's statement of your priorities isn't a full truth of your situation.

The Head of Customer Success  has shown a willingness in the past to blame engineering and product if they fail to hit their retention numbers.

Separately, the Head of Customer Success

The only way you and your team will create significant value is if you can relentlessly focus on the most important, most valuable work at every moment. People you can't ignore are, in the actual,
