:PROPERTIES:
:ID:       25B84349-E03D-4C1D-AA91-6F2C1E050E6E
:END:
#+title: The Struggle to Create Value
#+filetags: :Chapter:
* The Struggle to Create Value
# A Root Cause & A Fundamental Solution
** Analytics 2.0 Story
If the leaders of a business are trying to make investment decisions, and your peers across the business are trying to make coordinational decisions, but there's massive uncertainty in timelines, what can you do?

There's a simple answer: they can't make all their decisions up front.

Both your leaders and your peers need to be able to make provisional, "for now" decisions, and be ready to revisit them and *change their minds* as the work progresses, and as new information emerges.

Now, despite what your stakeholders may say to you, having to revisit decisions is not inherently bad! It's only bad if they have to revisit a decision when they don't have any good options left.

If, for a massive, year-long project, you find out after one month of work that your planned solution won't work for half your customer base, that's *valuable* -- leadership can quickly pivot your team to focus on some new solution (e.g. a variant on what you had planned, or an entirely different approach), and your peers in marketing or sales can adapt their early planning without much pain.

If, however, you only make that discovery after 11 months of work, *and* after an expensive marketing campaign has sold the upcoming feature to your entire customer base... then your leadership and your peers have no good options left.

So, the key is to work intensively to:

 a) Understand what key decisions need to be made

 b) Understand how the results of your work can inform those decisions

 c) Build early increments that turn up the most important information

Aka, find ways to *sequence* your work, so that leaders and peers can make the most important decisions *early*, while they still have plenty of time to adapt.

This will almost always require some resetting of their expectations (which is the building of trust and rapport from Part II of this book is so important), but a huge part of it still falls on the engineers.

Let me illustrate this with a story, of a time where I first started to learn to work this way, and it saved me from a certain disaster.

In 2009, I joined HubSpot, a rapidly growing startup focused on supporting B2B marketing teams. It was still pretty small -- I was the 12th engineer, and the 70th overall employee.

I was hired as a Principal Engineer at HubSpot.

I joined "The Celtics" scrum team -- our sprint teams were Boston sports themed.

Yoav Shapira, the head of engineering, asked me to lead a rewrite of the Marketing Analytics feature within the overall HubSpot product. I had been learning about Hadoop and HDFS, and believed those could be a good foundation to build on top of.

I worked closely with Dan Dunn the (excellent) Product Manager for the Celtics, and with Patrick Fitzsimmons, Owen Raccuglia and Amy Eastment.

The work, as initially planned, was trying to achieve two major outcomes:

 - Move off of SQLServer, and on to something which was much cheaper per hit

 -

There were a thousand decisions to make, of course, but one central one was:
** Scraps from Rewrites Blog Post
A few years back, I joined a rapidly growing startup named HubSpot, where I ended up working for a good solid while (which was a marvelous experience, btw -- you should all have Yoav Shapira as a boss at some point). In my first year there, I was one of the tech leads on a small team that rewrote the Marketing Analytics system (one of the key features of the HubSpot product), totally from scratch. We rewrote the back end (moving from storing raw hit data in SQLServer to processing hits with Hadoop and storing aggregate reports in MySQL); we rewrote the front end (moving from C#/ASP.Net to Java/Tomcat); we got into the guts of a dozen applications which had come to rely on that store of every-hit-ever, and found a way to make them work with the data that was now available. (Note: HubSpot is now primarily powered by MySQL/Hadoop/HBase. Check out the HubSpot dev blog).

It took a loooong time. Much, much longer than we expected.

But it generated a ton of value for HubSpot. Very Important People were, ultimately, very happy about that project. After it wrapped up, 'Analytics 2.0', as it was known, somehow went from 'that project that was dragging on forever', to 'that major rewrite that worked out really well'.


--

As an example, for our big Analytics rewrite, the developers involved sat down with Dan Dunn, the (truly excellent) product guy on our team, and worked out a list of business-visible wins we hoped to achieve. In rough priority order, those were:

Cut cost of storing each hit by an order of magnitude

Create new reports that weren't possible in the old system

Serve all reports faster

Serve near-real-time (instead of cached daily) reports

And you should know: that first one loomed really, really large. HubSpot was growing very quickly, and storing all that hit data as individual rows in SQLServer had all sorts of extra costs. The experts on Windows ops were constantly trying to get new SQLServer clusters set up ahead of demand (which was risky and complex and ended up touching a lot of the rest of the codebase). Sales people were told to not sell to prospects with really high traffic, because if they installed our tracking code, it might knock over those key databases (and that restriction injected friction into the sales process). Etc, etc.

Solving the "no more hits in SQLServer" problem is the Hard kind for a rewrite -- you only get the value when every single trace of the old system is gone. The other ones, lower down the list, those you'd see some value as individual reports were moved over. That's a crucial distinction to understand. If at all possible, you want to make sure that you're not only solving that kind of Hard Problem -- find some wins on the way.

--

Going back to my running example: our existing analytics system supported a few thousand customers, and served something like a half dozen key reports. We made an early decision to: a) rewrite all the existing reports before writing new ones, and b) rewrite each report completely, push it through to production, migrate any existing data for that report, and switch all our customers over. And only then move on to the next report.

Here's how that completely saved us: 3 months into a rewrite which we had estimated would take 3-5 months, we had completely converted a single report. Because we had focused on getting all the way through to production, and on migrating all the old data, we had been forced to face up to how complex the overall process was going to be. We sat down, and produced a new estimate: it would take more like 8 months to finish everything up, and get fully off SQLServer.

At this point, Dan Dunn, who is a Truly Excellent Product Guy because he is unafraid to face a hard tradeoff, said, "I'd like to shift our priorities -- I want to build the Sexy New Reports now, and not wait until we're fully off SQLServer." We said, "Even if it makes the overall rewrite take longer, and we won't get off SQLServer this year, and we'll have to build that one new cluster we were hoping to avoid having to set up?" And he said "Yes." And we said, "Okay, then."

That's the kind of choice you want to offer the rest of your larger team. An economic tradeoff where they can chose between options of what they see when. You really, really don't want to say: we don't have anything yet, we're not sure when we will, your only choices are to keep waiting, or to cancel this project and kiss your sunk costs goodbye.

Side note: Dan made 100% the right call (see: Excellent). The Sexy New Reports were a huge, runaway hit. Getting them out sooner than later made a big economic impact on the business. Which was good, because the project dragged on past the one year mark before we could finally kill off SQLServer and fully retire the old system.

For you product dev flow geeks out there, one interesting piece of value we generated early was simply a better understanding of how long the project was going to take. I believe that is what Beck means by "feedback". It's real value to the business. If we hadn't pushed a single report all the way through, we would likely have had, 3-4 months in, a whole bunch of data (for all reports) in some partially built new system, and no better understanding of the full challenge of cutting even one report over. You can see the value the feedback gave us--it let Dan make a much better economic choice. I will make my once-per-blog-post pitch that you should go read Donald Reinertsen's Principles of Product Development Flow to learn more about how reducing uncertainty generates value for a business.
** Random Old Bits
Distinctive things about software: 1) estimates are basically impossible, 2) systems require non-obvious investments to keep producing value.

They want to make decisions, you can't give them the information they want. And also, you want them to invest in things they don't understand


Is it this hard in every part of the business? Honestly, in my experience, no. I have enormous respect for the challenges of leading a sales team, or running a marketing operation. But, in those disciplines, it's possible, with real effort, to sit down and map out meaningful plans stretching out over the year. The sales team can develop quotas and targets and then manage to those. The marketing team can set targets for numbers of leads, and then map out the steps to get to those, and then manage against that plan. Of course, they won't always hits those plans -- and sometimes they need to help their CEO to understand, e.g. a profound external change in the market. But it's nothing like the astonishing level of uncertainty involved in developing new software.


# This should not surprise us, because the steps connecting the actions we take this morning, after we browse through emails or check Slack channels, seem so distantly related to ultimate company success.
** The Unfortunate Truth of the Stakeholder's POV

Obviously, the engineers can't be expected to win in the scenario above.

But I have some bad news.

The stakeholders in the story above *genuinely reasonable concerns*.

They're trying to solve for those concerns in ways that are ultimately counterproductive. But that's not because they're dumb or unreasonable.

Let's unpack each of the challenging moments above.

*** Why demand a "commitment" to a launch date 9 months out?

First off, let's convert that, mathematically, into an estimate of project length.

I can offer two very good reasons why executives ask for estimates of project length -- two genuinely important things they want to *use* those estimates *for*:

 1) To decide which of several alternatives to *invest* in

    Imagine that, in attempting to grow revenue for the next year, the executive team has narrowed in on two options: one is overhauling the patient onboarding process, the other is creating a new product offering for enterprise customers.

    In such a situation, an executive team will ask for an estimates of effort from the engineering team, in order to both understand the relative *costs* of the two options, and also how long they'd have to wait to see a *return*. Depending on what they hear, they will then select one option or the other.

    Making such *overall investment decisions* is a core part of the executive team's job -- and the engineering team absolutely needs to support them in doing it.

    But, unfortunately, the engineers simply *can't* provide reliable long-term estimates of effort. So they'll have to find another way to help make such investment decisions.

    By the way, you might be thinking "Oh, that's too oversimplified, in reality they won't be able to narrow it down to two clean options." But that makes my case even more strongly! An executive team with less clarity about options will be *more* hungry for information about potential project durations, in order to find one that might work.

    As a general statement, the leaders of the business are trying to deploy capital to obtain a return -- and they'll need information about the *costs* of investments, as they do so.

    The second genuinely important thing they're looking to use estimates for is:

 2) To coordinate long lead time efforts

    A business that depends on the creation of software generally has to do something *with* that software to turn it into revenue or profits.

    The CEO can't just wave their hands over a pile of code that implements requirements and have money pour into a cauldron in front of them [fn:: that kind of is my mental model of working on ad algorithms at Google, to be fair].

    # [chest, bucket, vat]

    Many of those things the business needs to do require *time*.

    In the story above, there was a marketing campaign that had to be designed and then run, well in advance of the actual launch of the software.

    Again, this is a *genuine* need of the business, and engineers need to find a way to give sufficient advance notice to marketing, sales, and other functions to turn launched software into value for customers and the business.

    So if you want to say to the executive team "We can't commit to launching in Q4", then you need to also be able to give them *some* way to coordinate the work to support the launch, when it *can* happen.

Those are two good reasons.

Sadly, there are also some *bad* reasons why executives ask for estimates and commitments, including:

 1) Because they don't know any other way

 2) Because they don't want to think about the risks and uncertainties inherent in developing software

 3) So they can hold the team "accountable" (which, far too often, means: force the team to take the blame if there are any unpleasant surprises)

 4) To push the engineers to agree to an uncomfortably early launch date

    Sigh on this one. But, sadly, there's a real chance that at some point you'll work with a stakeholder who will first browbeat the team into an unrealistically optimistic estimate, and then later express shock and anger when the team is unable to deliver "what they promised".

    I wish this wasn't true.

    But plenty of business leaders believe they're good at their jobs because they "push people to go the extra mile". And this is how they do so, when working with engineering teams.

Because of this slew of things all tied up in "asking for estimates", what to do *instead* requires both a deep understanding of the overall business, *and* the development of trust with your stakeholders.

We'll talk about how to incrementally build both of those.

*** Constantly interrupt for status and to advocate for new priorities

A stakeholder who is working with an engineering team needs to both understand *how* the work is going, *and* have opportunities to influence that work, based on what has been learned (either by the stakeholder, or by the team(.


*** Reacting to a surprise as a human

*** Evaluating investment opportunities


** Selecting Among Investment Opportunities

Imagine that your team is being asked for an estimate about the time to deliver a new product -- with a particular focus on launching in time the annual customer event next year.

Say there are two potential product opportunities:

 - Option A is a new payments integration that uses AI to automatically categorize revenue

 - Option B is an AI-enabled help desk auto-responder that embeds a jingle in the auto-response emails[fn:: At the time of writing, it's partway through 2025, I'm not legally allowed to brainstorm product features that don't include AI].

say you currently have 10,000 customers. Let's simplify and assume you can sell either new product to all of them.

For the payments integration (Option A), sales and marketing estimate that you'll be able to charge $100 / year for it.

For the auto-response jingle (Option ), sales and marketing estimate that you'll only be able to charge *$50* / year for it.

Company leadership is trying to decide which of the two to work on -- and, *as a key part of that*, they're trying to understand how much effort each might take.

Let's say that the engineering team digs in and comes up with *similar* high-level estimates for the two. Either new product would *hopefully* be deliverable by the big customer launch event next year, if the team fully focused on that work.

In that case, company leadership will choose Option A, because the payments integration generates twice the revenue, on the same timeline and for the same investment cost.

But imagine that the engineering team knows there's a specific risk for the payments integration -- it depends on the nitty details of what the payments vendor exposes in their API.

If the vendor exposes a full, accurate set of metadata about each transaction, the AI model will have plenty to work with, and the team will be able to build something of real value.

If, on the other hand, the metadata exposed is either much more limited, or (more insidiously), much less *accurate*, then the team won't be able to build anything vaguely worth $100 / year for your customers.

What can the team do?

In particular, what can the team do, to help *the overall business succeed*?

Well, if the team considers this API question the biggest risk, then the very first thing they build should be something that fully digs into that question.

They can "build the API integration first", and do so in a way which aggressively explores both the scope and the accuracy of the included metadata. This doesn't necessarily have to be a separate "research" step -- it can more be a creative sequencing of the work that needs to be done.

In any event, whether framed as "ahead of time research" or as "early sequencing", if the team *quickly* hits the roadblocks they were afraid of, *the overall business still has time to change their mind*.

Company leadership can fall back on Option B, the auto-response jingle -- which the team should still have time to deliver before the big launch.

That's the whole trick!

But that requires:

 - A willingness and cadence for changing decisions

 - The eng team surfacing risks

 - The eng team generating information about risks early

And also, it's not just the decision -- there's also coordination.


Let me tell a story.

** Coordinating Work To Turn Delivered Software Into Profits

A business that depends on the creation of software generally has to do something *with* that software in order to increase profits.

The CEO can't just wave their hands over a pile of bits [a blinking command line cursor] [that implement some requirements] and have money pour into a cauldron [chest, bucket, vat] in front of them [fn:: except, um, that kind of is my mental model of tweaking ad algorithms at Google?].

Some examples:

 - Marketing might need to generate demand for a new product, before it can be sold

 - The Sales Team might need to develop a new demo and playbook

 - An internal operational team might need to develop a migration plan for moving to a new system

All of these kinds of efforts take a lot of preparation and planning.

If that preparation and planning can't start until the software is well and truly finished, the company is giving up a ton of profit opportunity.

(Both because of the delay in achieving revenue or savings, but *also* because, here in reality, all of the above things need to happen iteratively, so it's not a one-time cost, it's a multiplier forever)

If it's going to take a team a year to build something, sales, marketing and/or operational leadership will want to start planning, *way in advance* of the year being up, on how to take advantage of the new software to increase profits.

So they ask for an estimate partly so they can "freeze" "what the software will be", and those other teams can start their work.

Again, the overall answer here is simple. The business as a whole, not just the engineers, face a tradeoff:

 - Wait until the software is fully finished, and pay a high delay cost (and a high missed feedback cost)

 - Restructure the work of the other teams to collaborate much earlier with engineering and product, to start their work before the product is fully finished

So so so easy to say, and yet so so so hard to do.



As a part of this, they tend to want to ask the engineers what the product will actually, y'know, *do*.

** If Only
Look, engineers aren't stupid. They know how hard it is for the rest of the business to deal with the ever-shifting nature of engineering work.

If you could just get three things going, you could partner, you could work together.

The dream.

 - If your stakeholders could *adapt* as you went. Instead of trying to make all the decisions up front, you could learn as you went, together

 - If your stakeholders could actually share enough context, you could be much more creative in coming up with solutions for them

 - If your stakeholders would actually be willing to steadily pay down tech debt, you'd see the benefits together

But how on earth can you get there, starting with someone staring at you, demanding a commitment.

Let's dig into each of those.

* Alternate Titles
** The Root Cause & The Fundamental Solution
** A Root Cause & A Fundamental Solution
** The Root Causes of Conflict
** Why Does Love Got To Be So Hard
