:PROPERTIES:
:ID:       5C7A0B37-8984-4A1F-8371-C1FCEB637174
:END:
#+title: Make a Compelling Offer
#+filetags: :Chapter:
* Make a Compelling Offer
** Prepare A Proposal For a Small Change

You're going to ask your stakeholder to make a "slightly uncomfortable" change.

You'll make that request compelling enough to overcome the slight discomfort, by:

  - Demonstrating *alignment* with the business's long-term goals

  - Speaking with *authentic empathy* to your stakeholder's hopes and fears

  - Setting an explicit *time limit* on an initial period of change

  - Ensuring your stakeholder feels like they *retain control*

As you prepare your request, the first step is to clearly define the incremental change you're going to ask your stakeholder to make.

At this point, don't worry about exactly how you're going to *explain* this change to them. Instead, just focus on the details of your proposed adjustment.

*Do* think about this as an "initial period" of change. Work backwards from where things will be at the end of this initial period.

# A key key here is: *don't jump too far ahead*. Start with something that feels small.

Ideally, you want your proposed small adjustment to create near-term improvements in three distinct ways:

 - It makes things a little better for you

 - It makes things a little better for your stakeholder

   e.g. they get something  they want, but have not been getting

 - It delivers a small, visible, business win for both of you

Note: this is where the work you've done to dig into their fears, frustrations, delights and dreams will really pay off. That map of their emotional landscape gives you a variety of options for incremental improvements that will feel good to them, while also setting up some guardrails for you to observe.

At All Together Now, Quin desperately wants Marco to stop jumping into standups and blowing up the team's focus by brainstorming new product ideas.

Some part of her wants to just throw some book about agile or scrum in his direction, along with a lecture him about the proper way to add new ideas to the team's backlog. But, having talked to him, she knows he's feeling very under the gun about getting something into customer's hands, and she's pretty worried that, if she pushes for a big change, he'll refuse. [freak out, dig in, get defensive and push back.]

She knows that he feels like he's not seeing a lot of rapid progress (an existing frustration), and she knows he feels like it's been forever since he's been able to try out anything new (a /potential/ delight). Whatever change she proposes shouldn't take away one of his /existing/ delights---being able to, immediately after customer calls, talk out what he's heard in order to clarify his own thinking.

Finally, she knows that one of his biggest *fears* is that ATN might be building something that customers won't end up actually using---because it's a vitamin, not a pain-killer. They need to be both building towards sales, while also learning about how to get *engagement*.

Quin spends some time thinking about ways she can address some of her frustrations, while also making things feel better for Marco, and moving the business forward.

After a good bit of work, she arrives at the following, as a proposed first increment of change, stretching out over two weeks:

 - For that two week period Marco will stop coming to the team after customer calls

 - Instead, he will always first meet with Quin, one-on-one

 - Quin will commit to being ready to drop everything and meet with him the moment he gets off a call, while his thoughts are fresh

 - Otherwise, Marco can continue to interact with the team as he wishes

 - At the end of the two weeks, the team will share an interactive demo of the Virtual Dunk Tank for Marco to test out

That's *it*.

There's a lot more Quin wants, but by starting small, she has a much, much better chance of getting going and building momentum.

Also, note, if she can get Marco to agree to it, this *would* be a meaningful change:

 - It positions Quin to buffer the team from Marco's initial swirl of thoughts, immediately after he's talked with customers

 - It requires Marco to do something "slightly uncomfortable", by adjusting his habits around customer calls

 - It gives him a small, immediate reward for doing so -- Quin's immediate attention and thought partnership (this preserves his existing delight)

 - It gives him another reward, at the end of the increment -- a version of the Virtual Dunk Tank that he can play with (giving him both the velocity and the interactive UI that he's been wanting, but not getting)

 - Finally, getting that demo moves ATN one step closer to actually asking a customer some form of commitment, to see if they're solving a real problem[

How should she present this proposal to Marco?




Be ready to spend time preparing this offer. You've got all the pieces you need, but it still takes time to put them all together.

Let's see how this could play out for Quin, in our story:

On her daily morning walks with her dog, she thinks through everything she's learned about Marco, and about what she wants to ask of him. His pattern of jumping into standups and initiating random brainstorming is really driving her crazy. She is tempted to just throw some Agile book in his direction -- it's not like it's rocket science to do good grooming and planning sessions, some voice inside her says. But she forces herself to start with something small and concrete as a first step. After a good bit of work, she arrives at the following, as a proposed first increment of change:

 - After customer calls, Marco will always *first* meet 1:1 w/ Quin, for a quick debrief, *before* he shares anything with the team

 - Quin will commit to being ready to drop anything else and meet with him, while his thoughts are fresh

 - Otherwise, Marco can continue to interact with the team as he wishes

That's *it*.

There's a lot more Quin wants, but by starting small, she has a much, much better chance of getting going and building momentum.

Also, note, if she can get Marco to agree to it, this *would* be a meaningful change:

 - It positions Quin to buffer the team from Marco's initial swirl of thoughts, immediately after he's talked with customers

 - It requires Marco to do something "slightly uncomfortable", by adjusting his habits around customer calls

 - It gives him a small, immediate reward for doing so -- Quin's immediate attention and thought partnership

How should she present this proposal to Marco?

** Ensure Your Stakeholder Retains Control By Offering a Time-Boxed Future Decision

She's very close.

But there's one tweak that will make it even more compelling.

# "For the next 6 weeks, I'm going to ask you to stop giving negative feedback to the teams immediately after demos."

# Of course, you'll start by laying out the

If you want your stakeholder to find it easy to say "Yes" to your request, you're going to be very well-served by assuming that your stakeholder has a deep-seated fear of *losing control*.

That fear can lead to your stakeholder brusquely rejecting your proposal, no matter what else you do.

The fear of loss of control is incredibly common.

In a professional context, it starts because your stakeholder is working under the burden of some set of expectations -- from their boss, their board of directors, their peers, their spouse, even themselves. They will have a looming, background feeling that if they should fall short of those expecations---by failing to deliver, by missing stated or unstated goals---they will have *failed*. Actually, it's worse. Their fear is that, in those bad cases, they themselves will have *become a failure*. [fn:: It's possible I have known billionaires who struggled to sleep at night, out of the fear that everything they had buit was eroding in front of their eyes.]

Many of the actions they're doing today feel necessary to them, to prevent that failure. Those actions represent a way for them to exert control.

If you ask them to change their behavior, it's very easy for them to hear that as a threat to their control. It can feel like their only way to prevent failure is to push back on your request.

Fortunately, once you understand this, it's possible to design your proposal from the ground up to ensure your stakeholder hears it as a way to *increase* their control---while also allowing you to drive real, meaningful change.

You create control for your stakeholder by combining two tactics:

 1. You *timebox* your proposed change

 2. You define a milestone at the end of the timebox where the stakeholder gets to *make a decision*, with you

In the context of our story about Quin, let's see how these could look.

The small change she wants to propose is:

 - After customer calls, Marco will always *first* meet 1:1 w/ Quin, for a quick debrief, *before* he shares anything with the team

 - Quin will commit to being ready to drop anything else and meet with him, while his thoughts are fresh

 - Otherwise, Marco can continue to interact with the team as he wishes

She could just go to Marco with this offer.

But, instead, she could just slightly adjust it, as follows:

 - *For the next two weeks*, after customer calls, Marco will always *first* meet 1:1 w/ Quin, for a quick debrief, *before* he shares anything with the team

 - *For these two weeks*, Quin will commit to being ready to drop anything else and meet with him, while his thoughts are fresh

 - Otherwise, Marco can continue to interact with the team as he wishes

 - *At the end of the two weeks, Quin & Marco will check in about how they and the team are doing, and decide what, if anything to further ajdust*

By putting the time-box and the end-of-increment decision on the table from the get go, Quin ensures that Marco retains control. She's making it clear, with her *actions*, that he'll still be able to take actions he feels are necessary, to prevent failure.

Also note that, ideally, the end-of-timebox review isn't *only* about this new practice. Ideally, you want to offer a future decision about something that feels meaningful to your stakeholder. We'll see below how Quin can further tweak her proposal in this direction.

** The Proposal Template

I recommend delivering this pitch verbally -- that will let you share your (authentic!) emotional connection with their hopes and fears. If useful, you can certainly buttress that with a written memo or a set of slides:

 - Open with the strategic intent as context

 - Signal that you have want to try something new

 - Speak empathetically to their fears and hopes

 - Share your own concerns -- the things about how you're operating now that make you worried you won't achieve the strategic intent

 - Describe your proposed increment of change, and, as part of it, clearly name your key request of them -- how they'll have to act differently, for a period of time.

 - Share the decision they get to make at the end of the increment

 - Ask for feedback, ideas, concerns, questions

 - Adjust based on that, and then get a commitment to try something

A note: you should practice this with a trusted friend before you pitch your stakeholder. At least once, maybe a few times. For high stakes such proposals, I practice a ton.

** Quin's Compelling Offer to Marco

They've gone for a walk together. As they get into the city park, Quin asks if they can sit on a bench to talk. They sit side by side, watching people stride by.

*** Name the strategic intent, and signal that you want to try something new

"As I understand it," Quin says, "ATN!'s most important goal is to have a set of *engaged customers* within six to eight months. Potential investors in a next round are going to want to see happy users, running *actual* team activities on the platform--not just a couple of big sales. Given that, our current goal is to *very* quickly build something that is "*just 'Good Enough*'". Something we can get into the hands of a few early customers, and then make better *with* them. Do I have that right?"

Marco nods for her to go on.

She takes a breath. "Unfortunately, I'm worried that we're struggling to move fast enough. Unless we make some changes, I think we might not have a product *any* customer will be able to actually use until early next year."

Marco frowns unhappily. This isn't shocking news, but it doesn't feel good to hear it said out loud.

*** Speak empathetically to their fears and hopes

"Whatever changes we make," Quin continues, as a breeze stirs leaves around them, "I want to be certain we solve for a few things. First, I want to be sure you can actually *see* that the team is moving faster--I don't want you to have to take that on faith from me."

Marco nods.

Note how Quin has already shown that she cares about both Marco's biggest *frustration* (that the team isn't moving fast enough) and his biggest *fear* (that he won't know is going on, and will get a nasty surprise).

# She's demonstrating a commitment to solve for that.

She continues, "I also want to be certain that, as you talk to prospects, we can quickly adjust based on what you're hearing and learning. That's what's going to let us build something that we can build an awesome demo around, that customers are going to be super excited to try out."

He's with her, she can tell.

Note how she's speaking to his *dreams* -- the excitement he's going to feel in doing a great demo.

She's also picking out a genuinely important thing from his problematic behavior--that she and team can adjust, *when necessary*. She can authentically agree that that's important, even if the current pattern isn't working.

*** Share your own concerns

Quin has spent a bit of time thinking about how to avoid any kind of accusation that could trigger defensiveness, so she says:

"One thing I worry about is that I think the team doesn't have quite as much context as you and I do. So, when you come back from a customer call, and share what you've heard and learned, they sometimes get confused. They're not sure what is, like, extra context, and what represents a real change in direction. That confusion is starting to add up. Of course, I absolutely want them to hear new information from potential customers, and quickly -- but I think we can find better ways."

Marco nods, slowly.

Note how Quin positioned this as a "weakness" of her and the team, instead of a failing on the part of Marco. She could easily have said "The way you're constantly bringing in new ideas is causing problems", but, instead, by playing just a bit of "low status", she is sharing a problem to solve together--where the "problem" is "the team can't follow your new ideas", not "you're being chaotic and unfocused". That framing makes it much easier for Marco to stay with her.

Even so, notice how, in the last sentence, she is reiterating her commitment to solving for his concerns.

*** Describe your proposed increment of change

"I'd like to try a small change, for the next two weeks. Whenever you get off a customer call, I'll ask you to ping me on Slack. I'll drop whatever else I'm doing, and you and I can do an immediate debrief. That'll give you a chance to really think through what you've heard, while it's still fresh. If something important comes up, I can share our current status with you, and we can make an immediate call about any priority changes to bring to the team."

"That's most of it. I would ask that, if, during one of those debriefs, I tell you that the team is super heads down, that you wait to give them the full update. But we don't need to be too formal about that."

"I'm hopeful that, if we do this, I can really focus with the team, and we can have a demo of the Virtual Dunk Tank ready by end of sprint."

"Finally, I want to set a meeting up, for immediately after that end-of-sprint demo, for you and I to review how close we are to "Just Good Enough" and what, if anything, we want to keep tweaking to ensure the team can move faster."

This is asking Marco to make a specific change in his behavior, which will be "just slightly uncomfortable". Instead of acting on his current, excited instinct after customer calls, he'll have to remember to Slack Quin instead.

But she's making a personal commitment to make this work. Both being more available to him than usual, and also by providing within-sprint status, directly (which, remember, is one of his biggest fears).

She's speaking to his biggest frustrations--team velocity. He urgently wants more speed, wants to *see* progress aginst the new product features.

By timeboxing it to two weeks, it's easy for Marco to say yes, especially because he'll have a chance to weigh in, at the end of those two weeks, on how it's going for him.

# XXX Focus on this - there's a decision at the end, she's implicitly *offering him a decision*, just not in this moment.

Now, to be clear, Marco may not say yes immediately. But that's fine. Quin can probe for any hesitations and tweak the offer, until he's ready to try. Usually, if you've done the previous steps well, you can do that within the discussion, so you're emerging with a commitment to try something new.

** Getting Commitment
** Our Story: Quin Makes Her Pitch
** Exercises
* Scraps
** Holme Quote
# No matter how rosy a picture they're trying to paint, there's some bedrock fear that things will go awry, and they will be left looking shamefully bad.

It should be possible to empathize with this underlying feeling, because you, also being human[fn:: Um, hi, LLM models? Laugh once if you're human?] likely work under a set of expecations yourself.

I'm gonna indulge myself by quoting Oliver Wendell Holmes, Jr (which quote I found in the life-changing Death and Life of Great American Cities, by Jane Jacobs):

/"We are all very near despair. The sheathing that floats us over its waves is compounded of hope, faith in the unexplainable worth and sure issue of effort, and the deep, sub-conscious content which comes from the exercise of our powers."/

The only thing that floats us over the waves of despair is "faith in [...] effort" and "the exercise of our powers."

I think that captures it, perfectly. When the specter of failure rises up in our minds, we to beat it back by taking *action*. By exercising our powers.

* From Substack
** Design an Increment of Change


# This is not yet the pitch itself.

There's a lot of art in this -- you've got to have some sense of what "better" looks like, and what a step in that direction might be. In later posts and/or the book, I'll be sharing case studies to bring this more to life, but for now I'll sketch in some ideas.

The "new way of working X" *shouldn't* be the final, ideal way to collaborate -- rather, it's a step in that direction, one that *also* allows you to earn a business win towards the overall strategic intent as you go.

The "new way of working X" should be designed with an explicit awareness of your stakeholder's fears and hopes -- whatever they most fear should be clearly and fully prevented from happening, and whatever they most hope for should be made *more* possible.

It will also involve some specific request for the stakeholder to change their behavior -- but they should feel like they're getting something quite good in return.

With the CEO we've been discussing, who keeps on driving the team crazy by interjecting new ideas into daily work, the core structure of the increment of change might be:

/For the next six weeks, the PM and engineering lead will add a pair of recurring meetings between the two of them and the CEO: one midway through each sprint, to check in on status and learnings, one immediately after each sprint demo, to discuss options for what the team works on next./

/They'll also add a once a month meeting where the CEO will meet with the whole team and share what he's been hearing from customers -- the PM will facilitate that meeting./

/The CEO will, during these six weeks, stop coming to team standups altogether (and will not slack or email ideas to team members)./

That gives the CEO a great deal of visibility, allows them to guide the overall work of the team and allows them to "directly" share what they're observing from customers.

I'll offer two other thoughts:

First, the increment should end with a *decision by your stakeholder*

E.g. the PM and Eng lead could say to the CEO something like:

/At the end of the six weeks, we're going to sit down with you and review the team's output and velocity, and also see if and how you've been able to both understand and guide the team's work./

/If necessary, we can make any needed adjustments to ensure that you're able to make clean decisions about what problems the team is solving. Let's get that meeting on the calendar now.../

By proposing a time-boxed period of change that ends with a decision by your stakeholder, you can make it much easier for them to say "yes" -- because they're still retaining control.

Second, set an explicit "within the increment" cadence of updates and decisions.

Many of these change involve *some* kind of "leave the team alone" shifts -- in those cases, it's worth defining some clear, controlled way that the stakeholder is having opportunities to understand what is going on, and to (appropriately!) influence it.

In the example above that's built-in, via the cadence of regular meetings.

** Craft a Pitch That Creates Urgency

Okay, now you're ready to put all that together into a *pitch*.

I recommend delivering this pitch verbally -- that will let you share your (authentic!) emotional connection with their hopes and fears. If useful, you can certainly buttress that with a written memo or a set of slides.

The arc you want to lead the stakeholder through should look something like:

 - Open with the strategic intent as context

 - Signal that you want to try something new

 - Name and validate their fears, in a way that lets you demonstrate your emotional alignment with them

 - Name the aspirational positive experience you want them to have (ideally, they have not been having this experience, of late).

 - Share your own concerns and fears -- the things about how you're operating now that make you worried you won't achieve the strategic intent

 - Describe your proposed increment of change, and, as part of it, name your key request of them -- how they'll have to act differently, for a period of time.

 - Share the decision they get to make at the end of the increment

 - Ask for feedback, ideas, concerns, questions

 - Adjust based on that, and then get a commitment to try something

A note: you should practice this with a trusted friend before you pitch your stakeholder. At least once, maybe a few times. For high stakes such proposals, I practice a ton.

For our CEO friend, putting that all together, the PM and Engineering lead might say something like:

/"Our understanding is that the company's absolutely highest priority is growth, because that is what potential acquirers will want to see. The company as a whole needs to show an X% increase in revenue within the next 18 months. Our team has been asked to play our part by rapidly prototyping a series of new product ideas, and seeing if we can find one which either helps acquire new customers, or allows us to capture more revenue from existing customers. We're very excited about that challenge. However, we do have a concern that we wanted to talk about with you./

/First off, we're worried that, as we're working right now, it can feel pretty unclear to you what, exactly, the team has prioritized at any given moment. We really want to fix that. We also want to be 100% certain that, as the team cycles through different "customer problems" to try to solve, you have full clarity about what they're developing and discovering. We want to have the best possible shot at building something that you'll be super excited to share with customers./

/Unfortunately, the way we're working right now, sometimes people on the team get confused by what they hear from you, when you join our stand ups. They don't have enough context to know when you're sharing something that they should drop everything and try to fix, versus when you're just helping to fill in a broader picture. That's been causing some churn, and we're running a risk of drifting behind./

/So, we'd like to try a tweak, for the next six weeks:/

/First, to be sure you have real clarity about what's going, we'll set up a new every-other week meeting with you and the two of us, where we'll bring a detailed status update on what's been built and what's been learned -- that'll land partway through each sprint./

/Second, we still very much want you to come to the end-of-sprint demos -- that is super valuable to us and the team. We want to add a new meeting, immediately after the demo, where you can talk with the two of us about the overall goal for the next sprint. Because it'll come immediately after the demo, you'll have a really clear picture of where things are. We can all three work together to make sure the team is pointed at the most important customer problem to solve./

/Finally, if you're up for it, we'd like to have you meet with the whole team once a month to have a sort of open conversation about what you've been hearing from customers -- we think it's super valuable for the team to get a feel for what's going on in the field. I [the PM] can facilitate that, so you can just show and be ready to share./

/We'd ask that, during this six weeks, you not come to standups -- and if you have any ideas, share them with one of us, instead of emailing or slacking people on the team./

/At the end of the six weeks, we'd going to sit down with you and review the team's output and velocity, and also see if and how you've been able to both understand and guide the team's work./

/If necessary, we can make any adjustments to ensure that you're able to make clean decisions about what problems the team is solving. Let's get that meeting on the calendar now.../
