:PROPERTIES:
:ID:       ABD361FC-738D-440C-8778-4584C38EE0B1
:END:
#+title: Beta Reading Instructions
Dear Review Reader:

First off, thanks so much for taking a look.

Second off, I wanted to share some more info on the feedback I'm most eager for, at this stage.

Most centrally, I'm looking to learn if the book, in its current somewhat rough form, is *useful*. I'm genuinely not sure I'm there yet, so that's what I'm really focused on.

That said, it's definitely *not* polished. So, no need to flag typos (of which there are plennnnty).

Some questions I'd love your take on are:

 - Where does the book get at all confusing?

 - Where does the book get at all, well, boring?

   This might present as: a part where it was "easy to stop reading", or where you found yourself thinking "Fine, fine, I'd like to skip ahead".

   THIS IS SO USEFUL FOR ME TO LEARN!

 - Is there anything you found particularly interesting or useful?

 - Do I say things you're not sure you agree with? Do I leave anything super important out?

 - Is there someone you'd like to share it with? If so, why?

You can leave inline comments using the HelpThisBook tool -- I'm also happy to read anything you want to email me, at milstein.dan@gmail.com.

Thanks so much again,
-Dan
