:PROPERTIES:
:ID:       47FF75F6-17DB-4E36-950D-F7CFAFA950EA
:END:
#+title: Intro Chapter
#+filetags: :Chapter:
* Outline from ToC
** Stakeholders Scream About Features, the Team Screams About Tech Debt: The Joy of Engineering Leadership
# Statement of empathy, touching on a bunch of the human experience + potential failure modes.
** Why the "Tech Debt" Metaphor Has Become Limiting
# Sketch in the key problems (focus on "bad code", offers nothing positive to your product or stakeholder peers, don't go too deep on moral vs economic)
** A Better Way: Technical Investments
# Give the definition
** What If My Stakeholders Don't Care About Engineering?
** What If My Engineers Don't Care About the Business?
# Aka, what if my very senior engineer just wants to rewrite everything?
** What's Coming In the Rest of the Book


* Writing the Thing
** Stakeholders Scream About Features, the Team Screams About Tech Debt: The Joy of Engineering Leadership
# What does it mean to be an engineering leader?

# Fundamentally, it means being pulled in two different directions at once.

Stop me if you've heard this one before.

At this very moment, your stakeholders--the product team, executives at your company, operational users--are urgently demanding that your team deliver an ambitious set of *features*.

# absolutely as soon as possible.

# And, what's more, you're behind

Those stakeholders are certain that if the features aren't shipped *right this minute*, the business is going to suffer, and badly.

At the very same time, the engineers *on* your team are demanding that you carve out time, *now and not later*, to deal with a teetering pile of tech debt.

The engineers are equally certain that, if they don't have a chance to clean up some of the buggy, insecure, utterly inscrutable legacy code, the business is going to suffer, and badly.

So, what do you do?

First, I have some bad news.

# For all their hysterical urgency, the stakeholders are usually representing genuine needs of the business.

For all their hysterical urgency, the stakeholders are... not totally wrong.

# "are not totally wrong"?

# As you've moved up into engineering leadership, you've come to realize that
A lot of business opportunities *are* time-sensitve -- not having the new features shipped in time for a scheduled launch or an upcoming peak season will represent a big, visible missed opportunity.

# [One of the features of getting into leadership is often getting a clearer picture of those opportunities, *and* the expectations around them]

Except people in the business won't call it a "visible missed opportunity".

They'll call it a failure.

More specifically, since you're the engineering leader, they'll call it *your* failure (being in charge means failures are your fault! Like, that's literally and precisely what it means!).

You have the potential for failure hanging over you, all the time.

But, wait, I have *more* bad news.

The engineers who want to slow down and deal with tech debt... *also* aren't wrong.

If you simply race to build the features that stakeholders demand, you're going to end up with a system that fails in some very exciting way at the worst possible time.

Maybe it'll suffer a spectacular outage just as your peak season starts.

Or maybe you'll experience a painful security breach just as your sales team is trying to close that one extra security-conscious enterprise customer.

Or maybe the overall system will just become so difficult to safely change that the pace of delivery grinds to a halt (and your engineers lose all respect for you, and the very best ones start not deleting the recruiter emails they get every day).

All of those are *also* your (potential) failures.

# This doesn't even speak about the trust and respect of your engineers -- which you need to maintain to be effective.

# And of course, you can also feel the trust that your engineers have in you eroding over time, as they see you not use your authority to advocate for the crucial technical work.

So, again, what do you do?

# I have an answer.

** Um, Who Are You, Exactly?

Hi, my name is Dan.

For the last 30 years, I've worked in various combinations of engineering and product -- I love both discplines, and value both super highly.

I've worked as an senior IC engineer building and operating complex systems; I've led product at startups desperately trying to find traction; I've managed engineering teams ranging in size from 2 to 500.

Across it all, I constantly wrestled with this tradeoff between what was being explicitly asked for versus what engineers believed was important.

# were worried about.

I've tried a slew of things to manage that tradeoff -- many of which failed, some in interesting and instructive ways.

# works, first with a small group of engineers, and then, as I moved up in various organizations, across a much larger team.

# This book is sharing what I have learned.

# Fortunately, there's a way to approach this challenge so that, over time, you gradually bring those two sides together.

# so that all sides are *participating a collaborative discussion about how best to spend your team's time*.

Over time, I gradually found an approach that brings the two sides together, into a collaborative discussion about how best to spend the engineering team's time.

# Personally coached
# I've seen engineering leaders apply this approach to:
I've seen engineering leaders apply this approach to:

 - Visibly improve their systems

 - Build trust with their stakeholders

 - Create meaningful agency for their engineers

All while steering clear of the terrifying fire swamp of a ground-up rewrite.

I want to share that approach with you.

But...

# Where do we start?

# First, we all have to
The first step is to *stop talking about technical debt.*

** Avoid the "Tech Debt" Metaphor

I believe that, although "technical debt" started as a useful metaphor about economic tradeoffs, it has, over time, largely devolved into a shorthand for *"bad" code*.

As in, when engineers think, talk and argue about "tech debt", they're thinking, talking and arguing about the very worst, most horrifying code in their codebases.

There are two reasons why this causes problems.

First, by only thinking about *existing bad code*, the engineers miss a vast set of opportunties for improvements.

Over and over in my career, I've seen engineers propose and then deliver incredibly valuable work that involved writing *new code*.

And, pretty often that meant writing *more bad code* (of course, no one called it "bad" -- we called it "scrappy" or "pragmatic").

Those opportunities just don't come up much, when you start the conversation by talking about "technical debt".

# I could show you bash scripts that would make your eyes bleed, but that were just insanely valuable.

# E.g. the junior engineer who hacked something together over the weekend to log stack traces from failed deploys, or the senior engineer who bargained for enough time from their PM to jury-rig a hacky testing framework that stubbed out the entire OS layer, or the engineer who threw together a UI to allow members of the ops team to clean up failed shipments, so that the engineers could stop spending all their time executing SQL queries against production.

E.g. the junior engineer who hacked something together over the weekend to log stack traces from failed deploys... which saved hours and hours of fruitless debugging and ultimately sped up deploys enormously.

Or the senior engineer who bargained for enough time from their PM to jury-rig a hacky testing framework that stubbed out the entire OS layer... which allowed the team to finally write tests to cover the weird network errors that kept tripping them up.

Or the engineer who threw together a UI to allow members of the ops team to clean up failed shipments, so that the engineers could stop spending all their time executing SQL queries against production.

Note, carefully: *none of the above efforts "retired tech debt"*.

The problems addressed -- unreliable deploys, blind spots in testing, repetitive operational work -- aren't the kinds of things most engineers think of when you're talking about "tech debt".

The above efforts helped deal with *gaps* that the engineers were painfully aware of.

Crucially, those gaps represent *genuine problems* for their businesses.

In later chapters, we'll explore how such gaps aren't just *annoying* to the engineers, they are in fact *expensive* for the business.

And thus, dealing with such problems is a chance to *create value* for the business.

Unfortunately, engineers rarely identify and advocate for such forms of value, when they're thinking about "tech debt".

So, that's the first reason to not use the metaphor -- because it tends to focus on too narrow a kind of potential improvement.

The second is a bit more subtle, and has to do with the conversations you'll get into with your stakeholders.

*** Lo, Let Us See This From the Stakeholder's Perspective

Any stakeholder who has worked with engineers for any length of time knows about "tech debt".

When the team asks for time to deal with "tech debt", the stakeholder hears a request to give up something they actively want (the requested features), for something that will create *no visible value* (reducing the amount of "bad code" in the system).

The stakeholder does not, in general, experience it as an economic argument where they'll get something they understand as valuable in return for what they're giving up.

This is in part because some engineers have strong emotions about how bad the technical debt is (again, because they're talking about "bad code")

They'll sometimes feel like *they shouldn't have to explain why fixing bad code is valuable*.

# Maybe, combined with frustrations over not being able to do what they perceive as important..

They might say or feel:

Why should they have to *prove themselves* to the stakeholders?

Shouldn't they be *trusted* to know what good code is? Isn't that their job?

When engineers fall back on their technical authority like this, they are essentially saying:

/Bad code is bad because it is bad, and getting rid of it is an inherently good thing, and you have to just trust us./

A student of human nature would say that they are framing this as *moral decision* -- a question of right vs wrong.

Unfortunately, that kind of moral framing is a reliably terrible starting point for conversations with stakeholders.

Both sides will usually exit such conversations feeling very frustrated.

# TODO open this up a bit, play out the convo, even if it gets to a one-time agreement, it's a concession, etc.

# See my talk [[https://www.youtube.com/watch?v=78qzrXIPn5Q][How to Run a 5 Whys (With Humans, Not Robots)]] for more on the moral vs economic mindsets (and also for a somewhat dramatically hilarious mustache I briefly adopted in late 2012).

The engineers, even if they extract some amount of time to work on the issues they're worried about, will feel like their stakeholders don't care about the horrible code they have to work with, nor the looming problems getting worse with every commit.

The stakeholders, even if most of the engineering capacity is still devoted to the features they're want, will experience the engineers as just completely unaware of the pressing needs of the business, and of the very real costs of slowing down. They will be girding themselves to push back the next time the engineers make their urgent demands in service of an abstract notion of "quality".

By starting with tech debt, with its underpinnings of "good" vs "bad" code, you're just inviting the moral frame and the resulting oppositional arguments.

The poor engineering leader will find themselves caught between the two sides, making both unhappy.

So, if talking about "tech debt" causes problems, what's the alternative?

** Talk Instead About "Technical Investments"

Instead of technical debt, engineering leaders can challenge their teams to talk about *technical investments*, which we'll define as:

/Work the engineers believe is *valuable for the business*, but that *no one is asking for*./

That puts the focus on the genuine problem: a *mismatch in understanding* between the engineers and their stakeholders, about what is *potentially valuable* for the business.

At heart, the vast majority of both engineers and stakeholders want to create value for the business.

They just have different information and beliefs about how best to do so.

Many engineers try to resolve this gap by *explaining* the potential value: "You see, when code has bad 'coupling', a change in one place can impact many other places, which is a drag on development. This is why we should spend a week refactoring."

Although there's a good instinct in this -- bringing the stakeholders into a shared understanding with the engineers about what is valuable -- it has one crucial flaw:

It requires the stakeholders to take the entire statement of value on faith.

There is nothing they can *see*, that shows them things are "bad", before the investment is made.

And there will be nothing they can *see*, after, that shows them things have gotten "better".

Given that lack of visibility, it's hardly surprising that stakeholders, confronted with such a choice, often feel like they are giving something up and getting nothing in return.

One of the core theses of this book is that engineering leaders can *build visibility* into potential value.

That way the engineers and their stakeholders can look at something, *together* -- a shared understanding of the reality the business is currently.

both when deciding what work to prioritize, and after an investment, to see if things have improved.

Having that shared visibility can be an absolute game changer.

Stakeholders like to make decisions about what's best for the business. That's their job. By creating visibility, you're allowing them to make better decisions.

An example to bring it to life:

# Change to: at a recent job, the engineers were super frustrated by

Maybe the engineers are frustrated by the flaky Selenium tests that keep on stalling out their attempts to deploy the main app to production.

They're not just complaining (though, don't get me wrong, the #deploy-sucks Slack channel is just a bloodbath of angry emojis)...

...they're starting to batch up changes into One Big Deploy per week, to avoid dealing with the pain.

In such a case case, you can build visibility by starting to track both:

 - The time to deploy a single change

 - The average number of deploys per engineer per week

(You may recognize those as two of the four golden Accelerate metrics, we'll return to those later)

A key: you can *start small*

At at a recent job, we didn't have a good way to track the end-to-end times of the hodgepodge of jobs that had to be run for a full deploy.

One afternoon, while waiting, *again*, for a deploy to finish, a very bright and very frustrated engineer threw together a spreadsheet (I think she called it "Deploy Misery") and asked all the engineers on the team to just manually log their deploy times in it.

That took her about 10 minutes to do (couting the, um, vigorous email she sent all of engineering). The engineers were plenty motivated to track their deploys... and had plenty of time to do so, while waiting for the tests to finally pass.

After a few short weeks, the engineering manager brought that spreadsheet to the product team. Looking at how miserably long it was taking to get changes out to product, it was pretty easy to convince the product team to carve out a week for that same engineer to instrument a few key stages of the deploy process, so they could actually understand where time was being spent.

Which then led to more investments, etc.

It is just about always *massively cheaper* to build visibility than it is to make the full investment -- e.g. making the spreadsheet was much cheaper than instrumenting the pipeline which was itself much cheaper than overhauling the flaky tests.

The very best way to run tech investments is to do them *iteratively*:

 1- Spend a *small increment* of time to build *some* visibility

 2- Share that visibility with your stakeholders

 3- Together, prioritize an incremental investment to either visibly improve *or* to build the next increment of visibility

 4- Return to step 1





There are two separate challenges with bringing stakeholders along:

 - Helping them *understand* the potential value

 - Making it possible for them to *see* the potential value

That second one is profoundly powerful -- it allows you to convert from the "just trust us" moral argument to a collaborative review of a *shared view of reality*.

Exploring that defintion leads to the fundamental "technical investment cycle":

 - Collect a set of issues the engineers are worried about or frustrated by

 - For each, turn it into a statement of potential value

(it's a repeated cycle, not a one-time thing -- companies are constantly deciding how and what to next invest in, it's not a one-time "cleaning up of technical debt" or "paying off a loan")
Thus, a profoundly powerful trick is to start by *building visibility* -- something that the stakeholders and engineers can both *see* in the same way.

Usually, it's several orders of magnitude cheaper to build such visibility, than it is to execute on the actual work.

To bring the two sides together, engineering leaders must develop a deep understanding of how engineers can create value for a business.

We'll spend a great deal of part 1 (The Technical Investment Cycle) talking about the marriage of visibility and value.

Engineering leaders also have to be willing to *educate* their business peers -- and those business peers have to be willing to listen.

# Eh, this isn't quite right.

That requires a steady building of trust, which we'll talk about in part 2 - Scaling Up.

** What If My Stakeholders Don't Care About Engineering?
But wait, I can hear many of you saying, I don't know what delusional hippies you've worked with Dan, but you've apparently never met my stakeholders. They just don't care about quality at all, and there's no way I can make them.

First off, I also don't care about quality! (I joking-not-joking forbid discussions of quality on my teams).

But maybe what you're saying is: if you try to offer your stakeholder a tradeoff, where pursuing features now has a cost later that they have to sign up for, they reject that discussion.

I'm not going to lie -- there *are* some business leaders who are just profoundly unwilling to face tradeoffs, and worse, take pride in doing so. Such leaders think of their relationship with engineering as one of extracting "commitments", and then holding the engineers "accountable".

But here's the thing: the whole commitments/accountability/shame thing is an *objectively bad interface* with an engineering team.

Like, it's not just unpleasant, it will consistently lead to bad business outcomes.

In the vast majority of cases, stakeholders, well, want the business to succeed

(if they just want to advance their own career by showing they can crack the whip on engineers... you might need to find a new job).

If you follow the game plan in this book, you'll be offering your stakeholders something they will love -- a combination of meaningful *visibility* with meaningful *control*.

And you'll do so in a way which steadily builds trust and rapport.

** What If My Engineers Don't Care About the Business?

This overall approach does assume that the engineers care about "creating value for the business".

Again, I'm not going to lie. There are some engineers who truly don't care about the businesses they work in, and only want to pad their resume with cutting-edge technologies or impress other engineers with the clever complexity of the code they write.

# Footnote: maybe don't hire those engineers? That's the subject of another book.

But the vast majority of engineers are, in my experience, profoundly motivated to *solve problems*.

The rest of this book is going to explore a slew of ways to point them at the fascinating, profoundly difficult problem of creating as much value for the business as possible.

Let's go!
