:PROPERTIES:
:ID:       47DD5FFD-3D09-4A7B-890E-2C5933D583BB
:END:
#+title: Mastering The Art of Divining Emotions
#+filetags: :Chapter:
* Mastering The Art of Divining Emotions
** Deliberate Practice Is Almost Definitely Required

Being able to empathetically draw out emotions is *extremely* powerful, but it takes real practice to master, for (at least!) three reasons.

First, many of us have learned to *not* talk to other people about their feelings, especially people who seem upset or angry (and especially especially people who have any form of power over us). With experience, you'll find that successfully drawing out and validating emotions makes pretty much all humans feel good.[fn:: Chris Voss successfully uses exactly these tactics to build rapport with desperate, armed, hostage-taking criminals barricaded behind a locked door.] Once you experience these tactics as /defusing/ tension and anger, "talking about emotions" won't feel so risky. But you have to build up that personal, direct experience, to retrain your brain. In the exercises below, we'll build up our skills gradually, for exactly this reason.

Second, several steps require extremely precise language and timing. It can be hard to access the exact language and timing in the midst of a high-stakes conversation with your stakeholder. You'll want to rehearse enough so that you can successfully go through the precise steps even when your internal emotional dial is pegged to eleven.

Finally, it takes work to learn how to develop a detailed, empathetic description of a situation. To be able to frame the situation such that some feeling seems inevitable. To enrich your description with vivid details. This is very much a *learnable* skill, but it is not something most people have access to without practice.

# We're going to break the skill down into a series of discrete steps.

** Repeat Trailing Words Throughout Your Day

This one is simple enough that I recommend initially practicing it multiples times a day.

Whenever you can, in whatever conversations you find yourself in, try repeating the last few words someone says to you, inflected as a question. Try it in both professional and personal contexts, try it with your manager, try it with your peers, with your spouse, kids, neighbors.

As you do so, try to:

 - Allow yourself to be in a place of genuine curiosity

 - Say /only/ the last three or four words back

 - Wait silently for a response, even if it feels uncomfortable

Practice over and over. Take some time to reflect on how it feels, and use that reflection to tweak your personal approach.

As you build comfort, you'll find that you can go through multiple rounds of this, in a single conversation, and often get surprisingly deep. If you find you've learned something interesting or moving, try Echoing Back & Summarizing and/or Offering Labeled Feelings.

For an initial, focused period of practice to rewire yourself, aim to do this at least two to three times a day, every day for a week.

** Rehearse A Preface

On your own, test out a couple of different prefaces, e.g.:

 - "It seems like you might feel..."

 - "It would make sense if you were to feel..."

 - "I could imagine you might feel..."

 - "It could be easy to feel..."

 - "If I were in your shoes, I might feel..."

Pick one that feels comfortable to you. Then, rehearse it over and over until you can get through it, precisely word for word, without effort. Make 100% certain you're not dropping any key words: you don't want your brain to silently convert the useful "It seems like you might feel..." to the potentially damaging "I think you feel..."

Inserting this preface is likely to feel a bit unnatural at first. That's okay. Getting the knack of smoothly inserting a preface is like learning a physical skill---it takes practice to make it smooth.

Once you have that mini-script wired into your brain, you can move onto the next step.

** Label With A Friend

Because talking about feelings can feel so loaded, I recommend initially practicing this with a friend. Ask them something like:

"I'm practicing a form of active listening for my job. Can I try something with you?"

Then, tell them you'd like to talk about /their/ work. Ask them one of the following questions, which should help get into issues that have some emotions attached:

 - "Is there anything your boss does that makes your job harder?"

 - "If you could wave a magic wand, and change one thing about your job, what would it be?"

 - "Has anyone made a somewhat unreasonable request of you, lately?"

 - "Is there a project you're worried might go off the rails?"

Be ready to use Repeat Trailing Words to draw them out.

Once they mention something that seems to have any emotions attached, you're going to offer a labeled emotion. If need be, pause them by saying something like, "Hang on, I want to make sure I understand". Then:

 - *Briefly describe their situation*

   Use no more than a few sentences. For example: "Your boss keeps on asking for status meetings with you and your team. You're spending all your time preparing for those meetings, and no one can get anything done."

 - *Bridge to your preface*

   "It seems like you might be feeling..."

 - *Then name a feeling /directly/, as an offer*

   "...pretty frustrated with your boss...?"

Don't let yourself dance around or avoid saying the feeling. Put yourself in a place of curiosity, open with your rehearsed preface and then be *painfully* simple and direct. And then *stop talking*.

# Try to *not* say something like:

# "I'm just wondering, maybe, you said that he kept asking for meetings, like a lot of meetings? That's not great, of course. I sometimes have had that happen. At my last job, ugh. This is for the important project, right? Maybe that, is sometimes, I don't know, maybe a bit, like, frustrating. Or maybe not, maybe it's not that bad? I know you mostly like your boss, right?"

# That kind of scattered talking is the fear taking over your brain. It's telling you that the person won't want to hear their feelings out loud. The fear will desperately try to convince you to stall ("I sometimes have had that happen", "the important project, right?"). The moment say something at all direct, the fear will urge you to immediately walk it back ("Or maybe not...", "you mostly like your boss, right?").

# This is why you're practicing with a friend.

# You have to get yourself into that place of discomfort in speaking directly to emotions, and find a way through it.

Whatever they respond with, nod and agree. Continue on, and then, once you hit another emotion, pause them and offer a labeled emotion.

After you've done a few rounds of this, stop the exercise and ask your friend how it felt. Dig in specifically on whether or not they felt like you understood their situation. Ask if anything you said sounded odd or pushy. Ask if there was anything that was specifically good to hear.

Take the time to notice how *you're* feeling, in the midst of this.

Once you've gotten some practice with the structure, you're ready to use it with your stakeholder

** Prepare An Empathetic Description

As your first step, before you talk with your stakeholder, take some time to develop a "first draft" empathetic description of their situation. You don't have to get this perfectly right, but doing some ahead-of-time work is super useful.

# to put yourself in their shoes will help you very much when you're actually in conversation with them.

Your goal is to come up with a description that makes their frustrating behavior an *inevitable response*.

This doesn't mean justifying their behavior.

It means trying to understand the way the world presents to them. Trying to understand the story they're telling themselves.

# For example, say your stakeholder has a frustrating habit of being angrily unwilling to consider narrowing scope when any challenges arise.

For example, say your stakeholder has a frustrating habit of angrily pushing back whenever you propose narrowing scope to ensure hitting your key deadline.

What might be a way to describe their situation that makes this behavior an inevitable response?

 - Is their boss making unreasonable demands of them to "get everything done", and they don't feel like there's any way they can push back?

 - Did they misunderstand an earlier scoping and estimating exercise, so they're only now realizing that they have overpromised things to other people?

 - Have they experienced so many software projects as failing, they've "learned" that they need to push the engineers?

Again, developing this empathetic statement doesn't mean their behavior is *right*. It means you can see genuinely how it might *seem* right to them, given their context.

Talk this out with people you work with, see if you can learn something new about what might be driving the frustrating feelings and behavior.

** Put It All Together With Your Stakeholder

Find a time you can talk with your stakeholder, where you can, as much as possible, minimize external distractions. Then:

 - *Ask about a situation they are in*

   Started by asking an open-ended question, e.g. "How are your conversations with the CEO about Project Quux going?"

   # Maybe that's their relationship with their boss, or a peer. Maybe it's a regular meeting they seem frustrated by.

 - *Draw them out*

   To get them talking, use Repeat Trailing Words and Echo Back & Summarize

   Once you think you might understand an emotion, go through the steps of Offering Labeled Feelings:

 - *Share your empathetic description of their situation*

   Mix your ahead-of-time prepared statement with whatever you've just learned

 - *Bridge to your rehearsed preface*

   Use the precise words (if you want, write them down on a index card you can look at!)

 - *Offer a painfully direct statement of feelings*

   Force yourself to be brief.

 - *Stop talking and wait*

Be ready to Echo Back & Summarize what they then say.

You won't get this perfect the first time. That's okay! This is a marvelously useful super power. It's worth the time it takes to learn it.


# With practice you'll be able to deploy this in a wide variety of situations.

# Once you've acquired this bit of understanding and rapport, you're ready to actually ask your stakeholder to change!
** Four Flavors Of Emotions To Divine

As you develop your skills for diving emotions, here are four useful questions to ask:

# Fortunately, you don't have to worry about every facet of your stakeholder's inner life. You're going to develop a picture of just four key emotions, by answering four key questions:

 - What happens, day-to-day, that *frustrates* your stakeholder?

 - What are they *afraid* might happen at some point in the future?

 - What happens, day-to-day, that makes your stakeholder *feel good*?

 - What do they most fondly *hope* happens at some point in the future?

# These form an extremely powerful core for persuasion.

# I'll shorthand those as, respectively: Frustrations, Fears, Delights and Dreams. Two focus on day-to-day experiences (Frustrations and Delights), two on longer-term motivations (Fears and Dreams).

Two focus on day-to-day experiences, two on longer-term motivations.

You can usually find, within those four, extremely useful leverage for making compelling offers to your stakeholder.

Which is the subject of our next chapter!

# You won't need to answer every one of these questions in every situation. But, in total, they represent a very useful set of ways in.

# , that will allow you to develop a really strong pitch for change.

# We'll talk about how to craft your request in "Make a Compelling Offer."

# If you can come up with answers to these four questions, you can build an *extremely* compelling request to try something new. A request that the stakeholder will both *hear* and *feel* as compelling.

# But first we need to figure out how to answer these questions in the first place. Again, if you're blessed with that rare beast, the emotionally open Important Person, go ahead and ask them. "Bob, what would you say frustrates you day-to-day? What do you hope happens if everything goes really well?"

# But what should you do if your stakeholder is not so emotionally open?

# Step one: make a guess.

# If your stakeholder is in a position of authority within your company, you likely have a hunch about how to answer some of these questions. The emotions of people in power are important enough that, usually, people on the ground have at least *some* model of what is going on inside their various bosses' heads.

# But that guess should just be the start. Because Important People spend so much energy trying to hide their emotions (and because our own feelings of powerless frustration can block our own ability to read emotions), we'll want to test out and refine our guess.
