:PROPERTIES:
:ID:       784C3421-0397-49E7-B600-F6933AE9D73B
:END:
#+title: Platform Goals
As part of [[id:17305FA7-A43F-40C9-9309-0EF3577C70D0][Author Platform]], what do I want to aim for? How can I make those incremental?

* Broad Targets
** Subscribers

At the simplest level, this is the set of email addresses I can contact in a single step, it's who I can reach out to for beta readers, etc. It's a reasonable ultimate definition of success.

I could... eventually decide to play along with bluesky or something, and look to my follower count there, too.

** Connections

For my own sense of motivation, I think there's something to be said for comments, feedback, etc.

I've turned that *off* for my substack -- could do a bit of research into that.

Is there something in: people who I don't *know*?

** Recommendations
This would be great, but I'm not sure if there's any good way to track it. I'm happy if people share my stuff, but I want to make it trivially easy to do so, and I'm not sure I'll ever be able to track it. But worth thinking about.

* Simple and Dumb
** 100 Subscribers, (then 200, 300, 500)
Or 100, 200, 300, 500, 800, 1300, 2100

Oh, yes, absolutely: Fibonacci goals! Love it.

Or, simple, doubling, but Fibonacci is so fun!

** "Hear from" 10 people (20, 30,50)
Where hear from = comments, responses, etc.

For my own motivation, yes, but also to ensure I have a channel to understand what I'm doing.

** Viz into recommendations, then goals
