:PROPERTIES:
:ID:       22898D7F-26DD-4787-939B-B640B3D5BE56
:END:
#+title: Beta Reading Wave 1
A place to take notes on [[id:93FF0A9B-F54E-49D5-8154-640BBAE08D4D][Beta Readers]].

* Plan <2025-06-27 Fri>
Broadly, I need to:

** Load into HTB, in a repeatable fashion
I think, yes, take some time to make it scriptable, to lower cost of future work.

I'm close, with pandoc.

** Decide: how many readers do I want?

** Write my "do you want to be a beta reader" invite
Steal from WUB

** Decide where / how to post that

** Decide who / how to ask about that

** Write my "guide for beta readers", load into HTB
Steal from WUB

** Start the campaign

** Build a habit for checking progress
Could easily lose my mind, be careful.

** Call to Action = follow up email

* Wave 1 Details
** Up through chapter 7: Offer Decisions With Options & Off-Ramps
** Aim for inviting 12-20 readers
Expect half to never open, half to write one comment and bail, end w/ 3-5.

I have 7 on my list. Can do a rolling thing, don't need all at once.
** Beta Invite Targets
*** Email TD
Again, anyone on this list is welcome, but also, if you know any earlier in their career eng managers who are coming to you for ideas on how to work with product or stakeholders.
**** Don't Allow Kellan in the first round
*** My Substack
Looking for readers -- either you, or, if you know someone who is struggling with their partnership with product and stakeholders, esp around tech debt.

But try to not have that turn into a post
*** LinkedIn
** [[id:82076E65-A0D3-4B11-87F0-94FE905D5E33][Beta Reading Invite]]
** [[id:ABD361FC-738D-440C-8778-4584C38EE0B1][Beta Reading Instructions]]
** Beta Follow Up
* Invites Sent
 - [X] Edmund
 - [X] Dustin Bennett
 - [X] Brien Tate (ask him for people)
 - [X] Margaret Geary
 - [X] Andria Thomas (Datesman's wife)
 - [X] Peter O'Brien
 - [X] Elias Haddad
 - [X] Ben Clark
 - [X] Ed Lyons?
 - [ ] Sunny [Gleason?]
 - [ ] Mike Isman
 - [ ] Mike Daniels
 - [ ] Al Goodniss
 - [ ] Matt Papi
 - [ ] Dani Chamberland (and her coworkers)
 - [ ]
** Comments
*** Margaret


Hi Dan! I left some comments on your book draft - in short, I really, REALLY enjoyed it! How to establish buy-in from Product on tech investment opportunities is an area I’ve been wanting to improve, so for me it was a timely and serendipitous read. I’m looking forward to what’s coming!

Thanks for sharing, and I hope you and your family had a fun July 4th.
