:PROPERTIES:
:ID:       5DCF4CB9-9186-48DD-B1B8-01E09702F04A
:END:
#+title: New Titles
Part of [[id:42FF29AB-A3A1-4307-85E5-69C08C7D4DB4][Reframe/Restructure]]

* Human Challenges
Working With Humans
A Guide For Engineers (and Product Managers!)
A Guide For Engineers and Product Managers

A Rough Guide, A Lonely Planet,

Working With Humans
How Engineers Can Improve Relationships, Solve Business Problems and Win

Working With Humans
Improve Collaborations, Solve Business Problems and Win Together

Working With Humans
How Engineers & Product Managers Can
Improve Collaborations, Solve Business Problems and Win Together

Working With Humans
How Engineers Can
Improve Collaborations, Solve Business Problems and Win Together

Working With Humans
Build Software
Improve Collaborations, Solve Business Problems and Win Together

Software + Humans
How to Improve Collaborations, Solve Business Problems and Win Together

Building Software With Humans
How to Improve Collaborations, Solve Business Problems and Win Together

Those Pesky Humans
How Engineers(*) Can Improve Collaborations, Solve Business Problems and Win


*Also Product Managers. Also Designers. Also Most Humans

*Also Product Managers, Designers, Executives, Data Scientists, and others.

*Also Product Managers. Also Designers. Also Kind of Everyone?


Working With Humans: The Definitive Guide
How Engineers(*) Can Improve Collaborations, Solve Business Problems and Win

Working With Humans: The Not-So-Definitive Guide
How Engineers(*) Can Improve Collaborations, Solve Business Problems and Win

Working With Humans, A Guidebook
How Engineers(*) Can Improve Collaborations, Solve Business Problems and Win

A Guide to Working With Humans
How Engineers(*) Can Improve Collaborations, Solve Business Problems and Win

Working With Humans: The Missing Manual
How Engineers(*) Can Improve Collaborations, Solve Business Problems and Win

Working With Humans
How Engineers(*) Can Fix Their Collaborations, Solve Business Problems and Win

*Also Product Managers. Also Designers. Also Kind of Everyone

---

Working With Humans
How Engineers(*) Can Improve Collaborations, Solve Business Problems and Win

*Also Product Managers. Also Designers. Also Kind of Everyone?

# Play on both forms of Solving Problems
Working With Humans
How to Solve Problems
With Bosses, Peers & Stakeholders


Getting Unstuck
Solving Problems with Bosses, Peers & Stakeholders

Getting Unstuck
How To Solve Problems
With Bosses, Peers & Stakeholders

How To Solve Problems With Important People


* Current Leaders

Engineers & The Creation of Value: How to Win *With* Your Stakeholders

Thinking In Increments: How Engineers Can Partner With Stakeholders To Create Value

How To
+Survive+
+Manage+
+Ignore+
Partner With Stakeholders:
A Guidebook For Engineers

* Problem Statements
From EWJ: /Trying to put myself back into the early-to-mid-manager times of my life, what I remember is feeling, like, some guilt around tech debt, and some vague anger that my business partners didn't "get it."  But I remember feeling full-on desperation, which almost led to my quitting the industry, because it seemed like my stakeholders were asking for crazy shit / were focused on completely arbitrary deadlines / clearly didn't trust me, and I didn't trust them, because half the shit we worked on never launched, and half of what remained no one used./

E.g. building trust, breaking work down to offer meaningful increments, understanding how value is created in a business, advocating for either specific approaches or specific technical investments, pushing back without creating bad will

* How Would Engineers Describe This Problem

Fix Your Stakeholders

Win Without Estimates

Align With Your Stakeholders

Align With the Business

My Business Is Crazy, What Do I Do?

People are asking for the impossible

We Can't Win

How Engineers +Can't+ Can Win

I think there's something deadlines, projects, milestones, estimates

And something else about building trust with product/stakeholders

And something smaller about maintaining trust with the team



* Titles
Win Together

Engineers & The Creation of Value

Engineering Value: Partner With Your Stakeholders To Build Awesome Things

Build Better Partnerships to Build Better Things

Engineers & The Creation of Value

The collaborative creation of value

Engineers & The Creation of Value: Build Better Partnerships To Help Your Business Win

Engineers & The Creation of Value: Build Better Partnerships To Win

Engineers & The Creation of Value: Partner With Your Business To Win

Engineers & The Creation of Value: Build Better Partnerships To Win

Engineers & The Creation of Value: How To Work With Humans To Win

Work Better With The Humans All Around You

Engineers & The Collaborative Creation of Value

Deadlines to Decisions: Engineers & The Creation of Value

Decisions, Not Deadlines: Engineers & The Creation of Value

Engineers & The Creation of Value: Win *With* Your Business Partners

Engineers & The Creation of Value: How to Win *With* Your Business Partners

Engineering Value: How to Win *With* Your Business Partners

Win *With* Your Stakeholders: Engineers & The Creation of Value

Engineers & The Creation of Value: How to Win *With* Your Stakeholders

Engineers & The Creation of Value: Win *With* Your Stakeholders

Engineering & The Creation of Value: How to Win *With* Your Stakeholders

Make Better Decisions Together:

Decision-Oriented Development: How Engineers Can Win *With* Their Stakeholders

Decision-Driven Development: []

Engineering Decisions

Decisions, Increments & Value: How Engineers Can Win ...

Decisions, Increments & Value: A Plan for Winning With Stakeholders

Increments, Options, Decisions & Value: ...

The Extraordinary Value of Knowing What To Do Next

Decisions, Increments, Milestones & Value: A Plan for Winning With Stakeholders

Thinking In Increments: How Engineers Can Partner With Stakeholders To Create Values

Thinking In Increments: How Engineers Can Win *With* Stakeholders

Thinking In Increments: A Guide For Engineers Working With Stakeholders

A Guidebook For Working With Stakeholders

A Guidebook For +Surviving+ Working With Stakeholders

An Engineer's Guidebook For +Surviving+ Working With Stakeholders

The Care and Feeding of Stakeholders
An Engineer's Guide To The Collaborative Creation of Value

How To
+Survive+
+Manage+
+Ignore+
Partner With Stakeholders:
A Guidebook For Engineers

A Survival Guide?

For Engineering Leaders

A Guidebook For Engineers

How To Survive Your Stakeholders: A Guidebook For Engineers

* The Overall Problem Solving Frame

Solving Problems & Creating Value
A Guidebook for Engineers

Solving Problems & Creating Value
A Guidebook for Engineers

The Creation of Value
How Engineers Can Partner with Stakeholders to Develop Software That Solves Problems


The Creation of Value
How Engineers Can Partner with Stakeholders to Develop Software That Solves Problems

Solving Problems, Working With Humans and Creating Value

Solving Problems, Working With Humans and Creating Value
A Guidebook for Engineers

Solving Problems For Humans
An Engineer's Guidebook To The Creation of Value

Solving Problems For Humans
How software engineers can create value, while +managing+ partnering with stakeholders.

How software engineers can create value, +despite+ *with* their stakeholders.

How software engineers can create value, +despite+ *with* the other humans they work with and for. [around them]

Solve Problems With Humans To Solve Problems For Humans
A Guidebook For Software Engineers

Solving Business Problems
An Engineer's Guidebook To The Creation of Value
+Despite+ With Stakeholders

The Art of Solving Business Problems


How Engineers Can Create Value +Despite+ With Their Stakeholders

Solve Business Problems
Create Value +Despite+ With Your Stakeholders

Solving Business Problems
How Programmers Can Create Value +Despite+ With Their Stakeholders

Fixing the Engineering/Stakeholder Interface
How Programmers and PM's Can Solve Business Problems, Create Value and Win in the Long Term

Changing the Engineering/Stakeholder Interface

Refactoring the Engineering/Stakeholder Interface

How Engineers and PM's Can Solve Business Problems, Create Value and Win in the Long Term

A Guide for Engineers and PM's On Solving Business Problems, Creating Value and Winning in the Long Term
A Guide for Engineers and PM's On Solving Business Problems and Creating Value
A Guide for Engineers and PM's On Solving Business Problems, Working With Humans and Creating Value
