:PROPERTIES:
:ID:       5C7A0B37-8984-4A1F-8371-C1FCEB637174
:END:
#+title: Make a Compelling Offer
#+filetags: :Chapter:
* Make a Compelling Offer
** Prepare A Proposal [Request?] For a Small Change

You're going to ask your stakeholder to make a "slightly uncomfortable" change.

You'll make your request compelling by:

  - Demonstrating *alignment* with the business's long-term goals

  - Speaking with *authentic empathy* to your stakeholder's hopes and fears

  - Setting an explicit *time limit* on an initial period of change

  - Ensuring your stakeholder feels like they *retain control*

As you prepare your request, the first step is to precisely define the incremental change you're going to ask your stakeholder to make.

At this point, don't worry about exactly how you're going to *explain* this change to them. Instead, just focus on the details of your proposed adjustment.

As you define the change, do so in the contxt of an initial, limited period of time. It's *much* easier for a stakeholder to say "yes" to a request to try something a little uncomfortable for a few weeks, than it is to commit to changing "forever".

Of course, you want to then ensure that, at the end of those few weeks, the stakeholder feels like things are going great, and they therefore want to continue in this new way of working.

# That will allow you to work backwards from where things will be at the end of this initial period, and will also create an opportunity to help your stakeholder feel like they're retaining control.

# A key here is: *don't jump too far ahead*. Start with something that feels small.

To that end, you want your small adjustment to create three distinct kinds of wins:

 - It makes things a little better for you

 - It makes things a little better for your stakeholder

 - It delivers a small, visible, business win for both of you

This is where the work you've done to dig into your stakeholder's fears, frustrations, delights and dreams pays off. That map of their emotional landscape makes it possible for you to design incremental improvements that will feel good to them, while also addressing your concerns.

At All Together Now, Quin desperately wants Marco to stop jumping into standups and blowing up the team's focus by brainstorming new product ideas.

Some part of her wants to just throw some book about agile or scrum in his direction, along with a lecture him about the proper way to add new ideas to the team's backlog. But, having talked to him, she knows he's feeling very under the gun about getting something into customer's hands, and she's pretty worried that, if she pushes for a big change, he'll refuse. [freak out, dig in, get defensive and push back.]

She knows that he feels like:

 a) He's not seeing much in the way of progress (a frustration)

 b) It's been /forever/ since he's been able to try out anything new (a potential delight).

Whatever change she proposes should provide him a means to brainstorm and clarify his thinking immediately after customer calls (thus, preserving an existing delight).

Finally, she knows that one of his overarching *fears* is that ATN might be building something that customers won't actually use---their product might be a vitamin, not a pain-killer. To win, ATN needs to be simultaneously building towards sales, while also learning how to get *engagement*.

Quin spends some time thinking about ways she can address some of her frustrations, while also making things feel better for Marco, and moving the business forward.

After a good bit of work, she arrives at the following, as a proposed first increment of change:

 - For the next two weeks Marco will agree to *fully* stop coming to the team after customer calls

 - Instead, he will first meet with Quin, one-on-one

 - Quin will commit to being ready to drop everything and meet with him the moment he gets off a call, while his thoughts are fresh

 - Otherwise, Marco can continue to interact with the team as he wishes

 - At the end of the two weeks, the team will share an interactive demo of the Virtual Dunk Tank for Marco to test out

There's a lot more Quin wants, but she's going to start small, and then build momentum. This change is carefully calibrated to be "slightly uncomfortable" for Marco. He will, in his excited moments immediately after getting off a customer call, *not* do what feels natural to him. He'll have to do some actual work to remap his instincts.

However, if Quin can get Marco to agree to try it, can believes she can generate wins across the three fronts:

 - It positions Quin to buffer the team from Marco's initial swirl of thoughts, immediately after he's talked with customers

 - It gives Marco a small, immediate reward -- Quin's immediate attention and thought partnership after customer calls (this preserves his existing delight)

 - It gives him another reward, at the end of the increment -- an opportunity to try out an interactive demo of the Virtual Dunk Tank (giving him both the velocity and the interactive UI that he's been growing increasinly desperate for)

 - Finally, the creation of that demo moves ATN one step closer to being able to ask a customer to *use something*, which moves them towards their key strategic outcome around engagement.

Again note how all that she learned about his feelings has allowed her to develop something which has the potential to work for her, for Marco and fo the business as a whole.

There's just one last detail to touch on, before we map out how to walk your stakeholder through your offer.

** Work Backwards From a Future Decision

# Ensure Your Stakeholder Retains Control By Offering a Future Decision

# Offer a Future Decision To Maintain Feeling of Control

You're going to want to assume that, whatever else you've heard, your stakeholder has some fear of *losing control*.

The fear of loss of control is incredibly common.

Such a fear can easily cause your stakeholder to tensely [rigidly] reject your proposal, even if you've gotten all the other pieces right.

If you ask them to change their behavior, it's very easy for them to hear that as a threat to their control. They will feel like, if they go along with your request, it will leave them at the mercy of a situation that feels on the verge of tipping over into failure. It can feel like their only way to prevent that failure is to push back on your request.

Fortunately, once you understand this, it's possible to design your proposal so that your stakeholder hears it as a way to *increase* their control---even as you ask them to make an uncomfortable change.

You create the feeling of control for your stakeholder by making a centerpiece of your proposal a *meaningful future decision*.

Specifically, your initial period of change *explicitly* ends with a decision your stakeholder gets to make. Ideally, you want that decision to be both about "Should we continue working in this new way", and *also* about if and how to pursue some new, potentially valuable, business option.

In the moment that your stakeholder is contemplating your proposed change, they're imagining that future moment of decision, of control. That will make it far easier for them to say yes.

Let's see how this could work for Quin.

Remeber, the small change she wants to propose is:

 - For the next two weeks Marco will agree to *fully* stop coming to the team after customer calls

 - Instead, he will first meet with Quin, one-on-one

 - Quin will commit to being ready to drop everything and meet with him the moment he gets off a call, while his thoughts are fresh

 - Otherwise, Marco can continue to interact with the team as he wishes

 - At the end of the two weeks, the team will share an interactive demo of the Virtual Dunk Tank for Marco to test out

The only new thing to add is:

She and Marco will, today, schedule a meeting for immediately after that demo, to:

  a) Decide next steps with the Virtual Dunk Tank demo

  b) Review how the new way of working, and decide on any further adjustments

By explicitly putting the end-of-increment decision on the table, Quin ensures that Marco feels like he retains control. She's making it clear, with her actions, that if he ends up frustrated by something in this new way of working, he'll have a time to speak to those frustrations.

Even more fundamentally, she's increasing his control over his ultimate goals. Being able to review a demo of the Virtual Dunk Tank creates new options for the business, by inviting Marco to start thinking about those options, she's giving him something he very badly wants.

** The Steps in Making a Proposal

I'm going to map out a step-by-step plan. I'll encourage you to try to methodically work through the steps, without rushing. It's designed to gradually move your stakeholder to a willingness to consider a new way of working.

You should deliver yor proposal verbally -- that will let you share your (authentic!) emotional connection with their hopes and fears. If useful, you can certainly buttress what you say with a written memo or a set of slides. But find a way to connect, as humans, in this moment.

In order to make your proposal, create a space slightly outside of the normal flow of day-to-day pressures. That could simply be starting a regular 1:1 by sayhing "I have some concerns I want to talk out, can I ask to put aside our normal agenda for today?" Or it could mean breaking normal patterns, perhaps meeting in person instead of online. You want to signal that there's something important for you to face, together.

Once you've created that big of space, go through the following steps, checking for understanding with your stakeholder after each one:

 - Name the strategic intent

 - Speak to their concerns

 - Share your concerns

 - Describe your proposed increment of change

 - Name the future decision

 - Ask for commitment

You should practice this with a trusted friend before you pitch your stakeholder. At least once, maybe a few times. Personally, for high stakes such proposals, I practice over and over, until it feels fully smooth and authentic.

Let's see how this works for Quin.

** Quin's Compelling Offer to Marco

They've gone for a walk together. As they get into the city park, Quin asks if they can sit on a bench to talk. They sit side by side, watching people walk by.

*** Name the strategic intent

"As I understand it," Quin says, "ATN!'s most important goal is to have a set of *engaged customers* within six to eight months. Potential investors in a next round are going to want to see happy users, running *actual* team activities on the platform--not just a couple of big sales. Given that, our current goal is to *very* quickly build something that is "*just 'Good Enough*'". Something we can get into the hands of a few early customers, and then make better *with* them. Do I have that right?"

Marco nods for her to go on.

She has spoken to the stratgic intent, using some of his own words ("just 'Good Enough'", "make better with them"). She's also spoken to one of his biggest fears (that they won't see actual use), but done so in the "positive form", of the good thing they *want* to have happen.

Quin takes a breath. "Unfortunately, I'm worried that we're struggling to move fast enough. Unless we make some changes, I think we might not have a product *any* customer will be able to actually use until early next year."

Marco frowns unhappily. This isn't shocking news, but it doesn't feel good to hear it said out loud.

Note how Quin has named a desirable outcome, and then shared a specific "danger" that might make it impossible to achieve that outcome. This is powerful rhetorical tactic. It creates suspense that will make your listener sort of lean forward to hear more.[fn:: It does so by adapting the story-telling structures that are wired deeply into the human mind.]

*** Speak to their concerns

"Whatever changes we make," Quin continues, as a breeze stirs leaves in front of their bench, "I want to be certain we solve for a few things. First, I want to be sure you can actually *see* that the team is moving faster---I worry that we've drifted a bit into building separate bits and pieces of the final product, but we're not regularly putting together visual prototypes that you can test out and react to."

Quin has immediately shown that she cares about both Marco's biggest frustration (that the team isn't moving fast enough) and one of his potential delights (being able to interact with a visual UI).

Marco nods. He would certainly be happy if the team shipped, well, anything. He'd be even more happy if it was a thing he could *see*.

She continues, "Finally, I want to be certain that, immediately after you talk to customers, you have a chance to think through what you've heard, while it's still fresh in your mind. Most of the time, we won't adjust what the team is doing based on any one call, but, even if we don't, it's important to quickly update our shared understanding of customer needs."

"Does that sound about right?"

Quin has spoken to preserving something he cares about (a delight). She's paused and checked in, before she moves on.

Marco replies, somewhat cautiously, "That sounds mostly right, yeah."

He is remembering that Quin had recently demanded he *stop* talking to the team immediately after calls. He's not certain where she's going, but he appreciates that she now seems to understand why it's so important that he can process those calls right away. In fact, he likes the way she frames it: "quickly update a shared understanding of customer needs." That gets at it well.

He also thinks that, of course he understands that they're not to ask the team to, like, change everything based on one customer call. He's not unreasonable.

*** Share your concerns

Having heard his agreement about how she's framed his concerns, Quin is ready to move on to herown.

She has spent a bit of time thinking about how to avoid any kind of accusation that could trigger defensiveness, so she says:

"One thing I worry about is that I think the team doesn't have as much context as you and I do. So, when you come back from a customer call, and share what you've heard and learned, they sometimes get confused. They're not sure what is extra context, and what represents a real change in direction. That confusion is starting to add up. I want them to go faster, but we've been losing time when engineers went off in some new direction after one of thoses sessions."

Marco nods, slowly.

Note how Quin subtly positioned this as a "weakness" of her and the team, rather than a "failing" on the part of Marco. She could easily have said "The way you're constantly bringing in new ideas is causing problems", but, instead, by playing just a bit of low status, she is sharing a problem to solve together---where the "problem" is "the team can't follow your new ideas", not "you're being chaotic and unfocused". Those are actually exactly the same problem, just focused on different perspectives. The non-accusational framing makes it easier for Marco to stay with her.

*** Describe your proposed increment of change

Now Quin will walk through what she's worked out, and be very direct and very specific about what she's asking of Marco:

"I'd like to try a small change, for the next two weeks. Whenever you get off a customer call, I'll ask you to ping me on Slack. I'll drop whatever else I'm doing, and you and I can do an immediate debrief. That'll give you a chance to really think through what you've heard, while it's still fresh. If something important comes up, I can share our current status with you, and we can make an immediate call about any priority changes to bring to the team."

"That's most of it. I would ask that, if, during one of those debriefs, I tell you that the team is super heads down, that you wait to give them the full update. But we don't need to be too formal about that."

Note how extremely specific she is being, about what she is asking: "Whenever you get a customer call, ping me on Slack". That's far, far better than saying "Can you please stop coming to standups", or tip-toeing around it, ala, "I don't know maybe you and I could check in, sometimes, before you talk to the team?" You want to give your stakeholder a crisp, specific thing to visualize themselves doing.

"I'm hopeful that, if we do this, I can really focus with the team, and we can have a demo of the Virtual Dunk Tank ready by end of sprint."

She's immediately followed up her request with a benefit he'll get --- a demo of a feature he's been waiting on, for a while.

*** Name the future decision

"Finally, I want to set a meeting up, for immediately after that end-of-sprint demo, for you and I to review how close the Dunk Tank is to sharing with customers and what, if anything, we want to keep tweaking to ensure the team can move faster."

Note how she's mixing a business decision (What do we do with the cool new Dunk Tank?), with a collaboration decision (what do we want to tweak?)

Also, she is *not* offering a Yes/No decision. She could have said "if we want to keep working this way." You... can do that, in particular if it feels incredibly risky to your stakeholder to try this change. But you're generally better off drawing them into shared problem solving, so that the decision is about *how to continue to solve the problem together*, not simply yes/no on one specific practice.

*** Ask for commitment

Now, to be clear, Marco may not say yes immediately. But that's fine. Quin can probe for any hesitations and tweak the offer, until he's ready to try. Usually, if you've done the previous steps well, you can do that within the discussion, so you're emerging with a commitment to try something new.

** Getting Commitment
** Our Story: Quin Makes Her Pitch
** Exercises
* Scraps
** Loss of Control
In a professional context, it starts because your stakeholder is working under the burden of some set of expectations -- from their boss, their board of directors, their peers, their spouse, even themselves. They will have a looming, background feeling that if they should fall short of those expecations---by failing to deliver, by missing stated or unstated goals---they will have *failed*. Actually, it's worse. Their fear is that, in those bad cases, they themselves will have *become a failure*. [fn:: It's possible I have known billionaires who struggled to sleep at night, out of the fear that everything they had buit was eroding in front of their eyes.]

Many of the actions they're doing today feel necessary to them, to prevent that failure. Those actions represent a way for them to exert control.


** Holme Quote
# No matter how rosy a picture they're trying to paint, there's some bedrock fear that things will go awry, and they will be left looking shamefully bad.

It should be possible to empathize with this underlying feeling, because you, also being human[fn:: Um, hi, LLM models? Laugh once if you're human?] likely work under a set of expecations yourself.

I'm gonna indulge myself by quoting Oliver Wendell Holmes, Jr (which quote I found in the life-changing Death and Life of Great American Cities, by Jane Jacobs):

/"We are all very near despair. The sheathing that floats us over its waves is compounded of hope, faith in the unexplainable worth and sure issue of effort, and the deep, sub-conscious content which comes from the exercise of our powers."/

The only thing that floats us over the waves of despair is "faith in [...] effort" and "the exercise of our powers."

I think that captures it, perfectly. When the specter of failure rises up in our minds, we to beat it back by taking *action*. By exercising our powers.

* From Substack
** Design an Increment of Change


# This is not yet the pitch itself.

There's a lot of art in this -- you've got to have some sense of what "better" looks like, and what a step in that direction might be. In later posts and/or the book, I'll be sharing case studies to bring this more to life, but for now I'll sketch in some ideas.

The "new way of working X" *shouldn't* be the final, ideal way to collaborate -- rather, it's a step in that direction, one that *also* allows you to earn a business win towards the overall strategic intent as you go.

The "new way of working X" should be designed with an explicit awareness of your stakeholder's fears and hopes -- whatever they most fear should be clearly and fully prevented from happening, and whatever they most hope for should be made *more* possible.

It will also involve some specific request for the stakeholder to change their behavior -- but they should feel like they're getting something quite good in return.

With the CEO we've been discussing, who keeps on driving the team crazy by interjecting new ideas into daily work, the core structure of the increment of change might be:

/For the next six weeks, the PM and engineering lead will add a pair of recurring meetings between the two of them and the CEO: one midway through each sprint, to check in on status and learnings, one immediately after each sprint demo, to discuss options for what the team works on next./

/They'll also add a once a month meeting where the CEO will meet with the whole team and share what he's been hearing from customers -- the PM will facilitate that meeting./

/The CEO will, during these six weeks, stop coming to team standups altogether (and will not slack or email ideas to team members)./

That gives the CEO a great deal of visibility, allows them to guide the overall work of the team and allows them to "directly" share what they're observing from customers.

I'll offer two other thoughts:

First, the increment should end with a *decision by your stakeholder*

E.g. the PM and Eng lead could say to the CEO something like:

/At the end of the six weeks, we're going to sit down with you and review the team's output and velocity, and also see if and how you've been able to both understand and guide the team's work./

/If necessary, we can make any needed adjustments to ensure that you're able to make clean decisions about what problems the team is solving. Let's get that meeting on the calendar now.../

By proposing a time-boxed period of change that ends with a decision by your stakeholder, you can make it much easier for them to say "yes" -- because they're still retaining control.

Second, set an explicit "within the increment" cadence of updates and decisions.

Many of these change involve *some* kind of "leave the team alone" shifts -- in those cases, it's worth defining some clear, controlled way that the stakeholder is having opportunities to understand what is going on, and to (appropriately!) influence it.

In the example above that's built-in, via the cadence of regular meetings.

** Craft a Pitch That Creates Urgency

Okay, now you're ready to put all that together into a *pitch*.

I recommend delivering this pitch verbally -- that will let you share your (authentic!) emotional connection with their hopes and fears. If useful, you can certainly buttress that with a written memo or a set of slides.

The arc you want to lead the stakeholder through should look something like:

 - Open with the strategic intent as context

 - Signal that you want to try something new

 - Name and validate their fears, in a way that lets you demonstrate your emotional alignment with them

 - Name the aspirational positive experience you want them to have (ideally, they have not been having this experience, of late).

 - Share your own concerns and fears -- the things about how you're operating now that make you worried you won't achieve the strategic intent

 - Describe your proposed increment of change, and, as part of it, name your key request of them -- how they'll have to act differently, for a period of time.

 - Share the decision they get to make at the end of the increment

 - Ask for feedback, ideas, concerns, questions

 - Adjust based on that, and then get a commitment to try something

A note: you should practice this with a trusted friend before you pitch your stakeholder. At least once, maybe a few times. For high stakes such proposals, I practice a ton.

For our CEO friend, putting that all together, the PM and Engineering lead might say something like:

/"Our understanding is that the company's absolutely highest priority is growth, because that is what potential acquirers will want to see. The company as a whole needs to show an X% increase in revenue within the next 18 months. Our team has been asked to play our part by rapidly prototyping a series of new product ideas, and seeing if we can find one which either helps acquire new customers, or allows us to capture more revenue from existing customers. We're very excited about that challenge. However, we do have a concern that we wanted to talk about with you./

/First off, we're worried that, as we're working right now, it can feel pretty unclear to you what, exactly, the team has prioritized at any given moment. We really want to fix that. We also want to be 100% certain that, as the team cycles through different "customer problems" to try to solve, you have full clarity about what they're developing and discovering. We want to have the best possible shot at building something that you'll be super excited to share with customers./

/Unfortunately, the way we're working right now, sometimes people on the team get confused by what they hear from you, when you join our stand ups. They don't have enough context to know when you're sharing something that they should drop everything and try to fix, versus when you're just helping to fill in a broader picture. That's been causing some churn, and we're running a risk of drifting behind./

/So, we'd like to try a tweak, for the next six weeks:/

/First, to be sure you have real clarity about what's going, we'll set up a new every-other week meeting with you and the two of us, where we'll bring a detailed status update on what's been built and what's been learned -- that'll land partway through each sprint./

/Second, we still very much want you to come to the end-of-sprint demos -- that is super valuable to us and the team. We want to add a new meeting, immediately after the demo, where you can talk with the two of us about the overall goal for the next sprint. Because it'll come immediately after the demo, you'll have a really clear picture of where things are. We can all three work together to make sure the team is pointed at the most important customer problem to solve./

/Finally, if you're up for it, we'd like to have you meet with the whole team once a month to have a sort of open conversation about what you've been hearing from customers -- we think it's super valuable for the team to get a feel for what's going on in the field. I [the PM] can facilitate that, so you can just show and be ready to share./

/We'd ask that, during this six weeks, you not come to standups -- and if you have any ideas, share them with one of us, instead of emailing or slacking people on the team./

/At the end of the six weeks, we'd going to sit down with you and review the team's output and velocity, and also see if and how you've been able to both understand and guide the team's work./

/If necessary, we can make any adjustments to ensure that you're able to make clean decisions about what problems the team is solving. Let's get that meeting on the calendar now.../
