:PROPERTIES:
:ID:       D6564799-DCF0-4D14-BC29-C9A0E3B47B3F
:END:
#+title: Develop An Empathetic Understanding Of Their Concerns
#+filetags: :Chapter:
* Develop An Empathetic Understanding Of Their Concerns
** Intro

# Make a promise of what they'll get in this chapter

Identifying your stakeholder's most important goal is an excellent foundation on which to build a request for them to change their behavior.

But, by itself, it's rarely enough.

In this chapter, we're going to supply our final key tactical empathy tool: a conversational pattern that will allow you to draw out and validate your Important Person's underlying /concerns/.

# This will cover both straightforward concerns ("what if this project doesn't finish on time?", and also subtler, feelings that are driving some of their behavior ("what if I lose touch with how our code works?")

In fact, you'll not only come to understand those concerns, you'll be able to speak to them with true empathy.

# This will allow you to execute on the second step of our game plan: "Develop An Empathetic Understanding Of Their Concerns".

Being able to make an empathetic statement of their concerns will allow you to get past the armor your stakeholder puts on to get through their days. You'll be able to offer them something that they eagerly desire. You'll be able to carefully position your request to avoid triggering their biggest fears.

With this nuanced understanding in hand, you'll be able to make a surprisingly direct request for them to change their behavior.

Of course, all of that is only possible if you somehow come to understand /why/ they're acting in the crazy, mystifying, frustrating way that they currently are. Which is to say, you'll need to understand their feelings.

** The Basics Of Offering Labeled Feelings

Our key new conversational tool is "Offering Labeled Feelings".

It is a way to probe for underlying concerns, but to do so in a carefully structured manner that encourages people to open up. It is probably the most tricky of our tactical empathy skills to master, because it requires first an act of creative imagination, and then adherence to a very precise template in speaking with your stakeholder. But with practice it is a true superpower.

# This is another one of our tactics adopted from Never Split The Difference, where Chris Voss tells stories of using it to defuse armed standoffs with people

Here's how you can use it when speaking with your stakeholder:

 - Step 1: Share an empathetic description of the situation they perceive themselves to be in.

 - Step 2: Offer a potential emotion they may be feeling, as a natural response to that situation.

 - Step 3: Invite them to correct your understanding.

There are two reasons why successfully going through this arc lays the groundwork for you to challenge someone to change their day-to-day behaviors.

First, it prepares you to speak to your stakeholder about the world as they truly experience it. If your stakeholder is acting in a frustrating or difficult manner, odds are very, very good that, in their own minds, they are simply doing their best to handle  some Objectively Difficult Situation. If you can speak to that situation, they'll feel like you understand them. Conversely, if you /don't/ take the time to understand that situation, they'll just reject any requests you make out of hand.

Second, by digging beneath their frustrating behaviors to the underlying feelings driving those behaviors, you'll be able to propose a different way to act that will still /feel good/ to them. Once you get to an understanding of situation and feelings, you'll discover lots of creative options for proposing changes. Conversely, if you /don't/ understand their feelings, a proposal for change is almost certain to make them feel defensive and attacked.

In other words, you'll be able to tease apart their feelings (which you can authentically validate) from their actions (which you can directly ask them to change).

Your CISO keeps on blowing up your sprints by forcing you to take on an endless series of "urgent" security remediations---very few of which feel truly urgent at all.

Why might they behave in this fashion? Well, perhaps they perceive themselves to be in a situation where:

  a. There's no way for them to get work onto your team's backlog *other* than through urgent remediations.

  b. They will fail at their own job if they don't fully retire a large set of security risks.

  c. The CEO has announced that Security is Job One... but has also told the product team that they have to launch a new product asap, and has provided no means to establish tradeoffs between these two priorities.


The reason this is so effective is that /all/ humans perceive their own behavior---especially any potentially /negative/ actions---as forced on them by the situation they're in. If you can make a clear, empathetic statement that makes your listener feel like you truly understand the situation they're in, they will feel like you're not /accusing/ them, when you offer a potential emotion they may be feeling.

, rather than by characteristics of their personality. But when we look at others, we do the reverse, assuming their personality drives their behavior. This is such a pervasive pattern of human cognition, psychologists call it the Fundamental Attribution Error.

Just about all of us perceive any of our own negative behaviors as triggered by the situation we're in, rather than by characteristics of our personality.[fn:: But when we look at others, we do the reverse, assuming their personality drives their behavior. This is such a pervasive pattern of human cognition, psychologists call it the Fundamental Attribution Error.

Much of the work of offering labeled feelings is finding a way to imagine yourself into a situation where your stakeholder's seemingly crazy actions and emotions become natural and inevitable.

If you can do so, you can then share  your understanding of that situation with them, bringing it to life by citing specific, vivid details. The specificity demonstrates to your stakeholder that you truly understand and care about the challenges they're facing.

Then, you can move on to the next step. You explicitly name, or, as Chris Voss says, "label", an emotion that the situation could be causing them to feel. You /offer/ it to them as a possibility, not as a statement of fact.

Most importantly, you make it clear that you yourself might have that same feeling if you were in their situation.

Finally, as always, you throw the ball back to them, to give them a chance to "fix" your understanding. And of course you then echo back and summarize whatever they say to you.

# That's it. When done by someone very skilled, this can all happen very quickly, and can change the feeling in the room to a shocking degree.

Why is this so powerful? And why are we doing all this hard work to see things from our stakeholder's point of view? Are we trying to /justify/ their frustrating behaviors?

** Splitting Apart Feelings From Actions

The key to getting

Once you get this right, you'll be able to tease apart what your stakeholder is *doing* (e.g. shutting down every single question anyone asks them) from their underlying *concern* (e.g.that the team isn't moving fast enough, and might get distracted).

You can then validate the concern, but offer them a new, non-destructive way to address it. In fact, that will form a core of your request for change.

# XXX Make a table?

 - Frustrating Action: aggressively shut down questions about context or why

 - Potential Underlying Feelings:

   - Frustration the team isn't moving fast enough and a fear that they might get distracted

   - Fear that the team doesn't trust the stakeholder, and will push back on key actions

   - Fear that the team will discover that the stakeholder themselves doesn't understand why

#

# mirroring how they experience, and you're create *justification* for their feelings.

# If you do this right, you should feel like you, yourself, would feel similarly, if you were in their situation.

* Later Stuff

** Scraps re Defining Labeling

You make this an /offer/ by prefacing it with a careful bit of distancing, e.g. "It seems like you might...", or "I could imagine that you might...".

You avoid the risky bluntness of "You seem frustrated" (or, god forbid, "I think you're frustrated", which has patronizing judgment written all the heck over it). But you *directly name a feeling*.


ideally in a fashion which casts your stakeholder in the role of a "beleaguered hero". E.g. imagine that you're talking with a VP of Warehousing stakeholder. One way to frame a situation is to say: "We have to open three warehouses by early Q1 of next year, and it's not clear if we're on track".

# XXX Fix this

In NSTD, Chris Voss describes labeling emotions as akin to performing a tea ceremony. It's precise and persnickety and not particularly natural at first. I like that analogy very much. The act of labeling happens very quickly in real time, so you need to learn to go through the distinct steps very carefully. Let's break them down.

# BAD WRITING GO!

By empathetically describing the situation, you start by validating their *experience*.

That's... fine? It's true, and it's better than saying nothing. But it's not demonstrating a fully empathetic understanding of how all this presents to Mr Warehousing. Here's that same dry series of facts, enriched with details:

"The CEO is demanding that you open three warehouses by Q1. That's right at the limit of what's even possible -- like, everything has to go exactly right. Despite the risks, next year's forecast for the board assumes a full year of operational profits from those buildings. But the location team hasn't even given you all the possible sites yet. It's like you're behind before you're even able to start."

For example, with Mr. Beleaguered Warehousing, maybe that looks like:

"[...] But the location team hasn't even given you all the possible sites yet. It's like you're behind before you even able to start. That seems like it might be a pretty frustrating situation."

"You seem frustrated" and "That seems like it might be a pretty frustrating situation" are just miles apart in how they land with people.

The distancing preface allows the person to hear the statement of emotions as you *trying to understand them*, not as you judging them. This tactic work best if you can get yourself into a place of genuine curiosity, so that you truly *are* trying to understand. You might even find yourself naturally inflecting your statement as a question: "That seems like it might be a pretty frustrating situation?"

Other distancing prefaces include:

  - "It would make sense if you were to feel pretty frustrated..."

  - "If I were in your shoes, I might might feel pretty frustrated..."

# Going through the steps of this little dance is a way to help someone feel validated and understood, without falling into the trap of making them feel judged.

# When you make such an offer, it's *critical* that you preface it with an opening that creates separation between you and the statement of emotions you're about to make, e.g.:
#  - "It seems like you might..."
#  - "It would make sense if you were to..."
#  - "I could imagine you might..."

If you get this right, your stakeholder will feel a (possibly profound!) sense of /relief/. They may even visibly exhale and relax. You may see them smile or even laugh at the picture you've painted. They will be far more ready to see you as a potential partner in facing their challenges.

Let's see it at work.

# Let's review the two different ways Quin could speak to Marco's potential fear:

# Direct Question: "Are you afraid that we're not solving an important problem?"

# Labeled Offer: "We're in a tricky spot. Potential customers keep telling us that they're *interested*, but because we don't have a thing we can *sell* them yet, we can't find out if they're genuinely willing to buy. It seems like you might be afraid that we're not solving a genuinely *important* problem...?"

# On the page the two may not seem that different, but if you can do the work to lay out the situation first, and then offer that second part in a calm, curious, dispassionate tone, it has a *remarkably* powerful effect. Your stakeholder, instead of feeling *accused*, will feel *relieved*.

# As Voss explains, research shows that, by naming fears out loud in this way, you can actually help people *feel* calmer. It both shows the person that it's okay to openly name the fear, and it also engages the rational, problem-solving parts of their brain.


# Voss describes this as learning the steps of a tea ceremony, which I love. It's precise and specific and feels alien at first. But once you master it, you'll find it supremely uesful.

# ** Tactic: Make Your Stakeholder A Beleaguered Hero

** Stakeholder Is Human Being / Has Feelings
Because, all evidence to the contrary, your stakeholder is a human being. Their behavior is not driven solely by a rational desire to achieve an outcome.

# We are none of us robots.

# Making a purely rational case is not super likely to work.

Your stakeholder, being human, /has feelings/. And, shocker, not every one of those feelings comes from a perfectly cool, calm and collected desire to achieve their goals. To effectively advocate for change, you'll need to develop an understanding of their full suite of messy, human feelings. And not just any kind of understanding, but a special kind: an /empathetic/ understanding.

# Because your stakeholder is a human being. And thus they have /feelings/. To effectively advocate for change, you'll need to develop an empathetic understanding of their messy human feelings.

# This is so important, we're going to spend a few chapters on it.

# If you want to persuade your stakeholder to make a change, you're going to need to understand some messy human emotions.

# Thus, the second step in the game plan is to develop an empathetic understanding of your stakeholder's key underlying emotions.

# If you want one of those humans to change their behavior, it's absolutely critical for you to understand their *feelings*.

This is true even if you work with a CEO whose only outward expression of emotion is a tightly clenched jaw.

# This is true even if you and your coworkers engage in serious debates about whether or not your rigidly shut-down Head of Engineering even *has* feelings.

Understanding feelings doesn't mean gathering in a drum circle and getting in touch with our inner child. All humans, in whatever positions of power they may find themselves, have things they deeply want, and things they are deeply afraid of. Your stakeholder's current behavior patterns are driven by some combination of what they want and what they're afraid of.

When you advocate for change, you want to be able to speak with authentic connection to both the fears that are keeping them up at night, as well as the things that they desperately wish were happening.

# To bring this to life, let's first see what happens if someone tries to advocate for change, *without* that nuanced, empathetic understanding. Then we'll see how, armed with an understanding of their stakeholder's inner life, they could make a far, far more effective request for change.

# Over the next two chapters, we're going to show how to do a better job

** Leaders Hide Their Feelings
# But there's a problem.

# Many leaders do their best to *hide* their feelings.

To persuade your stakeholder change their behavior, you'll need to develop an empathetic understanding of their fears and dreams.

# That empathy will allow you to productively challenge them to change, by speaking authentically to their underlying concerns.

# Even if they've been trying to hide those from you.

# Persuading humans to change their behavior works roughly a thousand times better if you can find a way to speak to their hearts as well as their minds.

But there's a problem:

Very few Important People wake up in the morning and leap from their beds, eager to openly share their feelings.

# If you haven't had a position of responsibility, leading a group of other humans, I encourage you to have some empathy for people in these roles.

I mean, that's true of humans in general (do /you/ look forward to telling your co-workers /your/ deepest fears?). But it's even /more/ true of Important People. Humans in positions of authority often believe they must hide their emotions. For many leaders, emotional vulnerability presents as /dangerous/.

(I believe it *can* be extraordinarily powerful for leaders to share their emotions in an authentic, vulnerable manner. But, sadly, I suspect you're not going to run into a ton of Important People who have mastered that approach.[fn:: Two points for those interested in building powerful leadership through vulnerability. First, Dare To Lead by Brene Brown is excellent. Second, it *is* sometimes important for leaders to carefully put their own feelings aside: when they're using their authority to inflict something unpleasant on a team member. E.g. when firing someone, or giving a tough performance review. Many leaders will feel a storm of emotions in such situations---but they *must not* inject those feelings into those conversations. As a strong leader once said to me, when discussing termination conversations, "I *hate* when managers make it about them." But those are relatively rare circumstances.])

If your Important Person has learned that leadership = no emotions, one common consequence is that they have built up a self-protective habit of patronizingly implying that any issues are due to *your* out-of-control feelings, because they, of course, are totally calm and rational. This kind of gaslighting is suuuuuper exhausting and can drive you kind of insane. "I guess my CEO's relentless insistence that our obviously failing new product has traction is because they're just smarter than me? Am I a worrier? Or too conservative? Am I missing something? Everyone around me seems to agree with them? WHAT IS EVEN GOING ON?"

I AM SPEAKING THEORETICALLY OF COURSE AND NOT ABOUT ANY SITUATIONS IN WHICH I PERSONALLY HAVE BEEN DRIVEN MAD.

# , all my former bosses have been just models of rationality and I never get bent out of shape.

Ahem.

If you happen to have an emotionally open stakeholder, awesome! You don't need all the tactics in this chapter. If, on the other hand, talking to your stakeholder makes you feel like you're banging your head against an unyielding, inhuman, unemotional wall, read on.

# Even if your key stakeholder seems to be working very hard to present as a goal-driven business automaton, you must find a way to get past that.

** Look Who's Not Talking Now: Hitting Conversational Dead Ends

# It's not always easy to get humans talking. But you need your Important Person to talk, if you're going to have any shot at figuring out what underlying feelings are driving their problematic behavior.

If you want to understand someone's feelings, you need them to *talk to you*.

But it often requires real work to *get people talking at all*.


# , Well, Anything

# How Alistair Gets Max Talking

To illustrate this, let's return to our story of Alistair and Max. In the last chapter, thanks to waving a magic wand, we learned the following facts:

  1. Max /fears/ that the CEO will angrily blame and shame him for any customers issues

  2. Max is /frustrated/ that the new PM's don't fully understand the complex ProClaims product

However, we didn't talk about how Alistair might figure those things out.

Max certainly doesn't go around *explaining* his fears and frustrations. He just rigidly insists that he has to be in the loop for all decisions, he plays out his martyr complex, he looks tense and unhappy.

Alistair is not in the exec team meetings, so he doesn't know there's tension between Max and the CEO. He's not in Max's meetings with the PM's, so he can't see his concerns about the PM's first hand. He just experiences Max as brusque, remote and controlling. He (and just about everyone he works with), assumes Max's difficult behavior is entirely due to Max's difficult personality.[fn:: Again, this is the Fundamental Attribution at work, whereby humans mistakenly attribute other people's behavior to their personality instead of the situation those people are in. If you can get past this error and better understand the underlying situation, you'll often discover a variety of options for getting unstuck.]

And so, even though Alistair has acquired a truly actionable understanding of company strategy, and can cogently explain both how and why they are going to fail to finish their ProClaims restructuring on time... he is unable to get Max to consider changing his behavior.

# XXX Decide, husband or wife (has to match intro chapter)

** An Eventful Dinner Party

One night, Alistair goes out to eat with his husband and his husband's grad school friends, to  celebrate his husband completing his masters in social work. The grad school friends, being social workers in training, are somewhat irritatingly good listeners. Alistair sits at one end of the table, feeling like he's adrift in a sea of positive affirmations.

"C tells me your boss is driving you a little crazy?" Alistair turns. His husband's friend Naiah is sitting next to him, swirling wine in her glass. She flashes him a friendly grin. "Any interest in talking it out?"

"Did Carl put you up to this?" demands Alistair. He doesn't like being managed.

Naiah shrugs, cheerfully unrepentant. "Yep." She takes a sip of her wine. "But I think it'd be fun. Crazy bosses are kind of my specialty."

Alistair tries to maintain his sense of injured pride, but the twinkle in Naiah's eye finally defeats him. "Okay, fine. But I'm going to warn you, he's totally crazy."

"Bring it on."

And so they talk, leaning in close to hear each other over the background noise of the restaurant. After Alistair sketches in the situation, Naiah sits back and purses her lips thoughtfully. "I really appreciate you telling me how you're feeling, Alistair. But I want to ask: what do you think /Max/ is feeling?"

Alistair vengefully stabs a tiny boiled potato off his plate. "I have literally no idea".

Naiah shakes her head. "I'm not buying it. If you had to guess, what do you think /frustrates/ Max? Or, what do you think he might be /afraid/ of?"

# And so Alistair acquires a mentor. She asks him

# commits to divining Max's emotions. We'll even say he's gotten some coaching on how best to do so. As per that coaching, he starts by reviewing what he's been able to observe, so far.

Alistair cuts a piece of steak and chews, angrily. He doesn't *want* to think about Max's feelings. Max has made his life a nightmare. Max thinks everyone around him is an idiot. But Naiah is looking expectantly at him. He swallows.

"Okay, fine, you win. Let me think."

"Thank you," says Naiah.

He looks off into a corner of the restaurant and lets his mind wander back over the last few months. At first, he can't think of anything distinctive. But then he realizes that he /has/ recently noticed Max seeming extra tense and unhappy during the weekly ProClaims status meetings. Alistair is not totally clear on why that might be. If he had to guess, maybe Max is just frustrated because the project is drifting behind plan?

# Alistair slowly chews his potato.

He shares this with Naiah, and she immediately perks up. "Perfect, start there!"

"So you think that's right?"

"Oh, no," she says cheerfully, waving a spoon in his direction. "It's almost definitely wrong."

"What?" says Alistair, totally confused.

"You just need a reasonable guess to start. It's okay if you're wrong."

"I do? It is?"

And then, with the clatter of voices all around them, and the smell of roasted vegetables  in the air, Naiah explains to Alistair how he can guide Max into an emotionally open conversation.

When she finishes up, Alistair looks at her for a long moment. "You know, that... could work," he says slowly.

"Of course it could," she says. "I'm pretty amazing."

# Alistair has noticed that Max seems /extra/ tense and unhappy during the weekly ProClaims status meetings. Alistair is not totally clear on why that might be. His current theory is that Max is unhappy because the project is drifting behind plan. Note: this guess will turn out to be wrong! But that's okay. You need to start somewhere.

# How can Alistair learn more? How can he refine his guess? His next step is to simply /ask/.

** Alistair Opens His Conversation With Max

Max spends some time preparing, as per Naiah's advice. Finally, he decides he's ready.

It's his weekly zoom 1:1 with Max. They've reviewed progress on the ProClaims overhaul, and caught up on a few other action items.

There's a pause. Max's eyes flick away from the camera. No doubt he has Slack messages piling up from all the people seeking his attention. Alistair takes a breath and launches into the plan he talked out with Naiah: "Is there anything about our ProClaims status meetings you find frustrating?"

Max looks surprised. He frowns and then curtly replies, "They feel a bit slow."

Max shows zero interest in sharing anything beyond this incredibly generic critique. In fact, he seems, if anything, /bothered/ by this question. Alistair certainly isn't feeling excited about asking any follow ups. What does "a bit slow" even mean?

And here Alistair has hit the first fundamental challenge.

Imagine you're in Alistair's shoes. You've asked your key stakeholder a question you care a lot about. They've responded by immediately shutting the conversation down.

# when you ask a question they don't really want to answer.

# You may be familiar with this kind of unpleasant moment.

# about emotions. Where, after asking a question, you feel shut down by your stakeholder.

What should you do? Ask another question, and run the risk of pissing off your Important Person? Try to somehow divine your answer from whatever cryptic, fragmentary thing they said? Give up and go home and pour yourself a stiff drink? I have tried all of those, many times, and not seen much in the way of positive returns!

# Luckily, Alistair's mentor has forced him to read Never Split The Difference.
# Many stakeholders tend to clam up, the moment anything resembling an emotion drifts into view.

# This is a genuinely tricky moment.


Luckily, Naiah has prepared Alistair for this exact moment.

# so he pulls out a magic trick:

# He will *repeat the last three words* that Max said, inflected as a question.

** The Simplest, Dumbest, Bestest Tactic: Repeat Trailing Words


Alistair is going to employ a very, very simple, but very, very powerful tactic.

Naiah named it "Repeat Trailing Words", and this is it, in its entirety:

# One that is so seriously, marvelously, totally dumb.

# Here is the entirety of the tactic:

 1. You ask someone a question

 2. They respond

 3. You repeat the *last three words* they said

 4. Then, you stop talking and wait

*That's it*.

# You speak calmly and curiously, inflecting the three words as a question.

If you can stop yourself from saying anything other than those three words, and you can wait just a bit longer than feels comfortable...

...the person will start talking again, telling you more and more.

And, believe it or not, they will *feel like you're hearing and understanding them*.

Why on earth does this work?

When humans hear their words calmly and curiously echoed back, it makes them feel understood. Which is a rare and pleasant experience. Then, having an empty space to fill compels them to start speaking again. Which exposes more information and emotion. Which can then be understood and validated. After a few cycles, they will feel /far/ more open to their listener.

It shouldn't be this easy. But it totally, totally is.

** Alistair Draws Max Out

Let's rewind. Alistair asks about the ProClaims status meetings. Max looks irritated and says:

"They feel a bit slow."

Alistair now looks at Max, and, calmly and curiously, he repeats Max's last three words:

"A bit slow...?"

And then Alistair stops talking.

There's a long moment of silence. Max stares at Alistair. Just as Alistair is ready to give up, Max suddenly starts speaking again:

"Yeah. The PM's and the engineers just keep talking past each other."

He sits back and frowns. Alistair nods. Naiah had insisted he go through a few rounds, to fully draw Max out, so he repeats Max's trailing words again, again calmly and curiously:

"Past each other...?"

Again a pause. And then *again* Max suddenly starts talking. "Yeah," he says and then gives an unhappy sigh. "And I can't even blame the engineers."

This remarkable statement almost makes Alistair break down, but he manages to stick to his plan. But my goodness he can't wait to tell Naiah about this one. "Blame the engineers...?"

Max swifly replies, "Yeah. I don't think the PM's even really understand the product."

Alistair is startled to hear this statement of concern from Max. Max hasn't complained to him about the PM's even once before this. Alistair has seen Max "blame the engineers", plenty of times, but up to now, Alistair had been assuming Max was on the PM's side, in all of their debates.

This is the first glimmer he gets into Max's true source of frustration and fear -- the lack of understanding on the part of the PM's.

# It shouldn't be this easy. But it totally is.

Repeating trailing words is a kind of cheat code for talking with humans. It gets people talking, it creates space for openness and vulnerability, it helps build trust and rapport. And all in only three words.

In the exercises below we'll explore how to most effectively practice this tactic.

But first, what should one do, if confronted with a glimmer of openness?

# It gets people talking, it creates space for them to open up, it builds

# [fn:: If you happen to like romantic comedies, you might catch this *exact tactic* being referenced in episode <something> of Nobody Wants This, in the fun B storyline of the two loser siblings (look, yes, I'm low-grade obsessed with romcoms)]

# It allows you to achieve two extremely valuable outcomes:

 # - *Acquire context*

 #   Once stakeholders start talking, they almost always disclose incredibly useful information.

 # - *Build rapport*

 #   You demonstrate, simply by asking questions, that you understand and care about your stakeholder's challenges.

 # - *Discover feelings*

 #   As they talk, they will just about always reveal key underlying emotions.

# Consider putting this book down, right now, finding someone and try this out. See what happens!

# But he can also tell that Max is feeling uncharacteristically open.

# How can he build on this fragile moment of rapport?

# Below, we'll see how Alistair can usefully build on this moment of openness.

# Below, we'll see how Alistair can build on this fragile moment of rapport

# Add "I'm glad I decided to tell you."

** Some Mistakes Alistair Could Now Make

Alistair has learned something fascinating: Max is frustrated by how poorly the PM's seem to understand the product. That might well be a root cause of some of his problematic behavior.

As he tries to digest this piece of information, he realizes that Max is looking right at at him. For once, Max isn't tensely checking his watch or glancing at another screen. It's almost like Max is... waiting to see what Alistair will say.

This is unknown territory.

Alistair has almost no experience of powerful people sharing even a hint of their underlying emotions. He's not sure what to do. To his dismay, he hears himself say "Ummmm."

Max raises an eyebrow.

Alistair's pulse jumps up.

What should Alistair do?

# Note that he is feeling slightly unmoored.

# Alistair has also created a moment where Max is briefly, tentatively open.

# XXX bring this moment to life -- Alistair sees something out his window of his home office. A tree with orange leaves.

# Below, we'll talk about what I believe to be the best thing he could do, which is to "Offer Labeled Feelings". But that takes some practice to master.

# Let's first review a series of other things he might try:

This is a key moment. His stakeholder has offered a window into his feelings. Alistair's response will either cement a level of rapport, or will cause Max to retreat and shut down.

# Let's talk about some bad ideas!

Let's first talk about what Alistair should *not* do.

** Mistake 1: Offer To "Fix The Problem"

Alistair has heard Max express frustration about the PM's lack of knowledge of the product. Luckily, Alistair *agrees*! This is an actual problem he's also actually noticed! Buoyed up by this rare moment of alignment with Max, a part of him is eager to jump in with ideas.

Let's imagine he listens to this voice, and quickly says:

"How about if we set up some product training for the PM's?"

This is totally helpful, right? Max is going to really appreciate this, right?

# Sadly, no.

In point of fact, if Alistair were to say this, Max would frown, shrug, and looks away.

If Alistair could eavesdrop on Max's inner monologue, what he'd hear would be: "Oh, sure, like it's that easy. We did onboardings, we did trainings. They just don't get it. And who is going to run those trainings? Me? I don't have *time*. Speaking of which, when is my next meeting?" And the nascent moment of connection would fade away.

Why would Max be ranting internally like this?

# Alistair has offered a perfectly reasonable option for solving the problem they're facing.

Because Alistair acted as if Max was *asking for help*.

That's not what Max was doing. Max was describing the situation he perceives himself to be in. A part of Max was seeking hoping to be understood.

When someone is hoping to be understood, proposing solutions makes them feel like:

 1. You don't truly understand them

 2. You think you're smarter than them

That's a very unfun combo.

We can, I suspect, all relate to this experience. Take some situation you personally find frustrating---perhaps some specific challenge with a boss or perhaps a family member. Imagine that you're talking to a friend, sharing why this situation is so hard. You've just barely started to open up about it, when that person suddenly start telling you what you should do. *Of course you're irritated*. You weren't even done explaining what's going on! You're not an idiot!

# You've tried all the obvious things in your situation, because you are, in fact, not stupid. It's like they think you're an idiot. it's like the think they're so smart they can fix this problem that they barely took the time to even understand.

Note that this bad outcome can happen, *even if your idea is a genuinely good one*. The frustrated response is not about the quality of the idea. It's happening because you skipped past the key next step: validating their experience of the world.

# It will often be *enormously tempting* to do this! But it is often a genuinely terrible idea!

And this is what Naiah had told Alistair he must next do: validate Max's experience. But that's easy to get wrong, too!

** Mistake 2: Allow The Slightest Hint of Judgment To Creep In

How might you validate your stakeholder's experience of the world?

The answer (which should not surprise you by now! This is literally always the answer!) is: you're going to echo back what you've heard. But you're going to do so in a very, very specific way. When echoing back feelings, you need to tiptoe past a precipice that can carry you to your doom: you need to avoid making your stakeholder feel at all *judged*.

How can this happen? Surprisingly easily. Again, let's rewind. Max tells Alistair:

# Convert to "would" like the above.

"Yeah. I don't think the PM's even really understand the product."

Alistair has been practicing his echoing back skills. He's working on not jumping in with solutions. So, he takes the time to echo back what he thinks he's just heard.

He looks at Max and says, steadily, "You seem frustrated with the PM's."

Max blinks in surprise. His lips tighten into a frown. He gives a tense shrug and looks away.

What's going on inside of Max, this time?

"I don't *like* feeling frustrated with the PM's. I've been trying as hard as I can to manage what is an objectively difficult situation. And now Alistair is telling me I 'seem frustrated'?! It's like Alistair thinks there's something wrong with *me*. What, am I supposed to *not* be frustrated?!"

We can all very easily feel judged when someone announces our emotions to us.

# really don't like someone to announce to them what their feelings are, in a way that sounds at all like they're being judged for having those feelings.

But... we also all (desperately!) want to be understood.

Let's see how you can thread that needle.

# How much do you think Max likes being told his feelings? Right, not at all.

# *** Exit the Scene

# Alistair says "Thanks", and hang up on the zoom. He sits there, a bit uncertain about what just happened.

# This isn't a terrible option.

# But it has two pretty significant downsides:

#  1. He hasn't confirmed he correctly understands Max's feelings

#  2. He missed a (rare) opportunity to build trust and rapport with Max

** Alistair Breaks Through

Naiah had insisted that Alistair spend real time, *before this conversation*, building an empathetic understanding of Max's situation.

In this moment, with Max looking expectantly at him, Alistair is very glad Naiah made him put in that work. With an effort, he manages to recall the mantra he's built up:

/"It's about the delivery, stupid."/[fn::Alistair is a fan of DB Pennebaker documentaries, and has seen The War Room twice.]

# Delivery, Delivery, Delivery".

Alistair believes Max is feeling enormous pressure to deliver the ProClaims transition. Alistair has taken some time to pick out specific, vivid details to bring that pressure to life.

He launches into his prepared description.

"If I understand it right," he says, "you've been asked to lead the entire ProClaims rewrite, across all the different strands. The whole company is counting on that rewrite landing by Q4. In fact, next year's sales forecast depends on having the new version of ProClaims to offer at a higher price point. And, because you helped build version one of ProClaims, the exec team asked you to lead both engineering and product."

He can see Max subtly nodding at each point. It's going well, so far. He now bridges to the new information he just heard from Max, earlier in this conversation.

"It sounds like there are some real challenges with the product team: the new PM's don't really understand how ProClaims work. I could imagine that, if I were in your shoes, I might find that pretty frustrating."

He pauses, and looks intently into his zoom screen.

# I would guess that means you have to stay tightly in the loop on all the different work streams. But then they complain about not being given any autonomy.

Max exhales slowly. "That's exactly it. *Exactly*. Everyone keeps telling me to let the PM's make decisions, but they just *can't*."

"I get that," says Alistair, surprised to find that he actually does. "Is there anything you want to try to improve things, in the short term?"

"I feel like I've barely been able to keep my head above water. Do you have any ideas?"

# Alistair is surprised to find this moment of genuine connection with Max. And even more surprised to realize that he does feel some genuine empathy for the situation Max is in.

And with that invitation, Alistair and Max dig into a productive brainstorming session.

** True Connection Is Possible

I'm imagining many readers, in this moment, visualizing their very own frustrating, emotionally shut down stakeholder, and saying to themselves "Dan, are you, like stoned? There is no way on earth this is going to work."

Look, I get it. It may seem literally impossible to imagine that stakeholder opening up to you in any useful way. But I encourage you to study and then practice the tactical empathy skills we've been discussing. You may well find yourself astonished by how far a mix of active listening, echoing, validating and open-ended questions can get you.

I have witnessed conversations where, after a period of steady, supportive probing, a previously unavailable and tense stakeholder suddenly admitted, with true vulnerability, some of their deepest fears. I have seen the stunned looks on the faces of their team. I have seen the awareness of a common humanity fill the room---and then allow all sides to work together in a way they had previously considered impossible.

Mastering these skills requires deliberate, reflective practice.

But such mastery can take you much farther than you might imagine.


* Scraps
** Our Story: Quin Draws Marco Out

Returning to Quin and Marco, say she's been coached in this conversational tactic by her new mentor.

She starts by asking a question of Marco: "I noticed that that call seemed a little frustrating. Can I ask what was going on?"

He responds, brusquely, "It's nothing. I'd just like to advance the deal."

She feels a momentary spike of frustration. Why won't he /talk/ to her? But then she remembers the trailing three words tactic. She takes a breath to focus and then says, calmly and with as much genuine curiosity as she can muster, "Advance the deal...?"

Marco says nothing for a long moment. A silence opens up between them. Just as Quin is about to give up, Marco abruptly says, "Yeah, they just keep talking and talking." And then he sits back and frowns.

Quin tries the tactic once more. "They're talking and talking...?"

This time, there's a slightly shorter pause before Marco starts up again. "Yeah. I honestly don't know if they're *ever* going to convert. Of if they just like *talking* about their problems."

Quin finds it's now quite easy to access her curiosity, so she's able to continue to draw him out. "About their problems...?"

Marco replies quickly, there's barely a pause. "Yes. It's almost like these aren't *real* problems. We might be talking about a vitamin, not a pain-killer."

Reid Hoffman is credited with the "Vitamin versus Pain-Killer" formulation for product opportunities. "Vitamins" are nice-to-haves. Potential customers will /tell/ you they want such products, but often they're doing so because they feel like they "should". "Pain-killers", on the other hand, are products that solve pressing, painful, important problems.

Quin, who knows the vitamin/pain-killer metaphor, realizes with a start that she's turned up one of Marco's biggest fears: ATN might be building something that customers don't truly need. He has not mentioned this fear, even once, to her or the team. She's both excited and a little scared by what she's discovered. She needs some time to process it.

She wraps up the conversation. She once again repeats the last few words Marco said, but this time, instead of inflecting it as a question, she indicates agreement.

"A vitamin not a pain-killer, got it," she says, nodding her head.

"Great, thanks," says Marco. He seems, she realizes to her surprise, relieved.

Those may look like dry words on the page, but the tactic is *remarkably* effective in person. It's honestly kind of amazing that you can get so far with such a simple approach.[fn:: If you are in some form of therapy, you may realize that your therapist does a lot of this!]

If you're able to deploy this tactic well, you'll achieve two extremely valuable outcomes:

 - *First, you'll build rapport*

   You'll demonstrate, simply by listening, that you want to work *with* the stakeholder to solve their problems.

   Marco started the above conversation half shut-down, struggling with his unstated fear that ATN was pointed in the wrong direection. By the end, he has a cautious hope that Quin understands that risk, and will work with him to face it.

 - *Second, you'll acquire context*

   Quin learned that Marco has fears about how deeply customers *need* to put in place remote team-building tools. How much their teams' potential lack of connection *matters*. ATN's products might be that dreaded failure mode of startups throughtout time: a "nice to have".

Understanding that is going to be incredibly valuable, if Quin is going to ask him to change his behavior.

She now has at least one answer to a key question: what does Marco fear might happen, at some point in the future?

But she (and you!) needs more.

** Our Story: Quin Puts It All Together

Over the course of the next few days, Quin comes up with answers to the four key emotion questions.

# Quin guesses a few feelings, uses trailing three words, echoes back and summarizes, offers labeled feelings, at the end, Marco feels excited, open, energized.

*Frustrations: What happens, day-to-day, that frustrates Marco?*

Quin simply makes an educated guess. Marco clearly feels like it takes /forever/ to see progress on the product---that's why he suggested putting pressure on the team to work longer hours.

She starts to fill out the template she got from her mentor:

 - Frustrations
   - Lack of visible progress (i.e. poor velocity)
 - Fears
 - Delights
 - Dreams


*Fears: What is Marco afraid might happen at some point in the future?*

She develops a picture of two related fears.

First, in the scene above, we saw Quin draw out a key fear through Repeat Trailing Three Words and Offer Labeled Emotions: Marco is deeply afraid that, although potential customers *seem* excited about All Together Now's under-development product, they may not truly *need* it.

Second, when she dug into Marco's strategic intent for the business (where she used Echo Back & Summarize), she learned that ATN needs to see *engagement* from some of their customers, in order to generate interest from funders.

She extends the template:

 - Frustrations

   - Lack of visible progress (i.e. poor velocity)

 - Fears

   - ATN might be developing a vitamin, not a pain-killer

   - Customers might buy but not use (and that could take a long time to learn)

 - Delights

 - Dreams

Once she's developed this much of the template, she spends some time trying to put herself in Marco's shoes; in particular, she tries to imagine what it would be like to have those fears eating away at her, every day.

She realizes that, in such a situation, she might be *very* tempted to try, somewhat desperately, to make the product *more compelling*. If she had a fear that the product was maybe not that valuable, or that customers might not use it, she might feel an intense desire to add features, promise to solve more problems, and smooth away any annoyances.[fn:: These are natural feelings, but, if you're developing a new product, you should resist them. You must start by finding customers who will pay for and use your product *even though* it's painfully limited, clunky and/or ugly. If you can't find any such customers, the odds of building a real business are pretty terrible.]

If she were on a call with a potential customer, and she heard them claim they *needed* some specific feature, she might feel intense urgency to do what they asked. Rational thinking aside, adding that feature might *feel* like the only way to save ATN from a looming disaster.

She is now certain that this is part of why Marco keeps trying to jam new feature ideas into their development process.

# She realizes she can understand and empathize with these underlying fears, even if she thinks the actions they are leading to are profoundly counterproductive.

*Delights: What happens, day-to-day, that makes Marco feel good?*

Here, she again comes up with two answers.

First, she's always seen Marco absolutely light up when he has a chance to try out a new UI. On the other hand, she's also seen him glaze over when the team reports progress on modeling some key concept in the database, or adding a new data integration. Visual, interactive prototypes clearly feel more real to him, produce more delight.

Second, she spends some time thinking about the stand up meetings. From her perspective, Marco is barging in and blowing up the team's focus by forcing an instant brainstorming session about some new feature idea. She tries to put aside her frustrations for a moment and imagine the situation from Marco's perspective. In particular, what benefits is he getting, from his current behavior? What delights him? She can't initially come up with an answer that makes sense, in part because she's been finding his behavior so frustrating.

She resolve to observe more carefully next time.

Sure enough, two days later, Marco comes charging in after a customer call, all fired up about how they might integrate with TikTok. By dint of some committed deep breathing, Quin manages to observe his behavior with curiosity, instead of seething frustration.

As she does so, something clicks. She realizes that she's seeing Marco go through a familiar arc. At the start, he's swirling with excitement and ideas ("What if we hosted TikTok dance contests? We could do AI mask overlays!"). As they talk, he gradually hones in on a coherent way to summarize what he's heard ("TikTok is where the employees go for *fun*"). By the end of the brainstorming, he has condensed and clarified his own thinking, and understands some options for product ("Okay, we could either host our own TikTok-inspired videos, or we could embed links to actual TikTok. At a first cut, those have the following tradeoffs...").

She realizes that going through that arc from confusion to clarity *feels good* to Marco. Of course, the team is intensely dizzied and distracted, so he can't keep doing it. But Quin is surprised to discover she can empathize with Marco wanting to quickly talk out what he has heard from customers, while it's still fresh.

That afternoon, she extends her template further:

 - Frustrations

   - Lack of visible progress (i.e. poor velocity)

 - Fears

   - ATN might be developing a vitamin, not a pain-killer

   - Customers might buy but not use, and that will take a long time to learn

 - Delights

   - Interacting with visual prototypes

   - Clarifying his thinking immediately after customer calls

 - Dreams

*Dreams*

During a one-on-one, Quin prompts a conversation by saying, "I wanted to ask: if things go really great, everything works out even better than we could hope, what will that look like in a year or two? What's, like, a crazy optimstic best case?"

She then deploys her new tactics. She draws Marco out by repeating trailing words, she echoes back and summarizes what she hears, and, as he gradaully reveals what he dreams about, she steadily labels and validates emotions.

Quin discovers something surprising. She went in to the conversation expecting Marco to speak about customer counts or annual revenue numbers or maybe next rounds of fund raising. He does describe some of those things, be she also hears him speak, with warmth and excitement, about seeing people laughing with their colleagues. She hears him speak about the close friendships he made at his very first job, fed out of afternoon breaks at the Foosball table and lunches grabbed in the atrium of their office building. She realizes he has a deep, underlying desire to share that experience, in this new world of remote collaboration.

After that meeting, she finishes filling out her template:

 - Frustrations

   - Lack of visible progress (i.e. poor velocity)

 - Fears

   - ATN might be developing a vitamin, not a pain-killer

   - Customers might buy but not use, and that will take a long time to learn

 - Delights

   - Interacting with something visual

   - Clarifying his thinking immediately after customer calls

 - Dreams

   - Building a successful business

   - Creating genuine connections that allow people to laugh together.

Quin now has everything she needs to make a compelling offer. She can offer Marco things he wants---greater velocity, visual UX prototypes he can interact with, options to quickly learn if there are real risks around the value of their product.

When she challenges him to change his behavior, she can offer him new, less disruptive ways to work together that will still give him what he wants and needs.

She can anchor all of that in profoundly motivating long-term goals.

Her work to develop a genuinely empathetic understanding has created a foundation for effective advocacy.

In the next chapter, we'll see how she can put this all together.
** Humans Love To Be Told What They're Afraid Of, Right?

Repeat Trailing Words will help get your stakeholder talking. But we want to, specifically, understand their feelings.

In fact, we want to *ask* them about their feelings to make sure we've got it right.

Of course, just as leaders are often resistant to *showing* their emotions, they can also easily become defensive if they perceive you as, in any way, *telling them* what their emotions are.

How can you talk *directly* about emotions with your stakeholder?
** Tactic: Offer Labeled Feelings

/"I see,"/ Alistair manages to say. He needs time to digest this new piece of information. He wraps up by echoing back. /"Let me say that back, make sure I understand. Those meetings are feeling slow and even a bit frustrating, because the PM's don't understand the product deeply enough to have a useful conversation with the engineers. Is that mostly right?"/

/"Yes,"/ says Max with a look of relief. /"That's exactly it."/


For example, in our story, Quin has gained some evidence that Marco has a significant fear around the value of what they're trying to build.

Imagine Quin were to say to Marco: "Are you afraid that we're not solving an important problem?"

Although that may actually be Marco's biggest fear, there's a very good chance that, instead of agreeing, he will become defensive and push back: "It's going to be fine. We just need the team to *deliver*."

This problem is particularly tricky for the negative emotions---frustrations and fears. If you try to speak to those, your stakeholder can easily feel like you're accusing them of being weak, or too emotional. But you urgently need to understand frustrations and fears---those two have the potential to absolutely shut down any attempt you make to change.

The trick to get these negative feelings out in the open is to carefully go through two steps, which Chris Voss names "Labeling" emotions:

 1. Describe the *situation* your stakeholder is in, with empathy

 2. Offer a potential label for their emotion, as a *natural response* to that situation

For part 1, Quin might /describe/ Marco's situation as follows:

"We're in a tricky spot. Potential customers keep telling us that they're *interested*, but because we don't have a thing we can *sell* them yet, we can't find out if they're genuinely willing to buy."

She would then immediately follows that up with part 2, an offer of a labeled emotion, lightly inflected as a question:

"It seems like you might be afraid that we're not solving a genuinely *important* problem...?"

Note that Quin has specified, in specific detail, what, in their current situation makes "being afraid" natural ("we can't find out if they're genuinely willing to buy").

She's also called the overall situation "tricky", which, again makes "being afraid" a  natural response.

Finally, when she then goes to describe his emotional reaction, she prefaces it with "It seems like you might...". She's not *telling* him his feelings, she's *offering* a potential understanding of his feelings.

When you make such an offer, it's *critical* that you preface it with an opening that creates separation between you and the statement of emotions you're about to make, e.g.:

 - "It seems like you might..."

 - "It would make sense if you were to..."

 - "I could imagine you might..."

Those prefaces allow the person to hear the statement of emotions as you *trying to understand them*, not announcing their feelings to them. Of course, those openings really only work if you can get yourself into a place of genuine curiosity, so that you truly *are* trying to understand.

Let's review the two different ways Quin could speak to Marco's potential fear:

Direct Question: "Are you afraid that we're not solving an important problem?"

Labeled Offer: "We're in a tricky spot. Potential customers keep telling us that they're *interested*, but because we don't have a thing we can *sell* them yet, we can't find out if they're genuinely willing to buy. It seems like you might be afraid that we're not solving a genuinely *important* problem...?"

On the page the two may not seem that different, but if you can do the work to lay out the situation first, and then offer that second part in a calm, curious, dispassionate tone, it has a *remarkably* powerful effect. Your stakeholder, instead of feeling *accused*, will feel *relieved*.

As Voss explains, research shows that, by naming fears out loud in this way, you can actually help people *feel* calmer. It both shows the person that it's okay to openly name the fear, and it also engages the rational, problem-solving parts of their brain.

This approach is *extremely* powerful, but it takes real practice to master, for two reasons.

First, it's not always easy to develop an empathetic understanding of the *situation* which leads to the feelings. You want to describe the situation in such a way that the resulting feeling seems *inevitable*. This is very much a learnable skill, and we'll return to it in the exercises.

Second, many of us have learned to *not* talk to other people about their feelings, especially people who seem upset or angry in any way (and especially especially if those people have some form of power). With experience, you'll find that offering labeled emotions almost always makes listeners feel *good*. Once you experience this tactic as defusing tension and anger, it won't feel so risky. But you have to build up that experience. In the exercises, we'll talk through how to practice this tactic in low-stakes situations.

# ** Tactic: Make Your Stakeholder A Beleaguered Hero

** Sidebar: You Have Feelings, Too

Before we dig into the exercises, I want to talk about a feeling you may be having:

Why are you the one who has to do this work?

Perphaps you have been struggling with your stakeholder's behavior for a long time.

Maybe they have an unpleasant habit of setting unrealistic goals and then self-righteously blaming you for not achieving them.

Maybe they have poor emotional boundaries, and their volatile anger undermines the fragile psychological safety of everyone around them.

# Maybe they are so unwilling to show vulnerability that they refuse to share any form of "bad news" with you. You repeatedly learn about serious external problems very late in your projects, and keep having to throw away months and months of work.

In such cases, you may be experiencing very natural feelings of frustration, resentment, or even anger. Feelings which can make it hard to do the work of developing an empathetic statement of your stakeholder's situation.

First off, I want to say: you may very well be /right/.

Far too few leaders take responsibility for the impact their behavior has on the people over whom they have authority.

# That said, another way to understand your current situation is simply that it's one in which you don't have *control*. Putting aside questions of right or wrong, part of what is going on is that you feel, accurately, like you have little power. You feel at the mercy of this stakeholder and their behavior. That doesn't feel good.

I wish I could tell you that you're going to be able to consistently work for leaders who possess the self-knowledge and emotional maturity to avoid inflicting problems on their teams. But, sadly, that has very much not been my experience. Having a robust toolkit of ways to engage with flawed human leaders and all their marvelously specific imperfections will serve you very well throughout your career and life.

Thus, my pitch to you is: consider doing the work to develop tactical empathy skills as a means to regain power for youself. As a means to get what *you* want and need.

But I don't want to pretend that it's always easy to handle your own feelings as you do so.

* Todos
** DONE Move the exercises into their own chapter?
CLOSED: [2026-02-04 Wed 08:08]
What would I call it?
 - Exercises For Divining Emotions
 - Mastering The Art Of Diving Emotions
** DONE Try putting bad ideas ahead of good for repeat trailing words
CLOSED: [2025-11-25 Tue 10:35]
** DONE Move definintion of Repeat Trailing ahead of example
CLOSED: [2025-12-03 Wed 13:33]
** TODO
