:PROPERTIES:
:ID:       4FEA3BD5-8E85-4BB6-8F59-15FDE4F38572
:END:
#+title: Master Tactical Empathy
#+filetags: :Chapter:
* Master Tactical Empathy
** Warning: Deliberate Practice Required

I'm going to share what I have experienced as one of the most powerful tactics of my entire working life.

# No exaggeration, I think my good fortune to be strong at this has made me a few million dollars over the course of my working career.

I have coached dozens and dozens of people on this approach -- and seen them adopt it with outstanding results.

But I have also seen it, consistently, take some real work to master.

It's what Chris Voss calls, in his truly excellent book, Never Split the Difference, "tactical empathy".

I'm going to lay out suggestions in the below, both on some specific skills and some ways to practice those skills. But this chapter, more than most, is going to require you to do some genuine homework, to get the value.

** What is Tactical Empathy
A series of ways that, when talking with someone, you can make them feel deeply and fully *heard* -- both intellectually (as in, they feel like you actually understand the some thing they care deeply about), and also emotionally (as in, they "feel felt", they perceive you as "with them" in some difficult challenge).

The trick is that, by doing this, you're not only building trust, you're *also* drawing out vastly more information than you otherwise would, about the context, their goals, etc.

Let me bring that to life with two versions of a conversation an engineering leader might have with an executive at their company.

# With a product manager
** Cultivate Curiosity & Sincerity
** Repeat Trailing Three Words
** Echo Back as Inquiry
** Posit a Spectrum to Draw People Out
** Make The Speaker a Beleaguered Hero
** Wait, Isn't This Product's Job?
