:PROPERTIES:
:ID:       4FEA3BD5-8E85-4BB6-8F59-15FDE4F38572
:END:
#+title: The Core Empathy Skill: Echoing Back
#+filetags: :Chapter:
* The Core Empathy Skill: Echoing Back
# Build Influence Through Empathy
** Intro

We're going to talk in this chapter about a foundational skill for building trust and rapport.

Developing this specific skill can dramatically increase your *influence* with the people around you--very much including your stakeholder. If you can demonstrate to your stakeholder that you truly understand and care about their concerns, you will find them enormously more ready to listen to *your* concerns, and then be willing work with you to find a way to address both.

The specific skill is Echoing Back.

Which, in brief, simply means summarizing what you've just heard your conversational counterpart say to you, and then asking if you've got it right.

This simple-sounding conversational widget is one of the most valuable skills I know.

# Within the overall suite of Tactical Empathy skills, I think Echoing Back is, in the working world, the most foundational.

# you'll be able to get people to listen to and your concerns, you'll be able to persuade them to take a chance on trying something new.

You'll be employing Echoing Back in just about every step of the overall game plan:

 - You'll use it when you mine for business context and goals during Identify a Strategic Outcome,

 - When you Map Key Emotions, you'll echo back as part of sussing [puzzling, ferreting] out your stakeholder's underlying feelings

 - As part of Propose an Adjustment, you'll use it to smoothly integrate any concerns or suggestions your stakeholder raises

We'll bring Echoing Back to life in the remainder of this chapter, and offer some concrete exercises to practice it. Although it sounds simple, it's interestingly hard to retrain yourself to confidently and repeatedly use it.

*Sidebar: Wait? Do Engineers Need All This Empathy Bushwa?*

/"Sure, Dan, I can see how building trust and rapport is important for *product*, but isn't that kind of the whole point of having a product team? So the engineers can just focus on building stuff? Do I really need to practice this Echoing Back thing? Or any other tactical empathy skills?"/

Indeed, tactical empathy is fundamental survival skill for a PM.[fn:: I test for it when interviewing for product roles] But it is also /insanely valuable/ for engineers. Empathy allows you to get unstuck with stakeholders, and engineers *very* much have stakeholders (often, y'know, the product team). It's also super valuable for many other facets of engineering work, such as: getting buy-in to try a new technical approach; advocating for technical investments with business counterparts; negotiating tradeoffs with engineering leaders; handling concerns from other engineers on your team, etc.

Most of the ways I know how to be a really strong, really valuable engineer involve working with other humans. And these skills are just crazy valuable for doing so.

** Defining "Tactical Empathy"

# /In my negotiating course, I tell my students that empathy is "the ability to recognize the perspective of a counterpart, and the vocalization of that recognition." That's an academic way of saying that empathy is paying attention to another human being, asking what they are feeling, and making a commitment to understanding their world./

   # /Notice that I don't say anything about agreeing with the other person's values and beliefs or giving out hugs. That's sympathy. What I'm talking about is trying to understand a situation from another person's perspective./

    /Empathy is paying attention to another human being, asking what they are feeling, and making a commitment to understanding their world. [It's] trying to understand a situation from another person's perspective./

    /One step beyond that is tactical empathy./

    /Tactical empathy is understanding the feelings and mindset of another in the moment and also hearing what is *behind* those feelings so you increase your influence in all the moments that follow. It's bringing our attention to both the emotional obstacles and the potential pathways to getting an agreement done./

From /In Never Split The Difference/, by Chris Voss, with Tahl Raz.

What makes this form of empathy "tactical" is that it *has a purpose*. You are trying to get to an /agreement/. To do so, you're looking for /emotional obstacles/ to overcome. You're trying to find /potential pathways/ forward.

Having a purpose to an act of empathy doesn't mean you're being insincere or manipulative. On the contrary, you *must* be sincere, or your stakeholder will immediately detect it. You must authentically speak to their experience of the world, to the situation they perceive themselves to be in. And then, from that place of genuine connection, you can find a way to move towards solutions that work for both of you.

Also, I *love* that Voss describes it as /"bringing your attention"/. So much of the work of empathy is quieting your own chorus of inner voices, so you truly fully pay attention to someone in front of you.

** An Absurdly Short Template For Echoing Back

We'll touch on various tactical empathy skills throughout the book, but for this chapter, we'll just focus on echoing back.

Here's how it works. Someone is talking to you. They pause You say:

 - "If it's okay, I'm going to say that back, make sure I understood it."

 - <you summarize what you think you heard>

 - "Is that about right?"

 - <you wait>

That's... it.

Why is this so powerful?

First, by summarizing, you will just about always discover something you didn't get quite right.

Your stakeholder will say, "Almost. But it's honestly not /that/ big a deal if we churn a few customers. What's /really/ important is..."

When this happens, you thank them and *immediately try again*:

 - "Oh, interesting! I didn't realize that. It sounds like it's more:"

 - <summarize what you heard again, incorporating this piece of information>

 - "Is that right?"

You repeat that little game until, eventually, they nod and say some form of "Yes, that's exactly right."

Refining your understanding this way is *incredibly valuable*. No matter how carefully you listen, it's almost always impossible to fully understand and align with someone based on a single statement they make.

By echoing back and inviting them to interactively "fix" your understanding, you can very quickly get to a fuller, richer, more nuanced understanding of what your stakeholder feels or believes. Which improved understanding will serve you *extremely* well, both when you later wish to influence themd, but also for accomplishing various key parts of your job. Basing your efforts on a flawed understanding of what your stakeholder is trying to tell you is a path straight to misery.

But there's another, extremely significant benefit to using this pattern.

Echoing back helps your stakeholder to *feel understood*.

When a person explains something they care about, it's, well, extremely rare for them to feel genuinely understood. For some stakeholders, that might present as a vague feeling of, "Ugh, that thing I said sounded really complicated, I'm not sure I made myself clear." For other stakeholders, especially those who enjoy projecting their insecurities onto others, it might present more as, "Man, I sure did an objectively awesome job of communicating that point. I wonder if my listener is too stupid to understand."

If my game plan for working with stakeholders assumed they were all kind and pleasant, I would not have very much to offer you. Luckily, that's not the case. You can address both "nice" and "not so nice" stakeholder the same way -- because they are driven by the same underlying uncertainty about being understood.

# Humans rarely experience themselves as being fully understood.

If you, as  that listener, take the time to summarize back your understanding, and get it even vaguely right, the speaker will feel a sense of *relief*.

If you pay careful attention, you may even see them visibly exhale and relax.

# It's like you've completed an open transaction that was otherwise hanging.

Which is exactly the mode you want them to be in, if you're going to turn the corner and ask them to engage in *your* concerns. Or if you're going to ask them to open up, just a little bit, about their hopes and dreams. Or if you're going to propose a new way of working, that may sound a bit risky or uncomfortable.

Fundamentally, you earn space to advocate, by demonstrating that you are willing to do the work to understand.

This is an incredibly valuable tactic, usable in an incredibly wide variety of situations. If you're only going to take one thing away from this book, spend some time learning to effectively echo back and summarize.

** Deanna Draws Out Karim

# Have them fail, then succeed.

# XXX Name the startup

Remember Deanna, our frustrated engineer at the startup? Whose CEO, Karim, keeps on blowing up her team's sprints with new feature ideas? And which CEO apparently believes that working longer hours will somehow fix his own inability to stick with a decision for longer than the lifespan of a fruit fly?

One day, after a particularly frustrating standup, Deanna pings Karim on Slack, and asks if they can check in one-on-one. He sends back a quick thumbs up, and a minute later, they're staring at each other in Zoom.

Behind Karim Deanna can see, as always, his bookcase with its neat rows of colorful business books. As she gathers her thoughts, she can see Marco's eyes flicking off screen. He has a habit of keeping other windows open during Zooms, she knows. She finds it a bit frustrating at the best of times. And this is very much not the best of times.

"I have to do this", she tells herself firmly. "It's for the team. Not just for me."

"I'm worried about our progress," she says, as firmly as she can. Karim nods without fully looking up from his other screens. "I know," she continues, "that you're wanting to see more velocity from the team."

She draws a deep breath. "I wanted to ask: if we did go faster *what would happen*? What would be a real *success*? Say it's six months from now, and things have gone *great*... what's happened? What have we gotten done as a company? I just don't feel as clear on that as I'd like to be."

Deanna is asking about goals in an excellent way -- by invoking a positive future, and then asking Karim to fill in the details. That framing often gets the person you're asking into an open state of mind, imagining things that make them feel good.

Unfortunately, today, it doesn't seem to work with Karim. He just squints at her. "We need sales," he says, brusquely. "And engagement." His eyes flick back towards another screen.

Just keep going, Deanna tells herself. "What /kind/ of sales?" she asks.

Karim shrugs. "I mean, it can't just be these little onesie twosie friends and family deals we've been getting. We need a *big* customer to commit. And we need them to *love* the product. We need to see excitement." He sits back. "That's why I keep telling you that we have to make the product *awesome*." He nods again, apparently in vigorous agreement with himself.

How is Deanna going to respond?

Let's /freeze/ Deanna and Karim in the midst of their conversation. They sit there, poised in the moment after Karim shared some information about his goals, but before Deanna has responded.

A mote of dust is hanging in the air in front of Deanna's screen.

We're going to grant outselves a magic ability. We can peer into their minds. We can observe their thoughts and their feelings. What do we find?

Let's start with Karim.

First off, as should not surprise us, given the tenor of his dialogue, Karim is more than a little tense. He's very worried about hitting the goal he just described. The one big customer he thought was going to commit has gotten skittish. Another saw an early demo and bounced off. Karim is also worried that Deanna is about to launch /another/ attempt to shut down his feedback on the product (naturally, that is how he thinks about his constant randomizing requests). They've been trapped in that argument for so long, he assumes they're still in it. He's not feeling connected or confident.

Okay, that's Karim. How about Deanna? What is running through her mind, as the mote of dust hangs suspended in the air?

Deanna is feeling, more than anything, *stymied*. Karim threw out his summary in such a terse, almost dismissive manner, she feels a bit rocked back on her heels. There was maybe something new, something she hadn't quite heard before, in how he spoke about customers needing to "love" the product. But... given his tone, it's hard to imagine getting into any form of collaboration whatsoever. Furthermore, Karim's statement about "making the product awesome" felt like a dig at her, an invitation to get back into their ongoing argument. Some part of her fight or flight system is threatening to kick in.

Let's see what happens if she gives in to the /flight/ impulse. Time moves forward, and...

Deanna blinks. "Okay, got it," she says. Her heart is racing. Karim is staring aggressively into his camera. She tries to come up with something to say, but her brain seems stuck. Finally, she musters a half-hearted "thanks." Karim nods in reply, they both awkwardly close their zooms and go about their day. In that moment, each of them is feeling secure in a sense of self-justified victimhood. Each blames the other.

Uggggggh. This is a near-total failure all around.

Let's rewind. Let's see what happens if, instead, Deanna gives in to the /fight/ impluse.

Karim threw down a gauntlet. Let's see what happens if she picks that gauntlet right the hell back up...

Deanna grits her teeth. "Look, I'm just saying that we need to *prioritize*. We need to pick something and stick with it. I'm obviously not saying we shouldn't make the product *better*."

Karim is shaking his head. "What you're /really/ saying is that you don't want me to talk to the engineers, right? That's not going to work. We're a *startup*. We need to move fast. You need to trust me."

At this apparently complete denial of the reality she lives in, Deanna feels almost dizzy with frustration and anger. The argument staggers fruitlessly on for a few more minutes, as it always does. After Deanna exits the zoom, she's closes her laptop and just stares blankly around her home office.

Alright, that was an even worse failure? It left them each in the same awful place. Feeling *justified* in their resentment.[fn:: The truly fascinating book, Leadership And Self-Deception, showed me that, when I'm stuck in a conflict, I often don't want my counterpart to change. What I want is to be *justified* in my anger.]

Let's rewind, and try one more time.

Let's see what happens if, despite feeling that rush of emotion, Deanna is able to access her ability to echo back.

Deanna makes herself pause. She sees, just to the side of her screen, the sticky note she posted there, which has "ALWAYS ECHO BACK" written on it. And underlined.

She takes a deep breath, and slowly exhales. She forces herself to go through her script.

"Let me say that back, see if I understood. We need to see sales, and some of those sales have to be from bigger customers than we've been getting. *And* we need to see those bigger customers *loving* the product. We need to see them highly *engaged*. That's why we need to keep making the product better. Is that about right?"

Karim stares at her intently. "That's pretty good," he says, slowly. It was... interesting to hear her summarize their goals. It sounded like she actually understood? Maybe she finally sees why he can't just let the product sit there, why he has to keep pushing to improve it. But, there was /something/ that didn't sound quite right. "But..." he starts, but then trails off.

"But what?" asks Deanna. This is easy for her to say--she's genuinely curious. And their not arguing.

Karim looks away, gathers his thought. It clicks into place. "You said we need to see those big customer highly enaged. I'm not sure that's realistic. For those big customers, it's going to take a while to ramp up to full use. What we need in the shorter term is for the buyer to love it."

"Oh, interesting," says Deanna, eagerly. "Let me see if I've got that. We /do/ need more sales, and we /do/ need some of those sales to be to larger customers. But, when we actually close those deals, getting to full engagement will take a while. So what we're looking for in the shorter term, is evidence that the buyer genuinely *loves* the product."

"Yes," says Karim. "I want to hear them talk about *how* they're going to get people to use it. I want to hear about the levers they're going to pull. To see them making a plan to *get* to engagement."

This is a fascinating bit of insight for Deanna. She hadn't thought much about what the buyer does after commiting to purchase. She certainly hadn't thought about leading indicators of engagement, pre-sale. This is what Karim is really good at, she remembers -- he's done a ton of sales. She wants to go and think about their backlog in light of this new understanding. She's getting ready to sign off when she sees her "ALWAYS ECHO BACK" sticky note. She thinks for a moment about how to summarize what she just heard.

"Could I maybe say that back as: the key evidence you're looking for is... an explicit plan to use their influence to get engagement. Is that about right?"

"That's /exactly/ it," Karim says. "You know, I like that. 'An explicit plan to use their influence.' That's good. Do you have any other questions?"

"No, I feel a lot clearer now. Thanks!"

"No problem," he says. "I'm glad we talked."

Let's freeze again.

Deanna has acquired a deeper understanding of both *why* Karim wants the product to seem exciting to their buyer, *and* how he'll be able to tell if they're succeeding in doing so. This gives her lots of interesting options. She feels engaged. Her mind is scanning over their backlog, thinking about how they could turn the various feature ideas into evidence of a plan to use influence. She's excited to share this insight with the engineers on the team.

Karim feels a rare sense of calm. It seems like Deanna really gets it, really understands what he's trying to do. That phrase she used is rattling around his head: "an explicit plan to use their influence." He likes it a lot. He can imagine saying it to their lead investor, at their meeting later that week. He remembers why he was excited when he first met Deanna--she had such a clear way of explaining things.

Notice how, as the conversation went on, Karim and Deanna just altogether stopped talking about his pattern of derailing sprints and/or giving feedback. They ended up just talking about the underlying thing he is trying to achieve.

Which allowed them to *connect*.

** How To Retrain Your Brain

I have coached dozens of people on echoing back and summarizing.

Over and over, I have seen people significantly level up their ability to influence and persuade. However, also over and over, I've seen them initially struggle to apply these tactics. Repeating words and echoing back summaries can just *feel* like such a strange way to talk to someone.

There are, I think, two core drivers for this:

First, when you're about to echo or repeat, your brain will tell you /"Ugh, they just told you this, don't *bore* them."/ This can feel weirdly intense. Almost like you're going to insult them.

Here's the thing. Humans, well, *love* hearing their own words and thoughts reflecte back to them. If you get it slightly wrong, they'll enjoy correcting you. If you get it right, they'll feel pleasantly surprised at the sense of clear connection.

Your brain just can not be trusted on this one. But you'll need to spend a bit of time retraining yourself.

Once you've practiced this enough, that feeling will disappear -- because you'll see how much people love to hear their own words and thoughts.

The second problem is that using these tactics will turn up valuable context, aka things you didn't previously know.

When that happens, your mind will suddenly make connections and see new opportunities. That will often feel *exciting*.

# In our scenario the engineering leader might suddenly see the connection between the Enterprise customers and the capacity challenges they were already eager to discuss.

When that kind of discovery happens, a spike of excitement hormones hits your bloodstream, and your brain immediately *urges* you to share this new awesome idea, right away.

"Oh," your brain will say, "they're going to love this, go go go!"

That's a trap -- you are *always* better served by first ensuring you fully understood and ensuring the speaker feels fully heard.

But it will feel urgently exciting, and you'll *forget*.

Again, it takes practice to retrain your brain.

I recommend doing some of that practice when the stakes are low -- aka, *not* in the midstof a critical negotiation with a key stakeholder.

Instead, pick someone you trust -- it doesn't have to be a co-worker, I've seen people profitably practice with a friend, roommate, or spouse.

If you're feeling nervous, you can explicitly ask that person, "Is it okay if I practice some active listening skills that I'm working on for my job?"

# This is for *you*, not for them -- to remove some of your fear of being annoying.
Then, ask your friend to explain something from their job. Ideally, something that's a bit irritating. Like, a problem they're wrestling with, or a difficult coworker.

Tell yourself, "My job is to deliberately do use the echoing tactic *too much* -- my goal is for the other person to say, afterwards, 'Eh, you could have echoed/repeated a bit less'".

Then, *every single time* the other person pauses after saying something, employ the tactic.

It should feel weird as heck.

After a few conversation rounds, pause, and ask the person "How did that feel?"

Listen to them, and repeat back what they tell you (no, really, it's empathetic turtles the whole way down).

Some questions you can ask your friend include:

 - "Did I miss anything important?"

 - "Was any part of it annoying?"

 - "Was there any part where I didn't sound sincerely interested?"

Then, keep practicing. Once you start to get a feel for it, work it into conversations with your stakeholder.

Throughout the rest of the book, you'll see a ton of places where I'll ask you to echo back and summarize.

** Cultivate Curiosity & Sincerity

A final point.

As you work to learn these tactics, you'll be very well-served by living in a place of *curiosity*.

If you can allow yourself to be genuinely curious, all of these tactics will come across as *sincere* -- which makes them 100x more effective.

Allow yourself to be curious about your business, allow yourself to be curious about your stakeholders, allow yourself to be curious about the problems in your business that your stakeholders are wrestling with.

It can sometimes be useful to try to unhook the part of your brain worries about whether or not you'll be percieved as intelligent or experienced (which is a totally natural thing to be worried about!)

You *will* be able to demonstrate intelligence and experience -- by asking great questions, and by giving concise and clear summaries.[fn:: Of course, I must acknowledge that I'm saying this as a tall, straight white man... so people are far too ready to ascribe intelligence and experience to me. But I have seen the tactic of "moving the conversation forward by being the listener and summarizer and clarifier" be a form of leadership for folks from less privileged groups.]

* Snipping Heres
** Example Stakeholder Won't Prioritize
Let's bring this to life.

Say you're facing a difficult prioritiation decision.

# XXX Be specific, tell a story

# Do an Echoing Back story?

Unfortunately, your stakeholder is angrily insisting that they shouldn't "have to" make this difficult choice. They bitterly push back, and say *all the goals* are equally important. You can't fail on any of them.

Tactical empathy means reaching for ways to connect with the underlying *feelings* that are leading to such irrational statements--aka, the situation your stakeholder perceives themselves as being in. What Voss calls "understanding their world".

Maybe that means digging for enough information to be able to summarize at the end by saying /"Wow, it sounds kind of like you have two different bosses. And you're being held accountable by them for different goals that are actually in fundamental conflict with each other. I could imagine that feeling like there's no way for you to win. Is that what's going on?"/

Note how, in this formulation, you're *offering* a potential understanding of your counterpart's situation and feelings, by using phrases like /"it sounds kind of like"/, and /"I could imagine that feeling"/. That's a powerful way to get feelings on the table without triggering defensiveness (absolutely no one likes being "told" their feelings directly).

If you can say something like the above, there's a very good chance the stakeholder will visibly relax.

You're then positioned to offer productive challenge and collaboration, e.g. "Okay, if we're able to get a clear, visible win for *one* of your two bosses, and just keep things kind of going as they are for the other, which one would you want to get the win for?"

And, lo, you have the start of a prioritization scheme.

Never Split the Difference is *incredibly* good, by the way. It sits very comfortably in my list of top five "You should totally go drop everything and read this" books.[fn:: Others in competition for that top five include "Escaping the Build Trap" by Melissa Perri, "The Principles of Product Development Flow" by Don Reinertsen, "The Mom Test" by Rob Fitzpatrick, "High Output Management" by Andy Grove, "The Art of Action" by Stephen Bungay, "The Pricing Roadmap" by XXX. And, of course, "Eleanor & Park", by Rainbow Rowell, because literally everyone's lives are better reading about two high schoolers falling in love while riding the bus.]

** Deliberate Practice Required

Mastering the skills of tactical empathy can be transformative.

I've seen leaders who had developed a damaging reputation as bruisingly difficult become respected and valued thought partners.

# , who people made certain to consult when facing hard problems.

I've seen people who had struggled to make their voices heard become confident, effective facilitators, deftly guiding tricky conversations forward.

I've seen people who felt stuck and bitter in their career discover profoundly meaningful agency, by being able to productively challenge the decisions they were most concerned about.

But *none* of those people accomplished those changes without putting in *significant* work to practice these skills.

Mastering tactical empathy means rewiring some of your conversational patterns. That is not easy.

At the very least, doing so involves practicing a set of situational scripts *and* practicing some specific, focused forms of listening and responding.[fn:: for all you theater geeks out there, it's like mastering the tactics of improvising with other people onstage. Also, hi there, theater geeks! You are so very much my people, if that wasn't clear already.]

Those two take some solid practice on their own.

But there's often something *beyond* those which is even trickier. Trying to master these skills will ultimately require you to face some of your *own* driving emotions... which can make it extremely difficult to change, well, yourself.

Of course, I can't tell you in detail how to face such struggles in your self (I am, y'know, kind of trapped in a book at the moment). But I will encourage you to, more than anything, cultivate a sense of curiosity *about your own reactions*. After you practice one of the below tactics with an actual stakeholder, take some time to reflect, with open curiosity, on whatever *feelings* came up for you. Maybe talk that out loud to yourself on a walk with your dog, or take a few minutes to write it out in a journal, or the like.

For some examples:

Maybe you were talking with a stakeholder who you experience as having an extremely frustrating form of control over your life, and, as a result, you found yourself so flushed and almost dizzy with resentment, you couldn't even hear what they were saying.

Maybe you attempted to assert some kind of control over a conversation, but found your anxiety spiking and making it hard to breathe, because of a painfully long history of feeling like your contributions were being cruelly and unthinkingly dismissed.

Maybe you set out to persuade someone to change a broken pattern of planning, but, before you could get into any dettails, you felt panic surging at the prospect of being blamed, once again, for the inevitable project failure, which made it hard to remember even a single tactic from the list.

As above, give yourself room to have these responses, and see if you can find a way to reassure that part of yourself that you're going to find a better way.

For more ideas on facing these kinds of internal challenges, take a look at the "Further Notes on Tactical Empathy" in the Appendix.

# somewhat surprisingly hard to apply these.

Okay, now let's dig in.

For each skill, I'm going to list some exercises afterwards. There's more in this chapter than you'll be able to master in a single sitting. I recommend reading through this, finding a skill that sound interesting, and then practicing that one for a bit.

As that skills becomes more comfortable, return to this chapter and pick another.

I've put three core skills in here, and added another three in an Appendix.

** The BreadBox Scenario

We're going to develop a scenario to explore these tactics.

Meet Janine, an engineering manager. She works at BreadBox, a SaaS startup which builds products for small- and medium-sized grocery stores, to help them manage inventory and purchasing. Janine leads a team of engineers who maintain BreadBox's flagship product. For reasons literally no one at BreadBox can explain, that product is named "Cogs".

Janine's team has been working for much of the last year on a pretty significant overhaul of that flagship product. The "Cogs 2.0" project, as it's known internally, has stretched a few months past its original planned go-live date (surprisingly approximately no one). That said, they *do* have some adventurous early adopter customers using a very rough beta version in the field, and a full migration is starting to feel possible at some point in the not too distant future.

The team's product manager is named Eduardo--he and Janine worked together for more than a year at this point. Eduardo has been a fairly solid partner to engineering--he manages stakeholder expectations well enough to create space for the team to execute, and he's not afraid to dig into the details to identify good increments.

But there is one part of their working relationship which Janine finds very frustrating.

It's painfully difficult for her to get Eduardo to listen to *any* concerns from the engineering team.

The team's grooming and planning meetings are entirely centered on user stories that Eduardo writes up, and he seems to write those on the fly in between meetings with stakeholders, which makes it impossible for Janine to participate.

If she tries to raise concerns about scalability or talk about tech debt, Eduardo expresses sympathy, and assures her that they'll find time for it as some point... but then they never do so. Worse, Janine feels like she's being "managed" by Eduardo during these conversations, and that's starting to damage her trust in him.

As a full customer migration to Cogs 2.0 approaches, the team is getting more and more nervous about all the corners they've cut. They've started pushing Janine to make a case to slow down and deal with some nasty buried problems. But Eduardo seems to feel more and more pressure to cram in "just one more feature" to please various stakeholders, and as a result, he seems even less willing than usual to listen to engineering's concerns.

Before we go any futher, I just want to note that this is a genuine problem.

Whether or not it's right to "fix tech debt" now, it's very important that there be a clear means for the engineers to advocate for investments in things they believe are valuable to the business. I believe the PM should almost always have ultimate say over prioritization (that's the heart of their job), but they should *also* be accountable for listening clearly to engineering and factoring engineering's concerns into the work of the team.

Eduardo isn't truly listening, and he doesn't seem willing to work with Janine to understand the concerns she's trying to raise. That broken interaction pattern is  creating real risk for the business.

# Of course, as more grocery stores are starting to use Cogs 2.0 in the field, there's more and more demand for Eduardo's time, so their regular 1:1's are starting to get cancelled with a somewhat alarming frequency.

# Which is hard, because there is a

# What should Janine do?

# Well, so far, her attempts to talk about the overall problem, the *pattern* of their working together, have gotten nowhere. And, as more grocery stores are starting to use Cogs 2.0 in the field, there's more and more demand for Eduardo's time, so her 1:1's with him have started to get cancelled with a somewhat alarming frequency.

Given this, Janine has (wisely) decided to narrow her requests down to one specific thing that she and them team are most worried about: database performance.

She and several senior engineers work to come up with an initial increment of change, focused on that concern.

# In this particular case, the team's biggest immediate worry is how the database will handle a full launch of Cogs 2.0. The new version makes a *lot* more requests from the front to the back end, and a bunch of those requests then issue DB queries  that are very, very far from optimized. There's even a chance they're going to have to reorganize some tables under the hood. They're pretty worried.

# They got enough worried that Janine and a couple of the engineers on the team have come up with a first increment -- they read O'Reilly's Implementing Service Level Objectives, and want to follow the game plan in the first few chapters to implement SLI's (those first few chapters are incredibly good, btw).

Now, Janine could go to Eduardo and lay that out as a proposal, ala:

/We want to spend a few weeks building Service Level Indicators, which will create insight into site performance, before we do any more migrations./

That's reasonable. It might work.

But let's think for a moment about the broader situation Eduardo finds himself in, when he hears this request from Janine.

As the migration approaches, Eduardo has dozens and dozens of other people making similar requests of him -- half the sales team, the director of customer success, Chelsea from the help desk, the company CEO who likes to check up on his corner grocery store's install of Cogs, etc. All of those people are constantly reaching out to Eduardo via Slack, email, casual conversations in the office kitchen.

Each requests sounds important. But Eduardo's default starting point is going to be to say no, and, likely, to spend as little time as possible on each request while doing so.

He literally couldn't get through his day otherwise.

# Every request urgent, every request time-sensitive.

# Companies have product teams *because* they can't do all the things they want, and someone has to steward a difficult process of decision-making.

# The product manager *can't* say yes to all of those requests -- in fact, they can't say yes to almost *any* of them.

From a certain perspective, Eduardo's *job* is to continually disappoint everyone around him.[fn:: Nathan Papazian, my product partner at Ellevation, commonly referred to himself as the company's Chief Disappointment Officer.]

And that includes engineering.

So we should not be surprised if Janine's suggestion of adding SLI's falls on deaf ears. Or immediately gets put on the "We'll get to that when we have some downtime" list, aka, the "We'll probably never get to it" list.

What could she do, to move her request to the "Let's talk about if it's this sprint or the next one" list?

A fundamental truth of working with humans: if you want someone to *listen to you*, you are incredibly well-served by *first, listening to them*.

But, it takes a bit of work to get most humans to genuinely share what they're thinking and feeling, so that they can *feel* listened to and heard.

So we're going to use a few tricks.

** Tactic 1: Repeat Trailing Three Words

The first one is simple and somewhat *bizarrely* effective:

First, you ask someone a question.

They respond with an answer.

You then calmly and curiously repeat the last three words they said, back to them, inflected as a question.

And then you stop talking and wait.

*That's it*.

If you can achieve any form of genuine curiosity as you speak, and if you can stop yourself from saying anything other than those three words...

... the person will then start talking again, telling you more and more.

And they'll *feel* like you're hearing and understanding them.

It shouldn't be this simple. But it totally works.[fn:: If you happen to like romantic comedies, you might catch this *exact tactic* from Never Split the Difference being referenced in episode <something> of Nobody Wants This (in the very fun B storyline of the two "loser" siblings, which honestly, I maybe loved more than the main storyline?)]

In our scenario, let's start by imagining that Janine does *not* have this skill at her disposal, and let's see how the conversation might go.

    JANINE: I'd like to talk about taking the time this month to implement Service Level Indicators -- it'd really help us stay ahead of potential performance issues.

    EDUARDO: [Busily typing away into Slack, only half looking up.] Okay, like, how much time are we talking about?

    JANINE: We're not sure, we think it's probably three weeks of work for Andrea. And we'd need some of your time to review what she comes up with.

    EDUARDO: [Looks up sharply] Wait, wait. I thought we were depending on Andrea to fix the issues with the 2.0 Snack Aisle features? I don't think we can pause that.

    JANINE: If we don't do the work now, we're not going to find time for it before launch. We're only talking about three weeks, we can timebox it you want.

    EDUARDO: [Frowns as he turns back to Slack] Okay, I'll think about it.

How'd that go?

Janine is trying to speak to value, which is good.

But Eduardo is clearly ready to ignore this... along with a dozen other things people are asking him for today.

To find another way, let's replay this conversation with the Repeat Trailing Three Words tactic.

First, Janine starts with a question -- *not* with immediate advocacy.

    JANINE: I wanted to ask -- how are you thinking about our key priorities for the month?

    EDUARDO: [typing on his laptop] I mean, we've gotta stay on track for the Cogs 2.0 migration.

    JANINE: ...the Cogs migration?

    [brief pause]

    EDUARDO: Yes. The Success team has *finally* started converting some of the busy urban grocery stores. [He stops typing, sighs]. Of course now they want to add all these new blocker "requirements".

    JANINE: ...oh, new blocker requirements?

    [pause]

    EDUARDO: [Now looking at Janine] Yeah. I mean, we're absolutely not going to do them all, but we're going to have to figure out which ones are genuinely important.

    JANINE: ... which are genuinely important?

    [pause]

    EDUARDO: Yep. Oh, that, and just some other fit and finish work, I think. [He considers for a moment, then nods and exhales] What's on your mind?

Those may look like dry words on the page, but it can be remarkably effective in person -- and it's, honestly, kind of bonkers that it can be done with such a simple approach. You sort of have to try it and experience it to fully believe it.

If you're able to deploy this tactic well, you'll achieve two *super* important things:

 - *First, you'll build rapport*

   You're demonstrating, simply by listening, that you want to work *with* the PM to solve their problems.

   Eduardo started the above conversation in a bit of a haze, half-listening, half-distracted.

   By the end, he had a sort of cautious hope that maybe Janine understands his problems.

 - *Second, you'll acquire context*

   Janine learned: how he thinks about the team's overall goal; which segment of customers Eduardo is focused on; and some tricky internal company dynamics he's wrestling with.

   She can put those to use in making her case.

We'll demonstrate how to do so, but first, we'll talk about a second core skill of Tactical Empathy.

*** Exercises

Because it's so simple, there are two good ways to practice the Repeat Trailing Three Words tactic.

1) Experiment In Random Parts of Your Life

Whenever you can, in whatever conversations you find yourself in, try repeating the last few words someone says to you, inflected as a question. Try it in both professional and personal contexts, try it with your boss, try it with your peers, with your spouse, kids, neighbors, whoever.

Do it over and over, and you'll find your own authentic way in, and it'll start to feel and more more natural.

If you start by using it just once in a given conversation, then, as that feels comfortable, see how long you can keep someone talking and opening up by just repeating those last three words of each thing they say to you.[fn:: "Dan, this whole active listening thing has helped my relationship with [insert spouse's name]", is something I've heard let's just say, a bunch of times.])

As above, take a bit of time to explicitly reflect on how it feels to do it, and use that reflection to tweak your personal approach.

For an initial, focused period of practice to rewire yourself, aim to do this 2-3 times/day for a week, and see where that lands you.

2) Explicitly Test With a Trusted Friend

Tell a friend you want to work on active listening, and then ask them a series of questions to dig into some issue -- maybe specifically something close to the kind of conversations you might have with a stakeholder.

E.g. you could say "I want to practice some active listening sikills I'm working on. Would it be okay if I ask you some questions about your work?"

And then see if you can dig for information about what they're most worried about, and what they most hope to achieve, using the repeat trailing three words tactic as you go.

At the end, pause and ask for feedback from them on how it felt for them.

During a period of focused practice, do this 3-4 separate times, and again, make sure you make time to reflect.

** Tactic 2: Echo Back and Summarize

Returning to our story of Janine and Eduardo, she has, thanks to the repeat trailing three words tactic learned that Eduardo is focused on migrating busy urban grocery stores to Cogs 2.0.

# XXX a bit of a repeat with the end of previous section.

This context provides an *excellent* opening to discuss the database performance issues she's worried about--those busy urban grocery stores will use some of Cogs 2.0's new features at a scale that could really strain the DB.

If the team *doesn't* build better visibility into capacity limits via SLI's, they could end up frustrating those valuable, high-traffic customers the moment they convert.

Given the above, here is the key question:

*What should Janine say next?*

Remember, the last thing Eduardo said was:

    /EDUARDO: Yep. Oh, that, and just some other fit and finish work, I think. What's on your mind?/

He has *invited* Janine to state her concerns!

Clearly, she can now start speaking to potential value, right?

Nope.

Instead, in this moment, she should slow down and carefully *repeat back a brief summary of what she's just learned*.

And then ask if she's got it right.

i.e. in our story above, that might look like:

    EDUARDO: Yep. Oh, that, and just some other fit and finish work, I think. What's on your mind?

    JANINE: Let me just say that back, see if I've got it. [consults her notes, takes a breath, then looks up]. The biggest focus for this month is migrating as many high-traffic urban groceries as we can. The success team is raising a lot of issues they think are blockers, but your guess is that not all of them are *actual* blockers, so there's going to be some work to untangle that. Beyond that work, it's mostly just fit and finish, to get ready for the full migration. Is that about right?

    EDUARDO: Yeah, that's... most of it. [He trails off]

    JANINE: [notices his hesitation] What's not right?

    EDUARDO: Well, I don't expect us to *actually* migrate many urban stores *this* month -- but we need to be sure we can *next* month.

    JANINE: So, it's, like, ensuring we're fully *ready* to migrate, is that right?

    EDUARDO: [He nods, satisfied] Yes, that's it.

Why is this so valuable?

First, by summarizing, you will nearly always discover something you didn't get quite right.

In the example above, *being ready* to convert some key customers *next* month is quite different from *actually converting* those customers *this* month.

If Janine had left the conversation believing the goal was immediate conversions, she'd be taking her team down the wrong road.

Second, summarizing back makes an enormous difference in helping the speaker to *feel understood*.

When a person explains something they care about, it's quite rare for them to feel confident that they've actually been understood.

It's rare for them to be consciously aware of this -- but some part of them will wonder, uncertainly, if their attempt succeeded or not.

I feel like I should say that, for certain kinds of, well, extra difficult stakeholders, they won't be thinking "Did my attempt to communicate succeed?" but rather, "Did the listener understand this completely clear point I just made, or are they stupid?" If my game plan for working with stakeholders assumed they were all kind and pleasant, I would not have very much to offer you. Luckily, that's not the case.

You can address both "nice" and "not so nice" stakeholder the same way -- because they are driven by the same underlying uncertainty about being understood.

# Humans rarely experience themselves as being fully understood.

If you, as  that listener, take the time to summarize back your understanding, and get it even vaguely right, the speaker will feel a sense of *relief*.

If you pay careful attention, you may even see them visibly exhale and relax.

# It's like you've completed an open transaction that was otherwise hanging.

Which is exactly the mode you want them to be in, if you're going to turn the corner and now ask them to engage in *your* concerns.

You can earn space to advocate, by demonstrating that you are willing to lead with empathy and understanding.

This is an incredibly valuable tactic, usable in an incredibly wide variety of situations. If you're only going to take one thing away from this chapter (or, frankly, this book), spend some time learning to effectively echo back and summarize.

*** Exercises

I'm going to take some time to talk about how to learn this one, because it's so foundationally valuable. I have coached dozens of people on this approach. Over and over, I've seen them initially struggle.

Echoing back summaries just *feels* like such a strange way to talk to someone. When you're about to echo or repeat, your brain will tell you "Ugh, they just told you this, don't *bore* them."

Once you've practiced this a few times, this feeling will fade away. You'll come to realize that people love to hear their own words and thoughts.

Another problem is that using these tactics will turn up valuable context, aka things you didn't previously know. When that happens, your mind will suddenly make connections and see new opportunities.

That will often feel *exciting*.

In our scenario the Janine suddenly sees the connection between the large customers and the database performance challenges she's eager to discuss.

When that kind of discovery happens, a spike of excitement hormones hits your bloodstream, and your brain immediately *urges* you to share this new awesome idea, right away.

"Oh," your brain will say, "they're going to love this, go go go!"

That's a trap -- you are *always* better served by first ensuring you fully understood and that the speaker feels fully heard.

Also, the ideal way to play this game is to clarify the speaker's thoughts, as you echo them back. To make your summary *useful*. That also takes real practice.

Because of these challenges, it's best to first practice this one when the stakes are low--aka, *not* in a negotiation with a key stakeholder.

Here's the game plan:

First, pick someone you trust -- it doesn't have to be a co-worker, I've seen people profitably practice with a friend, roommate, or spouse.

Ask that person, "I'm working on some active listening skills. Would it be okay if I asked you some questions as part of that?"

# This is for *you*, not for them -- to remove some of your fear of being annoying.

As the conversation starts, tell yourself, "My job is to deliberately do use this tactic *too much* -- my goal is for the other person to say, afterwards, 'Eh, you could have echoed/repeated a bit less'".

Then, *every single time* the other person says something, say "Let me say that back to you, see if I've got it right." Then say your understanding, then say "Is that about right?"

It should feel weird as heck. After a few conversation rounds, pause, and ask the person "How did that feel?" Listen to them, and then repeat back what they tell you.

If you'd like, dig for a bit more info, by asking if they ever felt at all irritated or annoyed, or if you missed anything important.

Then, keep practicing.

Once you've got some basic comfort with it, try it out with a "lower stakes" peer, then move on to stakeholders.

A great topic to practice this with is Mapping Fears and Aspiration.

** Tactic 3: Posit a Spectrum to Draw Someone Out
The two tactics we've discussed so far are useful for keeping a conversation moving.

But sometimes, it's hard to get a conversation going at all.

Sometimes, you ask a stakeholder:

/"What are most important goals for the next quarter?"/

And they say:

/"All our goals are important."/[fn:: Sometimes, as a bonus, they look vaguely affronted that you've asked them to prioritize and/or think.]

It can feel like the stakeholder is an unyielding wall, and you can't get into an actual conversation.

One tactic I've found useful is to:

 - Guess two different, potentially valid answers to the question

 - Offer them as "ends of a spectrum"

 - Ask the stakeholder where they think things land on that spectrum

Part of why this works so well is that you are, in essence, *offering the stakeholder an opportunity to tell you you're wrong*.

But to do so in a way which allows you to fill in your picture, to answer the most important contextual questions.

That is much "safer" and easier for a stakeholder to do than to come up with an initial answer themselves.

Let's say that Janine finds herself in a conversation with the CEO, and takes the opportunity to try fill in her picture of overall company context[fn:: This is a super valuable habit to build, by the way.]

    JANINE: I'm pretty excited about how Cogs 2.0 is coming together, on the engineering side. Oh, that reminded me, I wanted to ask: when we finally *do* migrate all the stores, what's the win you're most excited to see, at that point?

    CEO: [tilts his head] What do you mean?

    JANINE: We've been working on it for so long, and I've heard lots of different things people are hoping for from it. I'm just curious: what's the thing you, specifically, are most excited about?

    CEO: [laughs] Having the project be over? I mean, honestly, there's a lot, dunno if I can narrow it down. [shrugs]

Now, Janine could certainly give up at this point. But she could also take a shot at  using the Offer a Spectrum tactic to get her CEO talking:

    JANINE: I could almost imagine two different ends of a spectrum.

    [Holds her left hand up to indicate one end]. On the one hand, I've heard that, once we've got all the stores on 2.0, it's going to simplify new store set up a *ton*.

    The Success team won't have to build an inventory plan from scratch every time, we can use templates, it'll be both faster and cheaper.

    So that should save us a bunch of money, and maybe let us go after some smaller stores.

    But, [holds up her right hand, showing a space between it and her left] I've also heard a lot of excitement about, once 2.0 is out, being able to create new add-on features for high-volume stores.

    Which will let us add a pro tier, charge more, increase revenue per store.

    Is it more one of those than the other? Or some mix of the two? Or something else?

The CEO is going to hear this, and it's going to be hard for them to not jump in and respond. They might pick one end, they might pick a mix, or they might reject the spectrum altogether. *All of those are valuable to Janine*.

Let's see how that could look:

*** One End Is Right

/"Oh, don't worry about the Success team. They like to complain about store set up, but, frankly, it's fine. But we *need* to start adding pro features, our whole growth plan depends on that."/

Great! Janine can now not worry so much about the complaints from the Success team.

*** It's a Mix

/"Those *are* the key things -- but those are both part of improving profitability as we grow. I think we'll be doing a mix of both, neither one will likely be enough on their own./

Ah hah! Janine has learned that the CEO is thinking a lot about profitability. Super useful.

*** Something Else Altogether

/"I mean, it's not really either of those. We've got a whole high end sales pipeline that is stalled, beacause of the crappy ways that PoS integrations works in Cogs 1.0. Once Cogs 2.0 gets out there, with better integrations, we can move upmarket./

Fascinating -- hopefully she already knew about PoS integration pains. It'd be great to find out more about moving upmarket, and why the CEO thinks that's so important.

And of course, ocne she's got the CEO talking, Janine can start to repeat trailing words and echo back summaries and draw out more information.[fn:: *hopefully* Janine hasn't spent a year building something without being clear on the ultimate strategic value that the CEO is hoping for. Sigh.]

*** Exercises

This one rewards some slowing down and practicing ahead of time, because it requires a skill of "imagining two plausible answers".

Thus, I'd recommend:

 - Make a list of 3-5 interesting questions in your part of the business

   E.g. this could include engineering-centric things like "What is the immediate win from building product <X>?", but also further afield things like "What part of the sales demo do prospects find most exciting?"

 - Pour yourself some coffee, and for each, brainstorm a bunch of answers, and then narrow it down to two.

 - Take those into conversations with people use the tactic and see what you find

#  Putting It Altogether

# XXX E.g. say that Eduardo and Janine are now talking to the head of Customer Success, who has been raising the potential blockers for moving the high-end urban stores over. Eduardo asks "What's the exact problem if one of them experiences sluggish site performance?" But gets nothing back. Janine then steps in and guesses.

* For an Appendix
** Tactic 4: Offer a Labeled Understanding of Feelings
It seems like, maybe you could
** Tactic 5: Play Low Status to Inject Concerns
** Tactic 6: Make Your Stakeholder a Beleaguered Hero
ad

** Parts Work
<touchy feely emotional stuff>

If you find one of these, or something similar, I will offer the approach I have found most useful for myself. At the recommendation of some excellent therapists I've worked with (and also of the movie Inside Out), I visualize a part of myself, who is responsible for that emotion, as a specific imagined person. I take time to *appreciate* that that person, that part of me, as important. I work to recognize that they are doing their very best to *protect* me. I then *thank* them, and tell them that I've got it for now, and it's okay for them to stand down for a bit.

For me, probably my biggest trigger is feeling like there's a looming disaster which I am going to be blamed for--but where both my concerns and my proposed plans are being patronizingly dismissed. Being talked down to when I'm trying to bring attention to a real problem just makes me kind of lose my mind. And not in a useful way.

In trying to gain some understanding and control over myself, I spent some time developing a picture of a part of me I named "The Panic Captain". He sits in a small office, tensely scanning screens full of information. If it looks like I'm going to get blamed for a failure, he reaches over and presses a giant red button. An alarm sounds, lights would flash, and my veins flood with cortisol and adrenaline. He had helped me many times through the years, by quickly putting me on high alert when I need to react quickly -- but he also sometimes grows tired, and haggard, and starts reaching for the big red button all the time. And so, when I feel a surge of panic rising, I sometimes take a deep breath, visualize him at this desk, and genuinely thank him. I say to him "It's okay, I've got this. If I need you, you'll be there."

This kind of, well, empathy with yourself can be a key to making these kinds of changes.

</touchy feely emotional stuff>


* [OLD] Practice Tactical Empathy
** Putting Ourselves In a Stakeholder's Shoes

# A Brief Exercise In Stakeholder Empathy

# Sometimes, It's Hard To Be a Stakeholder

# It's Hard Out There for a Stakeholder

#

I think it's legitimately hard for most engineers to imagine just how [well and truly] *miserable* it is for many stakeholders to work with engineering.

In almost every other part of their working life, a business leader gets to:

 - Identify an important problem

 - Set goals that represent solving that problem

 - And then *give those goals to someone*

# That is, in fact, what it means to be an effective leader -- set clear goals, and hold people accountable to achieving them.

But once engineering gets involved, everything goes to hell.

What seem like straightforward goals turn into an absolute blizzard of confusion, the engineers produce ridiculous estimates, then fail to meet those estimates, then finally deliver something that doesn't even *work*.

When the business leader asks questions, they get back a flurry of incomprehensible jargon.

And then, despite literally *everything* being painfully far behind plan, the engineers announce that they want to *stop working on actual business needs* so they can "clean things up", or "retire tech debt".

It's weird as hell to work with engineering.[fn:: I like to think it's like hiring a contractor to remodel your kitchen, going away for the weekend, and coming back to discover they've demolished your entire house because they found some wiring they think is "ugly".]

# XXX Cut the below and stash it somewhere for later/other book

If you want to be effective in *advocating for technical investments*, you need to build a different kind of relationship -- one founded on trust and rapport.

Ideally, your company has a strong product team, who play a central role in building trust and rapport with The Rest of the Business.

But I have found that, for *technical investments specifically*, it's often down to the engineering leader to persuade their business counterparts -- be they sales, the CEO, *or their product manager* -- of the potential value of some specific chunk of work.

# This is a core part of why great engineering leaders combine strong technical judgment with *effective influence*.

We're going to talk in this chapter about leveling up on influence.

# XXX Connect to multiple steps of game plan

** Defining "Tactical Empathy"

Mastering effective influence is the work of a lifetime.

We're going to focus on a few core skills.

These are factors in what Chris Voss, in his excellent book "Never Split the Difference" (written with Tahl Raz), calls *Tactical Empathy*:

    /In my negotiating course, I tell my students that empathy is "the ability to recognize the perspective of a counterpart, and the vocalization of that recognition." That's an academic way of saying that empathy is paying attention to another human being, asking what they are feeling, and making a commitment to understanding their world./

    /Notice that I don't say anything about agreeing with the other person's values and beliefs or giving out hugs. That's sympathy. What I'm talking about is trying to understand a situation from another person's perspective./

    /One step beyond that is tactical empathy./

    /Tactical empathy is understanding the feelings and mindset of another in the moment and also hearing what is *behind* those feelings so you increase your influence in all the moments that follow. It's bringing our attention to both he emotinoal obstacles and the potential pathways to getting an agreement done./

A key: as Voss emphasizes, deploying the skill of tactical empathy doesn't meant that you have to believe your conversational counterpart is *right* or *justified*.

If your stakeholder is angrily insisting that they shouldn't "have to" make a difficult prioritization choice, and they bitterly push back by saying "everything is important"... they are, of course, wrong.

Tactical empathy means reaching for ways to connect with the underlying *feelings* that are leading to such irrational statements -- aka, the situation that person perceives themselves as being in.

Maybe that means digging for enough information to be able to summarize at the end by saying "Wow, it sounds like you kind of have two different bosses. And you're being held accountable by them for different goals that are actually in fundamental conflict with each other. I could imagine that feeling like there's no way for you to win."

Note how, in this formulation, you're *offering* a potential understanding of your counterpart's situation and feelings, by using phrase like "it sounds kind of like", and "I could imagine that feeling". That's a powerful way to get feelings on the table without triggering defensiveness (no one likes being "told" their feelings directly).

If you can say something like the above, there's a very good chance the stakeholder will visibly relax.

You're then positioned to offer productive challenge and collaboration, e.g. "Okay, if we had to disappoint one of those two bosses, but get a visible, clear win for the other, which would be the way to go?"

NSTD is *incredibly* good, by the way. I super, super highly recommend it.

** A Scenario, An Opportunity And A Challenge

We're going to develop a scenario to illustrate these tactics.

Let's say you've followed the game plan in this book, up to here.

You've dug in on the engineering team's concerns, and, in so doing, found one that you were able to turn into a statement of significant potential value for the business.

Let's say that one was around site capacity -- the engineers are justifiably concerned about the risk of the site slowing down to the point of becoming unusable.

You've done a little bit of work on the side, to build some crude visibility.

As a next step up the ladder, you've roughly scoped a small project around developing good Service Level Indicators[fn:: The first few chapters of O'Reilly's Implementing Service Level Objectives are an incredibly good game plan for this].

You could go to your product counterpart and lay that out as a proposal, ala:

/We're worried about site capacity. Our initial monitoring of the database is showing some worrisome spikes, so we want to spend a few weeks building Service Level Indicators, which will create much more actionable data./

That's reasonable. It might work.

But let's practice empathy again, this time focused on the situation our product counterpart finds themselves in, as we go to them with this request:

Your product counterpart likely has *dozens* of other people making *similar* requests of them, *all the time* -- sales people, the success team, the help desk, your company's visionary CEO, all reaching out via Slack, email, casual conversations in the office kitchen, difficult negotiations in front of half the leadership team. Every request urgent, every request time-sensitive.

# Companies have product teams *because* they can't do all the things they want, and someone has to steward a difficult process of decision-making.

The product manager *can't* say yes to all of those requests -- in fact, they can't say yes to almost *any* of them.

The Product Manager's *job* is to continually disappoint everyone around them.[fn:: Nathan Papazian, my product partner at Ellevation, commonly referred to himself as the company's Chief Disappointment Officer.]

And that includes engineering.

So you should not be surprised if your well-reasoned advocacy about site capacity, as above, falls on deaf ears. Or gets put on the "We'll get to that when we have some downtime" list, aka, the "We'll probably never get to it" list.

What can you do, to move your request to the "Let's talk about if it's this sprint or the next one" list?

A fundamental truth of working with humans: if you want someone to *listen to you*, you are incredibly well-served by *first, listening to them*.

But, it takes a bit of work to get most humans to genuinely share what they're thinking and feeling, so that they can *feel* listened to and heard.

So we're going to use a few tricks.

** Tactic 1: Repeat Trailing Three Words

The first one is simple and somewhat *bizarrely* effective:

First, you ask someone a question.

They respond with an answer.

You then calmly and curiously repeat the last three words they said, back to them, inflected as a question.

And then you stop talking and wait.

*That's it*.

If you can achieve any form of genuine curiosity as you speak, and if you can stop yourself from saying anything other than those three words...

... the person will then start talking again, telling you more and more.

And they'll *feel* like you're hearing and understanding them.

It shouldn't be this simple. But it totally works.[fn:: If you happen to like romcoms, you might catch this *exact tactic* from Never Split the Difference being referenced in episode <something> of Nobody Wants This]

In our scenario, let's start by imagining that the engineering leader does *not* have this skill at their disposal, and let's see how the conversation might go.

    ENG: I'd like to talk about taking the time this month to implement Service Level Indicators -- it'd really help us stay ahead of potential capacity issues.

    PRODUCT: Okay, how much time are we talking about?

    ENG: We're not sure, we think it's probably three weeks of work for Andrea. And we'd need some of your time to review what she comes up with.

    PRODUCT: Oh, I don't know. I thought we were depending on Andrea to fix the issues with the search indexing with Forms 2.0. I'm not sure we can slow that down right now.

    ENG: If we don't do the work now, I bet we're not going to find time for it before launch. We're only talking about three weeks, we can timebox it you want.

    PRODUCT: Okay, I'll think about it.

How'd that go?

The Engineering leader is trying to speak to value, which is good.

But...

...most product leaders would experience this as someone *pushing* them for something.

And a core survival skill for a PM is being able to ignore people who push them for things.

To find another way, let's notice that, at one point, the PM stated a *concern*: "I'm not sure we can slow that down right now".

The Engineering Leader responded with, essentially, an *argument*: "If we don't do that work now..."

Let's replay this conversation with the Repeat Trailing Three Words tactic.

First, the engineer will start with a question -- not with immediate advocacy.

    ENG: I wanted to ask -- how are you thinking about our key priorities for the month?

    PRODUCT: Well, we absolutely have to stay on track for the Forms 2.0 migration.

    ENG: ...the Forms migration?

    [tiny pause]

    PRODUCT: Yes. The Success team has *finally* started converting some of the Enterprise customers, and they're complaining about all sorts of new blocker requirements.

    ENG: ...oh, new blocker requirements?

    [tiny pause]

    PRODUCT: Yeah. I mean, we're absolutely not going to do them all, but we're going to have to figure out which ones are genuinely important.

    ENG: ... which are genuinely important?

    [tiny pause]

    PRODUCT: Yep. Oh, that, and just some other fit and finish work, I think. What's on your mind?

# XXX Insert something about "Those may look like dry words on the page, but it's remarkably different in person -- and it can be done with such a simple approach. You have to try it and experience it to fully believe it.

If you play this game at all well, you'll achieve two *super* important things:

 - First, you'll build *rapport*

   You're demonstrating, simply by listening, that you want to work *with* the PM to solve their problems.

 - Second, you'll acquire extremely useful *context*

   Which you can then use as part of making your case.

We'll demonstrate how to do so, but first, we'll talk about a second core skill of Tactical Empathy.

** Tactic 2: Echo Back and Summarize

In using the Repeat Trailing Three Words tactic, the engineering leader has learned that the product manager is focused on transitioning Enterprise customers.

This context provides an *excellent* opening to discuss the site capacity issues, because enterprise customers use site features at a scale that puts greater than normal strains on capacity.

Thus, if the team *doesn't* build better visibility into capacity limits, they could end up frustrating those enterprise customers the moment they convert.

Given the above, here is the key question:

*What should the engineering leader say next?*

The last thing the product manager said was:

    /PRODUCT: Yep. Oh, that, and just some other fit and finish work, I think. What's on your mind?/

The PM has *invited* the engineering leader to state their concerns!

Clearly, the engineering leader can now start speaking to potential value, right?

Nope.

Instead, in this moment, the engineering leader should slow down and carefully *repeat back a brief summary of what they've just learned*.

And then ask if they've got it right.

i.e. in our story above, that might look like:

    PRODUCT: Yep. Oh, that, and just some other fit and finish work, I think. What's on your mind?

    ENG: Let me just see if I've got this. [consults notes]. The biggest focus for this month is converting Enterprise customers. The success team is raising a lot of issues they think are blockers, but your guess is that not all of them are *actual* blockers, so there's going to be some work to untangle that. Beyond that work, it's mostly just fit and finish, to get ready for the big launch. Is that about right?

    PRODUCT: Yeah. I mean, the one caveat is that I don't expect us to actually convert many Enterprise customers *this* month -- but we need to be sure we can *next* month.

    ENG: So, it's, like, ensuring we're fully *ready* to convert, is that right?

    PRODUCT: Yes.

Why is this so valuable?

First, by summarizing, you will nearly always discover something you didn't get quite right.

In the example above, *being ready* to convert Enterprise customers *next* month is quite different from *actually converting* Enterprise customers *this* month.

If you had left the conversation believing the goal was immediate conversions, you'd be taking your team down the wrong road.

Second, summarizing back makes an *enormous* difference in helping the speaker to feel understood.

When a person explains something they care about, it's quite rare for them to feel confident that they've actually been understood.

They won't usually consciously articulate this to themselves -- but some part of them will wonder, uncertainly, if their attempt succeeded or not.

I feel like I should say that, for certain kinds of speakers who are maybe not the most fun to work with, their internal narrative will not be "Did my attempt to communicate succeed?" but rather, "Did the listener understand this completely clear point I just made, or are they stupid?"[fn:: If my game plan for working with stakeholders assumed they were all kind and pleasant, I would not have very much to offer you. Luckily, that's not the case.]

Luckily, you address both of those the same way -- because they are driven by the same underlying uncertainty about being understood.

# Humans rarely experience themselves as being fully understood.

If you, as  that listener, take the time to summarize back your understanding, and get it even vaguely right, the speaker will feel a genuine sense of *relief*.

If you pay careful attention, you may even see them visibly exhale.

# It's like you've completed an open transaction that was otherwise hanging.

Which is exactly the mode you want them to be in, if you're going to turn the corner and now ask them to engage in *your* concerns.

You earn space to advocate, by demonstrating that you are willing to lead with empathy and understanding.

** Tactic 3: Posit a Spectrum to Draw People Out
The two tactics we've discussed so far are useful for keeping a conversation moving.

But sometimes, it's hard to get a conversation going at all.

Sometimes, you ask a stakeholder:

/"What are most important goals for the next quarter?"/

And they say:

/"All our goals are important."/[fn:: Sometimes, as a bonus, they look vaguely affronted that you've asked them to prioritize and/or think.]

It can feel like the stakeholder is an unyielding wall, and you can't get into an actual conversation.

One tactic I've found useful is to:

 - Guess two different, potentially valid answers to the question

 - Offer them as "ends of a spectrum"

 - Ask the stakeholder where they think things land on that spectrum

For example, that could sound like:

/"I've heard you say that the Enterprise customers are our next key target for conversion. I could imagine at least, like, two different reasons for that. On the one hand, I could imagine it's because they represent so much of our revenue -- so we need to make sure we're converting them, because we think getting them on 2.0 will make for happier customers. Or, on the other hand, I could imagine it's more that the Enterprise customers have the most complex use cases, so doing the conversion will force us to ensure that 2.0 fully meets all the use cases of 1.0 -- across all of our customers, not just the enterprise ones. Would you say it's more one of those than the other? Or more something else?"/

Part of why this works so well is that you are, in essence, *offering the stakeholder an opportunity to tell you you're wrong*.

But to do so in a way which allows you to fill in your picture, to answer the most important contextual questions.

That is much "safer" and easier for a stakeholder to do than to come up with an initial answer themselves.

In the above, they might say something like:

/"It's mostly just that they're such a big chunk of our revenue. Well, that and also because they each have a hotline to someone on Customer Success, who will then come and derail our work if things don't seem right."/

Or they might say the opposite:

/"Oh, the immediate revenue is not important, you can not worry about that. It's really much more about ensuring that 2.0 has genuine feature parity with 1.0."/

Or they might say:

/Oh, it's really not either of those. The enterprise customers just have so many users, it's going to take a long time to do the change management. And our support team can't support both versions forever, so we need to start that clock./

Then, you've got them talking, and you can start to repeat trailing words and echo back summaries.

** Wrapping It All Up

Continuing our scenario, having gained all this information, the engineering leader is ready to lay out a really effective case for technical investment.

They could take some time to review their notes, maybe talk to an engineer to flush out a bit more detail and then say[fn:: Or write down in a memo -- I find writing both forces a useful clarity of thinking and can also provide a nice opportunity for sharing your thinking with engineers who are growing towards leadership] something like the following:

/Okay, it sounds like our key goal for *this* month is to ensure we're ready to transition Enterprise customers to Forms 2.0, *next* month./

/We really want those first ENT customers who come over to have a *great* experience of Forms 2.0, because the ENT segment represents almost half our revenue, so we can't win without them. And they have a lot of clout through their dedicated Success team partners, so if any one of them has a bad experience, it could blow up our ability to keep moving forward./

/The engineers have identified a risk -- all our early adopters of Forms 2.0 come from our SMB segment. Those customers all have relatively small data sets. But the Enterprise customers who use the old, legacy Forms 1.0 product, all have *much* bigger data sets than we've seen for the new Form 2.0 in production so far./

/As we've sprinted to build Forms 2.0, we've asked the team to get things out in the simplest form as quickly as possible. Which we're really glad about. But we think there's a very real chance that, if an ENT customer were to start using Forms 2.0 today, with their large data sets, they would experience painfully long load times for almost all the key new pages. In fact, worst case, many of those pages could potentially seem broken./

/We really don't want that to happen./

/Fortunately, we think we have a couple of good options for speeding things up -- once we find any bottlenecks./

/Unfortunately, we don't have great *visibility* into how those pages are performing, or where bottlenecks are./

/Therefore, we'd like to propose that we commit time to building a clearer picture of our capacity limits, and, once we've done that, ensuring that we have sufficient capacity to guarantee an excellent experience for the first Enterprise customers who commit to Forms 2.0./

This is a far more persuasive pitch then where things started -- it's laid out in the context of the stakeholder's immediate goals, it makes clear that the lack of visibility is in and of itself a key problem, it even subtly evokes some specific and vivid fears ("many pages could potentially seem broken.")

In fact, the product leader is so convinced, they say:

/"That sounds like a great idea, thank you raising this concern. Just one question, and then I'd be ready to commit time on the roadmap: how long will this project take? How long will it take to ensure good performance for enterprise users?"/

How to answer that question is the subject of our next chapter.


** Cultivate Curiosity & Sincerity
A final point.

As you work to learn these tactics, you'll be very well-served by living in a place of *curiosity*.

If you can allow yourself to be genuinely curious, all of these tactics will come across as *sincere* -- which makes them 100x more effective.

Allow yourself to be curious about your business, allow yourself to be curious about your stakeholders, allow yourself to be curious about the problems in your business that your stakeholders are wrestling with.

It can sometimes be useful to try to unhook the part of your brain worries about whether or not you'll be percieved as intelligent or experienced (which is a totally natural thing to be worried about!)

You *will* be able to demonstrate intelligence and experience -- by asking great questions, and by giving concise and clear summaries.[fn:: Of course, I must acknowledge that I'm saying this as a tall white man with a deep voice... so people are far too ready to ascribe intelligence and experience to me. But I have seen the tactic of "moving the conversation forward by being the listener and summarizer and clarifier" be a form of leadership for folks from less privileged groups]

* Scraps
** Warning: Deliberate Practice Required

I'm going to share what I have experienced as one of the most powerful tactics of my entire working life.

# No exaggeration, I think my good fortune to be strong at this has made me a few million dollars over the course of my working career.

I have coached dozens and dozens of people on this approach -- and seen them adopt it with outstanding results.

But I have also seen that it takes just about everyone some real work to master.

The approach I'm talking about is what Chris Voss calls, in his excellent book, Never Split the Difference, *"tactical empathy"*.

I'll explain what that concept means, break down some specific tactics, and offer exercises that I've seen people use to build their skills up.

But this chapter, more than most, is going to require you to do some genuine homework, to get the value.

** Engineers Need Context and Decision-Making

# Product? CEO? Marketing? Yes.

Unfortunately, for the company as a whole to be successful, engineers also need two things from their business counterparts, that *not all other teams need*.

First, engineers need a lot of *context* -- they need to know *why* they're being asked to achieve certain goals.

It's only with generous amounts of context that engineers can, when they hit the inevitable roadblocks in the original plan, come up with creative solutions that still solve the underlying problems.

Second, engineers also need someone who can make frequent *decisions*. So much is learned as you go, the company can only win if there's someone who is ready to swiftly make difficult tradeoff and reprioritization calls.

In some ways, we're just talking about the role of product management.


But, I have found that, for *technical investments specifically*, it's often down to the engineering leader to persuade their business counterparts -- be they product, marketing, or the CEO -- to provide that kind of full context and decision-making partnership.

I would love to live in a world where, when an engineer asked someone "*Why* are you asking me to build thing X?", they got a rich, full answer, situating the desired feature as part of a coherent business strategy, with various options and tradeoffs already on the table.
But, back here in reality, we often fail to live up to that ideal.

So, the first thing engineering leaders are going to want to level up on is, extracting business context from those around them -- and doing so in a way that builds trust and rapport.

Which brings us to the marvelously powerful skills of *tactical empathy*.

** Scrap

I would love to live in a world where, when an engineer asked someone "*Why* are you asking me to build thing X?", they got a rich, full answer, situating the desired feature as part of a coherent business strategy, with various options and tradeoffs already on the table.
But, back here in reality, we often fail to live up to that ideal.

So, the first thing engineering leaders are going to want to level up on is, extracting business context from those around them -- and doing so in a way that builds trust and rapport.

Which brings us to the marvelously powerful skills of *tactical empathy*.

** Tactical Empathy By Example

A series of ways that, when talking with someone, you can make them feel deeply and fully *heard*.

Both intellectually (as in, they feel like you actually understand some thing they care deeply about), and also emotionally (as in, they perceive you as "with them" in facing some difficult challenge).

It allow you to both building trust, but *also* draw out vastly more information than you otherwise would, about context, goals, risks, etc.

All of which is just incredibly valuable for engineering leaders -- *especially* if they are preparing to advocate for a technical investment.

I'll bring that to life with two versions of a conversation an engineering leader might have with an executive at their company.

*** Scrap

The information you're obtaining is super useful for at least two reasons:

 - First, so you can understand what technical work is most valuable to the business right now

 - Second, so you can clearly draw those connections

E.g. if you come to understand that the new user model tweaks are a part of a major strategic shift to open the product up to more users, who are are likely to significantly increase the volume of daily visits, suddenly those lingering database capacity issues might feel a lot more important to fully suss out. And you have a straightforward way to advocate for that work, by tying it to the upcoming shift.s

*** Version 1 - Solid Questions, No Tactical Empathy

[Scene: Morning. We're in the kitchen in the offices of WeFixU, a health care startup that provides virtual primary care. LIESL KO, an engineering manager at WeFixU, is blearily pouring herself a cup of coffee. She looks up, and there, hovering by her elbow, she discovers CHRIS COLABRI, WeFixU's CEO. LIESL blinks uncertainly.]

CHRIS: [briskly] Morning.

LIESL: Morning, um, Chris.

CHRIS: [Nodding] It's... Lisa, right?

LIESL: Actually Liesl, but close enough, haha.

[CHRIS smiles absently and, as LIESL steps back, pours himself a cup of coffee. LIESL screws up her courage].

LIESL: Do you mind if I ask you a question?

[CHRIS blows on his coffee and shrugs, non-committally. LIESL forges on.]

LIESL: So, my team is adding providers to our user model.

CHRIS: Okay?

[LIESL has clearly lost him]

LIESL: Let me back up. I think we're trying to let doctors log in? Is that right?

CHRIS: Oh, absolutely. That's a key goal. [He nods vigorously]

LIESL: Why are we... doing that?

CHRIS: Because it's really important.

LIESL: Oh. I see.

CHRIS: Glad we got to talk, Lisa. Wait, Liesl! [He claps her on the shoulder and strides off]

*** Post-Game Analysis

First off, seriously, god bless Liesl, for having the guts to ask her CEO *why* her team was building something.

But... she didn't get very far -- her question kind of bounced off Chris.

She neither learned anything that might help her team come up with creative solutions to underlying business problems, *nor* did she build up rapport and trust with Chris so that she could later be ready to advocate for one of those creative solutions.

Let's see how it might go, if Liesl had really strong tactical empathy skills.

*** Version 2 - Same Questions, Solid Tactical Empathy

[...]

LIESL: Let me back up. I think we're trying to let doctors log in? Is that right?

CHRIS: Oh, absolutely. That's a key goal. [He nods vigorously]

LIESL: [intently]... a key goal?

CHRIS: Yes. We've got to improve the provider experience.

LIESL: ... the provider experience?

CHRIS: *Exactly*. Right now, specialist providers can't even find us an option, so they're turning patients away.

LIESL: Oh, interesting. Let me say that back, see if I've got it. It sounds like right now, when patients talk to a specialist, and tell them that WeFixU is their primary care, the specialist doesn't know who we are. And that means they turn the patients away? Is that right?

CHRIS: Yes, yes. Well, *almost*. It's also, they have systems to verify primary care providers, but we're not listed in those.

LIESL: ... not listed in those?

CHRIS: Right. And that's not something we think we can fix.

LIESL: Okay, let me say that back. The reason we're getting turned away is partly because we're not listed in the systems that the specialists use to verify primary care providers. But that's hard enough to solve, we think we're better off giving the specialists a way to connect with us directly? Is that about it?

CHRIS: Yes, exactly. That's good. That's right.

LIESL: Cool. Can I ask one more question?

CHRIS: [checks watch] Shoot.

LIESL: Why, exactly, do we think we can't fix the issue with being listed?

CHRIS: What do you mean?

LIESL: Well, it's like, I could imagine a couple of reasons. Maybe [she gestures with one hand, over to her right], it, like, takes a long time to get listed, and we don't think we can afford to wait. Or, on the other [gestures with the other, to her left], I could maybe imagine that, because WeFixU is a pretty different kind of primary care provider, the main listings don't know what to do with us. Is it one of those, or like, a mix of the two? [indicates with her hands, points on the spectrum between the two]. Or something else?

CHRIS: Oh I see what you're saying. It's kind of a combination -- *because* we're so different, it seems to be taking forever to move ahead with the listing companies. So we think it makes more sense to let providers just directly log in.

LIESL: Got it, got it. It's the combination of those two.

CHRIS: Exactly. Well, I've got to go. I'm really glad we got to talk!

LIESL: Me, too. And remember, Liesl not Lisa!

[CHRIS laughs]

*** Post-Game Analysis

** Old Conclusion w/ Good Increment

/Therefore, we're proposing that Andrea spends the next three weeks developing and implementing a first draft of Service Level Indicators -- which will show us, basically "Are customers happy in their use of Forms 2.0?". And if they're *not*, we can know before the help desk or success team comes to us, and the team can quickly swarm and address it./

/This has some real tradeoff costs. We had planned for Andrea to take point on adding new features to the Search Indexing. We think the potential performance issues are a bigger risk. And, if we understand it right, not all the ENT customers need those new Search features, so we might be able to delay the transition for customers who do need them. We believe the risk of bad performance cuts across all of the ENT customers./

/The key milestone Andrea would be working towards, which she can hit within 3 weeks, would be to ready to sit down with you and me, and review both the definitions of an initial set of the SLI's *and* how those SLI's are performing in production./

/We'd then be able to decide, together, if that performance seems acceptable. If so, we can return to our original plans and just keep an eye on performance as transitions ramp up. If performance already seems problematic, or if we're just uncertain, the team could start some proactive load testing, or if we've found any bottlenecks, deal with those./

/But we don't have to make that decision yet -- we'll have more info in just a few weeks./

Note how the engineering leader is offering a carefully time-boxed increment that ends with a *shared decision*

The fundamental definition of the first stage of this technical investment is: build a thing in mo more than 3 weeks that will both create some incremental improvements *and* allow the stakeholder and the eng leader to make a collaborative decision about what to do next.
