:PROPERTIES:
:ID:       8CF44890-0C7E-4892-9C0E-21DFE789C7FF
:END:
#+title: Dani Notes
* <2025-06-30 Mon>
What are problems that people talk about, worry about?

The way they're introducing planning cycles, they plan in halfs.

Your plan can be

Different interpretations of it - some, month by month roadmap.

Others, e.g. Dani's, this is the direction we're committing to learning in.

As they're talking through it all -- since this is the first planning cycle. For the first 10 years, build the thing they wanted to build.

Because they had autonomy, they 'managed tech debt really well'.

Over last year and a half -- PM was introduced. Understood it as this is my boss -- I can only do what they ask for. Became a feature factory.

Engineers saying "these all sound good", but if we don't deal with Unity upgrade, it's going to suck.

Pull vs push.

Metaphor she'suing which is clicking. Our goal for H2 is to run a maraethon in under 4 hours. Have to invest in good shoes.

We don't say our goal is to take a bath every six months.

Is helping them find the ability to factor in, e.g.

How is that shared w/ product team. Not too much.

Her product partner isn't deeply engaged in details.

She is expecting there will be some bigger rocks, they'll need to prioritize. She's encouraging the teams to write up one-pagers. And they'll review those along w/ PRD's.

PRD

They use "Linear".

What about other engineering managers.

The more junior one more frequently laments that they're building debt. Will occasionally "go take care of it on the weekends". He's about to learn the limits of the sustainability for that one.

The other one, more experienced, she -- Dani talks w/ her about recognizing the systems that are fragile, need more support.
