:PROPERTIES:
:ID:       5903AFE7-4B1E-422C-8537-2C56BBFBA643
:END:
#+title: Mine for Frustrations, Fears & Dreams
#+filetags: :Chapter:
* Mine for Fears & Dreams
** Humans Have Feelings, Ignore At Your Own Risk

I'm going to go out on a limb here and guess: you probably work with humans.

That's great! Except, of course, for when it's not.

If you want one of those humans to change their behavior, it's absolutely critical for you to understand their *feelings*.

This may sound a bit odd. Perhaps you work with a CEO whose only outward expression of emotion is a series of variations on the tightly clenched jaw. You might have legitimate debates with coworkers about whether or not this CEO even *has* feelings.

Look. Understanding feelings doesn't mean gathering in a drum circle and getting in touch with our inner child. All humans, in whatever positions of power they may find themselves, have things they deeply want, and things they are deeply afraid of. I don't care what role they're in, your stakeholder's current behavior patterns are driven by some combination of what they want and what they're afraid of.

When you advocate for change, you want to be able to speak with authentic connection to both the fears that are keeping them up at night, as well as the things that they desperately wish were happening.

But there's a problem.

Many leaders do their best to *hide* their feelings. If you haven't had positions of serious responsibility over large groups of other humans, I encourage you to have some empathy for people in these roles. It can feel incredibly important to "project confidence". And that can very easily turn into "pretend to have no fears or desires". In fact, many leaders unconsciously feel a sort of desperate fear of their emotions being found out. They feel, usually without realizing it, that they must *hide* their emotions to retain control.  That is why it's so common to feel like you're banging up against an unyielding, inhuman, unemotional wall.

However, even if your key stakeholder seems to be working very hard to present as a goal-driven business automaton, you *must* find a way to get past that.

To persuade your stakeholder to risk making a change, you need to to develop an *empathetic understanding* of their fears and dreams.

That empathy will allow you to productively challenge them to change their current behavior, by speaking authentically to their *underlying concerns*. Even if they've been actively trying to hide those from you.

Persuading humans to change their behavior works roughly a thousand times better if you can find a way to speak to their hearts as well as their minds.

Let's talk about how to map your stakeholder's feelings.

** The Four Key Emotions

Fortunately, you don't have to worry about every facet of your stakeholder's inner life. You're going to develop a picture of just four key emotions, which will mean coming up with answers to four questions:

 - *Frustrations*

   What happens, day-to-day, that frustrates your stakeholder?

 - *Fears*

   What are they afraid might happen at some point in the future?

 - *Delights*

   What happens, day-to-day, that makes your stakeholder feel good?

 - *Dreams*

   What do they most fondly hope happens at some point in the future?

These form an extremely powerful core for persuasion. Two focus on day-to-day experiences (frustrations and delights), two on longer-term motivations (fears and dreams).

If you can come up with answers to these four questions, you can build an *extremely* compelling request to try something new. A request that the stakeholder will both *hear* and *feel* as worth listening to.

We'll spend real time on how to craft such a request in the "Make a Compelling Offer" chapter.

But first we need to talk about how to come up with answers to these questions.

You're going to use a mix of two techniques:

 - Making an Educated Guess

 - Mining For Emotions

The first one is, well, about as simple as it sounds.

If your stakeholder is in some position of authority within your company, you should be able to *guess* at answers to at least a few of the four questions by simply spending some time talking with people you trust. Of course, that's only true if you work at a company where people consider it important to understand what the hell the people in power are doing and *why* they're doing those things, but that's every company I've ever worked at?

Making an educated guess is a very good way to start, but, often that's not enough. Especially if your stakeholder seems committed to showing as little vulnerability as possible.

In that case, you'll need to do a bit of detective work, which we'll call "mining for emotions". For that, we'll develop two more tactical empathy skills.

** Tactical Empathy Skill #3: Repeat Trailing Three Words

If you want to understand your stakeholder's fears and dreams, you're going to, well, need them to *talk to you*.[fn:: At least that's true... now? If this book is invalidated by mind-reading technologies, ALL BETS ARE OFF.]

Unfortunately, it often requires real work to *get people talking at all*.

Luckily, there's a surprisingly simple tactic that helps a great deal on this front.

Let's see it in action, with Quin and Marco. First we'll show the challenge, and then we'll lay out the tactic:

One day, Quin notices that Marco seems frustrated after a call with a potential customer. Eager to build up her picture, she says, "I noticed that that call seemed a little frustrating. Can I ask what was going on?"

Marco says shortly, "It's nothing. I'd just like to advance the deal." He shows no interest in explaining more.

This is a near-total failure. Quin hasn't learned anything useful about Marco's feelings, beyond the fact that he'd like this potential customer to buy their product. Which, of course, she already knew.

If you were in Quin's shoes with some key stakeholder of yours, what would you do? It seems like the stakeholder actively wants to shut the conversation down. Asking another question about their feelings could easily slide over into being irritating. Should you just give up and wait for another day? Or should you push for more, despite the risk of actively annoying them?

Unfortunately, *neither* of these approaches is likely to help you. Neither will give you the insight you need into your stakeholder's underlying drives, in order to advocate for change.

What you *can* do instead is to employ a simple and somewhat *bizarrely* effective tactic, "Repeat Trailing Three Words".

Here's how it works.

First, you ask someone a question.

They respond with an answer.

You then calmly and curiously repeat the last three words they said, back to them, inflected as a question.

And then you stop talking and wait.

*That's it*.

If you can achieve any form of genuine curiosity as you speak, and if you can stop yourself from saying anything other than those three words...

...the person will start talking again, telling you more and more.

And they'll *feel* like you're hearing and understanding them.

It shouldn't be this simple. But it totally works.[fn:: If you happen to like romantic comedies, you might catch this *exact tactic* and the book Never Split the Difference being referenced in episode <something> of Nobody Wants This (in the fun B storyline of the two "loser" siblings, what, you're not low-grade obsessed with romcoms?)]

Returning again to Quin and Marco, say she's been coached in the Repeat Trailing Three Words tactic by her new mentor.

She has asked Marco a question. He has responded with: "It's nothing. I'd just like to advance the deal."

To employ the tactic, Quin simply responds, calmly and with genuine curiosity, "Advance the deal...?"

Marco says nothing for a long moment. A silence opens up between them. Just as Quin is about to give up, Marco abruptly says, "Yeah, they just keep talking and talking." And then he sits back and frowns.

Quin tries the tactic once more. "They're talking and talking...?"

This time, there's a slightly shorter pause before Marco starts up again. "Yeah. I honestly don't know if they're *ever* going to convert. Of if they just like *talking* about their problems."

Quin tries again, "About their problems...?"

Marco is now talking smoothly, there's barely a pause. "Yes. It's almost like these aren't *real* problems. We might be talking about a vitamin, not a pain-killer."

Reid Hoffman is credited with the vitamin versus pain-killer formulation for product opportunities. "Vitamins" are nice-to-haves. Potential customers will /tell/ you they want such products, but often they're doing so because they feel like they "should". "Pain-killers", on the other hand, are products that solve pressing, painful, important problems.

Quin, who knows the vitamin/pain-killer metaphor, realizes with a start that she's turned up one of Marco's biggest fears---that ATN might be building something that customers don't truly need. He has not mentioned this fear, even once, to her or the team. She's excited by what she's found, but needs some time to process it.

She can now wrap up the conversation with a slight variation on what she's been doing. She'll once again repeat the last few words Marco said, but this time, instead of inflecting it as a question, she'll indicate agreement.

"A vitamin not a pain-killer, got it," she says, nodding her head.

"Great, thanks," says Marco.

Those may look like dry words on the page, but the tactic is *remarkably* effective in person. It's honestly kind of amazing that you can get so far with such a simple approach.[fn:: If you are in some form of therapy, you may realize that your therapist does a lot of this! It really works.]

If you're able to deploy this tactic well, you'll achieve two extremely valuable things:

 - *First, you'll build rapport*

   You'll demonstrate, simply by listening, that you want to work *with* the stakeholder to solve their problems.

   Marco started the above conversation half shut-down, struggling with his unstated fear that ATN was pointed in the wrong direection. By the end, he has a sort of cautious hope that Quin maybe understands that risk, and will work with him to face it.

 - *Second, you'll acquire context*

   Quin learned that Marco has fears about how deeply customers *need* to put in place remote team-building tools. How much their teams' potential lack of connection *matters*. ATN's products might be a "nice to have".

   Once she has a little time to think, she realizes this might help explain why Marco keeps coming back with new feature ideas---doing so is a means to soothe that fear.

   Understanding that is going to be incredibly valuable, if Quin is going to ask him to change that behavior pattern. She'll have to come up with more productive options to address that underlying fear.

Now, let's talk about the second Tactical Empathy skill you'll use, when mining for emotions.

** Tactical Empathy Skill #4: Offer Labeled Feelings

Repeat Trailing Three Words will help get your stakeholder talking, and start to fill in your picture of their key emotions.

But if you're going to advocate for change, you often need to go further. To develop a nuanced understanding of their four key emotions...

...you'll need to talk to them *about* their emotions.

Now, I'm imagining many readers, as they read this, visualizing their critical, frustrating, emotionally shut down stakeholder, and saying to themselves "Dan, you are completely stoned. there is no way on earth this is going to work."

I get it. It may seem literally impossible to imagine that stakeholder opening up to you in any useful way. But I encourage you to really study and then practice the tactical empathy skills we're talking about. You may well find yourself astonished by how far a mix of active listening, echoing, validating and open-ended questions can get you.

Returning to the challenge in front of us, how can you get into a useful conversation with your stakeholder about their emotions?

Just as people are often resistant to showing their emotions, they can *also* easily become defensive if they perceive you as, in any way, *telling them* what their emotions are.

E.g. imagine Quin were to say to Marco: "Are you afraid that we're not solving an important problem?"

Although that may be exactly right, there's a very good chance that he will feel accused, and become defensive.

This problem is particularly tricky for the the negative emotions---the frustrations and fears. Your stakeholder can easily feel like you're accusing them of being weak, or of being too emotional. But you urgently need to know both their frustrations and their fears, because those will otherwise absolutely shut down any attempt you to make change.

The trick to get these negative feelings out in the open is to carefully go through two steps, which Chris Voss calls "Labeling" emotions:

 1. Describe the *situation* your stakeholder is in, with empathy

 2. Offer a potential name/label for their emotion, as a *natural response* to that situation

For example, Quin might describe Marco's situation, as follows:

"We're in a tricky spot. Potential customers keep telling us that they're *interested*, but because we don't have a thing we can *sell* them yet, we can't find out if they're genuinely willing to buy."

She immediately follows that up with an offer of a labeled emotion, as a natural response to the situation, lightly inflected as a question:

"It seems like you might be afraid that we're not solving a genuinely *important* problem...?"

Note that Quin has specified, in some detail, what, in their current situation makes that fear natural ("we can't find out if they're genuinely willing to buy").

Also note that, when she then goes to describe his emotional reaction, she prefaces it with "It seems like you might...". She's not *telling* him his feelings, she's *offering* a potential understanding of his feelings.

When you go to make such an offer, it's critical that you preface it with an opening that creates a bit of separation between you and the statement of emotions you're about to make:

 - "It seems like..."

 - "It would make sense if..."

 - "I could imagine you might..."

Those create space for the person to hear it as you *trying to understand them*, not announcing their feelings to them.

To review, here are the two different ways Quin could speak to the fear she thinks Marco may have:

Direct Question: "Are you afraid that we're not solving an important problem?"

Labeled Offer: "We're in a tricky spot. Potential customers keep telling us that they're *interested*, but because we don't have a thing we can *sell* them yet, we can't find out if they're genuinely willing to buy. It seems like you might be afraid that we're not solving a genuinely *important* problem...?"

On the page the two may not seem that different, but if you can do the work to lay out the situation first, and then offer that second part in a calm, curious, dispassionate tone, it has a *remarkably* powerful effect. Your stakeholder, instead of feeling *accused*, will feel *relieved*.

As Voss explains, research shows that, by naming fears out loud in this way, you can actually help people *feel* calmer. It both shows the person that it's okay to name the fear, and it also engages the rational, problem-solving parts of their brain.

This approach is *extremely* powerful. But it takes real practice, for two reasons.

First, many of us have learned to *not* talk to other people about their feelings, especially people who seem upset or angry in any way (and especially especially if those people have power or authority).

Overcoming that takes real work, and you're going to stumble here and there as you do so.

I find the key is to focus first on developing a specific, empathetic understanding of the *situation* which leads to the feelings. In particular, try to get to the point that, when you describe the situation, the resulting feeling seems *inevitable*.

We'll return to this in the exercises.

** Our Story: Putting It All Together
# Quin guesses a few feelings, uses trailing three words, echoes back and summarizes, offers labeled feelings, at the end, Marco feels excited, open, energized.
** Exercises
*** Repeat Trailing Three Words

Because it's so simple, there are two good ways to practice the Repeat Trailing Three Words tactic.

1) Experiment In Random Parts of Your Life

Whenever you can, in whatever conversations you find yourself in, try repeating the last few words someone says to you, inflected as a question. Try it in both professional and personal contexts, try it with your boss, try it with your peers, with your spouse, kids, neighbors, whoever.

Do it over and over, and you'll find your own authentic way in, and it'll start to feel and more more natural.

If you start by using it just once in a given conversation, then, as that feels comfortable, see how long you can keep someone talking and opening up by just repeating those last three words of each thing they say to you.[fn:: "Dan, this whole active listening thing has helped my relationship with [insert spouse's name]", is something I've heard let's just say, a bunch of times.])

As above, take a bit of time to explicitly reflect on how it feels to do it, and use that reflection to tweak your personal approach.

For an initial, focused period of practice to rewire yourself, aim to do this 2-3 times/day for a week, and see where that lands you.

2) Explicitly Test With a Trusted Friend

Tell a friend you want to work on active listening, and then ask them a series of questions to dig into some issue -- maybe specifically something close to the kind of conversations you might have with a stakeholder.

E.g. you could say "I want to practice some active listening sikills I'm working on. Would it be okay if I ask you some questions about your work?"

And then see if you can dig for information about what they're most worried about, and what they most hope to achieve, using the repeat trailing three words tactic as you go.

At the end, pause and ask for feedback from them on how it felt for them.

During a period of focused practice, do this 3-4 separate times, and again, make sure you make time to reflect.
*** Labeled Feelings

Take your most frustrating stakeholder. Come up with a description of their situation that makes their frustrating behavior an inevitable response.

This doesn't mean *justifying* it, to be clear. It means understanding the story they're telling themselves, the way the world presents to them.

E.g. say your stakeholder is demanding progress across far more initiatives than your team can possibly achieve. Is their boss making unreasonable demands of them? Have they experienced so many software projects as failing, they're trying to cover their bets?
* Structure Ideas
** What are my learning outcomes?
Have I sold the idea enough in the previous chapter, of the value?
*** Humans Have Feelings
*** The Key Questions To Answer
**** Frustrations
**** Fears
**** Delights
**** Dreams
*** Tactical Empathy Skill #3: Repeat Trailing 3 Words
*** Tactical Empathy Skill #4: Offering "Labeled" Feelings
*** Our Story: Quin Mines for Feelings
*** Exercises

* Title Ideas

** Mine for Context, Fears & Dreams
** Mine for Strategy, Fears & Dreams
** Mine for Frustrations, Fears, Delights & Dreams
** Mine for Intent & Feelings
* Scraps
** Afford to Ignore

One useful frame is: someone is one of your stakeholders if you *can't afford to ignore them*. That may sound a bit brutally transactional, but if there's too large a set of people who you can't ignore, then there's almost no chance your team can move quickly and create meaningful value.  Asking who you can ignore will sometimes shine a light on the implicit power structures of your company--and can reveal fundamental conflicts that are making it impossible for you to win. E.g. maybe your CEO talks night and day about how critical it is for your team to stay on track for the big new product launch they've promised to the board. However, your team is *also* expected to handle a stream of feature requests from existing customers, which that CEO doesn't pay any attention to. If, one day, the Head of Customer Success comes banging on your door, demanding you immediately add a new feature for enterprise customers, can you *afford* to ignore them? Or if you do, will you receive an unpleasant lecture from the CEO and then acquire a reputation as "not being a team player"?

If not, the CEO's statement of your priorities isn't a full truth of your situation.

The Head of Customer Success  has shown a willingness in the past to blame engineering and product if they fail to hit their retention numbers.

Separately, the Head of Customer Success

The only way you and your team will create significant value is if you can relentlessly focus on the most important, most valuable work at every moment. People you can't ignore are, in the actual,
