:PROPERTIES:
:ID:       47DD5FFD-3D09-4A7B-890E-2C5933D583BB
:END:
#+title: Mastering The Art of Divining Emotions
#+filetags: :Chapter:
* Mastering The Art of Divining Emotions
** Be Ready To Spend Time Learning To Label

Invest

Being able to empathetically draw out emotions is *extremely* powerful, but it takes real practice to master, for (at least!) three reasons.

First, many of us have learned to *not* talk to other people about their feelings, especially people who seem upset or angry (and especially especially people who have any form of power over us). With experience, you'll find that successfully drawing out and validating emotions makes pretty much all people feel good. Once you experience this tactic as /defusing/ tension and anger, it won't feel so risky. But you have to build up that personal, direct experience, to retrain your brain. In the exercises below, we'll build up our skills gradually, for exactly this reason.

Second, several steps require precise language and timing, which can be hard to access in the midst of a high-stakes conversation with your stakeholder. You'll want to rehearse enough so that you can successfully employ the skills even when your internal emotional dial is pegged to eleven.

Finally, it takes work to learn how to develop a detailed, empathetic description of a situation. To be able to frame the situation such that some feeling seems inevitable. To enrich your description with vivid details. This is very much a *learnable* skill, but it is not something most people have access to without some practice.

# We're going to break the skill down into a series of discrete steps.

** Practice Repeat Trailing Words

This one is simple enough that I recommend practicing it throughout your day.

Whenever you can, in whatever conversations you find yourself in, try repeating the last few words someone says to you, inflected as a question. Try it in both professional and personal contexts, try it with your manager, try it with your peers, with your spouse, kids, neighbors.

As you do so, be sure to:

 - Allow yourself to be in a place of genuine curiosity

 - Say only the last three or four words back

 - Wait silently for a response, even if it feels uncomfortable

Practice over and over. Take some time to reflect on how it feels, and use that reflection to tweak your personal approach.

As you build comfort, you'll find that you can go through multiple rounds of this, in a single conversation, and often get surprisingly deep. If you do find you've learned something interesting or moving, practice Echoing Back & Summarizing and Offering Labeled Feelings.

For an initial, focused period of practice to rewire yourself, aim to do this at least two to three times a day, every day for a week.

** Rehearse Your Preface

First, on your own, explore a couple of different prefaces:

 - "It seems like you might feel..."

 - "It would make sense if you were to feel..."

 - "I could imagine you might feel..."

 - "It could be easy to feel..."

 - "If I were in your shoes, I might feel..."

Pick one that feels reasonably comfortable. Then, rehearse it over and over until you can get through it, precisely word for word, without effort. Make 100% certain you're not dropping any key prefatory words: you don't want your brain to convert "It seems like you might feel..." to the potentially damaging "I think you feel..."

Inserting this preface is likely to feel a bit unnatural at first. That's okay. Getting the knack of smoothly inserting a preface is like learning a physical skill---it takes practice to make it smooth.

Once you have that mini-script wired into your brain, you can move onto the next step.

** Label With A Friend

Because talking about feelings can feel so loaded, I recommend initially practicing this with a trusted friend. You can ask them:

"I'm practicing a form of active listening. Can I try something with you?"

Tell them you're going to ask them to talk about their work. Then, ask them one of the following questions, which should help get into issues that have some emotions attached:

 - "Is there anything your boss does that makes your job harder?"

 - "If you could wave a magic wand, and change one thing about your job, what would it be?"

 - "Has anyone made a somewhat unreasonable request of you, lately?"

Be ready to use Repeat Trailing Words to draw them out.

Once they mention something that seems to have any emotions attached, pause them, if need be, ("Hang on, I want to make sure I understand").

Then:

 - Briefly describe their situation, using no more than a few sentences

   "Your boss keeps on asking for status meetings with you and your team. You're spending all your time preparing for those meetings, and no one can get anything done."

 - Bridge to your preface

   "It seems like you might be feeling..."

 - Then name a feeling *directly*, as an offer

   "...pretty frustrated with your boss...?"

Don't let yourself dance around or avoid saying the feeling. Put yourself in a place of curiosity, open with your rehearsed preface and then be *painfully* simple and direct. And then *stop talking*.

# Try to *not* say something like:

# "I'm just wondering, maybe, you said that he kept asking for meetings, like a lot of meetings? That's not great, of course. I sometimes have had that happen. At my last job, ugh. This is for the important project, right? Maybe that, is sometimes, I don't know, maybe a bit, like, frustrating. Or maybe not, maybe it's not that bad? I know you mostly like your boss, right?"

# That kind of scattered talking is the fear taking over your brain. It's telling you that the person won't want to hear their feelings out loud. The fear will desperately try to convince you to stall ("I sometimes have had that happen", "the important project, right?"). The moment say something at all direct, the fear will urge you to immediately walk it back ("Or maybe not...", "you mostly like your boss, right?").

# This is why you're practicing with a friend.

# You have to get yourself into that place of discomfort in speaking directly to emotions, and find a way through it.

Whatever they respond with, nod and agree. Continue on, and then, once you hit another emotion, pause them and offer a label once again.

After you've done a few rounds of this, stop the exercise and ask your friend how it felt. Dig in specifically to whether or not they felt like you understood their situation. Ask if anything you said sounded odd or pushy. Or, conversely, if there was anything that was specifically good to hear.

Take the time to notice how *you're* feeling, in the midst of this.

Now that you've gotten a bit of practice with the structure, you're just about ready to use it with your stakeholder

** Develop An Empathetic Description

As your first step, before you talk with your stakeholder, take some time to develop an empathetic description of their situation. Specifically, a description that makes their frustrating behavior an *inevitable response*.

This doesn't mean justifying their behavior.

It means trying to understand the way the world presents to them. Trying to understand the story they're telling themselves.

For example, say your stakeholder has a frustrating habit of demanding progress across an ambitiously complex plan, and seems angrily unwilling to consider narrowing scope when any challenges arise.

What might be a way to describe their situation that makes this behavior an inevitable response?

 - Is their boss making unreasonable demands of them, and they don't feel like there's any way they can push back?

 - Did they misunderstand an earlier scoping and estimating exercise, so they're only now realizing that they have overpromised things to other people?

 - Have they experienced so many software projects as failing, they've "learned" that they need to push the engineers?

Again, developing this empathetic statement doesn't mean their behavior is *right*. It means you can see genuinely how it might *seem* right to them, given their context.

Talk this out with people you work with, see if you can learn something new about what might be driving the frustrating feelings and behavior.

You don't have to get this perfectly right, but the work to put yourself in their shoes will help you very much in the moment of your conversation with them.

** Put It All Together With Your Stakeholder

# XXX Add this, actually talking w/ your stakeholder
** Four Flavors Of Emotions To Divine

As you develop your skills for mapping feelings, here are four useful questions to ask:

# Fortunately, you don't have to worry about every facet of your stakeholder's inner life. You're going to develop a picture of just four key emotions, by answering four key questions:

 - What happens, day-to-day, that *frustrates* your stakeholder?

 - What are they *afraid* might happen at some point in the future?

 - What happens, day-to-day, that makes your stakeholder *feel good*?

 - What do they most fondly *hope* happens at some point in the future?

# These form an extremely powerful core for persuasion.

# I'll shorthand those as, respectively: Frustrations, Fears, Delights and Dreams. Two focus on day-to-day experiences (Frustrations and Delights), two on longer-term motivations (Fears and Dreams).

Two focus on day-to-day experiences, two on longer-term motivations.

You won't need to answer every one of these questions in every situation. But, in total, they represent a very useful set of ways in

# , that will allow you to develop a really strong pitch for change.

# We'll talk about how to craft your request in "Make a Compelling Offer."

# If you can come up with answers to these four questions, you can build an *extremely* compelling request to try something new. A request that the stakeholder will both *hear* and *feel* as compelling.

# But first we need to figure out how to answer these questions in the first place. Again, if you're blessed with that rare beast, the emotionally open Important Person, go ahead and ask them. "Bob, what would you say frustrates you day-to-day? What do you hope happens if everything goes really well?"

# But what should you do if your stakeholder is not so emotionally open?

# Step one: make a guess.

# If your stakeholder is in a position of authority within your company, you likely have a hunch about how to answer some of these questions. The emotions of people in power are important enough that, usually, people on the ground have at least *some* model of what is going on inside their various bosses' heads.

# But that guess should just be the start. Because Important People spend so much energy trying to hide their emotions (and because our own feelings of powerless frustration can block our own ability to read emotions), we'll want to test out and refine our guess.
