:PROPERTIES:
:ID:       E0ADBF07-90B8-4C37-81C0-96A428020F5E
:END:
#+title: Substack
As part of my [[id:17305FA7-A43F-40C9-9309-0EF3577C70D0][Author Platform]], I've gone and set up a Substack.

* Tooling / Links

Substack Dashboard: https://buildingandlearning.substack.com/publish/home

* Substack Buttong HTML
<iframe src="https://buildingandlearning.substack.com/embed" width="480" height="320" style="border:1px solid #EEE; background:white;" frameborder="0" scrolling="no"></iframe>

* Ideas for posting cadence
3x / week.

Pick out 2 things I've written, and 1 reference to something I like.

Schedule those for, like, Mon/Wed/Fri.

Do it... when? Either EOW, when I'm done writing?

Do it in the afternoon, maybe on Mondays or some such.

For now, reference or all of them on LinkedIn?

** Email to EWJ re posting cadence
Subject: Rubber Ducking Substack Posting Cadence
E-

I want to write out some thoughts about posting cadence plus patterns for Substack, so I can see if I can clarify my own thinking (and of course I super value your take on the below).

So, to start, what is the value of, the goals for posting to Substack:

 - Develop a pool of beta readers

 - Build a seed audience for when the book launches

 - Build a long-term platform

 - Create motivation and connection (by e.g. hearing that what I'm writing is useful)

I think that, if I can make the substack itself recommendable, it helps on all those fronts.

And, even in starting to work on it, I'm discovering something which is kind of blindingly obvious in retrospect, which is:

Because I'm already spending hours and hours every day *writing a book*...

...I have *tons* of content available to post.

And thematically related content, etc.

And I'm not gonna, like, run out, any time soon.

So then the question kind of becomes: how often should I post? Should I worry about annoying people?

I have 3 posts scheduled for this week -- each about 500 words, each, I think, pretty fun and tight (and each having, like, one insight that I think people might say "Oooh, I want to tell someone this").

I took me very little time to get those set up (most of the time was just figuring out how to deal with formatting and scheduling on substack). Cutting and pasting out of all this writing I'm doing is not hard.

So, one option is to post every (week)day. And celebrate that fact.

I could do something like:

 - Mon/Wed/Fri are ~500 word excerpts from the book

 - Tue is Tuesday Thank You Notes, where I spend a couple hundred words celebrating some book or blog post or paper I've found influential in my thinking. I've got a list, this would be fun and easy to write, and create some variety.

 - Fri is Questions for the Community -- something where I'm asking people to send in stories or questions or the like, on some theme (and later sharing back what I hear).

I mean, having written that out, why... wouldn't I do it?

I think there's decent evidence my writing isn't annoying, and it's email, they can just ignore it if they want.

It sounds like a thing that people might well start recommending, esp if it's at all playful and/or fun. Plus if I can get a Friday Mailbag going, I think I would find that super motivating (plus, frankly, great early customer development for later Highly Paid Consulting gigs, if I want to go down that road)

I can likely get the work down to ~1-1.5 hours a week, to prep 5 days worth of posts, out of the stream of writing I'm alrady doing.

Could just build a hbabit around that for, like, Wednesday afternoons, to prep next week's posts.

And any fears that "people won't need to buy the book if it's all out there on a blog" are just batshit crazy and dumb. If the blog gets enough traction that I have *any* worries on that front, I'm selling a metric ton of books, *because* of the traction, not despite it. Just need to like beat myself up over that fear or something.

Thoughts?
D
* About

*Building & Learning*

aka

Some Adventures At the Intersection of Engineering, Product & Human Nature Whilst Engaged in the Pursuit of Value

aka

Some Things I've Learned Both From & With All The Excellent People With Whom I Have Worked Over These Years

aka

Build -> Learn -> Build -> Learn

aka

The Name of the Song is Haddock's Eyes, and The Tune's My Own Invention

(No, *you're* obsessed with Lewis Carrol, shut up)

Hi, my name is Dan.

For the last 30 years, I've worked in various combinations of engineering and product -- I love both discplines, and value both super highly.

I've worked as a principal engineer building and operating complex systems; I've led product at startups desperately trying to find traction; I've managed engineering teams ranging in size from 2 to 500.

Right now, I'm working on a book:

"Tech Investments, Not Tech Debt: How To Make Time For Engineering Work That Matters".

In this herein Substack, I'll be sharing ideas from it and thoughts the writing of it triggers and the like.

(and just possibly some random Lewis Carrol-inspired absurdity once in a while, I make no promises otherwise)

Speaking of said book, if you're potentially interested in being a beta reader at some stage of development, holler at me.
