:PROPERTIES:
:ID:       9410A7DC-111C-4791-B8A1-C20867904251
:END:
#+title: Unstuck Beta
For a round of [[id:93FF0A9B-F54E-49D5-8154-640BBAE08D4D][beta reading]] of Getting Unstuck

Just gonna start to type, see what I come up with.

* Beta Invites

** My Own Take 1

Subject: Working on book about resolving problems w/ bosses/peers/etc

Heya, how’s it going?

As you may (or may not?) know, of late, I’ve been focusing on helping people navigate tricky situations with bosses & peers. In addition to direct coaching, I've been doing a lot of writing, and... I’ve actually got a solid chunk of a book written.

Not sure if it’s relevant to you right now. But if so, I’d love your thoughts and feedback:

https://helpthisbook.com/dan-milstein/getting-unstuck

I’m especially curious to hear what’s helpful and, on the other hand, which parts are boring (I'm sure there are some!).

The version I'm sharing is about 29k words. That's around 2 hours of reading time, but you'll probably know right away if it's worth your time, and should feel free to bail if not.

No stress whatsoever if it's not for you right now. Hope life is going well...

Dan


** From Useful Books, 1

Subject: Still working on [PROBLEM]?

Hi, you mentioned a while back that you'd be interested to see my notes on [TOPIC] to help you with your work on [THING].

The latest draft has taken longer than expected, but it's here: [LINK]

It's a quick read at 10k words and covers the major pieces of how I approach the most crucial concepts.

If you've got any feedback — and especially confusion or questions! — you can just comment directly in the document while you're reading. No worries if this is too big of a thing right now — thanks for your support either way.

** From Useful Books, 2

Subject: Putting together a book about [PROBLEM]

Hey, how’s it been? As you know, I’ve been focused on [PROBLEM] for a while now, and I’ve actually got the beginnings of a book written.

Not sure if it’s relevant to you right now. But if so, I’d love your thoughts and feedback: [LINK].

I’m especially curious to hear what’s most helpful and which parts are boring. It’s about 6k words, so maybe 20 minutes of reading time, but you’ll probably know right away whether it’s worth your attention.

No stress whatsoever if it's not for you right now. Hope all's good!

** Overall Useful Books Rec
You'll notice that my scripts are non-pushy to a degree that might be seen as suboptimal. I do that on purpose. After all, the last thing I want is to "convince" someone into "doing me a favor" of providing detailed feedback on a book they wouldn't have wanted to read in the first place. Because then I've got to navigate through a bunch of feedback that looks all deep and insightful, but which is actually from a non-reader! So one of the ways I filter for qualified readers is to frame the request in such an easy-going, zero-pressure way that I'll only end up hearing back from the people who really, truly do want to read it.

* Specific Beta Readers
 - [X] Jarrett Goldfedder <Jgoldfed@msn.com>
 - [X] Keisha Johnson
 - [X] Stephen Wright
 - [X] Matt Papi
 - [X] Mike Isman
 - [X] Irene Daly
 - [X] Kristin Baker
 - [X] Owen Raccuglia
 - [X] Edmund
 - [X] Craig
 - [X] Andrea Guatemala
 - [X] Bennett Chamberland
 - [X] Wassaf Farooqi
 - [ ] Al Goodniss
 - [ ]

* Goals

What is my goal with a round of beta reading?

 - See if I'm speaking to a problem people care about

 - See when they stop reading

 - See if they apply any of it

* High-Level Chunks

 - Finish a draft

 - Upload to HelpThisBook

 - Write an invitation

 - Decide who to send that to

 - Go?

* What goes into the draft?

Current ToC

  Chapter 1: Introduction: The Joys and Pains of Working With Humans

  Part I: How to Solve Problems So You Can Solve Problems
    Chapter 2: The Getting Unstuck Game Plan
    Chapter 3: Align On a Strategic Outcome
    Chapter 4: Mine for Fears & Dreams
    Chapter 5: Make a Compelling Offer
    Chapter 6: /Quin & Marco Go For A Walk/

I think, get rid of the Part I/Part II, but do the three part breakdown of compelling offer, so it becomes something like:

  1. The Joys and Pains of Working With Humans
  2. The Getting Unstuck Game Plan
  3. Align On a Strategic Outcome
  4. Mine for Fears & Dreams
  5. The Elements of a Compelling Offer
  6. Offer A Small, Easy-To-Agree-To Change
  7. Motivate Action (Now and Not Later)
  8. Speak To Your Stakeholder's Human Experience
  9. /Quin & Marco Go For A Walk/

In the vicinity of 30,000 words, give or take 5,000 words, at a guess. 150 minutes, call it 3 hours of reading.

* Open Questions/Work I've Considered Doing
** Review/merge new Intro ideas in [[file:20250913100150-make_a_compelling_offer.org::*Introduction][Compelling Offer]]
All the stuff I have written in for Substack. Also maybe I have something in the abortive "Four Key Feelings" in sub
** Review Strategic Outcome chapter
Comb through all the substack writing, strip it down and simplify.

** Review/merge from [[file:~/Dropbox/Projects/TechInvestBook/substack/013-four-emotions.org::*Fears & Dreams & Humans & Building Softare: Part I][4 Emotions]] substack
And, not, I develop a whole narrative in there.

** Experiment: Quin & Marco as separate chapters
Move to interstitial chapters? Keep woven through? Get back to them... when?

** Experiment: lots of little stories vs one big story
** Split out Compelling Offer, review

* Target Date
December 5th is 5 weeks out.

What would a week by week breakdown look like, to get to that date? Let's look by end of week dates:

** 11/07: Review/edit Intro + Fundamental Game Plan
** 11/14: Review Strategic Outcome chapter
*** Experiment: Quin & Marco as separate chapters
** 11/21: Review/merge from 4 Emotions substack
*** Experiment: lots of little stories vs one big story
** 11/28: Split out Compelling Offer, review
** 12/05: Finalize, upload to HTB
* Hit List of Todos
In case I want a list of small things, that shouldn't all take over my clock time.
