:PROPERTIES:
:ID:       EFCE67BB-7CC9-4142-AD65-132ECB4F9172
:END:
#+title: Tech Investment Titles

Just to get them out of my head. Can also put some "scopes" in here.

* Tech Investments: How Engineering Leaders Can Advocate For the Technical Work They Believe Is Important

* Tech Investments: How Engineering Leaders Can Advocate For Important Work

* Tech Investments: How Engineering Leaders Can Identify & Advocate For Important Work

* Tech Investments: How Engineering Leaders Can Identify & Advocate For Valuable Work

* Tech Investments: How Engineering Leaders Can Advocate For the Work Their Teams Want To Do

* Tech Investments: Helping Engineering Leaders Negotiate With The Rest of the Business

* Tech Investments: Helping Engineering Leaders Negotiate With Their Business Teams

* Tech Investments: How Engineering Leaders Can Better Negotiate With Their Business Peers

* Tech Investments: How Engineering Leaders Can Better Negotiate What Their Teams Work On

* Tech Investments: How Engineering Leaders Can Negotiate What Their Teams Work On

* Tech Investments: How Engineering Leaders Can Influence What Their Teams Work On

* Tech Investments: How Engineering Leaders Can Negotiate, So Their Teams Work On What Really Matters

* Tech Investments: How Engineering Leaders Can Effectively Negotiate For Work That Matters

* Tech Investments: How Engineering Leaders Can Negotiate For Work That Matters

* Tech Investments: How Engineering Leaders Can Win Negotiations About What Their Teams Work On

* Tech Investments: How Engineering Leaders Can Stop Losing All Their Fights With Product

* Tech Investments: How Engineering Leaders Can Do Something Other Than Just Crank Out Features

* Tech Investments: How Engineering Leaders Can Negotiate For Work That Matters... Instead of Just Cranking Out Features

* Tech Investments: How Engineering Leaders Can Make Their Systems Better, Even In The Face of Endless Demands for More Features

* Tech Investments: Moving Beyond Tech Debt

* Tech Investments: How Engineering Leaders Can Move Beyond Tech Debt When Negotiating What To Work On

* Tech Investments: How Engineering Leaders Can Move Beyond Tech Debt When Negotiating Priorities


* Tech Investments Not Tech Debt: How Engineering Leaders Can Effectively Negotiate For Work That Matters

* Tech Investments Not Tech Debt: How Engineering Leaders Can Better Negotiate For Work That Matters

* Tech Investments Not Tech Debt: How Engineering Leaders Can Negotiate For Work That Matters

* Tech Investments Not Tech Debt: How Engineering Leaders Can Identify, Advocate For, and Drive Technical Work That Matters

* Tech Investments Not Tech Debt: Identify, Advocate For, and Deliver Technical Work That Matters

* Tech Investments Not Tech Debt: How To Identify, Advocate For, and Deliver Technical Work That Matters

Execute on? Deliver? Build? Invest In? Prioritize? Lead? Drive?

Tech Investments, Not Tech Debt

Tech Investments
(Not Tech Debt)

Cut "Successfully"?
