:PROPERTIES:
:ID:       A1EF14A2-5F19-488D-926C-A8208142E794
:END:
#+title: Identify a Strategic Intent
#+filetags: :Chapter:
* Identify A Strategic Outcome
** A Story: Maria Struggles To Make Her Case

# Maria Is Stuck With Geoff
# Struggles to make her case

Remember Maria, the PM from our opening chapter, who was struggling with her VP of Sales, Geoff? Because the Geoffster kept on undercutting her prioritization to try to force work for his pet customers? And thus her product strategy was dying the death of a thousand cuts?

How might Maria make her case? Well, she could try saying something perfectly rational, like:
# If Maria *hasn't* identified the strategic outcome that Geoff cares most intensely about, she might try saying something perfectly rational, like:

/"We're never going to be able to deliver on our product strategy if we can't focus."/

This statement has the benefit of being *completely true*. But, is it going to be *effective*? Eh, not so much.

Geoff, like many executives, has a deep gift for /creatively mis-hearing/ requests.[fn:: I'm now 100% imagining this skill being taught to promising young leaders, before they're allowed into the hallowed halls of the Senior Leadership Team. Along with, /How To Demand Progress Against Obviously Conflicting Goals/, /How To Blame A Team For Your Own Failings: A Survey Course/, and /How To Join Meetings Late And Leave Them Early And Other Demonstrations Of How Just Important You Are/. Are these a series of lectures? Small group discussion sections? What are the titles of the HBS case studies? I have so many questions.]

He thus manages to hear this as Maria asking for something *for the product team*, which something is clearly not important for the business as a whole. Note that Geoff uses this skill of "creative mis-hearing" totally unconsciously! When we decide to act in our own self-interest, our brains are incredibly good at pretending that we're *not* doing so. We call this "rationalizing", and we're all masters of it.[fn:: Why is this such a profound human skill, you might ask? Evolution has relentlessly selected for our being able to truly believe in our own unselfishness, in order to effectively persuade others that we are unselfish. So being able to act selfishly, while honestly believing we're not doing so, is a fundamental trait of humans everywhere.]

How will Geoff's brain explain this situation to him, so that he can brush off Maria's request, and still maintain his belief that he, at least, is acting in the company's best interests? OMG, it's so easy:

Geoff has plan and quota to hit. He's not asking for much, just attention for a few key problems here and there. Maria clearly doesn't understand how hard it is to keep customers happy. Are they supposed to just let those customers churn? He's being completely and totally /reasonable/.

# And, having dispensed with this challenge, Geoff will continue on his merry,  distracting way.
Let's back up just a bit. *Why* is Geoff's brain spinning up all these stories, so quickly? What is it trying to protect him from? Why does he perceive Maria's request as *not* in his self-interest.

Simple:

*Geoff is worried that Maria is going to prevent him from succeeding at his job.*

# Where success is, ultimately, being able to keep working towards some long-term outcome he cares intensely about.

As long as he perceives Maria's requests as a threat to his own success, Geoff's mind will eagerly come up with all sorts of excellent reasons why he should push back.

But what if instead, Maria *knew* how Geoff thought about success?

What if she could speak to it in the very terms Geoff uses?

What if she could offer him a new way to succeed at his job, by working *with* her?

** Maria Makes A Compelling Offer

Geoff and Maria's company is facing a critical challenge.

For years, they've been successfully selling to small and medium-sized businesses (aka, the SMB segment). That segment is, unfortunately, pretty much completely tapped out. The marketing team is struggling to turn up any new SMB leads. SMB renewals are steady, but the tight budgets at small companies, means there's no real room to upsell. The company will only be able to grow revenue if they can somehow start selling to significantly larger businesses. Aka, the fabled enterprise segment.

So that's what they've decided to do.

At the last board meeting, the CEO stood up and confidently promised that, within eighteen months, a full 30% of annual recurring revenue would come from enterprise customers.

Geoff, being *the VP of Sales*, feels hugely under the gun for this outcome. He's been building up an enterprise sales team, he's been endlessly reviewing recordings of sales calls, he's personally conducted a half dozen interviews with enterprise buyers. None of it seems to be working yet.

# Some of the customers Geoff is trying to cadge favors for are their largest existing customers, the small number who are in that enterprise segment.

If Maria knew all this, she could approach Geoff in an entirely different manner, to make the *same underlying request*:

/"I know how important it is for us to break into the enterprise. And I know hard the sales team has been working on that."/

/"But I'm worried that the product team hasn't been supplying you with the kind of compelling features that will open the door to enterprise buyers. And since those deals take so crazy long to close, I'm really worried that, every month we don't have something new, your team is in a worse and worse position."/

/"Could you help me find a way to commit more time to developing those key enterprise features? Even if it means allowing some current customers to grow frustrated."/

/"One option: if you can identify current customers who have similar problems to your enterprise prospects, we can focus our limited support time on them, to maximize learning while also keeping those customers happy."/[fn:: Maria used several tactics that we'll explore in How To Make A Compelling Offer.]

Geoff will hear this request very, very differently.

The struggle to build an enterprise sales pipeline is keeping him up at night. The lack of  enterprise-specific features is a huge part of that. Thus, he hears this as Maria *understanding his pain*. He'll be enormously more ready to listen.

She's also proposed a specific adjustment that could work for both of them---limiting the support time, but focusing it on a small set of customers that *Geoff* identifies. That puts him in a position of some control, which feels much better than simply being told to back off.

After she finishes, Geoff asks a few questions, which Maria listens to carefully. Then, he shrugs, and says "Okay, let's talk it out." They dive into the mechanics of her proposed adjustment, which Maria can tell Geoff is intrigued by.

As they talk, Maria more about the enterprise prospects, and Geofff's struggles to unblock the sales pipeline. She discovers that not being able to *demo* the under-development features is a consistent shutdown moment. She makes an offer to Geoff: if the product team could really focus, they could enable Geoff's sales leaders to start demoing a few key features *next month*[fn:: Those features will take many more months to be production-ready, but given how long the enterprise sales cycle runs, this is a very reasonable approach.]. Geoff looks up sharply. Demos could unblock half his currently stalled sales conversations. He might even be able to hit his upcoming milestones around pipeline. "Okay, which features, exactly?" he asks, intently.

At the next prioritization sync, as Maria watches, slightly dizzy with surprise, Geoff stands up and tells the rest of execs to clear the decks so Maria's team can focus.

Now, is Geoff going to immediately become a perfect partner to Maria, and never act politically, ever again? Likely, no. But they are now genuinely working together, towards a common goal. As they overcome challenges together, they will build more and more trust.

And it all started because Maria was able to speak so well to what Geoff most deeply wanted.

There's just one teensy problem with this plan: *most stakeholders don't talk in detail about strategic outcomes*.

# There's just one teensy problem with this plan: *most stakeholders don't talk /usefully/ about strategic outcomes*. (and then bridge to what makes a useful outcome)

** Why Stakeholders Hide Their Dreams, And What You Can Do About It

Stakeholders do not always clearly share the long-term business outcomes they care most intensely about. Sometimes, believe it or not, stakeholders will even try to *hide* these outcomes from you.

/"What...?"/ , you might well be thinking.[fn:: Unless you've worked in software for a long time? In which case you might be thinking, "/sigh/?"]

Look, your stakeholder has a strategic outcome they're working backwards from. They've spent time and effort *converting* that outcome into a series of tasks, projects and milestones---aka, "a plan". That is *their job*.

Many stakeholders, having made such a plan, will proceed to *only* ever talk about the tasks, projects and milestones. Such stakeholders don't talk in detail about the long-term business outcome the plan is supposed to accompish. Which means they don't provide *you* with enough of a nuanced understanding to productively challenge them to work in a new way.

This can leave you very stuck, indeed.

I'll name three distinct scenarios in which stakeholders hide their dreams this way. For each, I'll offer an approach for productively learning more.

# Many stakeholders then convince themselves that the only way to achieve the outcome is to execute on the plan, just as they've imagined it.

# Why might they do so? I'll name three distinct things you might run into, along with, for each an approach for productively digging in.

** "What You Don't Know Won't Distract You"

Some stakeholders deliberately limit what they share to force you to "focus on what matters". They don't want you to be distracted by what they consider to be irrelevant information.

It's important to realize that this approach is not dumb or crazy. This exact approach may have served your stakeholder extremely well when running *non-software* projects. Such projects often *can* be broken down into genuinely independent parts, that play out mostly as planned. It's often better in such cases for a leader to spend most of their time with each team on the details of those parts, not on the far-distant big picture.

The good news and bad news, of course, is that this approach super doesn't work for software projects.

The reason that's *good news* is that, if you can learn that longer-term goal, you can quickly start offering your stakeholder creative options to get their faster. Which will feel good to them. Which will then make them more open to sharing their long-term goals with you.

To bootstrap this process, my recommendation is to steadily ask questions and echo back, using the tactics of the previous chapter to gradually draw out your stakeholder's goals.

Most such stakeholders will, after a brief period of resistance, start to open up. Most will ultimately speak in real detail to the long-term outcomes. If you do an even half-decent job of summarizing back what you've heard, most will thank you for having dug in.

I'll share an example of this below.

Unfortunately, the straightforward approach doesn't always work.

Some stakeholders get weirdly and even intensely *upset* when you ask questions about strategic outcomes. They might bluntly refuse to share anything with you. They might go and tell your boss that you need to stop wasting so much time and just execute.

In such cases, although your stakeholder may /say/ that they're limiting what they share in order to create focus, they're *actually* doing so for a different underlying reason.

** "What You Don't Know You Can't Argue With Me About"

Some stakeholders, being human, feel /insecure in their position of authority/.

Such a stakeholder may *fear* getting into a conversation with you about how they mapped from the strategic outcome to the tasks they're asking you to do:

 - They might fear that you'll find a deep flaw in their thinking, which will prove to everyone that they're a fraud.

 - They might fear that you will be unwilling to do what they're asking, which will prove to everyone that they have no control over you.

 - They might fear that simply considering alternatives to their plan will make them seem weak and indecisive.

Such feelings of fear can cause your stakeholder to aggressively shut down the conversation about long-term goals, altogether.

This particular challenge occurs often enough, and is tricky enough to resolve, that I'm going to explore it in detail in the next chapter, [[id:5903AFE7-4B1E-422C-8537-2C56BBFBA643][Mine for Frustrations, Fears & Dreams]].

But I will say: if you can develop a genuinely an empathetic understanding of the fears which are driving someone's problematic behavior, you can often find productive ways to move forward, that not only don't trigger those fears, but actually help them feel secure enough to take major risks.

# First off, let me encourage you to have some empathy for a stakeholder who is feeling stuck in this feeling of panic and fear. Empathy, to be clear, does not excuse bad actions. People acting out of insecurity do some awful things, and they must be willing to face the consequences if they do so. But, in order for you to be able to productively approach a leader who is trapped in their own fears, I believe it's extremely useful to try to tap into your sense of common humanity.

# derive some of their sense of status or self-worth from being the only one who truly understands the strategic outcomes. Such

# Unfortunately, some stakeholders, being human, derive some of their sense of status or self-worth from being the only one who truly understands the strategic outcomes. Such stakeholders can thus be /resistant/ to openly sharing outcomes.

# In this case, you'll want to steal some tactics from Mine for Emotions, so you can help that stakeholder feel less threatened by the possibility of your working with them at that level. To ensure they feel like they're retaining control, even as they open up.

# XXX Allowing the team to make decisions is scary -- shove it in later

# Which, sigh. We'll share tactics for helping such stakeholders open up in later in this chapter.

# You're not challenging your stakeholder by doing so, you're allowing them to be an expert. You're celebrating their own nuanced understanding of the challenges facing your business. And then, once you have that more nuanced understanding, you can make a compelling proposal to focus on *new* things that matter.


** "What You Don't Know You Actually Do Know Because I Totally Told You Already"

My final reason that stakeholders won't tell you in detail about their strategic goals is simple:

They think they've already done so.

# At other times this is, essentially, an accident.

# they think about it night and day

The long-term strategic outcome feels so blindingly obvious to your stakeholder, they simply /forget/ that they need to share it clearly and repeatedly. In fact, they may feel like they already *are* sharing it, over and over. When they say, "You need to hit your Q3 delivery deadlines," what they hear *in their own head* is, "...or else we won't be able to see if the new features *improve retention rates*."

# Sure, they're not saying the part about retention rates out loud, but everyone totally knows that, right? I mean, it's obvious. They talked about it, like, a bunch, right?

But the team has no idea of that connection. It got mentioned briefly in the Q2 kick off, and never spoken about again. The team was busy freaking out during that kickoff because they realized they were going to have to work with the nightmarish EasyConfig system[fn:: If you ever prefix the name of something you build with 'Easy- or 'Simple-', know in your soul that engineers will some day bitterly curse you and everything you hold dear.]

Thus, in order to hit the Q3 deadlines, the team cuts corners, breaks a key part of the product, and causes a raft of customers to churn, dropping retention rates safely into the garbage.

That stakeholder is furious. /"But I *told* you over and over how critical retention is!"/ the stakeholder says (or, um, shouts). /"It's all I ever talked about!"/ This statement is both completely true and completely untrue at the exact same time! Again, humans are fun.

This is why I very, very strong recommend making a consistent practice of echoing back and summarizing your current understanding of why you're doing the work you're doing. By steadily checking in, every time you talk with your stakeholder, about how their immediate requests fit into their long-term goals, you'll discover immediately when you're acting out sync with what they truly want.

# Furthermore, even when leadership *has* done the hard work to develop a coherent, focused strategy, they don't always share much in the way of *context* with individual teams. They may simply pass down goals, but not share the thinking that led to selecting those goals, nor the business outcomes that achieving those goals will hopefully unlock. For software projects, which need a tremendous amount of flexibility in order to succeed, passing down goals without context very rarely works.


*** How To Determine A Strategic Intent

One core challenge with running this game plan is that there is an uncomfortably high likelihood that *no one has told you* a strategic intent.

In an ideal world, company leadership would share a concise, coherent, *opinionated* statement of strategic intent with every team.  A statement that allowed the team to quickly and confidently say "No" to distractions. In that ideal world, even as you're reading the above, you'd be nodding and saying "Yep, I've got that, let's go."

Unfortunately, here in the *actual* world, that's almost never the case.

First off, company leadership isn't always fully clear in their own thinking. Developing an effective strategic intent means being rigorously, painfully clear about what your company is and is *not* going to be able to do. Many leaders resist this painful clarity of thought. If your company works off some sprawling list of "Critical Projects" or "Key Initiatives", your leaders might fallen into this trap.

Furthermore, even when leadership *has* done the hard work to develop a coherent, focused strategy, they don't always share much in the way of *context* with individual teams. They may simply pass down goals, but not share the thinking that led to selecting those goals, nor the business outcomes that achieving those goals will hopefully unlock. For software projects, which need a tremendous amount of flexibility in order to succeed, passing down goals without context very rarely works.

Luckily, even if leadership hasn't perfectly defined or communicated a strategy, you can, almost always, *still* identify and align around *some* form of strategic intent with your stakeholder. And then gradually improve that over time.

To do so, we're going to learn about our first two Tactical Empathy skills -- "Guess & Check" and "Echo Back & Summarize".
** Use Educated Guesses To Probe For Strategy

You're trying to determine a strategic intent for your business, and, in particular, one that your stakeholder finds *compelling*.

You might well imagine that your first step should be to simply *ask* your stakeholder about what the business needs to achieve, and how the work of your team fits into that.

That can sometimes work. However, I usually recommend a different approach:

 1. *Guess* a strategic intent

 2. *Check* that intent with your stakeholder

 3. *Invite* them to tell you how you got it wrong

Let's open that up a bit.

First, you'll likely want to do some preparation to come up with the "guess": talk to people you work with, review whatever leadership has shared, gather information from wherever you can. Then, take some time to distill it all down to a coherent statement. Test that out with someone you trust, ask for their feedback, and then make it sharper and clearer.

Once you've got something which feels clear and potentially useful, you're ready to share it with your stakeholder. You can use something like the following conversational template.

/I wanted to ask something -- my understanding is that, in the next 18-24 months, the most important thing we need to achieve is <X>, and that my team should be supporting that by way of <Y>. Do I have that mostly right? Am I missing anything important?/

In many cases, this works far better than just point-blank asking your stakeholder for a coherent intent.

There are two reasons why guess-and-check is an effective alternative to ask-directly.

First, it doesn't put the stakeholder on the spot -- it can be quite hard to come up with a clear, concise statement of strategy on your feet. If, instead, you offer one and invite their critique, you're making a smaller ask of them.

Second, it's usually much easier for people to express their thoughts by telling you what's wrong with yours, than it is to lay their own out.

Sometimes, they're not even perfectly clear on what they think, but when you say something like /"My understanding is that our top priority is growth, which means acquiring new customers, is that right?"/, they'll realize that sounds wrong, and say:

/"Wait, that's not quite it. A good bit of revenue growth should come from upselling *existing* customers -- but we need more compelling features in our Pro tier to do that."/

You say thank you, and then update your coherent statement and test it again.

This is part of why developing an *opinionated* strategy is so valuable. By making one which it's "possible to disagree with", you're far more likely to draw a response from your stakeholder. If you offer something vague and positive, they'll nod without really thinking. If, on the other hand, you say something which "feels wrong" to them, they'll engage and work to clarify.

Note: the "Guess & Check" approach can be applied in a very wide variety of situations.

If you want to dig for information, or understand someone's concerns, or draw out their opinions, your best bet is often to offer a guess, and then invite them to tell you where you got it wrong.

We'll lay out some exercises to practice this, at the end of the chapter.

** A Story: Alistair Digs In With Max Hartswell
** Handling Leaders Who Avoid Making Decisions

I can't get out of this chapter without mentioning the unfortunate possibility that your stakeholder may *angrily resist* making a clear statement of a *single* strategic intent. Such a stakeholder might say something like:

/"Look, it's not that simple. You're always asking for the "one top priority", but *all* the goals are critically important. We *can't* just pick one. We have to find a way to get them *all* done."/

Sigh.

An unwillingess to make hard prioritization calls is a reliable way to doom a team to failure.

That said, you still have options in this situation. There's a real chance that, if you can earn some shared wins, that same stakeholder will start to experience prioritization decisions as an *empowering* thing for them, rather than a demand for them to disappoint one of *their* stakeholders or bosses.

Thus, in such a case, my recommendation is to just go with your best guess for now -- it's likely pretty good, and having *some* direction to move in is better than just churning around at random.

** How To Practice Identifying Strategic Outcomes
*** Developing Strategy Is Hard

Before we go any further, I want to say: developing a coherent, concise and compelling strategic intent is *hard*.

The reality facing any business is always extremely complex. Trying to distill that down to a single core challenge takes real work. There are dozens of factors you could consider, dozens of problems people are worrying about, different hopes and dreams different people across the company are treasuring in their hearts.

As you work to develop your a strategic intent for your business, you may find that it's surprisingly challenging. That's okay!

Building such a clear picture is a *learnable skill*, but it does takes real practice.

We'll illustrate some ways to think about it, in the below. But I think you'll be well-served by being ready to productively struggle.

If you'd like to learn more about developing strategy, I recommend:

 - The Art of Action, by Stephen Bungay

 - Good Strategy/Bad Strategy, by Richard Rumelt

For ideas on how to work with strategic intents, Escaping the Build Trap does an excellent job of describing how to use strategic intents to *lead* an organization.

*** Developing Strategic Intents
Find some trusted peers or friends, and talk out the strategy of your business. Build a picture of:

 - Some centrally important thing your business is trying to achieve, over the next few years

 - A core challenge the business must face, on the path to that achievement

 - How your team can play a role in facing that challenge

Try to develop a few different formulations of the above, do some work to hone and clarify.

Depending on the size of your company, these outcomes might be scoped to a sub-part of your company instead of the entire business.

Once you arrive at some statement of strategic intent, ask yourself the key questions:

 - Is it possible to *disagree* with the intent?

 - Does the intent allow you to say *"No"* to things?

If not, continue to refine your statement.

As an experiment, try making your statement of intent "frighteningly opinionated": so clear that your team would have to immediately stop doing some things that "every knows are critically important". See what you find when you do that.

For further practice, talk this out with friends who work at other companies. Ask what their business is trying to achieve, ask about fundamental challenges they must face, brainstorm different ways their teams might help face those challenges. Look for something usefully opinionated.

*** Practicing Guess & Check

First, rehearse saying your intent, embedded in a template like the following:

/I wanted to ask something -- my understanding is that, in the next 18-24 months, the most important thing we need to achieve is <X>, and that my team should be supporting that by way of <Y>. Do I have that mostly right? Am I missing anything important?/

Make sure you're able to ask the questions at the end *authentically*. You wan tto channel true curiosity. Feel free to adjust the wording to make it feel more natural for you.

Then, once you've got that comfortable, take your strategic intent around, offer it to various people, and invite them to tell you how you got it wrong.

*** References

 - Never Split the Difference

 - The Art of Action

 - Good Strategy/Bad Strategy

* Stashed Old Sections
** Our Story: Quin Tries Guess & Check

When we last checked on Quin, she was struggling with her CEO, Marco, over his habit of constantly changing priorities at their startup, All Together Now (who are developing remote team building games). Her friend sent her to talk with an experienced engineering leader who, by the friend's account, likes "helping people get their bosses to stop being crazy."

"You're saying I should just, like, /make up/ a strategy for ATN?" Quin says, uncertainly.

Jeremiah nods vigorously. "Yep. Exactly."

"Okay," she says slowly, "I guess I can... try?"

"You're going to do great," he insists. "Be sure to let me know how it goes." He waves a cheerful goodbye as the Zoom fades out.

That evening, while washing up the dishes after dinner, Quin lets her mind wander. How can she come up with a business strategy for ATN? She thinks about all the things she's heard from Marco over their six months of working together. Is there some guiding theme in all of that? What might be a key 18-24 month "outcome" for All Together Now?

Well, she tells herself, ATN is an early-stage startup. Obviously, they need customers. In fact, that's all she and Marco talk about. Her team is trying to launch some initial set of features those customers might find compelling.

Could that be it?

It feels a bit... short-term? They need customers *way* before 18 months.

She picks up another pot and swishes in some sudsy water. What good thing might happen *later*, if they *do* get those initial customers? They'd get... more customers? Hmm.

She remembers something else Jeremiah suggested -- to think about what Marco might want, even if he's not talking about it, day-to-day.  Jeremiah has asked, "What do you think might *feel* like a success for Marco? What's he working backwards from?"

She tries to remember moments when Marco seemed to feel good, or excited. Honestly, she thinks wryly, it's not actually *getting* customers, it's *telling a story* about those customers. She can see his happy, confident grin as, after a good customer call, he's laying out how awesome landing this deal is going to be, and how the company is going to grow.

A thought suddenly hits her, and she freezes, a spatula in her hand. Stories! Of course! How could she be so dense!? She's only been thinking about ATN as a *business*, and how the new product might fit into that business. But they're a *startup*. The key thing that needs to happen in 18 to 24 months is that they need to *raise more money*!

*That's* their key outcome. That's why Marco likes telling stories. He's imagining telling those stories to potential investors! And, she realizes excitedly, as it falls into place, he doesn't like to talk with the team about that day-to-day, because, he's told her, "they shouldn't worry about the money stuff".

At that moment, her roommate Naia wanders into the kitchen. Quin turns to her and announces excitedly, "Naia! We're a *startup*!".

"Bully for you," replies Naia, as she grabs some Cocoa Puffs and heads back to the living room.

---

The next day, partway through their weekly Zoom 1:1, Quin says:

"I've been wanting to ask you a few questions, is now a good time?"

Marco shrugs in agreement. Quin is mostly sure he's got his email open in another tab.

# Bad prose go

She takes a deep breath. "I'm excited about all the customer calls you've been getting. And I want to keep the team laser-focused on shipping the Virtual Dunk Tank, so you can start demoing it, just as soon as possible. But I wanted to talk a bit, just you and me, about what might happen next, if we *do* get those customers."

Marco quirks his head. He's still got an eye on some other window, Quin thinks, but he's paying just a bit more attention.

She launches her guess-and-check. "I remember, when I interviewed at ATN, you had just raised a seed round. I'm guessing that a key next step is to be able to raise a Series A. To do that, we need to show that we've acquired some early customers. If I had to guess, I might imagine that investors are going to want to see a few deals with *big* customers." She sat back. "Is that vaguely right? Am I missing anything important?"

Note: this is genuinely opinionated. The larger customers they've talked to present a distinctive set of challenges. A valid alternative strategy would be to try to acquire a large set of smaller customers.

# "Our current runway is about 18 months", she begins, "but my understanding is that we need to get some big customers in the next six to twelve months. That way, you'll have time to tell a story to potential investors. Is that about right?"

Marco purses his lips and stares directly at Quin. "Almost," he says, slowly. "Yeah, big customers are going to be super important. But it's not enough that we just *land* some big customers--we need them to be *using* ATN. I've talked to VC's, and, for a subscription business, they're super worried about churn. We're going to need to raise money before we really know what churn looks like. So VC's are going to want to see *engagement*. We need actual teams using ATN, and, like, *often*. A couple of big sales where the implementations don't even get started could be worse than no sales." He seems to shiver a bit at the idea.

This is brand new information for Quin. They've been talking so much about sales, she hadn't realized that Marco was equally worried about usage and engagement.

Her mind starts whirring with ideas. They have that one big customer whose HR director seems to absolutely love the idea of ATN, and claims to be ready to use the Dunk Tank the moment it launches. She and the team have been putting off adding usage tracking to the product, but if they could focus on just shipping the Dunk Tank, they could probably get something out there *with* usage tracking, pretty fast. Quin thinks excitedly that they could be looking at actual engagement data within just a few weeks! *And* still be setting Marco up with a new sales demo!

Let's pause here for a moment, as Quin is midway through her conversation with Marco.

I want to ask you a very important question.

What, in your opinion, should Quin do, right in this moment?

** Tactical Empathy Skill #2: Echo Back & Summarize

It's going to be incredibly tempting for Quin to *tell Marco about these ideas*.

But that's *not* what she should do, *first*.

Instead, she should take the time to carefully echo back what she's just heard from Marco, summarize it as clearly as she can, and, again, ask if she's gotten it right.

# Insert what happens if she *doesn't* echo back

# Marco looked a bit non-plussed. "Okay, you're saying we should pivot to adding usage tracking? I thought you wanted us to focus?" And he's thinking: sure that HR lead is talking a good game, but their company is huge. They can't do *anything* quickly. He doesn't say that, though, since Quin has jumped so quickly into planning.

For example, she might do that by saying:

"Let me see if I've got that right. For us to be able to raise a Series A, we *do* need a few big customers, but, in addition, we need to show real engagement from those customers. We can't have those deals launch with no usage. Is that about right?"

Let's see what happens when she does this:

To her surprise, Marco pauses again. "Closer," he said. "But, actually, I'm not sure we need to see every one of our big customers engaged. VC's understand that things take time with larger customers. We need *some* engagement from the big customers, I'd guess we need them to be actively implementing. *And* we need some of our smaller, earlier customers to be very actively *using*. I think that mix will allow us to tell a good story."

"Okay, that's super useful," says Quin eagerly. "Let me say that back, see if I've got it. For us to raise a series A, we need to show we can sell to big customers, we need those big customers to demonstrate commitment by starting to implement, and we need some of our smaller customers to be actively engaged. Putting all of that together will let us tell a good story. Is that about right?"

This time, he nods vigorously.  "Yes, that's *exactly* it. I'm glad we talked this out." He's long since stopped looking at his other screens.

"Thanks," says Quin, "me, too."

What's been going on, here?

Why am I being so insistent that you should echo back & summarize, before moving on to the ideas that have been sparked?

# XXX add a bit more

# Why is this so valuable?

First, by summarizing, you will nearly always discover something you didn't get quite right, just as Quin did, about *which* customers need to show engagement.

Second, summarizing back makes an enormous difference in helping the speaker to *feel understood*.

When a person explains something they care about, it's quite rare for them to feel like they've actually been understood.

They're not usually consciously aware of this -- but some part of them will wonder, uncertainly, if their attempt succeeded or not.

# I feel like I should say that, for certain kinds of, well, extra difficult stakeholders, they won't be thinking "Did my attempt to communicate succeed?" but rather, "Did the listener understand this completely clear point I just made, or are they stupid?" If my game plan for working with stakeholders assumed they were all kind and pleasant, I would not have very much to offer you. Luckily, that's not the case.

# You can address both "nice" and "not so nice" stakeholder the same way -- because they are driven by the same underlying uncertainty about being understood.

# Humans rarely experience themselves as being fully understood.

If you, as  that listener, take the time to summarize back your understanding, and get it even vaguely right, the speaker will feel a sense of *relief*.

If you pay careful attention, you may even see them visibly exhale and relax.

# It's like you've completed an open transaction that was otherwise hanging.

Which is exactly the mode you want them to be in, if you're going to turn the corner and now ask them to engage in *your* concerns.

You will earn space to advocate, by demonstrating that you are willing to lead with empathy and understanding.

This is an incredibly valuable tactic, useful in an incredibly wide variety of situations. If you're only going to take one thing away from this chapter (or, frankly, this book), spend some time learning to effectively echo back and summarize.

We'll talk in the exercises about how to build it up.

* Scraps/Thoughts
Maybe, use this chapter to, like, *define* a strategy, and explain that, if they don't know one, they should guess. But they ideally want to state it in terms the stakeholder uses. And we'll learn more about that in the next chapter.

But you must be clear in your own hears and mind about what you think the most important challenge for the business is.

Can mention both Rumelt and Bungay/Art of Action.

Oooh, and what I fold in the "tell me how I'm wrong" tactic!
** Moving From Goals to Strategic Outcomes - XXX CUT THIS,

To bring this to life, let's dig into our first example above:

/"Over the next 18-24 months, we need to break into the enterprise segment, in order to unlock more growth. To enable that, our team needs to address key functionality limitations that are blocking enterprise sales."/

Now, at most software companies I've met, no one will have told the team the long-term goal that clearly, nor drawn the connection from their day-to-day work to that longer-term outcome.

Instead, the team likely has a much *narrower* goal.

E.g. perhaps every time someone on the sales team manages to get an enterprise prospect on the phone, said prospect immediately announces they can't even talk unless the product supports Single Sign On--which it does *not* currently do.

As a result, some engineering leader has been handed a goal that is simply "Add SSO Support", stripped bare of context and underlying purpose.

Someone has created some uncomfortably early deadline for "Adding SSO Support". That engineering leader's team has already started poring over SSO integration docs from vendors, and spelunking through ancient bits of login code in the legacy guts of the system.

Unfortunately, the key stakeholder for the team proceeds to badly drift into "project management" mode. They spend their days talking with the sales team and only join eng team meetings to check on status and harrangue the team about how they're drifting behind the schedule they "committed" to[fn:: Forcing teams to "commit" to schedules and then moralizing about their failures to live up to their "commitments", is a terrible economic practice, but sadly a somewhat common one.]. The stakeholder builds a spreadsheet of launch dates, which they routinely review with executive leadership, even though it feels more and more divorced from the reality the team is living in. Finally, the stakeholder does not seem to understand how SSO actually works, and is therefore unable or unwilling to engage in nuanced tradeoff conversations.

No one feels like there is time to breathe and/or consider a change in how they collaborate.

Say the engineering lead on that team decides to advocate for a change with that stakeholder. As per the advice of this book, they decide to start small by focusing on building a deeper shared understanding of SSO, so that they can make good tradeoff decisions together. They're not (yet) going to tackle the full suite of "project management" behaviors they want to change.

How might that engineering leader motivate this change?

Well, if all they have is their near-term goal, all they can do is speak to the risks of missing that goal.

They might say something like: /"I'm not sure we'll able to hit our launch dates for SSO unless we can make some hard tradeoffs. And to do that, I think you'll need a deeper understanding of SSO. Can we spend some time digging into what the team has learned?"/

Note: this is not terrible! The engineering lead has done a solid job of making their ask in the context of a *business goal*, instead of just relying on some appeal to authority (e.g. "You're doing Agile wrong.")

That said, how is the stakeholder going to hear this request? Let's look at the situation from their perspective for a moment.

Odds are very, very good that the stakeholder is *already* living in fear of missing their SSO launch dates. The reason they're holding that spreadsheet so close to their chest and constantly checking on status is because they're afraid. They've likely lived through some failed software projects in the past, and know, first hand, how badly engineering teams can miss deadlines. They're attempting to control the situation the only way they know how.

Thus, hearing the engineering lead say out loud that the team might miss the launch dates is likely to raise some low-grade panic. In such a state, the stakeholder is not going to be receptive to anything that feels uncomfortable or risky.

Furthermore, the *reason* the stakeholder fears missing SSO launch dates is because doing so will turn into a *failure for them*. They won't be able to achieve their actual goal, which is to unlock enterprise sales.

Hearing the team lead speak only to the near-term goal will make the stakeholder feel *alone* in facing their fears about the longer-term outcome.

Finally, precisely because the stakeholder doesn't understand the nuances of SSO, they likely can't even *imagine* how they can achieve their ultimate, longer-term outcome without delivering on their near-term goal *as originally planned*. So this request from the team lead will just sound like an invitation to accept failure. Given that, there's a decent chance the stakeholder will push back instead of engaging. They certainly aren't going to be excited about changing their own behavior.

What's the alternative?

Let's say the engineering lead has managed to develop an articulation of a strategic intent, one that they know resonates for the stakeholder (we'll explain how to do that, below). In such a case, they could instead say:

/"I wanted to check in about progress. As you've helped me understand, the company's ultimate priority is unlocking enterprise sales, so that we can continue to grow revenue. Unfortunately, right now, enterprise sales conversations keep getting killed because we don't support SSO. Our team is playing a key role in unlocking enterprise sales by adding SSO support as quickly as possible./

/We're very excited about that challenge, and have turned up some interesting options for getting something to the sales team very soon. In fact, we think we might be able to launch some key customer segments early -- but, to be able to do that, we'll need to spend some real time with you digging some SSO details. Can we look at our calendars to block out a few hours?/

Let's unpack that:

 - The team lead drew on *flexibility* to subtly deconstruct the monolithic "Add SSO Support" goal into an incremental launch plan ("launch some key segments early").

 - They demonstrated *alignment* by showing they understand and care about the goals that are keeping the stakeholder up at night ("unlock enterprise sales").

 - Finally, they created *motivation*, by citing things that the stakeholder urgently wants ("launching some key segments early", "getting something to the sales team very soon").

That is all far more compelling than just starting with concerns about not achieving near-term goals.

Note that the engineering lead has *not* yet proposed a wholesale change in practices---they're changing one thing at a time. If they can get the stakeholder into a tradeoff conversation around the details of various SSO options, they can then continue to move towards an incremental delivery plan (e.g. launching to some key customers first, gradually rolling out to more).

Of course, in the above sketch, the engineering leader is able to cite a strategic intent that they heard *from the stakeholder*: /"As you've helped me understand"/.

Sadly, that's not particularly common.

** Rants About Goals
Okay, I'm going to rant a bit here. Just be forewarned and stuff.

At most companies I've met, the goals are a fucking mess.[fn:: I would say 90% of my lunches with friends who work in tech end with them saying "Huh, I just realized my team is working on something meaningless."]

At least one of two significant forms of dysfunction are at play:

Dysfunction Number One: lack of context

Dysfunction Number One: too many goals

Why are these so terrible? Why am I being so swear-y? Why do stakeholders who have somehow risen to a position of business leadership so often set too many goals and also fail to share context?


And, at the heart of that weirdness is: it's impossible to plan a software project in advance and then *just do that plan*. You can (and should), make a plan. But, compared to most business plans, you're going to have to, like violently change the plan as you go.

You're going to have to:

 - Change your mind about what exactly what features to build, over and over

 - Change your mind about how those features should work, over and over

 - Reimplement parts of your system, over and over

And those things won't happen as big moments. For successful software projects, those things are happening *all the time*, at every level.


The key factor that


# Most leaders I've ever met believe that they are doing an excellent job of setting goals for their team.

A few examples:

 - Business: Break into the enterprise segment to unlock more growth

   Team: Address key functionality limitations that are blocking enterprise sales

 - Business: Show sufficient customer growth to enable an acquisition

   Team: develop new product that helps acquire new customers

 - Business: Integrate AI into company practices, to ensure we remain attractive to investors

   Team: Develop AI support for our data ingestion operations

We'll name that combo of a key strategic goal plus your team's part in that goal a "Strategic Intent" (this framing is adapted from the marvelous The Art of Action, by Stephen Bungay, which Melissa Perri also references in Escaping the Build Trap)

In particular, why take the time to do so if you already have a *goal*?

You're going to work on coming up with a clear articulation of that combination of a strategic outcome and your team's role in achieving that outcome.

# XXX Bad Prose GO!

** Table Stakes Rant
[fn:: Ugh, I can't even write that sentence without carping briefly. I dunno, 90% of the time someone has insisted that a set of features are "table stakes", what they're actually saying is "I personally like these features a lot." It's one of those ways to state an opinion as if it's an incontrovertible fact. In such situations I *don't* recommend getting into a debate about "what customers really need". Instead, I recommend just nodding and smiling, and then directing your team to build a coherent product which doesn't have the "table stakes" features. You can then offer that as a thing which could be sold, while you go about adding the table stakes features.]

** Breakdown of Compelling Offer Tactics used

 - She "Told A Story Of Growing Danger":

   /"Every month we don't have something new, your team is in a worse and worse position."/

 - She "Invited Her Stakeholder To Solve Her Problems"

   /"Could you help me find a way to commit more time to developing those key enterprise features?"/

 - She "Addressed Fears Directly"

   /"Even if it means allowing some current customers to grow frustrated."/

 - She "Kept Him Busy"

   /"If *you* can identify current customers..."/


** Frustrating Behavior = Only Way to Accomplish Goal

Often, a stakeholder's frustrating behavior is, in their mind, the only way to get that task done, and therefore the only way to accomplish the long-term outcome. To find a new way to work together, you have to get beneath what they're asking for, and understand what they're ultimately trying to achieve. Once you do so, you can propose a different, less frustrating way of working together, that will move you *both* towards the long-term outcome.


** Three-Part Breakdown of The Power of Speaking to Strategic Outcomes

# XXX Do I need this?

Being able to speak to a strategic outcome that your stakeholder cares intensely about is *insanely valuable*, for at least three reasons:

 - *Outcomes give you the flexibility to identify new ways to work together*

   Developing software is an incredibly complex effort, and can't be perfectly mapped out ahead of time. Having a nuanced understanding of the long-term outcome allows you to steadily come up with new ways to keep moving forward, as you hit unexpected blockers and problems.

   That nuanced understanding is what allowed Maria to come up with the idea of focusing support time on "enterprise-like" customers.

 - *You can position your proposed change as a necessary step to achieve the outcome*

   This helps enormously with motivation, because of how much your stakeholder cares about this outcome.

   Maria was able to say, authentically, that they must change how they work together if Geoff is going to have any chance of building his enterprise sales pipeline.

 - *You can demonstrate a personal commitment to achieving the outcome*

   Because your stakeholder is a human being, and not a robot, it will mean a lot to them to see that you understand, care about, and are deeply committted to achieving the outcome. It will enable them to see you as a potential *partner*.

   By showing her nuanced understanding of the pressures Geoff is under, Maria offered to join him in his biggest struggle. That act of empathy created enough trust and rapport for the two of them to collaborate. Together they discovered a creative option neither had been thinking about on their own: enabling sales team demos well before fully implementing features.

** Outcomes Must Enable Decisions

There are many, many mediocre goals, outcomes, key results, and intents out there.

Luckily, there's a razor sharp test of a good strategic outcome:

 - A good strategic outcome is one that allows people across the company to quickly make good decisions

(I encountered the idea of strategy enabling decisions in Stephen Bungay's The Art of Action, and it has, honestly, kind of changed my life)

Unfortunately, in my experience, the vast majority of companies building software do not set strategy in a way that allows for rapid on-the-ground decision-making. Rather, it's a set of aspirational goals, without any opinionated guidance on how to get to those goals. Or a set of clearly conflicting priorities, with no way to weight them against each other.

If you are trying to come up with a clean, effective statement of strategy, here are two excellent questions to ask yourself:

# I'll offer a simple lens for you to use, as you go about trying to develop and refine your understanding of a strategic outcome:

 - Is it possible to *disagree* with your statement of strategy?

 - Does the strategy allow you to say *"No"* to things?

These two questions ensure you avoid impressive-sounding by meaningless [toothless] strategies like "Accelerate growth" or "Become more customer centric". Who could possibly disagree with those? What would they possibly allow you to say "no" to?

You want to relentlessly refine such vague statements until they become sharper, clearer and more opinionated. For example, you might turn "Accelerate growth" into "Accelerate growth by enabling more upsells to existing customers".

# XXX Experiment with weaving back in Maria's story

That's a statement that someone could absolutely disagree with. Such a person might make a case for expanding your Total Addressable Market (TAM), instead of capturing more revenue from existing customers. That's a valid alternative strategy. If you can't imagine a valid alternative strategy, you're running some real risk of developing a statement too vague and aspirational to be useful.

If your company committed to "Accelerate growth by enabling more upsells to existing customers" that would absolutely let a team on the ground say "No" to things. When an excited sales leader shows up at the weekly demo and demands the team add a feature to allow them to sell into a new segment, the product manager can calmly refer to that intent to push back.

Fundamentally, a good strategic outcome allows you to *make decisions*.

** Sidebar: A Theory Of Why Most Goals Are Terrible

Here's the thing: developing software is weird as hell.

And, at the heart of that weirdness is: to successfully develop software, the team on the ground has to make a metric ton of *decisions*.

Like, way, way more than a team working on a typical non-software business project.

I don't say this to slag people working in sales, marketing or other critical business functions. Those jobs are extremely hard, and require a great deal of skill and experience to do well. Some of the smartest, most effective leaders I've ever known came up through marketing and sales.

But the special weirdness of software around both the quantity and the scope of decision-making is not shared by most business functions.

A team that spends six or twelve months building a valuable piece of software will have, over that time, made hundreds of decisions to:

 - Hone in on exactly the customer problem that software should solve

 - Iteratively explore features that could solve that problem

 - Identify which of those features can be built in a reasonable period of time

 - Find a safe, maintainable way to build those features

Crucially, all those decisions effect each other. If it proves harder than expected to build something, the team has to revisit their decision about what features to build. If early product testing reveals a key constraint that customers forgot to share, the team has to revisit a whole slew of decisions.

You can't make all the big decisions up front, and leave the executional details to the team.

Successful teams make decisions of different scopes, all the time.

They must be able to make a lot of those decisions *without asking their boss*.

Unfortunately, most goals fail on this front, for one of two reasons:

 - Insufficient context

 - Unclear prioritization

The former means: some stakeholder has decided what the team "should do", and they just tell the team to do that thing. They don't pass on why that thing is important, alternatives considered, risks to avoid, upstream dependencies, or downstream consequences, etc, etc. This cripples the team's ability to rapidly make good decisions.

The latter means: rather than face hard tradeoffs between competing priorities, a stakeholder simply assigns separate goals to separate teams, and washes their hands of the ensuing chaos and slowdowns.

# Also assign this to Maria's company

Company facing a hard choice between keeping existing customers happy and developing a new product? No problem, make the former the goal of the Account Management team, and the latter the goal of the Product Team, no tradeoffs needed. Until, of course, the product team's work grinds to a halt, because the AM team is constantly pressuring them to support existing customers, because they've been told that's the most important thing for the business. The product team can't make a quick decision to ignore the AM's -- they have to loop in the Nearest Common Ancestor of their team and the AM's. Which makes all those decisions take forever.

The lens of decision speed is incredibly useful.

The reason this is such a common form of conflict with The Rest Of The Business is that the uncertainty around developing software is just so much greater than around most business activities. It's a form of research as much as executional operation.

Please go read Principles of Product Development Flow, by Don Reinertsen if you would like to be blinded by the science of this.

# Why Most Goals Are Terrible

* Learning Outcomes/Arc
** Maybe: The Power of Speaking to Strategic Outcomes
** Some Problems With Goals
Failure to export context
** Use Strategic Intents To Define Core Challenge
** Tactical Empathy Skill #1: Guess & Check
** Tactical Empathy Skill #2: Echo Back & Summarize
** Quin Identifies a Strategic Intent
** Exercises
* Todos
** Overall rambles
I think, shorter, punchier sections, with stories woven throughout.
** TODO Maybe turn Avoid Decisions into "What You Don't Know.."
you can't force me to make a decision about
** TODO Decide "Intent" vs "Outcome"
I think, Outcome.
** TODO I think, several short stories
Like, tighten up the intro, really strip it down, and then tell stories, showing bad and good.

Maybe return to my intro chapter friends.
** TODO Maybe: open up The Feelings That Are Being Felt
Could even do: how on earth can Geoff be doing this? It's so clearly wrong? Let's look at it from his perspective.

** TODO Move guess & check into/after a story
** DONE Try developing new learning outcomes/arc
CLOSED: [2025-11-10 Mon 09:38]
* Alternate Learning Outcomes
** The Power of Strategic Outcomes
** The Keys To An Effective Statement Of Strategy
The Difference Between Goals and Strategic Outcomes

Goals vs Strategic Outcomes
** Story: Clarifying And Sharpening Strategy
** Why Some Stakeholders Hide Their Dreams
** Story: Drawing Strategy Out
** Handling Leaders Who Fear Decisions
** Story: Mining For Priorities
** Exercises
