:PROPERTIES:
:ID:       49E66E86-CE83-447E-87C2-3BFF3D8FE42E
:END:
#+title: Teaching/Helping Conversations

For [[id:5FAA80B0-D16C-424E-BF2F-1C5C45415618][Tech Investment Book]], notes and ideas for testing the ToC and learning structure by way of teaching/helping/coaching conversations.

* Note to Edmund
Subject: Teachable Chunks + What Have I Already Taught
E,

Hope you're enjoying playing along in the game of "Uh Oh, Dan Doesn't Have a *Job* So All He Is Apparently Going To Do Is Write Things Out and Harass Edmund With Them"

As the ToC is coming into focus, I'm thinking about how test it, as he says, via teaching/coaching sessions.

To that end, I've done two things:

 1- Broken up the overall thing into a few chunks, each of which I could reasonably work on with someone in the span of 1-2 hours

 For each, I'm trying to ask: what *actions* would I want to see someone take after, to see if they've been able to get real value from the ideas?

 2 Also asked myself: is this a thing I've already taught enough, that I can start writing with some confidence that people can act on and get real value from what I'm offering?

Below are my raw org notes, a reasonable summary is: out of three chunks, I think I've already taught two of them enough to get started.

I'm also attaching the latest ToC, which has some minor tweaks and updates (and makes more clear that the intro is just a single chapter).

* Teachable Chunks / Sections

** Chunk 1: Intro / Cycle Sketch / Build Viz / Value Examples / Small Increments

Action to take is have started to socialize the frame of "tech investments" + make a list of potential value with associated ideas for viz + developed some ideas for creative small increments

** Chunk 2: Advocating w/ Stakeholders / Storytelling to Celebrate Wins

Actions to take = have built empathy w/ stakeholders; have stopped trying bad things; have named future decision points with stakehoders; have started to work on metrics; have experimented w/ using storytelling structures.


** Chunk 3: Steady Habit of Decisons / 5 Scopes / Post-Mortems / Tech Stewardship

Actions = have used/put in place any of the above.

** (Advanced Topics)
I'm... not sure. Those have less in the way of direct actions and more in the way of "This drew sparks, I've got something to think about in a new way"

They are appendix-like, and that's okay.

* What Have I Already Taught?

I mean, I've taught the living hell out of the fundamental cycle + advocating with stakeholders. Like a *looooot*.

Less so w/ the scaling up parts, around cadence of decisions/scopes/post-mortems/tech stewardship.

Def try that out w/ Satoe

* Potential Act 2 Coaching
 - [X] Satoe
 - [ ] Dani (Bennett's wife)
 - [ ] Kinan (is he managing? I think, yes)
 - [ ] Eric Lundin
 - [ ] Tasneem
 - [ ] Gabby
 - [ ] Lilli
 - [ ] Sam Adelman
 - [ ] Tom Hare
* Template <2025-05-27 Tue>
Subject: A Thing I'm Looking to Learn
Dear <Person>,

tl;dr - I'm working on a book about technical debt (called "Tech Investments, Not Tech Debt")

If you have time, I'd love to talk with you about how you face the challenge of ensuring engineers are able to spend time keeping their systems healthy (vs just endlessly churning out features).

This could be lunch, or coffee (I have time to get myself places to, *gasp*, meet in person these days) or a zoom.

For reference I'm defining "technical investments" as:

/"Something that the engineers believe is *valuable for the business*, but that *no one is asking for*."/

Within that broad theme, I'd be happy to cover whatever is useful to you.

That said, I'm particularly interested in spending time on what I'll call "organization-level challenges", e.g.:

 - Getting stakeholders into a habit of repeatedly prioritizing technical investments (vs seeing each as a one-time only painful cost to pay)

 - Using post-mortems to help motivate technical investments

 - Assigning ownership of parts of your codebase in a way that allows for steady technical investments

 - Tactics for different scopes of investment: On the Side, A Ticket, A Within-Team Project, A Cross-Team Initiative, A Durable Team

 - Weaving technical investments into the career ladder

In each of the above areas, I've got some approaches I've seen work, I'd be curious to talk those out and see if they could apply in your world.

Thanks,
D
* Eail to Bennett <2025-05-30 Fri>

Subject: Hey There + Possible Intro

Bennett,

Heya, sir, hope life goes well.

I'm reaching out for two reasons:

 1- I'd love to catch up

Happy to hop on a phone or zoom, or, gasp, I could come out to some physical place you physically are with your physical self -- be that in Newton or downtown Boston (oh, speaking of which, are you anywhere near Community Rowing on Nonatum? Because I drive Jack there a couple times a week, it could be fun to swing by and say hi on one of those days).


 2- I'm like to ask you for an intro... to Dani ;-)

Here's the story.

A few weeks back, I started working on a blog post about preferring Tech Investments to Tech Debt.

I kept on finding more facets of it to talk about, then it turned into a /series/ of posts, and then, somewhat to my surprise, I discovered I was writing a book.

(I found a truly excellent gameplan for writing this kind of non-fiction, by the guy who wrote The Mom Test).

I'm pretty excited -- the book has a working title of "Tech Investments, Not Tech Debt: Identify, Advocate For, and Deliver Engineering-Led Work".

As part of the gameplan, I want to do some, essentially, customer interviews, of the kind of people who the book is hopefully helpful for.

Sadly, you are not allowed to be one of those people -- because you and I have worked and lived and breathed all the stuff I'm going to write about, together.

But I was thinking that Dani might actually be a good subject (and that *also* gives me a perfect excuse to reach out to you and say hi).

Below is the generic pitch email I've written up. Can I ask you to share that with Dani, and, if she's willing/interested, let me know, so I can reach out to her to find a time to chat?

Thanks,
-Dan

Dear <Person>

If you have time, I'd love to learn some about how you face the challenge of ensuring engineers are able to spend time keeping their systems healthy (vs just endlessly churning out features).

This could be an in-person lunch or coffee or a zoom.

If the below is potentially interesting, let me know, and I can propose some times.

I'm happy to talk about various facets of balancing feature work vs more technical investments but I'm particularly interested in spending time on sort of organization-level challenges, like the below.

For each, I've had some approaches I've seen work, I'd love to talk those out, see what you've tried, etc:

 - Getting stakeholders into a habit of repeatedly prioritizing technical investments (vs seeing each as a one-time painful cost to pay)

 - How to link post-mortems to later technical investments

 - Assigning ownership of parts of a codebase in a way that allows for steady technical investments

 - Weaving technical investments into the career ladder

Thanks,
Dan
