:PROPERTIES:
:ID:       18410F3D-0379-462B-96C1-A59B01047164
:END:
#+title: Unstuck Beta Journal

As part of [[id:9410A7DC-111C-4791-B8A1-C20867904251][Unstuck Beta]], a place to record observations about my own experience of checking HTB for feedback. Each time, just have to record something time stamped here. (C-u C-.)

For each:

 - What did I learn?

 - What did I observe in myself?

* Observations

** <2025-12-31 Wed 14:24>

The time spent is interesting.

*** 4 readers made it to end of first chapter

*** 2 readers made it to end of second chapter

** <2026-01-01 Thu 10:35>
Okay, 2 more reactions. Few comments from Owen. Interesting point re footnotes. Also, I had a spike of fear about "jokey tone". But I think, stick to my guns for now. I'm aiming for "Fun, Informative & Actionable" as my specific kind of useful. If I need to later boil that down to a leaner thing, I'll learn that from *test readers*.

And I can't ask him questions? I guess that makes sense?

But, for footnotes, I think I'll be well-served by his point.

But, again, remember: I'm waiting to get more feedback. People's identification of *problems* is the key.

What did I say: relish the fear!

** <2026-01-01 Thu 12:01>
