:PROPERTIES:
:ID:       5903AFE7-4B1E-422C-8537-2C56BBFBA643
:END:
#+title: Mine for Frustrations, Fears & Dreams
#+filetags: :Chapter:
* Mine for Fears & Dreams
** Humans Have Feelings, Ignore At Your Own Risk

I'm going to go out on a limb here and guess: you probably work with humans.

That's great! Except, of course, for when it's not.

If you want one of those humans to change their behavior, it's absolutely critical for you to understand their *feelings*.

This may sound a bit odd. Perhaps you work with a CEO whose only outward expression of emotion is a series of variations on the tightly clenched jaw. You might have legitimate debates with coworkers about whether or not this CEO even *has* feelings.

Look. Understanding feelings doesn't mean gathering in a drum circle and getting in touch with our inner child. All humans, in whatever positions of power they may find themselves, have things they deeply want, and things they are deeply afraid of. I don't care what role they're in, your stakeholder's current behavior patterns are driven by some combination of what they want and what they're afraid of.

When you advocate for change, you want to be able to speak with authentic connection to both the fears that are keeping them up at night, as well as the things that they desperately wish were happening.

But there's a problem.

Many leaders do their best to *hide* their feelings. If you haven't had positions of serious responsibility over large groups of other humans, I encourage you to have some empathy for people in these roles. It can feel incredibly important to "project confidence". And that can very easily turn into "pretend to have no fears or desires". In fact, many leaders unconsciously feel a sort of desperate fear of their emotions being found out. They feel, usually without realizing it, that they must *hide* their emotions to retain control.  That is why it's so common to feel like you're banging up against an unyielding, inhuman, unemotional wall.

However, even if your key stakeholder seems to be working very hard to present as a goal-driven business automaton, you *must* find a way to get past that.

To persuade your stakeholder to risk making a change, you need to to develop an *empathetic understanding* of their fears and dreams.

That empathy will allow you to productively challenge them to change their current behavior, by speaking authentically to their *underlying concerns*. Even if they've been actively trying to hide those from you.

Persuading humans to change their behavior works roughly a thousand times better if you can find a way to speak to their hearts as well as their minds.

Let's talk about how to map your stakeholder's feelings.

** The Four Key Emotions

Fortunately, you don't have to worry about every facet of your stakeholder's inner life. You're going to develop a picture of just four key emotions, which will mean coming up with answers to four questions:

 - *Frustrations*

   What happens, day-to-day, that frustrates your stakeholder?

 - *Fears*

   What are they afraid might happen at some point in the future?

 - *Delights*

   What happens, day-to-day, that makes your stakeholder feel good?

 - *Dreams*

   What do they most fondly hope happens at some point in the future?

These form an extremely powerful core for persuasion. Two focus on day-to-day experiences (frustrations and delights), two on longer-term motivations (fears and dreams).

If you can come up with answers to these four questions, you can build an *extremely* compelling request to try something new. A request that the stakeholder will both *hear* and *feel* as worth listening to.

We'll spend real time on how to craft such a request in the "Make a Compelling Offer" chapter.

But first we need to talk about how to come up with answers to these questions.

You're going to use a mix of two techniques:

 - Making an Educated Guess

 - Mining For Emotions

The first one is, well, about as simple as it sounds.

If your stakeholder is in some position of authority within your company, you should be able to *guess* at answers to at least a few of the four questions by simply spending some time talking with people you trust. Of course, that's only true if you work at a company where people consider it important to understand what the hell the people in power are doing and *why* they're doing those things, but that's every company I've ever worked at?

Making an educated guess is a very good way to start, but, often that's not enough. Especially if your stakeholder seems committed to showing as little vulnerability as possible.

In that case, you'll need to do a bit of detective work, which we'll call "mining for emotions". For that, we'll develop two more tactical empathy skills.

** Tactical Empathy Skill #3: Repeat Trailing Three Words

If you want to understand your stakeholder's fears and dreams, you're going to, well, need them to *talk to you*.[fn:: At least that's true... now? If this book is invalidated by mind-reading technologies, ALL BETS ARE OFF.]

Unfortunately, it often requires real work to *get people talking at all*.

Luckily, there's a surprisingly simple tactic that helps a great deal on this front.

Let's see it in action, with Quin and Marco. First we'll show the challenge, and then we'll lay out the tactic:

One day, Quin notices that Marco seems frustrated after a call with a potential customer. Eager to build up her picture, she says, "I noticed that that call seemed a little frustrating. Can I ask what was going on?"

Marco says shortly, "It's nothing. I'd just like to advance the deal." He shows no interest in explaining more.

This is a near-total failure. Quin hasn't learned anything useful about Marco's feelings, beyond the fact that he'd like this potential customer to buy their product. Which, of course, she already knew.

If you were in Quin's shoes with some key stakeholder of yours, what would you do? It seems like the stakeholder actively wants to shut the conversation down. Asking another question about their feelings could easily slide over into being irritating. Should you just give up and wait for another day? Or should you push for more, despite the risk of actively annoying them?

Unfortunately, *neither* of these approaches is likely to help you. Neither will give you the insight you need into your stakeholder's underlying drives, which you need in order to advocate for change.

What you *can* do instead is to employ a simple and somewhat *bizarrely* effective tactic, "Repeat Trailing Three Words".

Here's how it works.

First, you ask someone a question.

They respond with an answer.

You then calmly and curiously repeat the last three words they said, back to them, inflected as a question.

And then you stop talking and wait.

*That's it*.

If you can achieve any form of genuine curiosity as you speak, and if you can stop yourself from saying anything other than those three words...

...the person will start talking again, telling you more and more.

And they'll *feel* like you're hearing and understanding them.

It shouldn't be this simple. But it totally works.[fn:: If you happen to like romantic comedies, you might catch this *exact tactic* being referenced in episode <something> of Nobody Wants This (in the fun B storyline of the two loser siblings, what, you're not low-grade obsessed with romcoms?)]

** Our Story: Quin Draws Marco Out

Returning to Quin and Marco, say she's been coached in this conversational tactic by her new mentor.

She starts by asking a question of Marco: "I noticed that that call seemed a little frustrating. Can I ask what was going on?"

He responds brusquely, "It's nothing. I'd just like to advance the deal."

She feels a momentary spike of frustration. Why won't he /talk/ to her? But then she remembers the trailing three words tactic. She takes a breath to focus and then says, calmly and with genuine curiosity, "Advance the deal...?"

Marco says nothing for a long moment. A silence opens up between them. Just as Quin is about to give up, Marco abruptly says, "Yeah, they just keep talking and talking." And then he sits back and frowns.

Quin tries the tactic once more. "They're talking and talking...?"

This time, there's a slightly shorter pause before Marco starts up again. "Yeah. I honestly don't know if they're *ever* going to convert. Of if they just like *talking* about their problems."

Quin tries again, "About their problems...?"

Marco is now talking smoothly, there's barely a pause. "Yes. It's almost like these aren't *real* problems. We might be talking about a vitamin, not a pain-killer."

Reid Hoffman is credited with the vitamin versus pain-killer formulation for product opportunities. "Vitamins" are nice-to-haves. Potential customers will /tell/ you they want such products, but often they're doing so because they feel like they "should". "Pain-killers", on the other hand, are products that solve pressing, painful, important problems.

Quin, who knows the vitamin/pain-killer metaphor, realizes with a start that she's turned up one of Marco's biggest fears---that ATN might be building something that customers don't truly need. He has not mentioned this fear, even once, to her or the team. She's excited by what she's found, but needs some time to process it.

She now wraps up the conversation with a slight variation on what she's been doing. She once again repeats the last few words Marco said, but this time, instead of inflecting it as a question, she indicates agreement.

"A vitamin not a pain-killer, got it," she says, nodding her head.

"Great, thanks," says Marco.

Those may look like dry words on the page, but the tactic is *remarkably* effective in person. It's honestly kind of amazing that you can get so far with such a simple approach.[fn:: If you are in some form of therapy, you may realize that your therapist does a lot of this! It really works.]

If you're able to deploy this tactic well, you'll achieve two extremely valuable things:

 - *First, you'll build rapport*

   You'll demonstrate, simply by listening, that you want to work *with* the stakeholder to solve their problems.

   Marco started the above conversation half shut-down, struggling with his unstated fear that ATN was pointed in the wrong direection. By the end, he has a sort of cautious hope that Quin maybe understands that risk, and will work with him to face it.

 - *Second, you'll acquire context*

   Quin learned that Marco has fears about how deeply customers *need* to put in place remote team-building tools. How much their teams' potential lack of connection *matters*. ATN's products might be that dreaded failure mode of startups throughtout time: a "nice to have".

   Once Quin has a little time to think, she realizes this might help explain why Marco keeps coming back with new feature ideas---doing so is a means to soothe that fear.

   Understanding that is going to be incredibly valuable, if Quin is going to ask him to change that behavior pattern.

Now, let's talk about the second Tactical Empathy skill you'll use, when mining for emotions.

** Tactical Empathy Skill #4: Offer Labeled Feelings

Repeat Trailing Three Words will help get your stakeholder talking, and start to fill in your picture of their key emotions.

But if you're going to advocate for change, you often need to go further.

To develop a nuanced understanding of their four key emotions...

...you'll need to talk to them *about* their emotions.

Now, I'm imagining many readers, in this moment, visualizing some frustrating, emotionally shut down stakeholder, and saying to themselves "Dan, you are completely stoned. There is no way on earth this is going to work."

Look, I get it. It may seem literally impossible to imagine that stakeholder opening up to you in any useful way. But I encourage you to study and then practice the tactical empathy skills we've been discussing. You may well find yourself astonished by how far a mix of active listening, echoing, validating and open-ended questions can get you.

Returning to the challenge in front of us, how can you get into a useful conversation with your stakeholder about their emotions?

Just as people are often resistant to showing their emotions, they can *also* easily become defensive if they perceive you as, in any way, *telling them* what their emotions are.

E.g. imagine Quin were to say to Marco: "Are you afraid that we're not solving an important problem?"

Although that may be exactly right, there's a very good chance that he will feel accused and become defensive.

This problem is particularly tricky for the tnegative emotions---frustrations and fears. If you try to speak to those, your stakeholder can easily feel like you're accusing them either of being weak, or of being too emotional. But you urgently need to understand frustrations and fears---those two have the potential to absolutely shut down any attempt you make to change.

The trick to get these negative feelings out in the open is to carefully go through two steps, which Chris Voss names "Labeling" emotions:

 1. Describe the *situation* your stakeholder is in, with careful empathy

 2. Offer a potential name/label for their emotion, as a *natural response* to that situation

For example, Quin might /describe/ Marco's situation as follows:

"We're in a tricky spot. Potential customers keep telling us that they're *interested*, but because we don't have a thing we can *sell* them yet, we can't find out if they're genuinely willing to buy."

She immediately follows that up with an offer of a labeled emotion, as a natural response to the situation, lightly inflected as a question:

"It seems like you might be afraid that we're not solving a genuinely *important* problem...?"

Note that Quin has specified, in some detail, what, in their current situation makes "being afraid" natural ("we can't find out if they're genuinely willing to buy").

She's also labeled the situation as "tricky", which, again makes "being afraid" of something quite natural.

Furthermore, when she then goes to describe his emotional reaction, she prefaces it with "It seems like you might...". She's not *telling* him his feelings, she's *offering* a potential understanding of his feelings.

When you go to make such an offer, it's critical that you preface it with an opening that creates a bit of separation between you and the statement of emotions you're about to make, e.g.:

 - "It seems like you might..."

 - "It would make sense if you were to..."

 - "I could imagine you might..."

Those create space for the person to hear it as you *trying to understand them*, not announcing their feelings to them. Of course, they work far, far better if you can get yourself into a place of genuine curiosity, so that you *are* trying to understand.

Let's review the two different ways Quin could speak to the fear she thinks Marco might have:

Direct Question: "Are you afraid that we're not solving an important problem?"

Labeled Offer: "We're in a tricky spot. Potential customers keep telling us that they're *interested*, but because we don't have a thing we can *sell* them yet, we can't find out if they're genuinely willing to buy. It seems like you might be afraid that we're not solving a genuinely *important* problem...?"

On the page the two may not seem that different, but if you can do the work to lay out the situation first, and then offer that second part in a calm, curious, dispassionate tone, it has a *remarkably* powerful effect. Your stakeholder, instead of feeling *accused*, will feel *relieved*.

As Voss explains, research shows that, by naming fears out loud in this way, you can actually help people *feel* calmer. It both shows the person that it's okay to openly name the fear, and it also engages the rational, problem-solving parts of their brain.

This approach is *extremely* powerful. But it takes real practice, for two reasons.

First, it's often not easy to develop an empathetic understanding of the *situation* which leads to the feelings. The key is to get to the point that, when you describe the situation, the resulting feeling seems *inevitable*. This is very much a learnable skill, and we'll return to it in the exercises.

Second, many of us have learned to *not* talk to other people about their feelings, especially people who seem upset or angry in any way (and especially especially if those people have some form of power). With experience, you'll find that offering labeled emotions almost always makes listeners feel *good*. Once you experience this tactic as defusing tension and anger, it won't feel so risky. But you do have to build up that experience. In the exercises, we'll talk through how to practice this tactic in gradually higher-stakes situations.

** Our Story: Quin Puts It All Together
Over the course of the next few days, Quin employs different tactics to answer the four key emotion questions:

# Quin guesses a few feelings, uses trailing three words, echoes back and summarizes, offers labeled feelings, at the end, Marco feels excited, open, energized.

*Frustrations: What happens, day-to-day, that frustrates Marco?*

This one Quin is able to get to with a straightforward Educated Guess. Marco clearly feels like it takes /forever/ to see progress on the product---that's why he suggested putting pressure on the team to work longer hours.

She starts to fill out the template she got from her mentor:

Frustrations: lack of visible progress (i.e. poor velocity)

*Fears: What is Marco afraid might happen at some point in the future?*

She develops a picture of two related fears.

First, in the scene above, we saw Quin draw out a key fear through Repeat Trailing Three Words and Offer Labeled Emotions: Marco is deeply afraid that, although potential customers *seem* excited about All Together Now's under-development product, they may not truly *need* it.

Answer 1: he is afraid ATN is developing a vitamin, not a pain-killer.

Second, when she dug into Marco's strategic intent for the business (where she used Echo Back & Summarize), she learned that ATN needs to see *engagement* from some of their customers, in order to generate interest from funders.

Answer 2: he is afraid that, even if ATN makes a sale, customers won't end up using the product (and then he'll have nothing to show potential investors).

She extends the template further:

 - Frustrations

   - Lack of visible progress

 - Fears

   - ATN might be developing a vitamin, not a pain-killer

   - Customers might buy but not use, and that will take a long time to learn

Once she's developed this much of the template, she spends a bit of time trying to put herself in Marco's shoes; in particular, she tries to imagine what it would be like to have those fears eating away at her, every day.

She realizes that, in such a situation, she would be *very* tempted to try, somewhat desperately, to make the product *more compelling*. In particular, if she were on a call with a potential customer, and she heard them first describe a feature, and then claim they needed that feature to commit, she might feel intense urgency to do what they asked. Adding that feature might feel like the only way to save ATN from a looming disaster.

She's certain this part of why Marco keeps trying to jam new feature ideas into their development process.

She realizes she can understand and empathize with these underlying fears, even if she thinks the actions they are leading to are profoundly counterproductive.

*Delights: What happens, day-to-day, that makes Marco feel good?*

Here, she comes up with two answers.

First, she can make an Educated Guess, because she sees Marco absolutely light up when he has a chance to try out some sort of new UI, even if the full product isn't working yet. Correspondingly, she's seen him glaze over when the team reports progress on database structures under the hood.

Answer 1: Marco is delighted when he gets to interact with something visual.

She also spends some time thinking about the frustrating stand up meetings. From her perspective, Marco is barging and blowing up the team's focus by forcing an instant brainstorming session about some new feature ideas. She tries to put aside her frustrations for a moment and imagine the situation from Marco's perspective. In particular, what benefits is he getting, from his current behavior?

Part of it, she thinks, is that he is able to channel his fears into some sort of action.

But that's not all, she realizes. When she thinks about Marco, she realizes that, pretty much every time he blows up up one of the team's standups, he goes through the same arc. At the start, he's swirling with excitement and ideas, but doesn't have a clean way to express them. As they talk, he gradually hones in on a coherent way to summarize what he's heard, and what it could mean for the product.  By the end of the brainstorming, he has condensed and clarified his own thinking. And that, she realizes, *feels good* to him. Of course, the team is intensely dizzied and distracted by those same conversations, so they can't keep doing that. But she can very much empathize with Marco wanting to quickly talk out what he has heard from customers, while it's still fresh.

Answer 2: Marco is delighted by quickly turning a customer call into a clean understanding of product options.

She extends the template further:

 - Frustrations

   - Lack of visible progress

 - Fears

   - ATN might be developing a vitamin, not a pain-killer

   - Customers might buy but not use, and that will take a long time to learn

 - Delights

   - Interacting with something visual

   - Clarifying his thinking immediately after customer calls

*Dreams*

Here Quin is going to mix a few tactics together, let's see it in action

# XXX Notes on what to do, here.

# XXX Mix in another fear, around losing control? Or save for next chapter. Yes, save.

She asks him what, if things were go to really great, might happen by the end of next year. (maybe wave a magic wand).

She draws him out with repeat trailing words

Once she has a whole picture, she echoes back and summarizes.

Finally, she offers a labeled understanding of both the excitment and also the fear.

Maybe hone in on her figuring out that he wants the engineers to be *connected* to customers.

 - *What does he dream of or hope for*?

   Quin can see a glint of excitment in his eye when he imagines demoing a product to customers, and seeing them eager to start using it.

   # She's also heard him say more than once that he wants to build a company where everyone feels connected to the customers. She suspects that his constant updates after his customer calls are partly driven by a desire to live up to that vision.

Now that she's got all this critical information, Quin is ready to design a single increment of change.

** Exercises
*** Repeat Trailing Three Words

Because it's so simple, there are two good ways to practice the Repeat Trailing Three Words tactic.

1) Experiment In Random Parts of Your Life

Whenever you can, in whatever conversations you find yourself in, try repeating the last few words someone says to you, inflected as a question. Try it in both professional and personal contexts, try it with your boss, try it with your peers, with your spouse, kids, neighbors, whoever.

Do it over and over, and you'll find your own authentic way in, and it'll start to feel and more more natural.

If you start by using it just once in a given conversation, then, as that feels comfortable, see how long you can keep someone talking and opening up by just repeating those last three words of each thing they say to you.[fn:: "Dan, this whole active listening thing has helped my relationship with [insert spouse's name]", is something I've heard let's just say, a bunch of times.])

As above, take a bit of time to explicitly reflect on how it feels to do it, and use that reflection to tweak your personal approach.

For an initial, focused period of practice to rewire yourself, aim to do this 2-3 times/day for a week, and see where that lands you.

2) Explicitly Test With a Trusted Friend

Tell a friend you want to work on active listening, and then ask them a series of questions to dig into some issue -- maybe specifically something close to the kind of conversations you might have with a stakeholder.

E.g. you could say "I want to practice some active listening sikills I'm working on. Would it be okay if I ask you some questions about your work?"

And then see if you can dig for information about what they're most worried about, and what they most hope to achieve, using the repeat trailing three words tactic as you go.

At the end, pause and ask for feedback from them on how it felt for them.

During a period of focused practice, do this 3-4 separate times, and again, make sure you make time to reflect.
*** Labeled Feelings

Take your most frustrating stakeholder. Come up with a description of their situation that makes their frustrating behavior an inevitable response.

This doesn't mean *justifying* it, to be clear. It means understanding the story they're telling themselves, the way the world presents to them.

E.g. say your stakeholder is demanding progress across far more initiatives than your team can possibly achieve. Is their boss making unreasonable demands of them? Have they experienced so many software projects as failing, they're trying to cover their bets?

What if you're pissed at your stakeholder? You shouldn't have to be the one to do this work.
* Structure Ideas
** What are my learning outcomes?
Have I sold the idea enough in the previous chapter, of the value?
*** Humans Have Feelings
*** The Key Questions To Answer
**** Frustrations
**** Fears
**** Delights
**** Dreams
*** Tactical Empathy Skill #3: Repeat Trailing 3 Words
*** Tactical Empathy Skill #4: Offering "Labeled" Feelings
*** Our Story: Quin Mines for Feelings
*** Exercises

* Title Ideas

** Mine for Context, Fears & Dreams
** Mine for Strategy, Fears & Dreams
** Mine for Frustrations, Fears, Delights & Dreams
** Mine for Intent & Feelings
* Scraps
** Afford to Ignore

One useful frame is: someone is one of your stakeholders if you *can't afford to ignore them*. That may sound a bit brutally transactional, but if there's too large a set of people who you can't ignore, then there's almost no chance your team can move quickly and create meaningful value.  Asking who you can ignore will sometimes shine a light on the implicit power structures of your company--and can reveal fundamental conflicts that are making it impossible for you to win. E.g. maybe your CEO talks night and day about how critical it is for your team to stay on track for the big new product launch they've promised to the board. However, your team is *also* expected to handle a stream of feature requests from existing customers, which that CEO doesn't pay any attention to. If, one day, the Head of Customer Success comes banging on your door, demanding you immediately add a new feature for enterprise customers, can you *afford* to ignore them? Or if you do, will you receive an unpleasant lecture from the CEO and then acquire a reputation as "not being a team player"?

If not, the CEO's statement of your priorities isn't a full truth of your situation.

The Head of Customer Success  has shown a willingness in the past to blame engineering and product if they fail to hit their retention numbers.

Separately, the Head of Customer Success

The only way you and your team will create significant value is if you can relentlessly focus on the most important, most valuable work at every moment. People you can't ignore are, in the actual,
