:PROPERTIES:
:ID:       D6564799-DCF0-4D14-BC29-C9A0E3B47B3F
:END:
#+title: The Art of Divining Emotions
#+filetags: :Chapter:
* The Art of Divining Emotions
** Leaders Hide Their Feelings
# But there's a problem.

# Many leaders do their best to *hide* their feelings.

To persuade your stakeholder change their behavior, you'll want to to develop an *empathetic understanding* of their fears and dreams.

# That empathy will allow you to productively challenge them to change, by speaking authentically to their underlying concerns.

# Even if they've been trying to hide those from you.

Persuading humans to change their behavior works roughly a thousand times better if you can find a way to speak to their hearts as well as their minds.

But there's a problem: very few Important People wake up every day eager to openly share their feelings.

# If you haven't had a position of responsibility, leading a group of other humans, I encourage you to have some empathy for people in these roles.

I mean, that's true of humans in general (do you look forward to telling your co-workers your deepest fears?). But it's even more true of Important People.

Humans in positions of authority often feel like they must hide their emotions. With such stakeholders, you can feel like you're banging up against an unyielding, inhuman, unemotional wall. Your Important Person may even do their best to imply that any issues are due to *your* out-of-control emotions, as they seize [assume, take] the moral high ground of being perfectly calm and rational. For such leaders, being any form of emotionally vulnerable feels dangerous.

I do feel compelled to say: it's not only possible to lead with emotional openness, it can in fact, be exteremely powerful to do so. But you're not going to run into a ton of Important People who have mastered that approach.[fn:: Two points for those interested. First, read Dare To Lead by Brene Brown. Second, despite what I'm saying above, I think it *is* sometimes important for leaders to carefully put their own feelings aside. In particular when they're using their authority to do something that someone else finds hurtful. E.g. firing someone, or giving a tough performance review. As a very strong leader once said to me, 'I hate when people make it about them.' But those are rare circumstances.]

If you happen to have such an emotionally open stakeholder, awesome! You don't need all the tactics in this chapter. If, on the other hand, your stakeholder works hard to present an armadillo-like shell to the outside world, read on.

# Which, if they are feeling anxiety or fear, can turn into a And that can very easily turn into "pretend to have no fears or desires".

# In fact, many leaders unconsciously feel a sort of desperate fear of their emotions being found out.

# for some powerful ways to help them open up.

# Even if your key stakeholder seems to be working very hard to present as a goal-driven business automaton, you must find a way to get past that.

** Four Flavors Of Emotions To Divine

As you develop your skills for mapping feelings, you'll be guided by four key questions:

# Fortunately, you don't have to worry about every facet of your stakeholder's inner life. You're going to develop a picture of just four key emotions, by answering four key questions:

 - What happens, day-to-day, that *frustrates* your stakeholder?

 - What are they *afraid* might happen at some point in the future?

 - What happens, day-to-day, that makes your stakeholder *feel good*?

 - What do they most fondly *hope* happens at some point in the future?

# These form an extremely powerful core for persuasion.

I'll shorthand those as, respectively: Frustrations, Fears, Delights and Dreams. Two focus on day-to-day experiences (Frustrations and Delights), two on longer-term motivations (Fears and Dreams).

You won't need to answer every one of these questions in every situation. But, in total, they represent a very useful set of ways in, that will allow you to develop a really strong pitch for change.

# We'll talk about how to craft your request in "Make a Compelling Offer."

# If you can come up with answers to these four questions, you can build an *extremely* compelling request to try something new. A request that the stakeholder will both *hear* and *feel* as compelling.

But first we need to figure out how to answer these questions in the first place. Again, if you're blessed with that rare beast, the emotionally open Important Person, go ahead and ask them. "Bob, what would you say frustrates you day-to-day? What do you hope happens if everything goes really well?"

But what should you do if your stakeholder is not so emotionally open?

Step one: make a guess.

If your stakeholder is in a position of authority within your company, you likely have a hunch about how to answer some of these questions. The emotions of people in power are important enough that, usually, people on the ground have at least *some* model of what is going on inside their various bosses' heads.

But that guess should just be the start. Because Important People spend so much energy trying to hide their emotions (and because our own feelings of powerless frustration can block our own ability to read emotions), we'll want to test out and refine our guess.

** Look Who's Not Talking Now: Hitting Conversational Dead Ends

# , Well, Anything

# How Alistair Gets Max Talking

Let's return to our story of Alistair and Max. In the last chapter, we saw how Alistair could build rapport with Max if he knew the following two facts:

  1. Max /fears/ that the CEO will angrily blame him for any customers issues

  2. Max is /frustrated/ that the new PM's don't fully understand the complex ProClaims product

However, we skipped past *how Alistair would figure those things out*.

Max certainly doesn't go around *explaining* his fears and frustrations. He just rigidly insists that he has to be in the loop for all decisions, he plays out his martyr complex, he looks tense and unhappy.

Alistair is not in Max's meetings with the PM's. He's not in the exec team meetings. He doesn't know there's tension with the CEO. He doesn't know that Max has concerns about the PM's. He just experiences Max as brusque, remote and difficult, and assumes Max's difficult behavior is due to Max's difficult personality.

And so he stays stuck.

But let's say Alistair commits to divining Max's emotions. We'll even say he's gotten some coaching on how best to do so. As per that coaching, he starts with a guess:

Alistair has noticed that Max seems extra tense and unhappy during the weekly ProClaims status meetings. Alistair not totally clear on why that might be. His current theory is that Max is unhappy that the project seems to be drifting behind plan (this guess will turn out to be wrong).

How can Alistair learn more? How can he refine his guess? His next step is, in fact, to simply /ask/.

It's their weekly zoom 1:1. They've reviewed progress on the ProClaims overhaul, and they've talked out a role they're planning on opening.

There's a pause, Max's eyes flick away from the camera. No doubt he has Slack messages piling up from all the people seeking his attention for decisions he's holding up. Alistair takes a breath and says: /"Is there anything about our ProClaims status meetings you find frustrating?"/

Max looks surprised. He frowns and then curtly replies:

/"They feel a bit slow."/

Max shows zero interest in sharing anything beyond this incredibly generic critique. In fact, Max seems, if anything, /bothered/ by this question. Alistair certainly isn't feeling excited about asking any follow ups. What does "a bit slow" even mean?

And here we hit out first fundamental challenge.

If you want to understand someone's feelings, you need them to *talk to you*.

But it often requires real work to *get people talking at all*.

# Many stakeholders tend to clam up, the moment anything resembling an emotion drifts into view.

# This is a genuinely tricky moment.

Imagine you're in Alistair's shoes. You've asked your key stakeholder a question you care a lot about. They've responded by immediately shutting the conversation down.

# when you ask a question they don't really want to answer.

# You may be familiar with this kind of unpleasant moment.

# about emotions. Where, after asking a question, you feel shut down by your stakeholder.

What should you do? Ask another question, and run the risk of pissing off your Important Person? Try to somehow divine your answer from whatever cryptic, fragmentary thing they said? Give up and go home and pour yourself a stiff drink? I have tried all of those, many times, and not seen much in the way of positive returns!

Luckily, Alistair has gotten some coaching on this very front.

# Luckily, Alistair's mentor has forced him to read Never Split The Difference.

** The Simplest, Dumbest, Bestest Tactic: Repeat Trailing Words

# so he pulls out a magic trick:

# He will *repeat the last three words* that Max said, inflected as a question.

Alistair is going to employ a very, very simple, but very, very powerful tactic.

We'll name it "Repeat Trailing Words", and this is it, in its entirety:

# One that is so seriously, marvelously, totally dumb.

# Here is the entirety of the tactic:

 1. You ask someone a question

 2. They respond

 3. You repeat the *last three words* they said

 4. Then, you stop talking and wait

*That's it*.

# You speak calmly and curiously, inflecting the three words as a question.

If you can stop yourself from saying anything other than those three words, and you can wait just a bit longer than feels comfortable...

...the person will start talking again, telling you more and more.

And, believe it or not, they will *feel like you're hearing and understanding them*.

Why on earth does this work?

When humans hear their words calmly and curiously echoed back, it makes them feel understood. Which is a rare and pleasant experience. Having an empty space to fill compels them to start speaking again. Which exposes more information and emotion. Which can then be understood and validated. After a few cycles, they will feel far more open to their listener.

It shouldn't be this easy. But it totally, totally is.

Let's rewind. Alistair asked about the ProClaims status meetings. Max replied, curtly:

/"They feel a bit slow."/

Alistair now looks at Max. He repeats his last three words, calmly:

/"A bit slow...?"/

And then Alistair *stops talking*.

There's a long moment of silence. Max stares at Alistair. Just as Alistair is ready to give up, Max suddenly starts speaking again:

/"Yeah. The PM's and the engineers just keep talking past each other."/

He sits back and frowns. Alistair nods and repeats the trailing words again:

/"Past each other...?"/

Again a pause. And then again Max suddenly starts talking. /"Yeah,"/ he says. He sighs unhappily. /"And I can't even blame the engineers."/

This remarkable statement almost makes Alistair break down, but he manages to stick to his plan. /"Blame the engineers...?"/

This time, there's barely any pause before Max replies. /"Yeah. I don't think the PM's even really understand the product."/

Alistair is startled to hear this statement of concern from Max. Max hasn't complained to him about the PM's even once before this. Alistair has seen Max blame the engineers, plenty of times, but up to now, Alistair had been assuming Max was on the PM's side, in all of their debates.

This is the first glimmer he gets into Max's true source of frustration and fear -- the lack of understanding on the part of the PM's.

# It shouldn't be this easy. But it totally is.

Repeating trailing words is a bizarre cheat code for talking with humans. It gets people talking, it creates space for openness and vulnerability, it helps build trust and rapport. And all in only three words.

# It gets people talking, it creates space for them to open up, it builds

# [fn:: If you happen to like romantic comedies, you might catch this *exact tactic* being referenced in episode <something> of Nobody Wants This, in the fun B storyline of the two loser siblings (look, yes, I'm low-grade obsessed with romcoms)]

# It allows you to achieve two extremely valuable outcomes:

 # - *Acquire context*

 #   Once stakeholders start talking, they almost always disclose incredibly useful information.

 # - *Build rapport*

 #   You demonstrate, simply by asking questions, that you understand and care about your stakeholder's challenges.

 # - *Discover feelings*

 #   As they talk, they will just about always reveal key underlying emotions.

# Consider putting this book down, right now, finding someone and try this out. See what happens!

# But he can also tell that Max is feeling uncharacteristically open.

# How can he build on this fragile moment of rapport?

# Below, we'll see how Alistair can usefully build on this moment of openness.

# Below, we'll see how Alistair can build on this fragile moment of rapport

# Add "I'm glad I decided to tell you."


** Some Mistakes Alistair Could Now Make

Alistair has learned something fascinating: Max is frustrated by how poorly the PM's seem to understand the product. That might well be a root cause of some of his problematic behavior.

However, Alistair is now feeling slightly unmoored. For once, Max isn't tensely checking his watch or looking at some other screen. He's genuinely with Alistair. What should Alistair do next?

# Alistair has also created a moment where Max is briefly, tentatively open.

# XXX bring this moment to life -- Alistair sees something out his window of his home office. A tree with orange leaves.

This is unknown territory. Alistair has almost no experience of powerful people being emotionally open. He's not sure what to do next.

# Below, we'll talk about what I believe to be the best thing he could do, which is to "Offer Labeled Feelings". But that takes some practice to master.

# Let's first review a series of other things he might try:

Let's talk abot some bad ideas!

*** Bad Idea 1: Offer To Help

Alistair has heard Max share a problem to solve: the lack of knowledge of the product, on the part of the PM's. Therefore, he could offer a solution:

/"We could set up some training for the PM's, I could help organize that."/

Sounds helpful, right? Max is going to really appreciate this, right?

Um, no.

Alistair is acting as if Max is *asking for help*. But that's not what Max is doing. He's (tentatively) sharing his feelings.[fn:: He's not consciously thinking "I'm sharing my feelings." He's thinking "I'm telling you about this tough situation I'm in." But he's doing so in order to be understood--which is how his conscious mind explains to him his desire to express his feelings.]

Put yourself in Max's shoes. You're trying to get someone to understand why your situation is so challenging. You've tried all the obvious things in your situation, because you are, in fact, not stupid. The person talking to you just immediately starts telling you what you should do. It's like they think you're an idiot, and they're so smart they can fix your problem that they barely took the time to even understand. *Of course* you're a bit irritated.

Jumping ahead to solutions can make your stakeholder feel like:

 1. You don't want to take the time to really understand them

 2. You think you're smarter than them

Note that these bad outcomes can happen, *even if your idea is a genuinely good one*. If you can find a way to connect and validate, it's even possible that they will then welcome exactly the idea you had to offer. But don't skip past validating their feelings.

# It will often be *enormously tempting* to do this! But it is often a genuinely terrible idea!

*** Bad Idea 2: Explain Max's Feelings To Max

Okay, so I'm saying Alistair should validate the feelings he's hearing. How might he do so?

What would happen if he *told* Max what his feelings are, ala:

/"You seem frustrated with the PM's."/

Again, put yourself in Max's shoes. You don't *like* feeling frustrated with the PM's. You're probably trying as hard as you can to manage the *objectively difficult* situation of having inexperienced PM's. So if someone says to you "You seem frustrated", it suggests that there's something wrong with *you*. The person doesn't understand the difficult situation you're in. What, are you supposed to *not* be frustrated?!

Humans really don't like someone to announce to them what their feelings are, in a way that sounds at all like they're being accused of weakness or over-emotionality.

# How much do you think Max likes being told his feelings? Right, not at all.

# *** Exit the Scene

# Alistair says "Thanks", and hang up on the zoom. He sits there, a bit uncertain about what just happened.

# This isn't a /terrible/ option.

# But it has two pretty significant downsides:

#  1. He hasn't confirmed he correctly understands Max's feelings

#  2. He missed a (rare) opportunity to build trust and rapport with Max


** Tactic: Offer Labeled Feelings

Luckily, there is a way to directly validated to your stakeholder's feelings.

The trick is to carefully go through two steps, which Chris Voss names "Labeling" emotions:

 1. Empathetically describe the situation your stakeholder is in

 2. Offer a potential "label" for their emotion, as a natural response to that situation

# XXX Fix this

# BAD WRITING GO!

By describing the situation first, you're mirroring how they experience, and you're create *justification* for their feelings.

If you do this right, you should feel like you, yourself, would feel similarly, if you were in their situation.

You then explicitly name the resulting emotion with a "label"---e.g. "frustrating", "difficult", etc. But you make this an offer by prefacing it with a careful bit of distancing, ala, "It seems like you might...", or "I could imagine that you might...".  This gives them room to correct you and keeps them in control.

How might this work for Alistair?

He tries to imagine the situation that Max perceives himself to be in. He realizes Max might feel caught between what he's expected to get done, and the challenges of having a set of PM's who don't know how to port over all the old use cases of the product. If he were in that same situation, he would likely feel frustrated.

"Huh," he says slowly, buying a bit of time. "It seems like you've been asked to lead the ProClaims rewrite, and keep all the different strands on track. But the new PM's don't know enough to lead their independent parts. So you have to stay tightly in the loop on all the different work streams. But then they complain about not being given any autonomy. I could imagine that, if I were in your shoes, I might find that pretty frustrating." He pauses, and sits, fully present and listening.

Max slowly exhales. "That's about right."

Alistair is surprised to find this moment of genuine connection with Max. And even more surprised to realize that he does feel some genuine empathy for the situation Max is in.

# /"I see,"/ Alistair manages to say. He needs time to digest this new piece of information. He wraps up by echoing back. /"Let me say that back, make sure I understand. Those meetings are feeling slow and even a bit frustrating, because the PM's don't understand the product deeply enough to have a useful conversation with the engineers. Is that mostly right?"/

# /"Yes,"/ says Max with a look of relief. /"That's exactly it."/

# Note that Quin has specified, in specific detail, what, in their current situation makes "being afraid" natural ("we can't find out if they're genuinely willing to buy").

# She's also called the overall situation "tricky", which, again makes "being afraid" a  natural response.

# Finally, when she then goes to describe his emotional reaction, she prefaces it with "It seems like you might...". She's not *telling* him his feelings, she's *offering* a potential understanding of his feelings.

When you make such an offer, it's *critical* that you preface it with an opening that creates separation between you and the statement of emotions you're about to make, e.g.:

 - "It seems like you might..."

 - "It would make sense if you were to..."

 - "I could imagine you might..."

Those prefaces allow the person to hear the statement of emotions as you *trying to understand them*, not announcing their feelings to them. Of course, those openings really only work if you can get yourself into a place of genuine curiosity, so that you truly *are* trying to understand.

# Let's review the two different ways Quin could speak to Marco's potential fear:

# Direct Question: "Are you afraid that we're not solving an important problem?"

# Labeled Offer: "We're in a tricky spot. Potential customers keep telling us that they're *interested*, but because we don't have a thing we can *sell* them yet, we can't find out if they're genuinely willing to buy. It seems like you might be afraid that we're not solving a genuinely *important* problem...?"

# On the page the two may not seem that different, but if you can do the work to lay out the situation first, and then offer that second part in a calm, curious, dispassionate tone, it has a *remarkably* powerful effect. Your stakeholder, instead of feeling *accused*, will feel *relieved*.

As Voss explains, research shows that, by naming fears out loud in this way, you can actually help people *feel* calmer. It both shows the person that it's okay to openly name the fear, and it also engages the rational, problem-solving parts of their brain.

This approach is *extremely* powerful, but it takes real practice to master, for two reasons.

First, it's not always easy to develop an empathetic understanding of the *situation* which leads to the feelings. You want to describe the situation in such a way that the resulting feeling seems *inevitable*. This is very much a learnable skill, and we'll return to it in the exercises.

Second, many of us have learned to *not* talk to other people about their feelings, especially people who seem upset or angry in any way (and especially especially if those people have some form of power). With experience, you'll find that offering labeled emotions almost always makes listeners feel *good*. Once you experience this tactic as defusing tension and anger, it won't feel so risky. But you have to build up that experience. In the exercises, we'll talk through how to practice this tactic in low-stakes situations.

# Voss describes this as learning the steps of a tea ceremony, which I love. It's precise and specific and feels alien at first. But once you master it, you'll find it supremely uesful.

# ** Tactic: Make Your Stakeholder A Beleaguered Hero


** True Connection Is Possible

I'm imagining many readers, in this moment, visualizing their very own frustrating, emotionally shut down stakeholder, and saying to themselves "Dan, are you, like *stoned*. There is no way on earth this is going to work."

Look, I get it. It may seem literally impossible to imagine that stakeholder opening up to you in any useful way. But I encourage you to study and then practice the tactical empathy skills we've been discussing. You may well find yourself astonished by how far a mix of active listening, echoing, validating and open-ended questions can get you.

I have witnessed conversations where, after a period of steady, supportive probing, a previously unavailable and tense stakeholder suddenly admitted, with true vulnerability, some of their deepest fears. I have seen the stunned looks on the faces of their team. I have seen the awareness of a common humanity fill the room---and then allow all sides to work together in a way they had previously considered impossible. Mastering these skills requires deliberate, reflective practice. But such mastery can take you much farther than you might imagine.

** What If You're Angry At Your Stakeholder?

Before we dig into the exercises, I want to talk about a feeling you may be having:

Wny are you the one who has to do this work?

Perphaps you have been struggling with your stakeholder's behavior for a long time.

Maybe they have an unpleasant habit of setting unrealistic goals and then throwing you and your team under the boss for not achieving them.

Maybe they are so unwilling to show vulnerability that they refuse to share any form of "bad news" with you. You repeatedly learn about serious external problems very late in your projects, and keep having to throw away months and months of work.

Maybe they have poor emotional boundaries, and their volatile anger undermines the fragile psychological safety of your team.

In all these cases, you may feel like your stakeholder is the one causing problems. You may be experiencing feelings of frustration, resentment, or anger. In such a situation, it may seem deeply unfair that you're the one who has to do the hard work of developing an empathetic statement of your stakeholder's situation.

First off, I want to say: you're probably /right/.

Far too few leaders take responsibility for the impact their behavior has on the people over whom they have authority.

That said, another way to understand your current situation is simply that it's one in which you don't have *control*. Putting aside questions of right or wrong, part of what is going on is that you feel, accurately, like you have little power. You feel at the mercy of this stakeholder and their behavior. That doesn't feel good.

My pitch to you is: consider doing the work to develop both tactical empathy and an empathetic statement as a *means to regain control*. Approaching your stakeholder in this new way can give you the power to get what *you* want and need.

I wish I could tell you that you're going to be able to consistently work for leaders who possess the self-knowledge and emotional maturity to avoid inflicting problems on their teams. But, sadly, that has very much not been my experience. Having a robust toolkit of ways to engage with flawed human leaders and all their marvelously specific imperfections will serve you very well throughout your career and life.

But I don't want to pretend that it's always easy to handle your own feelings as you do so.

Okay, let's talk about practicing the new skills.

** Practice Repeat Trailing Words

This one is simple enough that I recommend practicing it throughout your day.

Whenever you can, in whatever conversations you find yourself in, try repeating the last few words someone says to you, inflected as a question. Try it in both professional and personal contexts, try it with your manager, try it with your peers, with your spouse, kids, neighbors.

As you do so, be sure to:

 - Allow yourself to be in a place of genuine curiosity

 - Say only the last three or four words back

 - Wait silently for a response, even if it feels uncomfortable

Practice over and over. Take some time to reflect on how it feels, and use that reflection to tweak your personal approach.

As you build comfort, you'll find that you can go through multiple rounds of this, in a single conversation, and often get surprisingly deep. If you do find you've learned something interesting or moving, practice Echoing Back & Summarizing and Offering Labeled Feelings.

For an initial, focused period of practice to rewire yourself, aim to do this at least two to three times a day, every day for a week.

** Practice Labeling Feelings With A Friend

Because talking about feelings can feel so loaded, I recommend practicing this with a trusted friend.

First, explore a couple of different prefaces, and find one you can work with:

 - "It seems like you might feel..."

 - "It would make sense if you were to feel..."

 - "I could imagine you might feel..."

 - "It could be easy to feel..."

Choose one, and just rehearse it over and over until you can get through it, precisely word for word, without effort. Make 100% certain you're not dropping the key prefatory words (e.g. "It seems like you might...").

This is likely to feel pretty unnatural at first. That's okay. Getting the knack of inserting this preface is like learning a physical skill---it takes practice to make it smooth.

Once you've practice one specific preface, ask a friend:

"I'm working on a form of active listening. Can I try something with you?"

Tell them you're going to ask them to talk about their work. Then, ask them one of the following specific questions, which should help get into issues that have some emotions attached:

 - "Is there anything your boss does that makes your days harder?"

 - "If you could wave a magic wand, and make one of your co-workers change some specific bit of their behavior, what might it be and why?"

 - "What's the most unpleasant assignment you've been given, lately?"

 - "Has anyone made unreasonable or impossible requests of you, lately? If so, who and why?"

 - "When's the last time you were caught between what two different people were telling you to do? What happened?"

Be ready to use Repeat Trailing Words to draw them out.

Once they talk about something that seems to have any emotions attached, pause them ("Hang on, I want to make sure I understand").

Then:

 - Briefly describe their situation, using no more than a few sentences

   "Your boss keeps on asking for status meetings with you and your team. You're spending all your time preparing for those meetings, and no one can get anything done."

 - Bridge to your preface

   "It seems like you might be feeling..."

 - Then name a feeling *directly*, as an offer

   "...pretty frustrated with your boss...?"

Don't let yourself dance around or avoid saying the feeling. Put yourself in a place of curiosity and then, from that place, be *painfully* simple and direct. End your offer inflected as a question, and then *stop talking*.

Try to *not* say something like:

"I'm just wondering, maybe, you said that he kept asking for meetings, like a lot of meetings? That's not great, of course. I sometimes have had that happen. At my last job, ugh. This is for the important project, right? Maybe that, is sometimes, I don't know, maybe a bit, like, frustrating. Or maybe not, maybe it's not that bad? I know you mostly like your boss, right?"

That kind of scattered talking is the fear taking over your brain. It's telling you that the person won't want to hear their feelings out loud. The fear will desperately try to convince you to stall ("I sometimes have had that happen", "the important project, right?"). The moment say something at all direct, the fear will urge you to immediately walk it back ("Or maybe not...", "you mostly like your boss, right?").

This is why you're practicing with a friend.

You have to get yourself into that place of discomfort in speaking directly to emotions, and find a way through it.

After you've done a few rounds of this, ask your friend how it felt. Dig in specifically to whether or not they felt like you understood how they were feeling. Ask if anything you said sounded odd or pushy.

Then, try again.

Take the time to notice how *you're* feeling, in the midst of this.

** Practicing Labeling Feelings Through Situations

Pick a stakeholder who exhibits some specific, frustrating behavior.

Then, take the time to develop a description of their situation that would make their frustrating behavior an *inevitable response*.

This doesn't mean *justifying* their behavior.

It means understanding the story they're telling themselves, the way the world presents to them.

E.g. say your stakeholder is demanding progress across multiple initiatives at once, and seems angrily unwilling to consider narrowing scope.

What might be a way to describe their situation that makes this behavior an inevitable response?

 - Is *their* boss making unreasonable demands of them, and they don't feel like there's any way they can push back?

 - Did they misunderstand an earlier scoping and estimating exercise, so they're only now realizing that they have overpromised things to other people?

 - Have they experienced so many software projects as failing, they've "learned" that they need to push the engineers?

Again, developing this empathetic statement doesn't mean their behavior is *right*. It means you can see genuinely how it might *seem* right to them, given their context.

Talk this out with people you work with, see if you can learn something new about what might be driving the frustrating feelings and behavior.

** Fill Out the Four Emotions Template

Now, put all your new tactical empathy skills together to fill out the template for your stakeholder:

 - *Frustrations*

   What happens, day-to-day, that frustrates your stakeholder?

 - *Fears*

   What are they afraid might happen at some point in the future?

 - *Delights*

   What happens, day-to-day, that makes your stakeholder feel good?

 - *Dreams*

   What do they most fondly hope happens at some point in the future?

* Scraps
** Our Story: Quin Draws Marco Out

Returning to Quin and Marco, say she's been coached in this conversational tactic by her new mentor.

She starts by asking a question of Marco: "I noticed that that call seemed a little frustrating. Can I ask what was going on?"

He responds, brusquely, "It's nothing. I'd just like to advance the deal."

She feels a momentary spike of frustration. Why won't he /talk/ to her? But then she remembers the trailing three words tactic. She takes a breath to focus and then says, calmly and with as much genuine curiosity as she can muster, "Advance the deal...?"

Marco says nothing for a long moment. A silence opens up between them. Just as Quin is about to give up, Marco abruptly says, "Yeah, they just keep talking and talking." And then he sits back and frowns.

Quin tries the tactic once more. "They're talking and talking...?"

This time, there's a slightly shorter pause before Marco starts up again. "Yeah. I honestly don't know if they're *ever* going to convert. Of if they just like *talking* about their problems."

Quin finds it's now quite easy to access her curiosity, so she's able to continue to draw him out. "About their problems...?"

Marco replies quickly, there's barely a pause. "Yes. It's almost like these aren't *real* problems. We might be talking about a vitamin, not a pain-killer."

Reid Hoffman is credited with the "Vitamin versus Pain-Killer" formulation for product opportunities. "Vitamins" are nice-to-haves. Potential customers will /tell/ you they want such products, but often they're doing so because they feel like they "should". "Pain-killers", on the other hand, are products that solve pressing, painful, important problems.

Quin, who knows the vitamin/pain-killer metaphor, realizes with a start that she's turned up one of Marco's biggest fears: ATN might be building something that customers don't truly need. He has not mentioned this fear, even once, to her or the team. She's both excited and a little scared by what she's discovered. She needs some time to process it.

She wraps up the conversation. She once again repeats the last few words Marco said, but this time, instead of inflecting it as a question, she indicates agreement.

"A vitamin not a pain-killer, got it," she says, nodding her head.

"Great, thanks," says Marco. He seems, she realizes to her surprise, relieved.

Those may look like dry words on the page, but the tactic is *remarkably* effective in person. It's honestly kind of amazing that you can get so far with such a simple approach.[fn:: If you are in some form of therapy, you may realize that your therapist does a lot of this!]

If you're able to deploy this tactic well, you'll achieve two extremely valuable outcomes:

 - *First, you'll build rapport*

   You'll demonstrate, simply by listening, that you want to work *with* the stakeholder to solve their problems.

   Marco started the above conversation half shut-down, struggling with his unstated fear that ATN was pointed in the wrong direection. By the end, he has a cautious hope that Quin understands that risk, and will work with him to face it.

 - *Second, you'll acquire context*

   Quin learned that Marco has fears about how deeply customers *need* to put in place remote team-building tools. How much their teams' potential lack of connection *matters*. ATN's products might be that dreaded failure mode of startups throughtout time: a "nice to have".

Understanding that is going to be incredibly valuable, if Quin is going to ask him to change his behavior.

She now has at least one answer to a key question: what does Marco fear might happen, at some point in the future?

But she (and you!) needs more.

** Our Story: Quin Puts It All Together

Over the course of the next few days, Quin comes up with answers to the four key emotion questions.

# Quin guesses a few feelings, uses trailing three words, echoes back and summarizes, offers labeled feelings, at the end, Marco feels excited, open, energized.

*Frustrations: What happens, day-to-day, that frustrates Marco?*

Quin simply makes an educated guess. Marco clearly feels like it takes /forever/ to see progress on the product---that's why he suggested putting pressure on the team to work longer hours.

She starts to fill out the template she got from her mentor:

 - Frustrations
   - Lack of visible progress (i.e. poor velocity)
 - Fears
 - Delights
 - Dreams


*Fears: What is Marco afraid might happen at some point in the future?*

She develops a picture of two related fears.

First, in the scene above, we saw Quin draw out a key fear through Repeat Trailing Three Words and Offer Labeled Emotions: Marco is deeply afraid that, although potential customers *seem* excited about All Together Now's under-development product, they may not truly *need* it.

Second, when she dug into Marco's strategic intent for the business (where she used Echo Back & Summarize), she learned that ATN needs to see *engagement* from some of their customers, in order to generate interest from funders.

She extends the template:

 - Frustrations

   - Lack of visible progress (i.e. poor velocity)

 - Fears

   - ATN might be developing a vitamin, not a pain-killer

   - Customers might buy but not use (and that could take a long time to learn)

 - Delights

 - Dreams

Once she's developed this much of the template, she spends some time trying to put herself in Marco's shoes; in particular, she tries to imagine what it would be like to have those fears eating away at her, every day.

She realizes that, in such a situation, she might be *very* tempted to try, somewhat desperately, to make the product *more compelling*. If she had a fear that the product was maybe not that valuable, or that customers might not use it, she might feel an intense desire to add features, promise to solve more problems, and smooth away any annoyances.[fn:: These are natural feelings, but, if you're developing a new product, you should resist them. You must start by finding customers who will pay for and use your product *even though* it's painfully limited, clunky and/or ugly. If you can't find any such customers, the odds of building a real business are pretty terrible.]

If she were on a call with a potential customer, and she heard them claim they *needed* some specific feature, she might feel intense urgency to do what they asked. Rational thinking aside, adding that feature might *feel* like the only way to save ATN from a looming disaster.

She is now certain that this is part of why Marco keeps trying to jam new feature ideas into their development process.

# She realizes she can understand and empathize with these underlying fears, even if she thinks the actions they are leading to are profoundly counterproductive.

*Delights: What happens, day-to-day, that makes Marco feel good?*

Here, she again comes up with two answers.

First, she's always seen Marco absolutely light up when he has a chance to try out a new UI. On the other hand, she's also seen him glaze over when the team reports progress on modeling some key concept in the database, or adding a new data integration. Visual, interactive prototypes clearly feel more real to him, produce more delight.

Second, she spends some time thinking about the stand up meetings. From her perspective, Marco is barging in and blowing up the team's focus by forcing an instant brainstorming session about some new feature idea. She tries to put aside her frustrations for a moment and imagine the situation from Marco's perspective. In particular, what benefits is he getting, from his current behavior? What delights him? She can't initially come up with an answer that makes sense, in part because she's been finding his behavior so frustrating.

She resolve to observe more carefully next time.

Sure enough, two days later, Marco comes charging in after a customer call, all fired up about how they might integrate with TikTok. By dint of some committed deep breathing, Quin manages to observe his behavior with curiosity, instead of seething frustration.

As she does so, something clicks. She realizes that she's seeing Marco go through a familiar arc. At the start, he's swirling with excitement and ideas ("What if we hosted TikTok dance contests? We could do AI mask overlays!"). As they talk, he gradually hones in on a coherent way to summarize what he's heard ("TikTok is where the employees go for *fun*"). By the end of the brainstorming, he has condensed and clarified his own thinking, and understands some options for product ("Okay, we could either host our own TikTok-inspired videos, or we could embed links to actual TikTok. At a first cut, those have the following tradeoffs...").

She realizes that going through that arc from confusion to clarity *feels good* to Marco. Of course, the team is intensely dizzied and distracted, so he can't keep doing it. But Quin is surprised to discover she can empathize with Marco wanting to quickly talk out what he has heard from customers, while it's still fresh.

That afternoon, she extends her template further:

 - Frustrations

   - Lack of visible progress (i.e. poor velocity)

 - Fears

   - ATN might be developing a vitamin, not a pain-killer

   - Customers might buy but not use, and that will take a long time to learn

 - Delights

   - Interacting with visual prototypes

   - Clarifying his thinking immediately after customer calls

 - Dreams

*Dreams*

During a one-on-one, Quin prompts a conversation by saying, "I wanted to ask: if things go really great, everything works out even better than we could hope, what will that look like in a year or two? What's, like, a crazy optimstic best case?"

She then deploys her new tactics. She draws Marco out by repeating trailing words, she echoes back and summarizes what she hears, and, as he gradaully reveals what he dreams about, she steadily labels and validates emotions.

Quin discovers something surprising. She went in to the conversation expecting Marco to speak about customer counts or annual revenue numbers or maybe next rounds of fund raising. He does describe some of those things, be she also hears him speak, with warmth and excitement, about seeing people laughing with their colleagues. She hears him speak about the close friendships he made at his very first job, fed out of afternoon breaks at the Foosball table and lunches grabbed in the atrium of their office building. She realizes he has a deep, underlying desire to share that experience, in this new world of remote collaboration.

After that meeting, she finishes filling out her template:

 - Frustrations

   - Lack of visible progress (i.e. poor velocity)

 - Fears

   - ATN might be developing a vitamin, not a pain-killer

   - Customers might buy but not use, and that will take a long time to learn

 - Delights

   - Interacting with something visual

   - Clarifying his thinking immediately after customer calls

 - Dreams

   - Building a successful business

   - Creating genuine connections that allow people to laugh together.

Quin now has everything she needs to make a compelling offer. She can offer Marco things he wants---greater velocity, visual UX prototypes he can interact with, options to quickly learn if there are real risks around the value of their product.

When she challenges him to change his behavior, she can offer him new, less disruptive ways to work together that will still give him what he wants and needs.

She can anchor all of that in profoundly motivating long-term goals.

Her work to develop a genuinely empathetic understanding has created a foundation for effective advocacy.

In the next chapter, we'll see how she can put this all together.
** Humans Love To Be Told What They're Afraid Of, Right?

Repeat Trailing Words will help get your stakeholder talking. But we want to, specifically, understand their feelings.

In fact, we want to *ask* them about their feelings to make sure we've got it right.

Of course, just as leaders are often resistant to *showing* their emotions, they can also easily become defensive if they perceive you as, in any way, *telling them* what their emotions are.

How can you talk *directly* about emotions with your stakeholder?
** Tactic: Offer Labeled Feelings

/"I see,"/ Alistair manages to say. He needs time to digest this new piece of information. He wraps up by echoing back. /"Let me say that back, make sure I understand. Those meetings are feeling slow and even a bit frustrating, because the PM's don't understand the product deeply enough to have a useful conversation with the engineers. Is that mostly right?"/

/"Yes,"/ says Max with a look of relief. /"That's exactly it."/


For example, in our story, Quin has gained some evidence that Marco has a significant fear around the value of what they're trying to build.

Imagine Quin were to say to Marco: "Are you afraid that we're not solving an important problem?"

Although that may actually be Marco's biggest fear, there's a very good chance that, instead of agreeing, he will become defensive and push back: "It's going to be fine. We just need the team to *deliver*."

This problem is particularly tricky for the negative emotions---frustrations and fears. If you try to speak to those, your stakeholder can easily feel like you're accusing them of being weak, or too emotional. But you urgently need to understand frustrations and fears---those two have the potential to absolutely shut down any attempt you make to change.

The trick to get these negative feelings out in the open is to carefully go through two steps, which Chris Voss names "Labeling" emotions:

 1. Describe the *situation* your stakeholder is in, with empathy

 2. Offer a potential label for their emotion, as a *natural response* to that situation

For part 1, Quin might /describe/ Marco's situation as follows:

"We're in a tricky spot. Potential customers keep telling us that they're *interested*, but because we don't have a thing we can *sell* them yet, we can't find out if they're genuinely willing to buy."

She would then immediately follows that up with part 2, an offer of a labeled emotion, lightly inflected as a question:

"It seems like you might be afraid that we're not solving a genuinely *important* problem...?"

Note that Quin has specified, in specific detail, what, in their current situation makes "being afraid" natural ("we can't find out if they're genuinely willing to buy").

She's also called the overall situation "tricky", which, again makes "being afraid" a  natural response.

Finally, when she then goes to describe his emotional reaction, she prefaces it with "It seems like you might...". She's not *telling* him his feelings, she's *offering* a potential understanding of his feelings.

When you make such an offer, it's *critical* that you preface it with an opening that creates separation between you and the statement of emotions you're about to make, e.g.:

 - "It seems like you might..."

 - "It would make sense if you were to..."

 - "I could imagine you might..."

Those prefaces allow the person to hear the statement of emotions as you *trying to understand them*, not announcing their feelings to them. Of course, those openings really only work if you can get yourself into a place of genuine curiosity, so that you truly *are* trying to understand.

Let's review the two different ways Quin could speak to Marco's potential fear:

Direct Question: "Are you afraid that we're not solving an important problem?"

Labeled Offer: "We're in a tricky spot. Potential customers keep telling us that they're *interested*, but because we don't have a thing we can *sell* them yet, we can't find out if they're genuinely willing to buy. It seems like you might be afraid that we're not solving a genuinely *important* problem...?"

On the page the two may not seem that different, but if you can do the work to lay out the situation first, and then offer that second part in a calm, curious, dispassionate tone, it has a *remarkably* powerful effect. Your stakeholder, instead of feeling *accused*, will feel *relieved*.

As Voss explains, research shows that, by naming fears out loud in this way, you can actually help people *feel* calmer. It both shows the person that it's okay to openly name the fear, and it also engages the rational, problem-solving parts of their brain.

This approach is *extremely* powerful, but it takes real practice to master, for two reasons.

First, it's not always easy to develop an empathetic understanding of the *situation* which leads to the feelings. You want to describe the situation in such a way that the resulting feeling seems *inevitable*. This is very much a learnable skill, and we'll return to it in the exercises.

Second, many of us have learned to *not* talk to other people about their feelings, especially people who seem upset or angry in any way (and especially especially if those people have some form of power). With experience, you'll find that offering labeled emotions almost always makes listeners feel *good*. Once you experience this tactic as defusing tension and anger, it won't feel so risky. But you have to build up that experience. In the exercises, we'll talk through how to practice this tactic in low-stakes situations.

# ** Tactic: Make Your Stakeholder A Beleaguered Hero

* Todos
** DONE Try putting bad ideas ahead of good for repeat trailing words
CLOSED: [2025-11-25 Tue 10:35]
** TODO Move definintion of Repeat Trailing ahead of example
