:PROPERTIES:
:ID:       EC373567-8471-4ECD-864B-DF57C1170053
:END:
#+title: A Catalog Of Offer Tactics
#+filetags: :Chapter:

* A Catalog Of Offer Tactics
** Intro

To equip you to work with your very own Important Person, I'm going to share a comprehensive list of tactics, organized by the frustrating stakeholder behaviors each can help address.[fn:: Let's be clear: every one of these frustrating behaviors is a super common /human/ behavior. Which is to say, you and I will demonstrate these exact same behaviors if someone were to have the temerity to ask us to change. But that's only because we're fundamentally nice and good people and none of our behavior is every frustrating to anyone, like, /reasonable/, lalalalala I can't hear you.]

I'm going to list the full set in summary form, first. Then, in the succeeding chapters, I'll bring each tactic to life with a brief story.

-----

# For each tactic, I'll first name a problem you might run into with stakeholders, and then sketch in the corresponding action you could take.

# Below, I'm going to list all the tactics in summary form.

 - Problem: Your stakeholder is human, and is thus reluctant to commit to "permanently" changing their behavior.

   Solution: *Propose a Timebox*

   Ask your stakeholder to try out a change in their behavior for a limited period of time, with, at the end, a built-in review of how it worked for them.

   -----

   Problem: Your stakeholder is human, and thus, they resist changing their behavior because some other human asked them to.

   Solution: *Offer A Future Decision*

   Ensure that your initial, timeboxed increment of change ends with a meaningful decision that your stakeholder gets to make. This securely positions them in a high-status role where they retain control.

   -----

 - Problem: Truly improving how you work with your stakeholder requires a complex adjustment, one you can't implement all at once.

   Solution: *Shrink Your Ask*

   Propose implementing just a part of that better way to work, even if that doesn't immediately improve things for you. Build momentum, and then gradually layer in the other pieces of the solution.

   -----

 - Problem: Your stakeholder doesn't hear your concerns as valid or important.

   Solution: *Link Frustrations To Outcomes*

   With a friend, conduct a Five Whys to develop a chain of consequences that shows how your day-to-day frustrations, if left unchecked, will eventually impact a strategic outcome your stakeholder cares intensely about.

   -----

 - Problem: The connections from your current frustrations to the strategic outcome feel abstract and theoretical to your stakeholder.

   Solution: *Tell A Story Of Growing Danger*

   Use the structure of a specific kind of story to render your concerns vivid, immediate and memorable to your stakeholder.

   -----

 - Problem: Your stakeholder accepts that your frustrations matter, but they seem unwilling to do anything now.

   Solution: *Create Urgency Through Visibility*

   Make it possible to see the underlying problems, so that you can both motivate immediate action, and also make it possible to demonstrate incremental improvements.

   -----

 - Problem: Your stakeholder is not the most secure person you've ever met, and thus, a request to change their behavior makes them feel attacked, defensive and resistant.

   # This is especially true if you feel like you have to tell them that their behavior is frustrating the people around them. But, good lord, they're being really frustrating.

   Solution: *Invite Your Stakeholder To Solve Your Problems*

   Find a non-judgmental way to describe the results of their behavior as a problem for the two of you to solve together. Ask them open-ended questions that offer them a chance to be clever by solving this problem. As part of that, "play low status".

   -----

 - Problem: You can't figure out a way for your adjustment to improve things for your stakeholder, while also addressing your key frustrations.

   Solution: *Find Wins For Your Stakeholder By Hook Or By Crook*

   Find some wins for you stakeholder that you can offer, even if they're not actually necessary for your adjustment.

   -----

 - Problem: You need to ask your stakeholder to stop doing something. You're worried that they will resist, because they like doing stuff.

   Solution: *Keep 'Em Busy*

   Ask your stakeholder to start doing something new, instead of their existing behavior. Allow them to channel their energy into that new thing.

   -----

 - Problem: Your proposed adjustment might raise concerns or fears for your stakeholder, in which case they will resist making a change.

   Solution: *Address Fears Directly*

   In your request for change, first validate their fears and then speak openly and clearly to how your proposed adjustment will address them. At all costs, resist the temptation to insist that there's nothing to be afraid of.[fn:: I mean, unless you want to seriously piss off your stakeholder, I guess?]

   -----

 - Problem: Your stakeholder is reluctant to commit to your proposed adjustment, because, being human, they feel like they will have to do all the hard work.

   Solution: *Put Yourself On the Line*

   Make it easier for your stakeholder to say yes by making it clear that you will personally take on extra work, and/or personally face some hard thing.

* A Catalog Of Offer Tactics (Longer)
# The Catalog of Tactics
*** Propose a Timebox - I

*Problem*

Your stakeholder is human, and is thus reluctant to commit to "permanently" changing their behavior.

*Example*

When you say to your PM, /"During planning, even though I know time feels tight, could you please spend more time sharing context with the engineers?"/...

...they hear this as an open-ended request to change their behavior.

That feels like a risky commitment to make, so their brain whirs up into action, quickly coming up with reasons to say "no": /"we barely have enough time to get through all the tickets already"/; /"it'll take *forever* to share all that context"/; /"that one scary engineer always glares at me when planning runs long"/; etc, etc.

*Solution*

Ask your stakeholder to try out a change in their behavior for a *limited period of time*, and promise to review how it's going at the end.

/"For our *next sprint*, could I ask you to, during planning, spend some time laying out the ‘Why’ behind the epics, before we get into the detailed tickets? After the planning session, we can check in, and if it turns out we ran tight on time, I'll work with you to streamline grooming and pre-planning, before the next one."/

The PM in question may still find this a bit nervous-making to contemplate, but it's being presented as an *experiment*, not a *commitment*, so your odds are much better of getting a "yes." Also, we're mixing in a bit of Address Fears Directly, by speaking to the time pressures.

*** Offer A Future Decision

*Problem*

Your stakeholder is human, and thus, they resist changing their behavior /because someone asked them to/.

*Example*

When you say, /"I want the team go off and spend a month in heads-down exploration, without having to constantly report back on status to you and me as they go."/...

...your stakeholder, who already feels like they're struggling to keep the work on track, hears you asking them to give up even more control! How are they supposed to know what is going on?! Those status check-ins are critical! They push back.

There are, subtly, two things going on here:

 - The new pattern of interaction would *genuinely* remove some touchpoints that allowed them to direct the work in the past.

 - But also, letting *you* dictate how you will work together places your stakeholder in a "lower status" role.

Humans have a powerful cluster of mental wiring around status -- many stakeholders will actively resist taking a "lower status" role, in which you "get to tell them what to do." But... humans *also* have a powerful cluster of mental wiring that works hard to preserve a belief in their own enlightened rationality, no matter how irrational they may actually be.[fn:: Evolution has carefully tuned us for certain kinds of self-deception. I believe it's quite useful to understand this in yourself, if you have a position of authority. Steven Pinker is quite strong on this.]

Thus, your stakeholder's brain will immediately *translate* the second fear into the first, quickly coming up with lots of Perfectly Rational reasons why your idea Just Won't Work... which gives them the pleasant benefit of retaining the higher status role. Arguing *directly* against those ideas is a trap, because what your stakeholder is really doing, without realizing it, is trying to retain the higher status role.

*Solution*

Ensure that your initial, timeboxed increment of change ends with a *meaningful decision that your stakeholder gets to make.* This securely positions them in a high-status place of control.

/"I'd like to ask for the team to do a month of heads-down exploration. At the end of the month, they'll sit down with you and share everything they've learned, so *you* can decide if they’ve found something worth committing to."/

/"During the month, I'd like to let them go fast, without having to report back on status to you and me, so they can produce a really thorough overview at the end of the month. Can we spend some time aligning on what key info you'll want to see at that point, in order to make your decision?"/

Your stakeholder can now express their control and status by first, setting the decision criteria to guide the month's work, and then, at the end of the month, actually Making The Big Decision. Your asked them to change their behavior (no more status check ins), but, by giving them a meaningful decision to make, helped them feel very much in control. By setting the decision criteria, they are still clearly "in charge".

*** Shrink Your Ask

*Problem*

Truly improving how you work with your stakeholder requires a complex adjustment, and you can't see a way to implement it all at once.

*Example*

You're worried that your team is toiling long hours in the feature factory, staying super busy but barely moving the business forward at all. You know you could create hugely more value (and find your job way more fun!) if only:

 - The exec team would set high-level strategy instead of relentlessly obsessing over features

 - The product team would turn that strategy into a series of outcomes instead of writing sprawling project specs

 - The engineers could learn how to collaborate around outcomes instead of just chewing through tickets as fast as possible

That's a genuinely great way to work! I highly recommend it! But good lord, there are so many moving pieces to get right. Trying to change too much at once is a pretty much guaranteed way to fail (I say, from genuine, bitter experience!).

*Solution*

Shrink your ask to implementing just a part of that better way to work, *even if that doesn't immediately improve things for you*.

/"For the next few sprints, can we take the time to be sure the engineers understand a specific outcome each bundle of features is supposed to unlock? I want to challenge the engineers to come up with creative options for achieving outcomes, but I think we need to start by just being certain they even know what those outcomes are."/

If the PM agrees to this, you won't necessarily see much immediate improvement in value creation (the engineers may genuinely have no experience turning outcomes into options, yet). But you'll start to build momentum, and can gradually layer in other pieces of the solution.

*** Link Frustrations To Outcomes

*Problem*

Your stakeholder doesn't seem to hear your concerns as valid or important. They don't understand why "your" problems matter for the business.

*Example*

When you say, /"We need to spend time reviewing our codebase for out of date libraries."/...

... your VP of Product /hears/:

/"Please allow us to miss our next several delivery deadlines so the engineers can do something that you'll never understand, to make things theoretically better in a way you'll never be able to see."/[fn:: Aka, for you old school Far Side fans, "Blah, blah, blah, Ginger, blah, blah, blah."]

That VP of Product is thinking night and day about an ambitious strategic outcome: /Grow top-line revenue by 50% in the next two years./

It's all their CEO ever talks about! They don't have time for theoretical engineering concerns! Launching a new product asap is do or die!

They tell you, brusquely, /"Unfortunately, we don't have time to focus on anything but business priorities right now."/

You seethe. Isn't having a well-architected, reliable, safe system a frickin' business priority?!

*Solution*

With a friend, conduct a Five Whys to develop a *chain of consequences* that shows how your day-to-day frustrations, if left unchecked, will eventually impact a strategic outcome your stakeholder cares intensely about.

Q: /"Why is it a problem for the business to not know if we have out of date libraries?"/

A: /"Because we need to know if any of those libraries contain security vulnerabilities."/

Q: /"Why is it a problem for the business if we don't know if we have libraries with security vulnerabilities?"/

A: /"Because we're trying to prepare for a SOC-2 audit, and we need to show that we're executing our process for keeping our libraries up to date."/

Q: /"Why is it a problem for the business if we can't complete a SOC-2 audit?"/

A: /"Because enterprise customers are demanding we provide them with a SOC-2 report, or they're going to churn."/

Q: /"Why is it a problem for the business if some enterprise customers churn?"/

A: /"Because our strategic outcome is increasing top-line revenue by 50% in the next two years, and enterprise customers are a central part of the plan to get there."/

You need to *connect to the strategic outcome*. That links your immediate concerns to the specific thing your stakeholder is most obsessively worrying about.

*** Tell A Story Of Growing Danger

*Problem*

You've linked your current frustrations to longer-term strategic outcomes... but the connections feel abstract and theoretical to your stakeholder.

# dry and unconvincing.

*Example*

You walk through the chain above, and wrap up with, /"... and that's why we believe we should conduct a thorough library review, if we're serious about the enterprise segment."/

The head of Product nods slowly. Each individual step in your Five Whys chain makes sense. But the whole thing feels a bit... tenuous. It's a bit of reach.

Also, they've *committed* to the CEO to ship a version of the new product by the end of the quarter. And there are a dozen other things that are urgently on fire.

They say, bluffly, /"Maybe we can talk about this, what did you call it, library review after we launch the beta. But I think we need to stay heads down for this quarter."/

And then the VP of Product promptly /forgets about this entire conversation/. It felt to them like "an engineering concern". It presented as kind of abstract. Without fully realizing they've done so, they've mentally tagged it as safe to ignore for now.

*Solution*

Use the structure of a *story of growing danger* to render your concerns vivid, immediate and memorable to your stakeholder.

That particular story arc begins:

The World Is At Peace -> A Danger Emerges -> A Hero Struggles To Face The Danger -> The Danger Intensifies

You say, /"Last week, I caught up with one of the senior sales reps. She told me that, a year ago, when she closed our first enterprise customer, they didn't ask much about security." (world at peace) "But, since then, more and more deals in her pipeline are stalling out, because everyone's getting so worried about data breaches." (danger emerges)/

/"She's tried buying time by promising that we'll have a SOC-2 by early next year. She's managed to close a few deals based on that promise." (struggle to face danger) "But now, because of the pressure to get the beta live, we're running a risk of missing our SOC-2 deadlines altogether. She's *really* worried about going back to those customers if we don't get an audit completed. She told me "there's no way on earth" the sales team will hit plan next year without a clean SOC-2." (danger intensifies)/

Even if your stakeholder doesn't commit to immediately taking action, they're going to *remember* that story in a totally different way than a dry, logical chain. It will feel vivid. It will feel "real".

That structure of a Story of Growing Danger is wired into the human mind (which is why such stories can be found across all cultures). Later, we'll dig into the beats of that story arc, and show other examples of how to apply them.

*** Create Urgency Through Visibility

*Problem*

Your stakeholder accepts that your frustrations matter, but they seem unwilling to do anything *now*.

*Example*

After you tell the above story of growing danger, your VP of Product is clearly *worried*. But they're still fretting over all the other priorities, and you can't seem to get into a concrete conversation about the steps to take, right now.

*Solution*

Create visibility into the early impact of the underlying problems, so that you can both motivate immediate action, *and* to make it possible to see incremental improvement.

/"We've worked with the security team to create a series of *overall milestones* for getting to SOC-2. For the detailed work leading up to the first milestone, we've set up a *burndown* for you to review as we go. We want to devote a bit of time steadily each sprint, but you'll be able to see if we're on track, and how much work remains. If it looks like we're running a risk around our SOC-2 deadlines, you'll know early, and can decide how to balance work between security and the new product."/

/"Also, sales has agreed to start *tagging opportunities* in the Salesforce when security concerns are a potential blocker. They'll be able to run reports across the pipeline to see potential impact on the sales plan."/

Not only does the visibility help with motivation (e.g. the cost of purely focusing on the new product can now be seen in the sales pipeline), but, as importantly, you're offering them a way to see *incremental progress*. Each week, they'll be able to see the burndowns burning down That converts the security work from an abstract, "blank check" investment to a steady forward march.

This is also mixing in Offer a Future Decision, to ensure the VP of Product can stay in control over the amount of time spent on security work.

*** Invite Your Stakeholder To Solve Your Problems

*Problem*

Your stakeholder is human, and thus, your request to change their behavior makes them feel defensive and resistant. This is *especially* true if you feel like you have to tell them that their behavior is frustrating the people around them. But, good lord, they're being so frustrating.

*Example*

After your team shares updates and options with your CEO, they have this habit of holding forth about all the *other* things the team *could* be doing. Then, once everyone is good and totally confused about priorities, the CEO says, sagely, /"It's all execution now."/ Then they stand up and leave the meeting. Everyone stares at each other.

If you say, /"You're confusing everyone by talking about all the other things you're thinking about. Could you maybe... not do that?"/...

...your CEO is, sadly, likely to hear it as a personal attack. In which case their brain will instantly spring to their own defense, confidently telling them: /"You're just sharing context! What, are you supposed to *not* talk openly with your own teams?! Can't you expect engineers to understand a free-flowing discussion!?!?"/

At which point, good luck in getting them to change their behavior.

*Solution*

Find a non-judgmental way to describe the /results/ of their behavior as a problem for the two of you to solve together. Ask them open-ended questions that offer them a chance to cleverly solve this problem. As part of that, play "low status".

/"At the end of our meetings, I'm worried the team is sometimes unclear about what is most valuable or important for the business. I hate to say it, but they sometimes end up spending time on things that don't really matter. They just don't have your depth of understanding about the business as a whole. How can we make sure the team doesn't end up wasting time on things that don't matter?"/

You're asking your CEO to be an expert! But you're pointing their expertise at the very problem they're currently causing -- leaving the team totally confused after the meetings.

If you keep on asking your open-ended question over and over, odds are extremely good that your CEO will come up with the brilliant idea of making sure they end the meeting by clearly stating the top priorities for the team, and clearly stating the things the team *shouldn't* work on. You say "Wow, what a great idea." Your CEO looks forward to trying out "their idea" at the next review meeting.

We'll share more details on how to apply this incredibly useful technique later! Humans are fun! This technique totally works, even if the person kind of knows you're trying to use it![fn:: I say this having personally experienced this!]

*** Find Wins For Your Stakeholder By Hook Or By Crook

*Problem*

You can't figure out a way for your adjustment to immediately improve things for your stakeholder. Try as you might, you don't see a way to address your frustrations that benefits them in the near term.

*Example*

The Head of Customer Success constantly interrupts you to check in on the status of the various troubleshooting tickets their team has submitted. You want them to instead bring all ticket questions to a weekly status/triage meeting. The resulting increase in focus time *will* accelerate delivery of new features that Success has been begging for. But... it will take a while for any one feature to go live.

If you directly ask the Head of Success to change their behavior this way, they might resist, since there's no immediate benefit for them, and they find it genuinely useful to get those quick updates from you. Even if they do try it out, they may perceive it as something they're doing "for you". Because they feel like they're doing you a favor, they continue to directly ping you about "important" tickets. And, it turns out that almost all the Success tickets are important. Who knew?

*Solution*

Find some wins for you stakeholder that you *can* offer... even if they're not strictly necessary for your adjustment.

You've noticed that the Head of Success /loves/ telling stories about customer problems. You think it *feels good* to them, to walk people through some specific challenge a customer is having with the product. Beyond a rational desire to get certain work prioritized, you suspect that makes them feel like they're doing "everything they can" to support their customers. Which you know is a profound motivation for them.

Thus, yYou add to your proposed status/triage meeting a "Customer Story Of The Week". The Head of Success will take a few minutes to tell a full story behind one specific ticket that their team has submitted. You'll bring along one engineer to triage, and the two of you will listen carefully to that story and ask questions.

Now the Head of Success has something to look forward to, and the new meeting feels like it's "for them", as much as for you. They're giving something up, but they're getting something in return.

Note that this addition *isn't* strictly necessary for your purposes -- you'd still get the key increase in focus time without it. But, by finding a win for them, you can get them to buy in much more wholeheartedly.

*** Keep 'Em Busy

*Problem*

You need to ask your stakeholder to stop doing something. You're worried that they will resist, because they are a human being, and thus like doing things.

*Example*

When you say to your product peer, /"Could you please stop bringing detailed design mockups to the brainstorming sessions? It's shutting down any chance of generating new ideas."/...

... your product peer immediately wonders: What am I supposed to do instead? They are going to feel some resistance.

*Solution*

Ask your stakeholder to *start* doing something new, *instead* of their existing behavior. Allow them to channel their energy into that new thing.

/"Could I ask you to, for the next brainstorming session, bring a handful of different super crude mockups, and be ready to talk about the tradeoffs you imagine for each?"/

What a fun request! And it will still completely deliver what you actually need.

Other examples include:

 - "Stop talking during meeting X" -> "Please take notes during meeting X to discuss after"

 - "Stop attending meeting X altogether" -> "We'd like to ask you to attend meeting Y instead"

 - "Stop overruling all the team's decisions" -> "How about if you pick the one or two most important decisions, we can spend time aligning on those"

 - "Stop crapping all over the team during demos" -> "I'd like you to note down any and all concerns so you can discuss them with me, immediately after demo"

 - "Stop trying to personally advocate with the PM for your priorities" -> "Bring your requests to the monthly shared triage meeting for review"

 - "Stop demanding high-stakes engineering commitments to long-term estimates" -> "Ask the teams to demonstrate that they deeply understand the key business outcomes and then make sure they steadily offer options and decisions, as the work unfolds"[fn:: This one is soooooo easy. I will leave the details as an exercise for the reader.]

*** Address Fears Directly

*Problem*

Your proposed adjustment might raise concerns or fears for your stakeholder, such that they resist making a change.

*Example*

To ship a key new product this year, you want to deprioritize Enterprise support, which currently consumes a lot of engineering time. But you know the VP of Sales will worry about retention, if you do so.

You might be tempted to sweep this under the rug, by just focusing on the positive, and avoiding open conflict. But, if you say, /"We're proposing to strongly focus engineering time on the new product, because that's the core of our company strategy"/...

... your VP of Sales will hear an invitation to start /arguing/, since you don't seem to even understand the retention risk this will cause.

*Solution*

In your request for change, first /validate/ their fears and then /address them directly/.

/"We realize that pulling engineering focus away from enterprise accounts runs a risk of frustrating some important customers. We'd like to propose that the account managers identify a small handful of really key customers, and we'll commit to maintaining full engineering support for those. But we also realize this shift will make the AM's jobs harder this year."/

By validating and addressing their fears, you're inviting the VP of Sales to work with you to figure *how* to make this change work, instead of just fighting *against* it.

*** Put Yourself On the Line

*Problem*

You're worried that your stakeholder will be reluctant to commit to your proposed adjustment, because, being human, they will feel like they'll have to do all the hard work.

*Example*

You run an internal platform/ops team, and have just rolled out a self-service tool that allows developers to spin up pre-configured instances. You want to ask the VP of Engineering to use their authority to mandate that all the teams use that tool, instead of directly contacting ops engineers to build custom one-offs.

But... the VPE knows that this will be *frustrating* to their teams. /All/ of the teams are used to getting custom builds, and some may genuinely need things that your pre-configured instances don't provide. If the VPE issues this mandate, they're going to get a flurry of upset Slack messages and emails over the next few weeks, as engineers suddenly hit roadblocks just as they're trying to get something live.

# This feels to them like a lot to ask.

*Solution*

Make it easier for your stakeholder to say yes by making it clear that you will *personally* take on extra work, and/or personally face some hard thing.

If humans see someone putting themselves on the line to face a difficult or risky challenge, they become much more willing to listen to requests from the person to help.[fn:: This is a big part of what we mean when we talk about someone having "moral authority".]

# Whereas, if a human is asked to do something that they perceive as risky or hard, but the person doing the asking doesn't seem to be taking any personal risks, or shouldering any of the new burdens created, that creates resentment and resistance.

In this case, you could say, /"I know this is going to have some shaky moments early on. My team will set up and monitor a dedicated slack channel for any problems. I'm going to personally clear my calendar for the next three weeks, so I can be as responsive as possible during the initial rollout. Also, if it's okay with you, I want to give the team leads my cell number, and encourage them to call or text me if they hit something tricky or time-sensitive. Finally, if it's okay with you, I'd like to lead a Q&A immediately after you announce this change, so I can hear about any concerns or frustrations."/

This makes clear that you are signing up for "unpleasant" parts of the work -- getting called at all hours, bearing the direct brunt of unhappiness from the team, etc.

* Scraps
** Intro With Lots of Bolding

To equip you to work with your very own Important Person, I'm going to share a sprawling smorgasbord of *tactics*. Which I will helpfully organize by *frustrating stakeholder behaviors*.[fn:: Let's be clear: every one of these frustrating behaviors is a super common /human/ behavior. Which is to say, you and I will demonstrate these exact same behaviors if someone were to have the temerity to ask *us* to change. But that's only because we're fundamentally nice and good people and none of our behavior is every frustrating to anyone, like, /reasonable/, lalalalala I can't hear you.]

I'm going to list the full set in summary form, first. Then, in the succeeding chapters, I'll bring each tactic to life with a brief story.

-----

# For each tactic, I'll first name a problem you might run into with stakeholders, and then sketch in the corresponding action you could take.

# Below, I'm going to list all the tactics in summary form.

 - Problem: *Your stakeholder is human*, and is thus reluctant to commit to *"permanently"* changing their behavior.

   Solution: *Propose a Timebox*

   Ask your stakeholder to try out a change in their behavior for a *limited period of time*, with, at the end, a built-in review of how it worked *for them*.

   -----

   Problem: *Your stakeholder is human*, and thus, they will resist changing their behavior *because some other human* asked them to.

   Solution: *Offer A Future Decision*

   Ensure that your initial, timeboxed increment of change ends with a *meaningful decision* that your *stakeholder* gets to make. This securely positions them in a *high-status role* where they *retain control*.

   -----

 - Problem: *Truly* improving how you work with your stakeholder requires a *complex adjustment*, one you *can't* implement all at once.

   Solution: *Shrink Your Ask*

   Propose implementing just *a part* of that better way to work, even if that *doesn't* immediately improve things for you. Build *momentum*, and then gradually layer in the other pieces of the solution.

   -----

 - Problem: Your stakeholder doesn't hear your concerns as *valid* or *important*.

   Solution: *Link Frustrations To Outcomes*

   With a friend, conduct a Five Whys to develop a *chain of consequences* that shows how your day-to-day frustrations, if left unchecked, will eventually impact a *strategic outcome* your stakeholder *cares intensely about*.

   -----

 - Problem: The connections from your current frustrations to the strategic outcome feel *abstract and theoretical* to your stakeholder.

   Solution: *Tell A Story Of Growing Danger*

   Use the structure of a specific kind of story to render your concerns *vivid*, *immediate* and *memorable* to your stakeholder.

   -----

 - Problem: Your stakeholder accepts that your frustrations *matter*, but they seem unwilling to do anything *now*.

   Solution: *Create Urgency Through Visibility*

   Make it possible to *see* the underlying problems, so that you can both motivate *immediate action*, and also make it possible to demonstrate *incremental improvements*.

   -----

 - Problem: Your stakeholder *is not the most secure person you've ever met*, and thus, a request to change their behavior makes them feel *attacked*, *defensive* and *resistant*.

   # This is especially true if you feel like you have to tell them that their behavior is *frustrating the people around them*. But, good lord, they're being really frustrating.

   Solution: *Invite Your Stakeholder To Solve Your Problems*

   Find a non-judgmental way to describe the *results* of their behavior as a problem for the two of you to *solve together*. Ask them *open-ended questions* that offer them a chance to be *clever* by solving this problem. As part of that, *"play low status"*.

   -----

 - Problem: You can't figure out a way for your adjustment to improve things *for your stakeholder*, while also addressing *your* key frustrations.

   Solution: *Find Wins For Your Stakeholder By Hook Or By Crook*

   Find *some wins* for you stakeholder that you *can* offer, even if they're not *actually necessary* for your adjustment.

   -----

 - Problem: You need to ask your stakeholder to *stop doing something*. You're worried that they will resist, because they *like doing stuff*.

   Solution: *Keep 'Em Busy*

   Ask your stakeholder to *start* doing something *new*, instead of their existing behavior. Allow them to *channel their energy* into that new thing.

   -----

 - Problem: Your proposed adjustment might raise *concerns* or *fears* for your stakeholder, in which case they will *resist* making a change.

   Solution: *Address Fears Directly*

   In your request for change, first *validate* their fears and then speak *openly* and *clearly* to how your proposed adjustment will address them. *At all costs*, resist the temptation to insist that there's *nothing to be afraid of*.[fn:: I mean, unless you want to seriously piss off your stakeholder, I guess?]

   -----

 - Problem: Your stakeholder is *reluctant* to commit to your proposed adjustment, because, being human, they feel like *they* will have to do *all the hard work*.

   Solution: *Put Yourself On the Line*

   Make it easier for your stakeholder to say *yes* by making it clear that you will personally take on *extra work*, and/or personally face *some hard thing*.

* Todos
** TODO In Mark Blevins story, make him push back, once
** TODO Count # of prod vs eng stories
** TODO Clean up Kahneman ref
** TODO For Growing Danger, make stakeholder the friend/mentor
** TODO Add: invoke a better world?
Like, it's not just at risk, it's possible.
** TODO Possibly: move Work Backwards into Define Strat Intent
