:PROPERTIES:
:ID:       95635819-413C-4C43-8A86-20C2DAD4ED43
:END:
#+title: Be Surprised Early
#+filetags: :Chapter:
* How To Create Value From Early Surprises

# How To Be Surprised Early

# How To Be Usefully Surprised Early

# How To Be Valuably Surprised Early

# How to win with early surprises

# The be surprised early game plan

# Turn surprises into decisions into value

# Early Surprises And The Incremental Creation Of Value

# Early Surprises Create Incremental Value

# Be Surprised Early To Create Incremental Value
** Order Increments By Degree Of Potential Surprise

Engineers can't reliably estimate how long it will take them to build things. But they *can* usefully speak to the comparative degree of uncertainty in the various bits they need to build. They know certain things are "hard but fairly certain" -- it will take two months, but at the end of two months, or, like, maybe three, you'll have the thing. Whereas others are profoundly uncertain: it could take two weeks, it could take two months, it could be impossible.

And if, early on, *everything is uncertain*, then you can make your first increment to build a little bit of "everything", specifically with a goal of learning where your biggest risks are.

Throughout the book, we'll explore a wide variety of ways for engineers and product managers to work together to, first, identify the riskiest parts of an effort, and second, to sequence their work to extract any surprises as early as possible.


** Use Future Decisions To Define Incremental Milestones

# Define Incremental Milestones Around Future Decisions

As a reminder, the entire reason we want to encounter our nasty surprises /early/ is so that the business as a whole can /adapt/, while there's still time to do so.

Your team launches a major effort to build Product A, but, the moment you start, you discover that it's going to take at least five years to build, not the five months you had initially estimated. You're so glad you figured that out right away! You can now quickly work with the broader business to pivot to building Product B instead.

In other words, an early surprise creates value if, /and only if/, your business as a whole changes their plans.

Which, a great deal of the time, will mean your stakeholder changing their plans.

# Easy, right?

"But, Dan," I can hear you thinking, "in my experience stakeholders really, really don't like changing their plans? Am I supposed to tell my stakeholders to just be cool, or something? This whole idea seems kind of dead on arrival?"

# If all engineers could say to their Important People was "Look, we can't really make plans, you'll just have to be ready to be unpleasantly surprised, at any moment," well, then those Important People would pretty justified in saying "I think I need some new engineers."

Look, your concerns are totally valid. Just shoving uncertainty into your stakeholders face isn't going to help either your business or your career. If you're going to have to ask them to be ready to change their plans, it'd be really good if you could offer them /something/ in return.

Do you know what most stakeholders love?

*Making decisions*.

Thus, instead of a fixed plan and a (false) statement of certainty, you can offer your stakeholder a *meaningful future decision*.

In fact, you can define your entire first increment to *enable your stakeholder to make an important decision*. You create a specific milestone, with a specific future date attached, where your stakeholder will get to make that decision.

This is actually surprisingly straightforward! After all, you selected some specific first increment because it allowed you to test for some specific unpleasant surprise. Therefore you can also identify the specific /decision/ that will have to be made, if you /are/ surprised.

For example: when your team tries to build Product A, and you start by tackling that nasty data integration, you're doing so /because/ you might have to decide to pivot from A to B, if the data integration turns out to be a real bear.

Although the effort to build the integration is unknown, the decision you would have to make is very much knowable.

So you define your end-of-increment milestone in terms of that decision. You tell both the stakeholder and the team that the first increment of work will take *exactly* four weeks, and the objective is:

"In order for <insert stakeholder name> to decide if we should continue to try to build A, or should instead pivot to B, the team will share a report on what data they'll be able to actually extract from our key data integration."

You're promising the stakeholder that, at a *specific* moment in the future, they will get to make a decision.

You're not saying "We can't make a plan, sorry!". You're saying "Here's a key thing we need to learn in order to empower you."

and, before you get started, you have an explicit conversation about *what evidence* they will need to make their decision.

(This is a Decision Story, like, a User Story, which we'll return to later)


** Gradually Draw Stakeholders Into Repeated Decision-Making
And that stakeholder is going to resist. They're going to *want* to make a single "big" decision up front -- "Do I fund this project or not?" Unfortunately, that simply does not work.

To create valuable software, "the business" will have to make a series of business decisions, as the team builds and learns.


* Old Structure
** The Answer, I: Design Increments To Create Early Surprises

# The Answer, I: Be Surprised Early

Although it's impossible to eliminate nasty surprises from software development, it is very much possible to make those surprises *less expensive*.

In other words, you prevent disasters not by preventing surprises, but instead by breaking the link between "surprise" and "economic disaster".

But, how is this even possible?

A team can turn surprises into non-events if they can:

*Design the increments so that the team is surprised /early/, instead of late.*

In our story above, everything would have been fine if the very first thing the team tried to build was the troublesome component. Although they didn't know up front how bad it was going to be, they would have figured that out as they went to actually build it.

# Specifically, let's say that, after three weeks of work, they realized that their whole plan was going to be impossible.

Let's get more specific. The reason the troublesome component blew up was because it turned out that it had been spec'd out with an assumption that it would be able to access a key bit of information about the user... but that information turned out to not be reliably available. The system had it for some users, but not for others. To "fix" this, they'd have to rewrite a complex data ingestion process (which their team doesn't own, nor know how to work with), to obtain and attach this bit of information about each user. And that would only work if the upstream data sources even *had* this information, which they might not.

But, a good bit of the sizzle of the new feature depended on being able to tune it to the user's needs, based on that bit of data.

In this case, they would likely have been pretty frustrated, but, once they reported this back to the PM, they could have worked with the PM to figure out a different product offering. Maybe it would be a bit less sexy, but the PM, being good at their job, is able to find a new way to solve user's underlying problem.

# They would have immediately realized how hard it was going to be, and could have immediately rethought the overall product offering.

The team could still have shipped something super valuable by Q2.

# (though, see below re: the flexibility they'd need to be able to do this).

# The senior non-technical stakeholder might not have been thrilled by this shift, but if the team were still able to ship something by Q2 which customers loved, that stakeholder would have quickly forgotten they ever asked for anything different.

# This is, fundamentally, our plan.

# They would still have been /surprised/ by just how bad that component turned out to be.

# But instead of being a disaster, that surprise would merely have been *valuable information*.

In other words, you don't try to get rid of all surprises before you start. You still assume you'll hit some potentially very nasty surprises /during the actual project/. But, thanks to a clever way of designing increments, you're able to /start/ by building the things which are mostly likely to blow up. This vastly increase the odds of hitting the nastiest surprises /early/.

And, if a team encounters a surprise early enough, *it's not a disaster*. Early on the team still has good options to offer the rest of the business (even if, sometimes, that option is "Abandon this entire project, because it's no longer economically rational").

# And, believe it or not, clever increment design will allow you to reliably flush out surprises early.

# You can't /eliminate/ all surprises before a project starts, but you *can* design your increments so that you attack the riskiest, most uncertain work *first*. This gives you an excellent chance of hitting your surprises early enough to still be able to adapt and find some win for the business.

# You can't eliminate all surprises before a project starts, but you *can* sequence your work so that you attack the riskiest, most uncertain work *first*. This gives you an excellent chance of hitting your surprises early enough to still be able to adapt and find some win for the business.

** How Our Friends Could Have Been Surprised Early

What would that have looked like, in our example above? Well, at the moment when the team had broken down their set of components, they could have sat down, and gone through each one, and, instead of simply estimating how long they believe it would take them to build it, they could have asked each other:

"How likely is this particular component going to be to blow up?"

Perhaps they would hit some (build a new front-end), which are going to take real amounts of time, but which are unlikely to explode in scope. But maybe others are much less certain, at the start. E.g. perhaps one of the components involves building an integration with a third-party data source that the team hasn't worked with. They tell the PM "That should take a month, but we really don't know. We're pretty worried about it."

In the original plan, they had put that very late, because they wanted (being good agilista's) to build something which they should show to users, so they had just faked out the third party data integrations, in order to get something working and demoable sooner. It was also clearly going to be a pain in the ass, and they wanted to build momentum.

Instead, they could have realized that that one component had the most uncertainty, the most risk, and designed their incrementsto build that component *first*.

In that world, just a few weeks into the project, they would have hit the profound challenges of integrating with that third-party data source, and realized that they couldn't build the product they were envisioning.

Engineers can't, in general, reliably estimate how long it will take them to build things. But they *can* usefully speak to the degree of risk and uncertainty in building things. They know certain things are "hard but fairly certain" -- it will take two months, but at the end of two months, you'll have the thing. Whereas others are profoundly uncertain: it could take two weeks, it could take two months, it could be impossible.

And if, early on, *everything is uncertain*, then you can make your first increment to build a little bit of "everything", specifically with a goal of learning where your biggest risks are.


# In our example above, when starting the project, the engineers could have said "Which of these components is the most uncertain? Which one is most likely to blow up?" That's a very productive conversation. If they had then built the "risky" component first, they would have discovered, just a month into the project, that their plans were going to have to change. The PM would have been able to renegotiate with the senior non-technical stakeholder, when they still had a lot of good options to offer.

Throughout the book, we'll explore a wide variety of ways for engineers and product managers to work together to, first, identify the riskiest parts of an effort, and second, to sequence their work to extract any surprises as early as possible.


# Early Surprises Create Options

# The Answer, II: Make Decisions More Often

** The Answer, II: Define Milestones Around Decisions

# Ask The Business To Make Business Decisions

# The Answer, II: Offer Decisions To "The Business"

Obtaining the information from early surprises is not, by itself, enough.

You also have to *draw your stakeholder into a process of repeated decision-making*.

When we hit a surprise early, we create value by enabling the business to make a new decision: based on what we just learned, what is *now* the most valuable thing the enginers can do?

# do for the business?

And, crucially: /The engineers and the PM can't make that decision on their own./

The senior non-technical stakeholder above will have to be a part of it. They're going to *want* to make a single "big" decision up front -- "Do I fund this project or not?" Unfortunately, that simply does not work.

To create valuable software, "the business" will have to make a series of business decisions, as the team builds and learns.

Thus, a core part of the increment design is to work backwards from the *decision you're going to ask an Important Person to make*.

Our friends above, when confronted with the demand for a commitment to Q2, could have defined their first increment around:

 - The senior non-technical stakeholder will review a few different possible prototypes, each of which we're fairly confident we can build, in order to decide what the overall shape of the product offering should be.

That's a *concrete goal*.

** The First Key Decision For Our Friends

# Surprises Are Decisions For "The Business"

# Options are ...
# "The Business" Makes The Decisions

** The Answer, III: Draw Stakeholders Into Repeated Decision-Making

# The Answer, II: Offer "The Business" Decisions

# The Answer, II: Make Smaller, More Frequent Decisions

# The Answer, Part II: Enable Smaller, More Frequent /Decisions/


# The Answer, Part II: Make Smaller Decisions More Often

# The Answer, Part II: Make Smaller Decisions As You Go

# The Answer, Part II: Make Decisions As You Go

# The Answer, Part II: Build Your Plan Around Decisions

# The Answer, Part II: Work Backward From Decisions

# The Answer, Part II: Plan To Make Decisions

** How They Charmed Ben
** A Map Of The Rest Of This Book
# The Answer, Part II: Smaller, Better, More Frequent /Decisions/

# The Answer, Part II: Subdivide Your Decisions

# The Answer, Part II: Offer Repeated Decisions

# The Answer, Part II: Offer Cadenced Decisions

# The Answer, Part II: Offer A Series Of Decisions

# The Answer, Part II: Make A Series Of Decisions
* Scraps
