:PROPERTIES:
:ID:       D2D9959D-3491-456B-89A0-E5ED5517E0BB
:END:
#+title: The Profound Value Of Increment Design
#+filetags: :Chapter:
* The Profound Value Of Increment Design

# Help Us, Good Increment Design, You're Our Only Hope
** Doing Agile But Not Feeling Agile

# What Is The Sound Of One Agile Hand Clapping?

Sometimes, in the middle of a dark wood, an engineer or a product manager will find themselves on a team that is *doing* Agile, but that somehow doesn't *feel* agile in any way.

# Switch all to "you" in the below?

The team observes all the agile rituals, and observes them faithfully and well. Their sprints are a crisp two weeks long. Each starts on a Monday morning with a full team planning session. During planning, the product manager patiently explains the nuances of the various stories and tickets at hand. Each morning at precisely 9:05 am, the team gathers for a stand up. As they work, the engineers steadily pull well-groomed tickets from the board. On the final Friday of each sprint, the engineers demo what they've built, and then the team runs a brief retro in the afternoon.

All that is as it should be, right?

In theory, yes.

But, in practice, there's a problem.

Somehow, the overall project is drifting totally out of control.

The team is far, far behind where they are supposed to be. They missed their first delivery deadline so badly that they had to negotiate a three month extension. They then promptly consumed all that time without any positive result. Every lingering problem the engineers tackle immediately sprouts three new problems, hydra-like. The PM is losing sleep, and wakes each morning from anxious dreams about their next update to the executive team. The engineers have grown defeatist and bitter. Every day they're asked to pile new expedient hacks on top of yesterday's expedient hacks, resulting in a system that is both more and more difficult to change, and also somewhat terrifyingly unstable. The engineers and the PM's have a growing suspicion that when they finally *do* ship the flaky, limited, badly compromised system, literally everyone will be angry at them.

This is, in fact, precisely what will happen.

# This is a team that is "doing waterfall with agile methods". Somehow, despite successfully applying agile *tactics*, they're still gaining the pretty nasty outcomes of waterfall.

How did this team get here?

How can you avoid getting to a similar place in the future?

Most of all, why didn't "doing agile" save them? Note: I am a /huge/ believer in agile as a way to organize the work of a team. But, unfortunately, agile tactics, as commonly practiced, are not enough. They are, in the precise terminology of mathematics, *necessary but not sufficient*.

To see the moment when things started to go off the rails, let's rewind to the start of the project.

** A Sadly Typical Exercise In Increment Design

At the time, the team was working closely with a senior non-technical stakeholder. That stakeholder, after a good bit of back and forth, grudgingly conceded to the project being run "via Agile", instead of the way, well, every other project they'd ever supervised had been run: with a task breakdown, and a schedule, and a PMO to ensure everyone stays on track.

Why did the stakeholder agree to this? Because the engineers and product team were so confidently  *dismissive* of the way the stakeholder *wanted* to run the project. The tech team derisively called the stakeholder's desired approach "Waterfall". The stakeholder didn't really understand any alternatives, but within their first five minutes of being even *near* software development, they had learned that "Waterfall" is Very Bad. They didn't want to look stupid, so they agreed to try this vague thing that everyone assured them was their only option.

# because otherwise the engineers would have actually quit.

But, in return, that stakeholder extracted a concession of their own: a commitment to complete the project by Q2 of the following year.

At the time, Q2 was a full nine months away. The engineers didn't love making this kind of long-term commitment, but they believed they had no choice but to give the business *some* kind of promise. They looked over the high-level Product Requirements Docs from the product team and said "It looks like we should be able to finish by Q2. I mean, if there are no horrible surprises."

The product team said "Of course, we understand." They even made a good-faith attempt to share that caveat with the senior non-technical stakeholder. But, surprisingly approximately no one, that stakeholder neither understood nor accepted the caveat. Instead, after meeting with the product team, they immediately turned around and told The Rest Of The Business, /"The engineering team has committed to an April 3rd launch."/

The Rest Of The Business said /"Great, thanks,"/ and started basing all their own plans on that date. (Where did April 3rd come from, you ask? Simple: it was the very first business day of Q2.)

What happened next?

The engineers sat down and broke the work down into increments.

That is to say, they decided what they would build first, what they would build second, etc. The product team wasn't closely involved in the development of the increments---they considered themselves a consumer of, rather than a direct participant in, this "engineering process".

The eng team, led by one of the senior IC's, developed their increments as follows: first, they broke the planned system down into a set of components; then they ordered the development of those components in a way that felt natural to them. The choice of order didn't feel particularly high stakes to them---no matter the order, they'd ultimately have to build all the pieces.

Once the engineers had the increments, they estimated each, then the product team turned all of that into a schedule with milestones and dates. Everyone then worked together to cut scope, to ensure there was a comfortable four weeks of padding at the end of the project, in case anything went wrong.

And then the engineers got to work, in their (well-observed!) agile process.

# Clean up tenses in the below

** Some Disasters The Team Could Now Experience

# icebergs

Unfortunately, in this moment, the team is (probabalistically) doomed.

They have chosen their overall increments arbitrarily and poorly. Even if they now run their agile processes well, sprint-to-sprint, they are running a simply gigantic risk of at some point finding themselves trapped, with no good options.

Part of what makes this so tricky is that there isn't just one potential disaster waiting for them. No, there are a variety of different ways such a project might fail.

To bring this to life, here are three different ways this team might run into an iceberg of disaster, and find themselves scrambling for lifeboats in the icy waters of the North Atlantic. Note, these are not the *only* three ways things could blow up unpleasantly.

First, one of the components could turn out to be impossible to build as the engineers had planned.

What happens in that case?

The absence of that component triggers a ripple effect through the rest of the system, requiring enormous amount of rework and ultimately forcing a rethinking of what the product is able to do. Unfortunately, the team chose to work on that component *late* in their sequence. By the time they make this unfortunate discovery, their original launch date is only four weeks away. There are no good options to adapt and still deliver something valuable anywhere close to the plan. They realize that they have to start an essentially entirely new project, moments before the original project was supposed to conclude.

This has wrecked many a project I've been on or near.

But sometimes, the engineers get extremely lucky, and are able to build all the new stuff they hoped, in more or less the time planned.

But then, they might hit a different disaster.

Second, it might turn out that customers don't truly need the thing the team just spent nine months building. They need something "close"... but much, much harder to build.

This can happen even if the product team does good, thorough user research ahead of time. Even if the PM's talked in detail with multiple customers, identified a real problem to solve, validated a willingness to pay, you name it. Even if the team showed customers detailed mockups, which they enthusiastically praised.

Unfortunately, once the engineers finally built a working version that was able to import and display the customer's own data for their review, the team discovered that the customers had been assuming all along that the data would be extraordinarly *fresh*. Specifically, for customers to successfully use the new product, all the screens of elegantly designed reports will have to include *yesterday's data*. The PM's were thunderstruck when they heard this. The team has never had access to daily data. It took a shocking amount of work to ingest weekly aggregations.

Because the team didn't discover this until late in the project, they don't have much in the way of good options. They start scrambling to decide if they should pivot to a fundamentally different value prop, or if they can somehow find and integrate with a daily data source. Either approach will take many, many months to execute on. Meanwhile, their original deadlines come and go.

But, wait, there's more!

A third fun way for such a project to run aground is because the engineers find themselves completely overwhelmed with *other work*. Their existing systems are being used by thousands of users, every day. Those systems are, of course, a bit buggy around the edges, but they seem to be chugging along in some kind of non-ideal but reasonably steady state. Sure, the engineers are constantly complaining about tech debt, and that one engineer who used to be a DBA keeps on talking about lock timeouts, but those are constant background noises of an engineering team, and the PM, like PM's everywhere, treats those as feeling to assauge, not critical inputs into planning. But then, mid-way through the new project, all the pigeons came home to roost. The help desk is overwhelmed with customer complaints about site load times, and the team starts finding half-completed transactions littering their logs. When they igs in, they discover that there's some horrifyingly complex contention for the main database, and there's no clean way to solve it without some months-long effort.

Because they only discover this once the project has been underway for months, they're unable to negotiate a sane tradeoff. "You commited to Q2", says their stakeholder.

I'm sketching in versions of three core problems:

 - We don't know how long it will take to do things

 - We don't know if the things we want to do are *worth doing*

 - We don't know if we'll have time to spend on the things we want to do

# Of course, missing plan isn't an uncommon occurrence. Why does this particular miss leave the team in such bad shape?

** Good Increments Create Incremental Value

How might the team have conducted their work differently to avoid this painfully unpleasant outcome?

Well, one easy answer is: the engineers /should have known/ that the component would be impossible to build as spec'ed. This answer is so easy, people come up with it all the time! But, unfortunately, it's not a very *useful* answer (except for making people feel bad, at which it excels). Any engineer who has worked for almost any amount of time can cite dozens of personal experiences of painful surprises blowing their plans up. If your only hope for creating value is for your engineers to /never be unpleasantly surprised/, well, then, good luck to you, is all I can say.

How might the engineers and PM's have somehow conducted their work so as to avoid the horrible discoveries, late in the project? What did they miss?

# The answer is somewhat subtle.

This book will offer an answer, based on my own several decades of trying to avoid such painful discoveries while, first, being paid to write software for people, and then, as my career went on, leading teams of extremely expensive engineers being paid to write software for people.

The heart of my answer is: the engineers and the PM did not engage their stakeholders in any discussion around the increments.

Instead, they treated the increments as an internal concern of engineering. Therefore, none of the intermediate increments delivered anything that their stakeholders found at all valuable. There was no point, before the very end of the project that the team could have decided, *with* their stakeholders, to take some form of a partial win, and move on.

One way to understand all of the above is that the team did not choose their sequence of work to *create incremental value*.

Despite the team working in an agile fashion day-to-day, the company as a whole only seemed to see *any* value at the very end of the project.

If a team creates incremental value, then, well, they can *never really lose*. There's no panicked anxiety looming over them, because they can always stop, and the Rest Of The Business will be some degree of happy---because they will have gotten *some* value. The Rest of the Business may not get everything they *expected*, but if the team can create some genuine value, a smart PM and engineering lead can find a way to help the rest of the business understand the win.

One note: drawing stakeholders into collaboration around valuable increments is a profoundly interesting challenge. We'll return to that challenge, once we have an understanding of which increments are even valuable in the first place. The concept of "creating value" will turn out to be well worth digging into.

** Creating Value Is A Suprisingly Subtle Concept

Now, if you're reading this you may be thinking: "Obviously, they should have built incrementally. They should have shipped working code, earlier."

Unfortunately, it's not that easy.

Plenty of engineers and product managers have developed some kind of heuristic sense of good increment design. Which, like most heuristics, works sometimes and fails horriby at others. Let me list a couple of approaches I've seen (and employed!) for designing increments which, although *sometimes* useful, are sometimes disastrously unuseful.

 - Build a high-quality implementation of a small part of the product

 - Build a super scrappy version of the entire product

 - Build an entirely fake version of the product to show to users

 - Build the external integrations

 - Build the internal logic

 - Build the backend

 - Build the frontend

 - Assemble the data

 - Design the overall component breakdown

 - Build a single small thing and grow it outward

Note that, for just about all of the above, a team would be "shipping working code". But those are profoundly different increments.

And that doesn't even mention all the other work that should be mixed in, to ultimately create maximum value for the business, e.g."

 - Speed up the development cycle

 - Address performance issues

 - Improve system stability

 - Address security concerns

 - Clean up legacy code



** This Skill Changed My Life And I Want It To Change Yours

Over the course of my career, I've come to believe that increment design is one of the most valuable skills engineers and product managers can develop.

# Over the course of my career, I've come to believe it's impossible for an engineer or product manager to be truly effective at their job unless they go deep on increment design.

# I further believe, that, for a business to create value by building new software, the design of increments must be a collaborative conversation among engineers, product managers, and stakeholders.

# For one simple reason: a "good" increment is one which *creates incremental value* for the business as a whole. But, for reasons we'll go into in great detail, engineers fundamentally *can't* determine value on their own.

Furthermore, it's physically impossible to fully determine the best value-creating increments ahead of time, and then just hand them to the engineering team to chew through, one after another.

No, for a business to generate value from a large software effort, the business as a whole must steadily *make decisions* as the work unfolds. There must be a given and take, as information is acquired, new increments are selected, and the ramfications filter through to the business as a whole.

# Breaking up a large system into distinct components is another fundamental skill, but it's a distinct from increment design. Component design is a bit like decomposing across *space*. Increment design is decomposing across *time*. And, since time only flows in one direction, it brings its own interesting, tricky challenges. Furthermore, there are lots of books about how to break large pieces of software into sane components -- some of them are even good! But I have really not run across that many about how to break the development of software down into a series of safe, value-generating steps.

# In fact, implicit in a lot of the book on architectural component design is a vague sense that building one component at a time, or possibly separate teams building separate components, is a natural and correct way to then incrementally construct a large system. Sure... sometimes. But very much not always.

# In fact, implicit in a lot of the book on architectural component design is a vague sense that the desired behavior of the program is a *known thing*. Like, the problem is "Given that the program must to this exact complex thing, how should we structure it". Which is far, far from the truth, for almost any meaningful piece of software development in the real world.[fn:: I should say: on rare occasion, you'll find an extremely precisely specified but extremely challenging problem to solve, e.g. improve render or compile times. But, man, there just isn't much of that work.]

# that building one component at a time, or possibly separate teams building separate components, is a natural and correct way to then incrementally construct a large system. Sure... sometimes. But very much not always.

To understand why, over the course of the book, we'll develop a nuanced understanding of how engineering work does (or does *not*) create value for an overall business. We'll discover how some increments can, despite requiring a great deal of engineering effort, somehow create *no value whatsoever*. We'll also find how other increments, including ones where the engineers write very little code, can somehow create a great deal of value.

This understanding of value will ultimately give us tools to break large efforts into small pieces, and will *also* offer creative ways to mix in increments of value-generating work to address a wide variety of concerns, e.g. being able to deploy more frequently; ensuring a system can handle increases in load; meeting security expectations; etc.

# This theoretical foundation will give you a powerful way to reason about your work. With practice (and some further tactics, to be explored in subsequent posts), it will allow you to find a path through the shifting chaos of reality to a valuable outcome for your business.

# When I talk with engineers or product managers at tech companies, just about universally, their teams are using some form of agile to organize their day-to-day work. They have sprint teams, those teams do daily stand ups, they work in iterations of a few weeks, with some form of planning at the start of each.

# In a sense, the alternative to agile (Waterfall, natch), has "lost"

* Other sections
** Increments Are A Decision We Make Over And Over

# The Perils of Bad Increment Design

This book is a deep dive into how to break up a large body of software engineering work into a series of small, safe, value-generating steps.

# Now, this challenge, of decomposing a large problem into smaller pieces, is, in the case of *software* projects, made just enormously difficult for one simple reason:

# Now, this challenge, of decomposing a large problem into smaller pieces, crops up over and over, in an extremely wide variety of domains.

# In fact, being skilled at this decomposition is one of the key ways we recognize a "senior" engineer, again in wide variety of domains.

# However, in the case of *software* projects, this challenge is made just enormously more difficult for one simple reason:

The challenge of decomposing a large body of software engineering work is made specifically difficult thanks to one simple reason:

# , which I, like, strongly suspect you already know:

# extremely, fascinatingly,

# *It's impossible to define all the steps before you start the work*.

For software projects, *it's impossible to define all the steps before you start*.

This is so widely accepted that engineers and product managers will dismiss the "define all the steps first" approach with a casual, patronizing, "Ugh, you're asking us to do /Waterfall/."

# And everyone will understand what they mean.

# The heart of the much-damned "waterfall" approach is to carefully define all the steps ahead of time, and to then hold a team accountable to executing on those steps as planned.

# That approach fails so reliably that many engineers and product managers will fight tooth and nail against it, purely in their own self-interest. As in, they are so certain the results will be a disaster (specifically, a disaster for which they will be blamed), that they'll push extremely hard for a different way of working, even to the point of risking getting fired.

But, if Waterfall is "bad", what's the alternative?

# Well, if you can't define all the steps ahead of time, you *have* to make some sort of an initial plan, but then be ready to *redefine that plan as you go*.

# That's it. There is no other choice.

To successfully build a large, valuable piece of software, you apparently have to start by *somehow* selecting one specific chunk of work, executing on that chunk, and only then choosing your next chunk.

In other words, you have to not only *build* incrementally, you also have to *plan* incrementally.[fn:: Many failed projects think they are being incremental, but they map out all their steps ahead of time and then attempt to march through them, one small, ahead-of-time defined step at a time. This works so reliably badly that I have personally run multiple project post-mortems for dramatically failed projects, which post-mortems all had the same fundamental learning: the team somehow ended up running a Waterfall project, even though they thought they were doing agile.]

Thus, because the steps can't all be defined ahead of time, the core act of working incrementally is /deciding what to do next/.

The fundamental thesis of this book is that deciding what to do next is an incredibly high-leverage act.

That act is best understood not as merely selecting from some set of fairly obvious alternatives, but as confronting a moment of intense challenge, requiring creative engineering and product management effort to overcome. Good increments aren't merely chosen, they are *designed*. In fact, I believe that increment design is among the most critical, valuable skills that engineers and product managers can develop.

# Selecting the next increment of work, based on what has been both built and learned up to this moment, is an incredibly highly levereage activity.

# Over the course of my career, I've come to believe it's impossible for an engineer or product manager to be truly effective at their job unless they go deep on increment design.

# I further believe, that, for a business to create value by building new software, the design of increments must be a collaborative conversation among engineers, product managers, and stakeholders.

# For one simple reason: a "good" increment is one which *creates incremental value* for the business as a whole. But, for reasons we'll go into in great detail, engineers fundamentally *can't* determine value on their own.

Why is good increment design so valuable?

# A teacher of mine once said, "The beauty of something is made clear by its absence."

Well, to answer that, let's flip it around.

What is life like, on a team that suffers from poor, haphazard increment design?

My guess is that you, dear reader, may have actually experienced this first hand.

# Let's see what that feels like.

** Intended Audience + Three Core Problems Solved
It's intended audience includes individual software engineers and product managers, leaders of both engineering and product teams, and a variety of curious non-technical stakeholders, who would like to understand how to improve their painfully broken relationships with their tech counterparts.

Believe it or not, good increment design holds the key to:

 - How engineers can consistently develop valuable software...

   ...even though they can't reliably estimate how long it will take them to do, well, almost anything.

 - How product teams can rapidly hone in on software that customers adore (and will happily pay for!)...

   ...even though the users are utterly incapable of describing what they need, the engineers can't tell you they'll actually be able to build, and the sales team wants to control every interaction with the buyer.

 - How engineers and product teams can work together to build valuable software atop hideously complex legacy systems...

   ...even though no one understands how those systems work and a massive outage may be just waiting in the wings to crush your dreams.


** My background a bit / live without fear

It represents what I have spent several decades learning, about how to, well, *live without fear*.

Early in my career as a programmer, as I steadily earned my way into positions of greater responsibility, I found that I was repeatedly asked to estimate how long it would take to code up various programs. I gradually discovered to my horror that, for work stretching out for more than a week or two, my estimates were just hideously [profoundly] unreliable [inaccuate]. I would promise to complete a project in two months (after scoping it out to take no more than four weeks and padding for safety). My business counterparts would put various wheels in motion based on that commitment. Two months would come and go, the project would drag endlessly on. I felt like a failure.

Even once I came to understand that all programmers struggle to make usefully accurate estimates, I wasn't much happier. What was I supposed to offer my business partners?




And then I came to realize that *everyone* is horrible at making such estimates.

It focuses on

Where, because you're developing *software*...

...it's impossible fully define all the steps ahead of time.

This is such a universally accepted truth of software development that, if someone attempts to plan a multi-month chunk of work by spending weeks precisely defining and scoping the various incremental steps involved, they will find themselves *laughed at*. The phrase "waterfall" will be invoked, and that will apparently end the conversation.

In other words, building software by attempting
** Intro - I Feel Your Pain

Developing software for a business would be delightfully easy if only the following three things were true:

 1. The engineers knew how long it would take them to build a piece of software

 2. The rest of the business actually knew what software they needed

 3. There was no existing software to maintain, extend and curse at

 # 1. The engineers knew how long it would take to build specified products, features or tools

 # 2. The rest of the business knew how valuable those various products, features or tools would actually be, as specified

 # 3. There were no existing systems to maintain, extend and curse at

But here in reality, estimates are unreliable, specifications are painfully wrong-headed, and legacy systems are lurking and waiting to crush everything you love.

lurking in the wings, laughing. waiting for their moment to crush you.

those three things are (checks notes), *essentially never true*.

Engineers can't make accurate estimates of the time to deliver a software system of just about any meaningful complexity.

The rest of the business, despite their professions of certainty, is routinely so misguided in their beliefs that entire new products, features or tools are just completely thrown away after being built.

# , because they create so little value for their businesses.


And, of course, most of the businesses that have the money to pay engineers, product managers and designers, have that money because someone in the past built some piece of software which people are now paying for, and which has to be considered as anything new is built, and that existing software has become encrusted with fragile special cases and opaque logic and endless amounts of confusing, subtly incorrect data.

** Intro: Bring Three Problems To Life As Learning Arc for an engineer

This book is a deep dive into how to break up a large body of engineering work into a series of smaller, safe, value-generating steps.

# In other words, how to design (and redesign) the increments of delivery.

# This book is a deep dive into how to design effective *increments* for developing software.

# By "increments" I simply mean: how to break up a large body of engineering work into a series of smaller steps.

#

When you're young, and first learning to code, this seems straightforward. You're asked to write a program, you think out a few different ways to break down its overall structure, you pick one of those ways, and then you build the various components in some order.

And that more or less works.

As you work on steadily larger programs, you learn some key lessons -- e.g. wire the components together early and often, to flush out any confusion around interfaces. Write automated testing so you can safely restructure the system as you go. Use abstraction to capture repeated patterns. Then, after you excitedly overuse abstraction and create extremely difficult-to-change systems, learn to employ abstraction judiciously.[fn:: I find a hallmark of truly experienced engineers is a willingness to cut and paste, like, a *bunch* of times, until they're certain they *fully* understand the pattern they want to pull out.]

But, there's a problem.

These skills, though extremely useful, turn out to be insufficient to enable you to develop valuable software for a business.

Why?

I'll offer three reasons.

First off, when you work in a business, Some Important Person will demand that, before you start coding, you tell them *how long* it's going to take to write your program.

After some *very* painful experiences, you realize that you can't answer this question in any meaningful way.

As part of onboarding at Ellevation, I would talk to a roomful of new hires, across both tech and non-tech roles. I would have an open-ended conversation about software development. At one point, I would say, "Sometimes, engineers tell you a project will take nine months." And, every single time, anyone with real experience in developing software -- engineers, product managers, designers -- would all do the same exact thing. They'd *laugh*. The rest of the room would look confused. What literally everyone has learned is that, when engineers tell you something will take nine months, you can not base any meaningful decisions on that estimate. And yet, business do, believe it or not, need to make some plans stretching out nine months into the future.

This thing called Agile is supposed to help, but once you scale up to either more than a single team or to a project that stretches out past a few months, it's somewhat profoundly unclear how to apply agile. Sadly, teams at the the median software company I meet are using agile for their day-to-day processes, but all the tickets and sprints are embedded in some giant, slow-moving project with fixed deadlines and little in the way of feedback. I can't tell you how many project post-mortems I've run which had the same learning: we somehow ended up running a Waterfall project, even though we thought we were doing agile.

Your options seem to be to either:

 a) Commit to long-term deadlines you're fundamentally uncertain about, and then spend your working hours in a state of ever-growing fear as you realize how impossible it will be to achieve what you've promised.

 b) Refuse to give your business partners what they insist they need, thereby poisoning your relationships with them and likely preventing your own advancement at your job.

So, problem one is: even though Everyone Knows how hard it is to estimate software projects that stretch out past a few months... when working to create valuable software, you'llk constantly be asked to make long-term commitments.

So, problem one is: in order for you to create value by writing software, your business seems to believe that you need to accurately estimate how long it will take. Which is, sadly, impossible.

[snippet]

Second, you have this repeated, extremely painful experience where you work hard, pulling long nights, pushing the people around you, making truly painful tradeoff choices in your code... and then, after you finally ship, the business shitcans [throws away] all your work. They show your new product to customers, who promptly throw up all over it. You attempt to roll out your new workflow software to your call centers, but there's a riot from the users. You attempt to connect your new data integration with a partner business, but it turns out that partner business has, like, hundreds of higher priorities than working with you, and after a painful year of trying to get them to answer your emails, you just archive all your work.

Again, you seem to have two equally unpleasant options:

 a) Not My Problem! Put your head down, write lots of code, focus on some notion of "quality", and completely disassociate from any hope of creating value or solving meaningful problems. Assume a stance of cynical bitterness as your code rots away unused. Watch your career go kind of nowhere because you never seem to ship anything impactful.

 b) Fight, Fight, Fight! Spend all your time just constantly arguing with your Important Person, until you find that you've got this new job, called Product Manager, and now *you're* expected to extract commitments and estimates from the engineers, and they seem to think you've become an Unreasonable Important Person, and ugh.

So, problem two is: despite Your Important Person's messianic self-confidence, they will frequently ask you to write software which it turns out creates no value whatsoever.

# this presents as straightforward

Finally, the third problem is... legacy code. Although your Important Person is obsessively focused on new features, new products, and new capabilities, you discover that you're also responsible for existing systems. If you ignore the latent problems, they have every chance of blowing up and, either thanks to constant fire-fighting, or thanks to an apocalyptic amount of work to evolve existing systems, it's now impossible for you to deliver the thing you're being held accountable for.

What are your options?

 a) Just pile more on top of the unstable foundation, and hope that the inevitable disaster arrives when you've moved on to another project, company, or career. Give up on any hope of building quality software that you can be proud of.

 b) Insist on rewriting the existing system to clean it up. This sounds like a great idea until you convince some credulous Important Person to let you do it, and then you find yourself on the horrifying death treadmill of the Grand Rewrite. You leave that job before the rewrite finishes.

 c) Argue constantly about technical debt. But, because the resulting improvements are invisible to your Important Person, you put your own advancement at risk, and incur a bad reputation.

So problem three is that, you have this incredibly strong feeling that there is important value in the long-term health of the systems engineering is responsible for. But no one seems to care about that value but you.

# Nothing could be further from the truth.

** All Three Are Same Problem

I'll offer something provocative.

Viewed from the right angle, these are all the same problem.

Specifically, all three of are concerned with the same question: what next increment of work will *create value* for the business? Or, correspondingly, which increment of work will destroy value for the business?

The business is, believe it or not, demanding estimates because they are trying to make a decision: what work should they ask you to do? What should they do, to take advantage of the work you're going to create?




* Notes From Walk <2026-01-04 Sun>
Okay, so definitely reuse the stuff that I did from the workshop and break it up and think about the thing of thinking about Satoy as sort of a model and then think about starting the product plan more wrong.

Maybe it's like a general sort of tracker of expenses and they ended up honing in on that.

The MRI machines and then they ended up discovering that the real question is not how they've been used, but when to buy a new one.

And they kind of revealed the product around that.

See if we can escalate from "we have the data, but what can we actually do with it" to which then ends up limiting the fields they have and then presenting the spreadsheet to actually understand the decisions getting made and then actually building the product with the sales team.

Think about kind of at each step hitting each step different stakeholder decision, kind of person and reference out the challenges drawing that person in and sort of forward reference that.

* Bad Ideas for Their Business

** Loyalty Program Management

** Paper Goods Supply Chain

** EMR For Dentists

** Lighting Equipment Rental

** Costume Rentals

** Coffee Roaster Software

** Ski Rentals

** Daycare Application Software

** Daycare Test Prep Software

** Perishables Supply Chain

** AI Dental Arts

** AI-Provided Therapy

** Applicant Tracking Systems

** Grocery Store Management Software

** Political Campaign Software

** Sand & Gravel Delivery

** Dispatch Software - 911?

** Math Practice Software

** Hotel Vacancy Filler

** Night Manager Support

** Policing Tools

** Political Protest Organizing

** Middle School Play Support

** Meditation Support

** Massage App Support

** Snow Removal Software

** Municipal Support

* From Substack/Other
# The Art of Increment Design, Part I: Help Us, Good Increments, You're Our Only Hope
# Only Good Increments Can Save Us Now
** Sadly, Blind Adherence To One Approach Will Not Save You
*** Intro
Someone might read the above parable and think: "Ugh, Dan, that team made an /obvious/ mistake. Teams should /always/ build an end-to-end solution first, and then gradually expand outward from that. That's the True Agile approach. If they had done that, they would never have gotten stuck in such a pit."

Unfortunately, that approach, though sometimes effective... can *still fail spectacularly*.

I have seen projects go horribly off the rails even though the team started by building an end-to-end prototype and immediately sharing it with users. Those teams discovered, very late in their work, that they couldn't actually deliver even vaguely what that prototype had promised (because, say, they had badly misunderstood what data was available to them, or delayed facing some profound technical challenge or risk).

# a constraint deep in the guts of a key data source).

There isn't one true sequence for building complex software.

Designing good increments requires an understanding of how teams create value, and a good deal of creative effort to apply that understanding to a specific situation.

# Designing good increments requires creative effort---and then, continual effort to redesign, as the work unfolds.

Consider the following approaches. Teams are, possibly implicitly, considering something like this list when selecting their next incremental chunk of work. Individual engineers or PM's might advocate for something on this list as the One True Way to decompose a software project into smaller pieces:

 - Build something limited-but-real that satisfies a subset of customers with a subset of planned functionality

 - Build an interactive-but-fake prototype of the complete set of planned functionality

 - Build a single back-end component in full, rigorous depth

 - Build lightweight versions of all the back-end components, and wire them all together

 - Don't build anything, but instead do a deep dive into a key data source

Here's the thing: in different situations, each of those could be the exactly right next increment, *or* the exactly wrong one.

Because each can either *create incremental value* for the overall business, or can completely *fail to create value* for the overall business.

And, remember, increments that don't create incremental value are super dangerous. A succession of such increments will leave a team in a very bad place. Every increment of work must create an increment of value.

Let's dig into how each of the above could or could not be valuable.

*** Build something limited-but-real that satisfies a subset of customers with a subset of planned functionality

Creates Value If:

 - That subset of customers is representative of the full set of customers

 - The subset of functionality is compelling enough for those initial customers to actually use it to solve problems they care about

 - The team can build the useful subset significantly faster than they can build the full product

Does Not Create Value If:

 - The subset of customers has completely different needs than the rest of the customer base, so a product that satisfies them can not be expanded to serve all customers.

 - The limitations in functionality mean customers can't use it to actually solve their problems.

   Massive risk in this case: customers tell you how great the limited product /looks/, and they'll /absolutely/ use it once you've added just a few more features. You feel like you're making tremendous progress, but, once you address the remaining "blockers", it turns out the customers just wanted you to not feel bad and were lying to you, and none of them are willing to use or pay for what you've built (see The Mom Test for how to handle customers cheerfully lying to you in this exact way).

 - The limited subset rests atop an iceberg of technical complexity below the surface, so getting it working requires 90% of the time and effort of the full project.

   Massive risk in this case: the product team names that limited subset the "MVP", but it's more than a few months to build it... so the engineering team drifts into the "build the technical components in some random order" plan described above, with all its attendant dangers.[fn:: The term "MVP" has, sadly, lost just about all ability to function as a useful piece of product development discourse. Far too often it becomes "What bundle of features does a stakeholder insist a customer will want." Rather than fight over a better definition of MVP (e.g. "The next hypothesis to test"), I've had better luck just leaving the term MVP fully on the side of the road, and focusing on building a shared understanding of other terms.]

*** Build an interactive-but-fake prototype of the complete set of planned functionality

Creates Value If:

 - The engineering team is confident in their ability to build the complete set of functionality

 - It's hard or impossible for customers to imagine how the product even could solve their problems

   Customers are universally terrible at imagining software that they can't interact with. If the team can allow them to interact with something where they can successfully imagine using it to solve their problems, the team can achieve one of two outcomes, *each of which* is valuable:

   a) Customers not only get excited about the product, they start talking in detail about *how* they would use it to solve their problems, they talk about what they are currently doing to try to solve those problems, they beg to show it to other people they work with, etc.

   Value = Great, you've gotten validation + a partner for incrementally testing out your solution as you go.

   Or,

   b) Customers demonstrate *none* of the above evidence of commitment.

   Value = Great, you've learned that you shouldn't waste time building that full set of planned functionality.

   This latter result is *super valuable*! It creates the opportunity for the team to build *something else* that customers will pay for, when there's still plenty of time to do so. (We'll dig into this form of value creation throughout this series)

Does Not Create Value If:

 - The product has the nature where interacting with a fake prototype isn't enough for customers to imagine using it to solve their problems

   A classic example of this is when the product involves aggregating some complex set of the customer's own data. Showing such customers a slick-looking visualization tool on top of /fake/ data often fails to engage the part of their brain that is worrying about their problems. Which means you fall back into the risk of them trying to make you feel good by "being nice".[fn:: Fun fact: the best early increment in this case is often a *spreadsheet*, into which you've painstakingly hand-collected that customer's *own data*, and can then see what they do with it.]

 - The engineering team isn't certain they can build all the functionality

   If, by building a cool looking prototype, you learned that customers would happily pay for some Magic Solution, but your engineering team knew all along that they can't build the Magic Solution (because, y'know, *magic*), you've wasted a bunch of time, and have to start over, no with less time. This kind of "learning" does not create value.

*** Build a single back-end component in full, rigorous depth

Creates Value If:

 - The engineering team has real fears about whether or not they even *can* build that back-end component

 - The absence (or shape) of that back-end component has a major impact on the design of the overall product

Does Not Create Value If:

 - It might take a while to build that back-end component, but there's no question about whether or not it's *possible* (aka, It's "hard but not risky")

 - The absence of that back-end component would only change the ultimate product design in a fairly minor way

*** Build lightweight versions of all the back-end components, and wire them all together

Creates Value If:

 - There a lot of engineers working on this effort, and the company wants subsets of them to work in parallel on different parts of the overall system

 - The engineering team, at project start, has broad-based concerns about if/how they can tie all the pieces together

   E.g. maybe the system depends on threading some key pieces of data through the various components, but the team isn't certain where that data is available. Or some are system decomposition questions will have a major impact on the design of the product (e.g. maybe the team fears that some key step in the user workflow will have be completed asynchronously).

   One way to say the above is: there isn't something that can be shown to users that the team is confident they can build.

Does Not Create Value If:

 - It's going to take a while to build all those components, and it's not clear if customers care about the *problem* the product tries to solve.

 - All the risks and questions are concentrated in one component

   E.g. if your team is trying to build some form of domain-specific AI assistant, there's a good chance all you should be focused on is "Can we get that assistant to usefully answer questions about that domain?", and not string together all the other bits of a full solution (e.g. automatic ingestion of relevant customer context, a smooth UI to offer answers, etc).

*** Don't build anything, but instead do a deep dive into a key data source

Creates Value If:

 - The presence, absence or shape of the available data will have a major impact on what product you can build

Does Not Create Value If:

 - The team knows the data inside and out already

** Outro

# For many experienced engineers and product managers, various situations above will, hopefully, feel familiar, and the "good" options may even feel kind of "obvious".

What is the pattern behind all of above?

How can you reason about your exact situation, and be certain you're picking a good increment?

My answer is: be sure your team is creating incremental value as you go.

To do this, you will be very well-served by having a first principles understanding of how value creation works during the development of software.

That understanding will allow you to design the increments for even very large software efforts such that you can offer your business counterparts both steadily visible *progress*, and more importantly, a steady series of options for when to *stop* and still realize value.

Now that we've established *why* good increment design is so important, in the next post we're going to dig into *how* engineering teams can create incremental value.

In closing, I'll offer a teaser for what's to come:

An engineering team can create incremental *value* for their company, even if they're *not* shipping software that is incrementally more *useful* to any users.

"...what?" I hear you thinking.

Shipping useful software is *not* the only way engineers create value for a business.

"...but doesn't the Agile Manifesto say working software is the measure of progress?" I hear you continue to think.

# "Working software is the primary measure of progress.", and it's Principles Behind the Manifesto

The Agile Manifesto is legitimately and enduringly great.

But they got this one wrong.


# The engineers had, of course, complained that the product team hadn't sufficiently defined the product for them to give a good estimate. But they always made that complaint.

# The product team complained (to each other, over drinks), that the engineers weren't willing to stand behind their commitments.
* Todos
** TODO Speak to challenges, early
 - Stakeholders don't want to work this way
 - It's not clear what increments create value
 - It's hard to set goals for good increments
 - No one person can do this on their own
** Maybe: other ways project could fail
 - Customers were wrong about desires or needs shift
 - Legacy system blew up
** TODO Find my exercises
** TODO Review those exercises
** TODO Copy and paste in a big chunk
