:PROPERTIES:
:ID:       95635819-413C-4C43-8A86-20C2DAD4ED43
:END:
#+title: Be Surprised Early
#+filetags: :Chapter:
* How To Win With Early Surprises
# How To Create Value From Early Surprises

# How To Be Surprised Early

# How To Be Usefully Surprised Early

# How To Be Valuably Surprised Early

# How to win with early surprises

# The be surprised early game plan

# Turn surprises into decisions into value

# Early Surprises And The Incremental Creation Of Value

# Early Surprises Create Incremental Value

# Be Surprised Early To Create Incremental Value
** Intro

To review: if you're trying to create valuable software, you win by uncovering unpleasant surprises as early as possible. You then share those surprises with your business counterparts, so that, together, you can decide what to do next. You don't do this just once as a project starts. Instead, you continuously seek surprises as you build. This allows you to steadily offer meaningful decisions to your business counterparts, so that, together, you're able to gradually hone in on something that is extremely valuable to your business.

In this chapter, we'll explore three key facets of this approach:

 1. *Order increments by degree of potential surprise*

    Instead of asking the engineers to *only* estimate how long it will take to accomplish various sub-tasks of an overall effort, you *also* work with them to identify which of those sub-tasks have the greatest potential to blow up the project.

    You then start by building the things which are most likely to generate the worst surprises.

 2. *Use future decisions to define your milestones*

    Once you've decided what to build first, you create your first milestone by identifying a future decision that your stakeholder will get to make, once the initial increment is complete. Although you /can't/ know ahead of time if things will blow up or not, you /can/ define the decision you'll have to make if you hit a snag.

    The team can then explicitly work backwards from supporting the stakeholder in making that future decision.

    #  (which will allow them to find creative tradeoffs to stay on track).

    # By focusing on a decision you create clarity for your stakeholder, while also ensuring flexibility for the team.

 3. *Gradually draw stakeholders into repeated decision-making*

    Unfortunately, many stakeholders will initially be resistant to making decisions throughout the life of a project. They'll pressure you to offer them a single big decision up front, in the guise of asking for a "commitment".

    Instead of front-loading an economics lecture about the value of information (which I can tell you from personal experience, super does not work), you'll start by identifying and clearly sharing *one* key decision. Then, as you start building, you can gather evidence to support your stakeholder in making that one key decision. Having done so, you then frame the next decision, gather more evidence as you continue to build, and repeat.

    # Over time, you will gradually draw your stakeholder into making a sequence of decisions with you, which they will come to experience as /empowering/.

    Over time, you will gradually draw your stakeholder into a collaborative decision-making relationship, which they will come to experience as /empowering/.

Let's dig in.

** Order Increments By Degree Of Potential Surprise

Although, engineers can't reliably estimate how long it will take them to build things, they *can* usefully speak to the comparative degree of uncertainty in their various estimates.

They know certain estimates are "relatively certain": they'll tell you it'll take two months to build something, and, although they won't be surprised if it takes three, the odds are genuinely minuscule of it taking two years.

They'll also know that other estimates are far more uncertain: they'll say some work should take two months, but, as they say that, they'll be worrying that, if the dice land wrong, it could easily take a full year. They'll also worry that, given what they currently know, it could simply turn out to be impossible.

In other words, although engineers can't know for certain if they /will/ be surprised, they /can/ very usefully talk about which parts of the planned work are mostly likely to yield the worst surprises.

Thus, you can sit down with a team of engineers, present a high-level picture of a desired piece of software, and ask them to do three things:

 - Break out a set of distinct pieces they'll need to build

 - Develop a very rough estimate of how long each piece will take

 - Identify the two or three pieces that have the greatest possibility of blowing up in painful ways

There's a good bit of art to this, that we'll return to in later chapters. E.g. what if your biggest potential surprise is whether or not the overall system can handle the full fury of production load? What "part" of the system is that? There are lovely answers to this question, that we'll return to in case studies later.

But can you almost always get a ton of value by simply taking your current project breakdowns, and engaging in an explicit conversation around the risks of each sub-estimate blowing up.

One nice way to do this is to run a "pre-mortem". You build an understanding of what needs to be done, and then say to a team of engineers: "Okay, this all sounds good. But I want to imagine, it's six months from now, and something has driven this project horribly off course. What has gone wrong? What might cause this all to fail?" Then spend a while (playfully!) brainstorming unpleasant surprises together. Once you have a list, work together to priority sort it by the product of "likeliness to happen" and "badness if it does happen". The top of that priority-sorted list represents your shared understanding of "the biggest risks", aka, the places you all fear unpleasant surprises are most likely to lurk.

You then set your first increment as building something that will steer right into the biggest risks. Usually, that means, starting by building the components the engineers are most "worried about". Again, there's interesting art to this! It may feel impossible to build those things in that sequence. There are clever ways to do this as well, by leaning on our second key idea: working backwards from supporting a decision.

# You're not asking engineers to build a perfect, fully functioning component, somehow isolated and hanging in space. You're asking them to build "just enough" of that component to understand if it's going to blow up or not. To create /evidence/. Given that charge, engineers can come up with very creative ways to build components in oddball sequences.

** Use Future Decisions To Define Incremental Milestones

# Define Incremental Milestones Around Future Decisions

Having selected your first increment, you're now going to create a meaningful /outcome/ for that increment, which you'll both use to create clarity with the engineers, /and/ to bootstrap your collaboration with your stakeholder.

# This will be something your stakeholder cares about *and* that your engineers will be happy to be held accountable to.

# Instead of a fixed plan and a (false) statement of certainty, you can offer your stakeholder a *meaningful future decision*.

Specifically, you'll define the outcome for your first increment as:

*Enabling your stakeholder to make a specific, important decision, at some specific date in the future.*

Let's explore this idea by way of an example.

Teresita Carlotta Torres is the tech lead for a team of engineers at OrthoMedica, a SaaS business that sells clinical support software to sports medicine practices. One day, her Product Manager, Alina, informs Teresita that company leadership wants them to build an Exciting New Feature. Alina shares a high-level understanding of the feature (which has to do with a slick automation of several steps in patient intake), and asks Teresita "Do you think we can get that done in the next six months?"

"I don't know," says Teresita, "let me talk to the team."

The next day, Teresita sits down with the other engineers and, together, they map out the various things they'll need to build. Then, they come up with an estimate: if everything goes right, it should take something like six to nine months.

Instead of immediately sharing this estimate with Alina, Teresita now leads a pre-mortem conversation. She invokes an imagined future where everything has gone wrong, and uses that to surface risks, concerns and questions. Surprisingly quickly, all the engineers agree that there's one central risk: building the Exciting New Feature as planned will require obtaining a new bit of data from patients' insurance companies. The engineers are genuinely uncertain how many insurance companies actually track and share that piece of data. They fear there might be some very nasty surprises lurking in that part of their plan.

That afternoon, Teresita shares this central concern with Alina, and, together, they define the milestone for their first increment as:

 - In order for Alina to decide whether or not to build the Exciting New Feature as planned

 - she will, in four weeks time, be able to review a summary of how often OrthoMedica can obtain the key data at time of intake.

Creating this milestone forced an early conversation with Alina about both the key future decision to make /and/ about what evidence she'll need to make it. Teresita had to explain enough about how the key data could impact their plans for Alina to be able to cleanly define the evidence she'd want to review. That also allows Alina to start thinking, now, about how she might adjust the product design if the dice land wrong. Note that, by picking out a top risk, Teresita was able to choose a single thing to go deep on with Alina. There are a dozen other nuanced technical questions that she /doesn't/ bring up, at this point.

Once this milestone is set, what will the team do? Well, the next day, the engineers start building exploratory bits of new ingestion logic. Two weeks in, one of the engineers finds a creatively scrappy way to run their new logic across multiple insurance companies, even the ones for whom they don't yet have production-quality connections. Throughout the month, they're talking continually with Alina, to make sure they're honing in on a "summary" that is genuinely useful to her.

Note that what they're doing isn't just research. They're genuinely /starting to build/ the Exciting New Feature. The exploratory ingestion coding is work that would need to get done at some point, they're just doing it /first/.

Four weeks in, they sit down with Alina and go through all the nuances of what they've found. She asks dozens of questions, because she's been able to educate herself on this data field and its ramifications for the overall product design. It turns out that the data is /not/ consistently available, so they won't be able to build the feature as planned. But Alina now has a backup plan prepared -- they can, even if they can't fully automate these intake steps, still streamline them considerably, by collecting data from patients ahead of time.

But... how has Alina managed the leadership team during this month? They wanted a commitment for their annual planning. What did she tell them? We'll turn to that in our next section.

Before we move on, we'll note two things.

First, if the team hadn't run the pre-mortem, they would have made this discovery much later, and the resulting nasty surprise would have sunk the project. Specifically, before the pre-mortem, Alina had been planning on asking the team to build the front-end first, so she could demo it to both users and leadership.

Second, setting milestones around decisions offers an extremely powerful tool for staying on track. Imagine that four weeks in, the team still didn't know whether or not they could consistently get the new data. Here's the thing: /someone would still need to make the "pivot or continue" decision./ The team will gather as much evidence as they can, and then sit down with Aina to decide what to do next. The team *can* reliably commit to supporting that decision, on a precise future date. They may not have as much evidence as they hoped, but they can still offer Alina a meaningful decision -- even if one of the arms of that decision is now "Continue to learn more."

# Thus, instead of saying "We can't make a plan, sorry!", you're saying "In order to empower you, we need to acquire a key piece of evidence, and here's the exact time you'll see some evidence."

** Gradually Draw Stakeholders Into Repeated Decision-Making

Eagerly seeking surprises and defining milestones around future decisions are powerful ways to unlock incremental decision making for your business---which is at the heart of creating value in the face of uncertainty.

But... many stakeholders will resist working this way. They want, often intensely, to make a single, big decision up front -- "Do I fund this project or not?" -- instead of steadily making decisions as the work unfolds.

What should you do?

Well, luckily, having conducted extensive experiments, and can tell you one thing to /not/ do: have a big theoretical argument up front.

Instead, your best bet is to:

 - Probe for the underlying reason they want to run your project

 - Signal your commitment to accomplishing that underlying thing

 - Clearly articulate the first key decision

 - Run your first increment

 - Offer them the decision

 - Now articulate the next key decision, and loop back

Eventually, they'll be ready to explicitly join you in talking about key risks, surprises, and hypotheses. Because they will have experienced that way of working as *empowering* them. In later chapters we'll dig into the steps above.

** Preview Of Coming Attractions

Hello, Beta Reading Person, Dan here.

First off, thanks so much for making it through to the end (or to jumping ahead to this moment out of curiosity!).

Second off, a request and an offer.

The request:

It's crazy valuable for me to hear first-hand about your reading experience. Thus, if you're interested, I'd love to hop on a brief zoom call with you to talk it out.

The offer:

As a sweetener for the deal, I'd be happy to spend a good chunk of that call brainstorming with you about how to apply the ideas of the book to your exact circumstances. I love doing that kind of collaborative thinking (and it helps me understand how well the ideas have landed, etc).

(Also, by all reports, I'm very nice)

If such a call sounds potentially valuable to you, please feel free to drop me an email at dan@dan-milstein.com. Just mention that you finished the beta of The Art of Increment Design and would be interested in discussing how to apply the ideas from the book.

Thanks,

-Dan


* Old Structure
** The Answer, I: Design Increments To Create Early Surprises

# The Answer, I: Be Surprised Early

Although it's impossible to eliminate nasty surprises from software development, it is very much possible to make those surprises *less expensive*.

In other words, you prevent disasters not by preventing surprises, but instead by breaking the link between "surprise" and "economic disaster".

But, how is this even possible?

A team can turn surprises into non-events if they can:

*Design the increments so that the team is surprised /early/, instead of late.*

In our story above, everything would have been fine if the very first thing the team tried to build was the troublesome component. Although they didn't know up front how bad it was going to be, they would have figured that out as they went to actually build it.

# Specifically, let's say that, after three weeks of work, they realized that their whole plan was going to be impossible.

Let's get more specific. The reason the troublesome component blew up was because it turned out that it had been spec'd out with an assumption that it would be able to access a key bit of information about the user... but that information turned out to not be reliably available. The system had it for some users, but not for others. To "fix" this, they'd have to rewrite a complex data ingestion process (which their team doesn't own, nor know how to work with), to obtain and attach this bit of information about each user. And that would only work if the upstream data sources even *had* this information, which they might not.

But, a good bit of the sizzle of the new feature depended on being able to tune it to the user's needs, based on that bit of data.

In this case, they would likely have been pretty frustrated, but, once they reported this back to the PM, they could have worked with the PM to figure out a different product offering. Maybe it would be a bit less sexy, but the PM, being good at their job, is able to find a new way to solve user's underlying problem.

# They would have immediately realized how hard it was going to be, and could have immediately rethought the overall product offering.

The team could still have shipped something super valuable by Q2.

# (though, see below re: the flexibility they'd need to be able to do this).

# The senior non-technical stakeholder might not have been thrilled by this shift, but if the team were still able to ship something by Q2 which customers loved, that stakeholder would have quickly forgotten they ever asked for anything different.

# This is, fundamentally, our plan.

# They would still have been /surprised/ by just how bad that component turned out to be.

# But instead of being a disaster, that surprise would merely have been *valuable information*.

In other words, you don't try to get rid of all surprises before you start. You still assume you'll hit some potentially very nasty surprises /during the actual project/. But, thanks to a clever way of designing increments, you're able to /start/ by building the things which are mostly likely to blow up. This vastly increase the odds of hitting the nastiest surprises /early/.

And, if a team encounters a surprise early enough, *it's not a disaster*. Early on the team still has good options to offer the rest of the business (even if, sometimes, that option is "Abandon this entire project, because it's no longer economically rational").

# And, believe it or not, clever increment design will allow you to reliably flush out surprises early.

# You can't /eliminate/ all surprises before a project starts, but you *can* design your increments so that you attack the riskiest, most uncertain work *first*. This gives you an excellent chance of hitting your surprises early enough to still be able to adapt and find some win for the business.

# You can't eliminate all surprises before a project starts, but you *can* sequence your work so that you attack the riskiest, most uncertain work *first*. This gives you an excellent chance of hitting your surprises early enough to still be able to adapt and find some win for the business.

** How Our Friends Could Have Been Surprised Early

What would that have looked like, in our example above? Well, at the moment when the team had broken down their set of components, they could have sat down, and gone through each one, and, instead of simply estimating how long they believe it would take them to build it, they could have asked each other:

"How likely is this particular component going to be to blow up?"

Perhaps they would hit some (build a new front-end), which are going to take real amounts of time, but which are unlikely to explode in scope. But maybe others are much less certain, at the start. E.g. perhaps one of the components involves building an integration with a third-party data source that the team hasn't worked with. They tell the PM "That should take a month, but we really don't know. We're pretty worried about it."

In the original plan, they had put that very late, because they wanted (being good agilista's) to build something which they should show to users, so they had just faked out the third party data integrations, in order to get something working and demoable sooner. It was also clearly going to be a pain in the ass, and they wanted to build momentum.

Instead, they could have realized that that one component had the most uncertainty, the most risk, and designed their incrementsto build that component *first*.

In that world, just a few weeks into the project, they would have hit the profound challenges of integrating with that third-party data source, and realized that they couldn't build the product they were envisioning.

Engineers can't, in general, reliably estimate how long it will take them to build things. But they *can* usefully speak to the degree of risk and uncertainty in building things. They know certain things are "hard but fairly certain" -- it will take two months, but at the end of two months, you'll have the thing. Whereas others are profoundly uncertain: it could take two weeks, it could take two months, it could be impossible.

And if, early on, *everything is uncertain*, then you can make your first increment to build a little bit of "everything", specifically with a goal of learning where your biggest risks are.


# In our example above, when starting the project, the engineers could have said "Which of these components is the most uncertain? Which one is most likely to blow up?" That's a very productive conversation. If they had then built the "risky" component first, they would have discovered, just a month into the project, that their plans were going to have to change. The PM would have been able to renegotiate with the senior non-technical stakeholder, when they still had a lot of good options to offer.

Throughout the book, we'll explore a wide variety of ways for engineers and product managers to work together to, first, identify the riskiest parts of an effort, and second, to sequence their work to extract any surprises as early as possible.


# Early Surprises Create Options

# The Answer, II: Make Decisions More Often

** The Answer, II: Define Milestones Around Decisions

# Ask The Business To Make Business Decisions

# The Answer, II: Offer Decisions To "The Business"

Obtaining the information from early surprises is not, by itself, enough.

You also have to *draw your stakeholder into a process of repeated decision-making*.

When we hit a surprise early, we create value by enabling the business to make a new decision: based on what we just learned, what is *now* the most valuable thing the enginers can do?

# do for the business?

And, crucially: /The engineers and the PM can't make that decision on their own./

The senior non-technical stakeholder above will have to be a part of it. They're going to *want* to make a single "big" decision up front -- "Do I fund this project or not?" Unfortunately, that simply does not work.

To create valuable software, "the business" will have to make a series of business decisions, as the team builds and learns.

Thus, a core part of the increment design is to work backwards from the *decision you're going to ask an Important Person to make*.

Our friends above, when confronted with the demand for a commitment to Q2, could have defined their first increment around:

 - The senior non-technical stakeholder will review a few different possible prototypes, each of which we're fairly confident we can build, in order to decide what the overall shape of the product offering should be.

That's a *concrete goal*.

** The First Key Decision For Our Friends

# Surprises Are Decisions For "The Business"

# Options are ...
# "The Business" Makes The Decisions

** The Answer, III: Draw Stakeholders Into Repeated Decision-Making

# The Answer, II: Offer "The Business" Decisions

# The Answer, II: Make Smaller, More Frequent Decisions

# The Answer, Part II: Enable Smaller, More Frequent /Decisions/


# The Answer, Part II: Make Smaller Decisions More Often

# The Answer, Part II: Make Smaller Decisions As You Go

# The Answer, Part II: Make Decisions As You Go

# The Answer, Part II: Build Your Plan Around Decisions

# The Answer, Part II: Work Backward From Decisions

# The Answer, Part II: Plan To Make Decisions

** How They Charmed Ben
** A Map Of The Rest Of This Book
# The Answer, Part II: Smaller, Better, More Frequent /Decisions/

# The Answer, Part II: Subdivide Your Decisions

# The Answer, Part II: Offer Repeated Decisions

# The Answer, Part II: Offer Cadenced Decisions

# The Answer, Part II: Offer A Series Of Decisions

# The Answer, Part II: Make A Series Of Decisions
* Scraps
** Ordering Concerns
Like, how can we build the risky data matching and ingestion bits before we've built new production integrations with our customerse? There are clever ways to do this as well, because our first key outcome is to support a decision (e.g. if the biggest risk is around the data matching, not the actual integrations, then "manually" download a bunch of data files from customers, and then use those as a reference to start to build your matching and ingestion logic, and see what you find).

Finally, if they engineers are feeling like *everything is uncertain*, then you can make your first increment to build a little bit of "everything", specifically with a goal of learning where your biggest risks are. You're going to support the business by fleshing out your picture just a bit.

** Old End of Use Future Decisions

This is actually surprisingly straightforward! After all, you selected your first increment because it allowed you to test for some specific unpleasant surprise. Therefore you can also identify the specific decision that will have to be made, if you /are/ surprised.

For example: when your team tries to build Product A, and you start by tackling that nasty data integration, you're doing so /because/ you might have to decide to pivot from A to B, if the data integration turns out to be a real bear.

Although the effort to build the integration is unknown, the decision you might have to make is very much knowable.

You can tell both the stakeholder and the team that the first increment of work will take *exactly* four weeks, and the objective is:

"In order for <insert stakeholder name> to decide if we should continue to try to build A, or should instead pivot to B, the team will share a report on what fields they'll be able to extract from our key data integration."

You're promising the stakeholder that, at a *specific* moment in the future, they will get to make a decision. You're being explicit with both them and the team about what evidence they will need, in order to make that decision.

This ahead-of-time focus on evidence has two excellent effects. First, it forces an upfront conversation with the stakeholder about what evidence they will need, to make their decision.

# Perhaps the stakeholder says "Look, we don't need a lot of fields, I just need to know if we can get the customer's most recent purchase pulled over." Great, you say, and adjust the milestone to say "... the team will share an updated estimate of the time to build an integration that obtains a customer's most recent purchase."

Second, it allows the team to be creative in achieving the outcome. If they truly understand the decision they're empowering someone to make, they can cut the right corners to get there.

Finally, focusing on a decision is incredibly useful for shrinking scope. Maybe four weeks in, there's still a lot of uncertainty about the data integration. Here's the thing: *someone will still need to make the "continue or pivot" decision.* You gather as much evidence as you can, and then sit down your stakeholder, and decide what to do next. You *can* reliably do that, on a precise future date.

You're not saying "We can't make a plan, sorry!" You're saying "Here's a key piece of evidence we need to aquire, in order to empower you, and here's the exact time you'll see that evidence."

# and, before you get started, you have an explicit conversation about *what evidence* they will need to make their decision.

I'm using a specific format I call a Decision Story, very much inspired by User Stories:

 - As a person in role x,

 - in order to make decision y,

 - I can review evidence z.

** The Tale Of Teresita And The Automated Intake

Teresita Carlotta Torres is an engineer at OrthoMedica, a SaaS business that sells clinical support systems to sports medicine practices all across the country. Her team owns the patient intake process, from the moment a patient calls in, until the moment a provider sits down with them to discuss their case. Because Teresita has done such a strong job of executing on various gnarly bits of intake, she has recently been promoted to Senior Software Engineer. As part of that promotion, she's been asked to play the tech lead role for her team of four engineers.

Teresita is excited by this new challenge, but also a bit nervous. She's generally been on the receiving end of large-scale project break downs, and now it's her turn to lead that process.

One day, Vivek, her product manager, pokes his head out of an all-day annual planning meeting and quickly asks if Teresita can block an hour the next day to "talk something out." Somewhat nervously, she agrees.

When they meet, Vivek, speaking in his measured way, lays out a new feature the exec team wants them to build this year: automated patient histories. At time of initial intake, OrthoMedica will obtain and scan through the patient's history of injuries and then use that to create a clear timeline for the treatment team.

Teresita's mind fills with considerations of all the various bits they'd need to build.

"So," asks Vivek, breaking in on her thoughts, "does that sound like something we can likely get done this year? Just at a high level?"

Teresita feels a spike of anxiety flood through her. Some part of her wants to say "Yes," right away. After all, she's gotten promoted in no small part because of her ability to "find a way". But she also knows her team has been very badly burned by casually-made estimates.

She decides to just be honest. "I don't know. We'd have to dig in, in some real detail, to make a good estimate."

Vivek shrugs. "I don't need a firm commitment, I'd just like to talk it out, get a sense of what I can tell Rory."

This does nothing to calm Teresita. Rory, the head of sales, is notorious for taking vague conversations about possible features and then simply claiming those features already exist in order to close deals. She fears Vivek is trying to earn goodwill with the exec team, by giving Rory grist for this particular mill.

She decides to buy time. "Can we talk it out with the team first?"

Vivek agrees, though Teresita can't shake the feeling that he's a bit disappointed. Maybe he thinks tech leads are supposed to give this kind of casual estimate? Maybe they're supposed to?


* Todos
** TODO Spike: tell a story
** TODO Pivot to making intake more efficient in another way
They create an ahead-of-time survey of the patient.
