:PROPERTIES:
:ID:       95635819-413C-4C43-8A86-20C2DAD4ED43
:END:
#+title: Be Surprised Early
#+filetags: :Chapter:
* Early Surprises Create Incremental Value
** The Answer, I: Design Increments To Create Early Surprises

# The Answer, I: Be Surprised Early

The fundamental trick which this book wishes to share with you is that, although it's genuinely impossible to eliminate nasty surprises from software development, it is very much possible to make those surprises *less expensive*.

In other words, you prevent disasters not by preventing surprises, but instead by breaking the link between "surprise" and "economic disaster".

But, how is this even possible?

A team can turn surprises into non-events if they can:

*Design the increments so that the team is surprised /early/, instead of late.*

In our story above, everything would have been fine if the very first thing the team tried to build was the troublesome component. They would have immediately realized how hard it was going to be, and could have immediately rethought the overall product offering. The team could still have shipped something super valuable by Q2.

# (though, see below re: the flexibility they'd need to be able to do this).

# The senior non-technical stakeholder might not have been thrilled by this shift, but if the team were still able to ship something by Q2 which customers loved, that stakeholder would have quickly forgotten they ever asked for anything different.

# This is, fundamentally, our plan.

# They would still have been /surprised/ by just how bad that component turned out to be.

# But instead of being a disaster, that surprise would merely have been *valuable information*.

In other words, you don't try to get rid of all surprises before you start. You still assume you'll hit some potentially very nasty surprises /during the actual project/. But, thanks to a clever way of designing increments, you're able to /start/ by building the things which are mostly likely to blow up. This vastly increase the odds of hitting the nastiest surprises /early/.

And, if a team encounters a surprise early enough, *it's not a disaster*. Early on the team still has good options to offer the rest of the business (even if, sometimes, that option is "Abandon this entire project, because it's no longer economically rational").

# And, believe it or not, clever increment design will allow you to reliably flush out surprises early.

# You can't /eliminate/ all surprises before a project starts, but you *can* design your increments so that you attack the riskiest, most uncertain work *first*. This gives you an excellent chance of hitting your surprises early enough to still be able to adapt and find some win for the business.

# You can't eliminate all surprises before a project starts, but you *can* sequence your work so that you attack the riskiest, most uncertain work *first*. This gives you an excellent chance of hitting your surprises early enough to still be able to adapt and find some win for the business.

** The Answer, II: Define Milestones Around Decisions

# Ask The Business To Make Business Decisions

# The Answer, II: Offer Decisions To "The Business"

Obtaining the information from early surprises is not, by itself, enough.

You also have to *draw your stakeholder into a process of repeated decision-making*.

When we hit a surprise early, we create value by enabling the business to make a new decision: based on what we just learned, what is *now* the most valuable thing the enginers can do?

# do for the business?

And, crucially: /The engineers and the PM can't make that decision on their own./

The senior non-technical stakeholder above will have to be a part of it. They're going to *want* to make a single "big" decision up front -- "Do I fund this project or not?" Unfortunately, that simply does not work.

To create valuable software, "the business" will have to make a series of business decisions, as the team builds and learns.

Thus, a core part of the increment design is to work backwards from the *decision you're going to ask an Important Person to make*.

Our friends above, when confronted with the demand for a commitment to Q2, could have defined their first increment around:

 - The senior non-technical stakeholder will review a few different possible prototypes, each of which we're fairly confident we can build, in order to decide what the overall shape of the product offering should be.

That's a *concrete goal*.

** The Answer, III: Draw Stakeholders Into Repeated Decision-Making

# The Answer, II: Offer "The Business" Decisions

# The Answer, II: Make Smaller, More Frequent Decisions

# The Answer, Part II: Enable Smaller, More Frequent /Decisions/


# The Answer, Part II: Make Smaller Decisions More Often

# The Answer, Part II: Make Smaller Decisions As You Go

# The Answer, Part II: Make Decisions As You Go

# The Answer, Part II: Build Your Plan Around Decisions

# The Answer, Part II: Work Backward From Decisions

# The Answer, Part II: Plan To Make Decisions


** How Our Friends Could Have Been Surprised Early

What would that have looked like, in our example above? Well, at the moment when the team had broken down their set of components, they could have sat down, and gone through each one, and, instead of simply estimating how long they believe it would take them to build it, they could have asked each other:

"How likely is this particular component going to be to blow up?"

Perhaps they would hit some (build a new front-end), which are going to take real amounts of time, but which are unlikely to explode in scope. But maybe others are much less certain, at the start. E.g. perhaps one of the components involves building an integration with a third-party data source that the team hasn't worked with. They tell the PM "That should take a month, but we really don't know. We're pretty worried about it."

In the original plan, they had put that very late, because they wanted (being good agilista's) to build something which they should show to users, so they had just faked out the third party data integrations, in order to get something working and demoable sooner. It was also clearly going to be a pain in the ass, and they wanted to build momentum.

Instead, they could have realized that that one component had the most uncertainty, the most risk, and designed their incrementsto build that component *first*.

In that world, just a few weeks into the project, they would have hit the profound challenges of integrating with that third-party data source, and realized that they couldn't build the product they were envisioning.

Engineers can't, in general, reliably estimate how long it will take them to build things. But they *can* usefully speak to the degree of risk and uncertainty in building things. They know certain things are "hard but fairly certain" -- it will take two months, but at the end of two months, you'll have the thing. Whereas others are profoundly uncertain: it could take two weeks, it could take two months, it could be impossible.

And if, early on, *everything is uncertain*, then you can make your first increment to build a little bit of "everything", specifically with a goal of learning where your biggest risks are.


# In our example above, when starting the project, the engineers could have said "Which of these components is the most uncertain? Which one is most likely to blow up?" That's a very productive conversation. If they had then built the "risky" component first, they would have discovered, just a month into the project, that their plans were going to have to change. The PM would have been able to renegotiate with the senior non-technical stakeholder, when they still had a lot of good options to offer.

Throughout the book, we'll explore a wide variety of ways for engineers and product managers to work together to, first, identify the riskiest parts of an effort, and second, to sequence their work to extract any surprises as early as possible.


# Early Surprises Create Options

# The Answer, II: Make Decisions More Often

** Surprises Are Decisions For "The Business"
# Options are ...
# "The Business" Makes The Decisions

** A Map Of The Rest Of This Book
# The Answer, Part II: Smaller, Better, More Frequent /Decisions/

# The Answer, Part II: Subdivide Your Decisions

# The Answer, Part II: Offer Repeated Decisions

# The Answer, Part II: Offer Cadenced Decisions

# The Answer, Part II: Offer A Series Of Decisions

# The Answer, Part II: Make A Series Of Decisions
* Scraps
