:PROPERTIES:
:ID:       B4926308-39DD-471B-8E71-5FFF7546D6E3
:END:
#+title: ToC
* Table of Contents
** [[id:454225CA-DD66-4ACA-B8B3-429F6551DBDC][New Intro]]
** Overview
*** [[id:25B84349-E03D-4C1D-AA91-6F2C1E050E6E][The Struggle to Create Value]]
*** Build Increments Around Decisions (Analytics 2.0)
*** Turn Interruptions Into Cadenced Decision-Making
*** Mine For Context Using Empathy
*** Take the Lead on Technical Investments

* Stashed for later
** Part II: Creating Value in the Presence of Uncertainty: Build Increments Around Key Decisions
*** [[id:D3158CC2-8A69-4097-B9ED-ED6BD855A7AD][Understand Value In Depth]]
*** Map the Landscape of Uncertainty
*** Develop Milestones Around Decisions ([[id:03D1870C-E583-4D5C-9589-5E0799793D48][Offer Decisions, Options & Off-Ramps]])
*** Case Study: Parent Comms (or Strats 2.5?)
*** Turn Interruptions Into Cadenced Decision-Making
*** Case Study: The Heartbeats
** Part III: Changing Stakeholder Behavior: First Hearts, Then Minds
*** [[id:78678319-4D0D-474C-AC5C-A3231B826D89][Understand Both Sides]]
*** [[id:4FEA3BD5-8E85-4BB6-8F59-15FDE4F38572][Practice Tactical Empathy]]
*** Create a Concise Statement of Strategic Intent (Identify a Strategic Intent)
*** Design an Increment of Change
*** Make Your Stakeholder a Beleaguered Hero
*** Case Study: Forms? Nexus?
** Part IV: Take the Lead on Technical Investments
*** Defining Tech Investments
*** [[id:2EC03879-2A23-4546-BCB8-E9A464665A03][Turn Engineering Concerns Into Potential Value]]
*** [[id:BB09F432-DEEB-4129-8F88-D23C86E8CEBB][Build Visibility First]] (The Power of Visibility)
*** [[id:4D62F0DE-2862-45F3-97EE-6AFED5382F2C][Use Storytelling To Celebrate Wins]] (To Share Progress And Wins)
*** [[id:EFA43963-DB19-4EA6-8EF3-4F4376AED1F1][A Series of Story Makeovers]]
*** [[id:3DE23585-34F0-4C88-A16B-4558ACC45C99][Make Your Post-Mortems an Act of Visibility]]
*** Case Study: Pinch Tests @ Wayfair

* Stashed For When I Get There
** Part I: Build Trust and Alignment
*** Build Trust In Loops
*** Understand Your Stakeholder In Depth
Make Your Stakeholder Into A Bealeaugered H
*** Convert Interruptions Into Cadenced Decisions (here?)
** Part III: Drive Technical Investments
*** [[id:22032FA8-F94E-492F-8138-7E1859B3F0CA][Assign Ownership to Align Costs With Benefits]]
*** [[id:722C702D-A6C2-4A51-AB62-515CE8144AA2][Climb the Ladder of Commitment]]

* Old Table of Contents
** [[id:47FF75F6-17DB-4E36-950D-F7CFAFA950EA][Introduction]]
** Part I: Identify Valuable Investments
*** [[id:71B164B6-0AB2-4FDE-B51E-71870F553C67][The Tech Investment Cycle]]
*** [[id:BB09F432-DEEB-4129-8F88-D23C86E8CEBB][Build Visibility First]]
*** [[id:D3158CC2-8A69-4097-B9ED-ED6BD855A7AD][Understand Value In Depth]]
*** [[id:2EC03879-2A23-4546-BCB8-E9A464665A03][Turn Concerns Into Potential Value]]
** Part II: Build Trust and Commitment With Stakeholders
*** [[id:4FEA3BD5-8E85-4BB6-8F59-15FDE4F38572][Practice Tactical Empathy]]
*** [[id:03D1870C-E583-4D5C-9589-5E0799793D48][Offer Decisions, Options & Off-Ramps]]
*** [[id:4D62F0DE-2862-45F3-97EE-6AFED5382F2C][Use Storytelling To Celebrate Wins]]
*** [[id:EFA43963-DB19-4EA6-8EF3-4F4376AED1F1][A Series of Story Makeovers]]
** Part III: Win the Long Game
*** [[id:3DE23585-34F0-4C88-A16B-4558ACC45C99][Make Your Post-Mortems an Act of Visibility]]
*** [[id:22032FA8-F94E-492F-8138-7E1859B3F0CA][Assign Ownership to Align Costs With Benefits]]
*** [[id:5AF07DBC-C0BB-4832-A900-CD261C4E90BA][Weave Tech Investments Into Your Career Ladder]]
*** [[id:722C702D-A6C2-4A51-AB62-515CE8144AA2][Climb the Ladder of Commitment]]

* Stashed for Future
** [[id:D901A4C9-885B-4F42-8B8D-3595616857E8][The Extraordinary Value of Knowing What To Do Next]]
** [[id:E7DB3CD4-9B7B-425B-BF07-E2607DDD6670][Forms of Value & Visibility]] (move to appendix and/or cut up)

* Old ToC
** Intro
*** Intro Chapter
**** Stakeholders Scream About Features, the Team Screams About Tech Debt: The Joy of Engineering Leadership
# Statement of empathy, touching on a bunch of the human experience + potential failure modes.
**** Why the "Tech Debt" Metaphor Has Become Limiting
# Sketch in the key problems (focus on "bad code", offers nothing positive to your product or stakeholder peers, don't go too deep on moral vs economic)
**** A Better Way: Technical Investments
# Give the definition
**** What If My Stakeholders Don't Care About Engineering?
**** What If My Engineers Don't Care About the Business?
# Aka, what if my very senior engineer just wants to rewrite everything?
**** What's Coming In the Rest of the Book
** Part I: The Tech Investment Cycle (Identifying Potential Investments)
*** The Tech Investment Cycle
*** Build Visibility First
*** Understand Value In Depth
*** Turn Concerns Into Potential Value
** Part II: Stakeholders Have Feelings, Too (Building Trust & Commitment)
*** Master "Tactical Empathy" To Build Trust {Commitment}
**** Avoid Anti-Patterns
Six Ineffective Ways to Advocate Before Breakfast
*** Build Milestones Around Decisions
Develop Incremental Options
Small Steps Are The Only Steps Allowed
# aka No, Really, It *Can* Be Done In Small Steps
**** The Full Rewrite: Only Undertake If You Wish To Be Fired Midway Through a Long, Painful & Ultimately Unsuccessful Death March
*** Bootstrap Regular Decision-Making Meetings
*** Use Storytelling to Celebrate Wins
*** Climb the Ladder of Commitment
5 Scopes: On the Side, Ticket, Project, Initiative, Durable Team
# Tease apart tiger teams vs cross-team initiatives
** Part III: Scaling Up: Tech Investments & the Engineering Organization
*** Assign Ownership to Align Costs With Benefits
*** Make Your Post-Mortems an Act of Visibility
*** Weave Tech Investments Into Your Career Ladder
*** Use the Dark Force of "Metrics" In Your Favor
** Part III: Case Studies
*** Forms of Value & Visibility
# For each, sketch in ideas on building visibility (and maybe actually do a bit of 1 -> 2 -> 3, viz -> commitment -> more viz -> more commitment
**** Speed Up The Build/Ship/Learn Cycle (Not Just The Build Part)
**** Ship Smaller Changes More Often
# aka, use Accelerate as teaching instrument/bludgeon
**** Enable (Specific) Upcoming Product Improvements
**** Reduce Steady Operational Work
**** Reduce Interruptive Maintenance Work
**** Enable Parallel Development Across Multiple Teams
**** Reduce Risk of Losing Customers Thanks to Losing Their Data
**** Reduce Risk of (Expensive) Outages
**** Reduce Duration of (Expensive) Outages
**** Reduce Risk of (Very Expensive) Security Breaches
**** Ensure Many Customers Can Use System At Once Without It Collapsing
# Aka, Load & Scale
**** Ensure "Big" Customers Can Use System In "Big" Ways Without It Collapsing
**** Reduce Costs Of Serving Customers (But, See: Drunk, Lamppost)
# See: drunk, lamppost issues.

**** Engineer Complaints: When To Act On vs When to +Ignore+ Express Sympathy
*** HubSpot "Customer Crisis"
Post-mortems led to investtments in tooling
*** Pinch Tests
*** EWJ's DevPlats Work
*** Inventory Variance
*** TRNS Criticals
*** Couchbase or ElasticSearch Retirement
*** SLI's & SLO's @ Ellevation
*** Load Testing Parent Letters
*** Assignment Paradigm?
*** Flex Fields?
** Appendix
*** The Moral Mindset: A Powerful But Dangerous Widget of the Human Mind
*** The Extraordinary Value of Knowing What To Do Next
# As my shrunk down form of the full information-as-value story
# Oooh, maybe I can use both my metaphors of Bad estimates are like having a contractor offer to burn your house down + the difference between planning a trip w/ milestones on roads vs exploring an undiscovered country (or alient planet)
#
# Maybe around here, do the super condensed Cliff's Notes form of value ala:
#
#  - The vast majority of time, we only truly know what we're going to do next once we finish what we're currently doing
#  - It's an exploration, not a planned itinerary
#  - Value comes both from building, but also from more rapidly figuring out the next thing to do

*** OMG If Someone Says "Productivity" One More Time I Will Not Be Responsible For My Actions

* Ideas for reordering beginning of Part I <2025-06-07 Sat>
Can I go:
 - The Tech Investment Cycle (w/ deploy story from Ellevation)
 - Build Visibility First (allow myself to be a bit tactical, focus more on the lack of shared understanding, inability to show progress, difficulty for the engineering leader to make decisions)
 - Understand Value in Depth
 - Catalog of Forms of Value/Visibility
 - *Then* The Extraordinary Value of Knowing What To Do Next
   (And I think, do it via something biz-centric first, then tell the story of Pinch Tests. But also, by that point there might be room to hear a full story)

* Notes on what robfitz says in [[id:27BF5BDA-3A83-49FA-A73F-9BA26EF096B9][Write Useful Books]]

Develop a skeleton/outline focused on *learning outcomes*. If a section has multiple such, map out sub sections.

Don't aim for being cute or fun in the headlines (yet), and let them be a bit talky and long.

Imagine someone reading them and, if they don't know this area, saying "Oh, man, I've gotta read that" or if they *do* know it saying "Okay, he's covering x, y, z, I can skip that chapter or skim it, oh hey I wonder what he means by 'w', I'll dip into that".

Don't worry about consistency in length of titles -- think of this is a testable framework, not an elegant ToC that has to read well (yet).

* Random Thinking

I think defining the problem and pain early, and then doing the following two things, in some order:

 - A very concise definition of the overall gameplan (ah-hah = "Oh, that's interesting. That's seeing it at a slight angle. I want to learn more.")

 - An example that brings that gameplan to life (ah-hah = "Oh, man, I want that. And it actually makes sense/is believable").

How early do I lean into the problems with Tech Debt?


* Edmund Notes
D,

I read through this, I have 3 snap reactions (these are basically stream of consciousness, caveat lector):
This will be a good book
Something that I feel might be missing in this organization / framing (or maybe even it's just the titles) is the really human angle that I feel like you've mentioned elsewhere in this discussion--e.g. I wonder if reframing "balancing tech & product is hard," which is already an implicitly economic framing, as "Your engineers are screaming at you for time to work on tech stuff and your PM is screaming at you because they need those features right now" might not be a more visceral & effective way of validating for your target market that yes, you have named their problem.  I recall you using this framing at some point, and I liked it.  I suspect most people who aren't you and me are not really depersonalizing this out of the gate, so I think it just broadens your target market.  Also, from a non-marketing POV, in one sense, *everyone* in the business is a stakeholder if you're in this job, your own engineers included, and doing the job well requires an economic theory of software that you are able to actually execute through a respect for human nature and personal interactions, so playing up the personal aspect more centrally feels good to me.  This also lets you say--again, even in headings--that, before you can talk about the most effective ways to deal with stakeholders putting up with tech investments, you actually have to be thinking of the tech problem in the right way, so it makes the "stakeholder management" placement near the end feel appropriate, even if it's the part the reader is most worried about.  Like, you can say "Look, you've got to learn to think about this right, otherwise all the charm in the world will only delay your eventual firing halfway through a massive, doomed-to-failure rewrite of some kind."  So you get a kind of structure of validating the human aspects of the pain, promising that to fix them requires "stakeholder management," yes, but you have to be managing them towards something that's actually got the chance to be successful, so let's focus on that first.  Great, now that we've understood technical investments in a way that makes them more likely to succeed, I've got bad and good news--the bad news is, this structure is even harder for your stakeholders to understand natively than, like, some waterfall chart and a request for six months of no feature work.  The good news is, it might actually work, and you *can* learn to exploit the inherent strengths of the proper technical investment (fast turnaround / value increments, visibility, etc.) as a way to build trust.
I wonder if swapping the tech debt & tech investment section could be powerful in the intro?  E.g. "Eng screaming about tech debt, product about features.  Ok, first of all--tech debt is the wrong term, has outlived its usefulness.  Tech *investments* are where it's at.  I'll teach you how to think about them right, get your eng to do them right, and involve your stakeholders along the way so they're cheering.  Here's the basic outline.  Then, I'll teach you how to make this durable and repeatable in your company."
I have a couple potential tweaks for some of the heading names, too, FWIW.

E.g. "Tech Investments and the Engineering Organization" could potentially be reframed as some sort of "making these durable?"

"Working with stakeholders" could be "How to make your stakeholders fans of technical investments" or "how to addict your stakehoders to technical investments" or something along those lines.

I might jot down some others.
