* Questions
Of course, big picture, happy for any feedback. Some specific questions, at various levels, include:

** Does this feel "useful"?
The risk in this approach, the line I'm trying to walk, is that people may bounce off, because they think "I don't care about feelings". So I'm trying to, as much as possible, draw the lines from understanding the feelings to the value it gives you. Does that seem to be working?

** Is it too long for a single piece?
I could split it in two, after having *named* the four key emotions, but before I dig into how those play out for the head of product in question

** Should I give the head of product a *name*
E.g. Arturo, or something. Would that help it feel more vivid/real/specific? Or does it work as it is?

** Did you find yourself glazing over at any parts of the "story"?
Or, conversely, were there any parts that you felt like you wanted to open up?

* Fears & Dreams & Humans & Building Software: Part I
Subhead: The Unreasonable Effectiveness of an Empathetic Understanding
** Introduction

It is a truth universally acknowledged, that a person in possession of a career in software, must be in a state of frustration with some Important Person.

/Hello! Today's post is an excerpt from a book [link] I'm writing, provisionally titled:/

/*Getting Unstuck*/

/How To Solve Problems With Bosses, Peers & Stakeholders/

/If you read [Fixing Engineering Stakeholder API], feel free to jump down to [link] Humans Have Feelings, Ignore At Your Own Risk./

To name a few fun such Important People:

 - The CEO who interrupts a team's stand up every other day to propose new product ideas, randomizing their work and killing any hope of velocity

 - The sales leader who relentlessly advocates for feature ideas for their pet customers, constantly undercutting the prioritization decisions of the product manager

 - The senior engineering leader who inserts themselves into so many decisions, every single one of their teams is just sitting around, waiting for approvals

 - The product manager who dismisses their engineering peer's concerns around system stability, and then angrily complains when the engineers spend all their time putting out fires

 - The engineering lead who refuses to let their product peer talk directly with the engineers on the team[fn:: No, really, I have seen this], blocking the development of rapport, shared context and velocity

I could go on! I suspect you could, too!

Furthermore, in such situations, the Important Person in question, be they CEO, sales leader, engineer or product manager, *super duper doesn't want to change their own behavior*.

Sadly, this should come as no surprise.

If there's one thing that unifies all humans, it's that we are *extremely* reluctant to change our own behavior.

/(I mean, why should *we* have to change!? Our behavior is clearly only natural and right, given the very special difficulties we personally are facing! There's literally nothing else we even *could* do![fn:: I don't know when, exactly in the savannas of early human evolution it took place, but clearly self-justifying and self-deluding rationalizations have been a key part of the package of human intelligence from, like, Day One.])/

Thus, if you approach an Important Person, and gently propose that they change their problematic behavior, you can expect to enjoy either the experience of being patronizingly dismissed, or, if you're luckly, ferociously attacked.

These are unpleasant and also pretty somewhat career limiting experiences.

And yet.

The Important Person's behavior is causing *real problems*.

Problems that make it very hard for you---and your team---to succeed at your jobs.

What can you do?

*How can you get unstuck*?

I'm so glad you asked.

/[Hello again! In the book, I develop a step-by-step game plan for drawing your very own Important Person, whom I term your "Stakeholder", into a process of collaborative problem-solving. This will allow you to, together, find a better way to work, together. A core part of that game plan is developing an understanding of the underlying *feelings* that are leading to your stakeholder's problematic *behavior*. The below is an excerpt from a chapter about how and why to develop such an understanding of feelings. Speaking of the book: if you would like to be a beta reader of an early version, please drop me a line at dan@dan-milstein.com! Ditto if you have some challenges with your very own Important Person and could use some [coaching support] from, say, an experienced product and engineering leader who finds human beings endlessly fascinating]/

** Humans Have Feelings, Ignore At Your Own Risk

If you want someone to change their behavior, it's absolutely critical that you understand their feelings.

More specifically, to persuade your stakeholder to change their behavior, you will need to develop an *empathetic understanding* of their feelings.

Which is to say: you need to understand not only their feelings, but also the *situation* they perceive themselves to be in, which is driving [triggering, causing] those feelings. Somewhere in that situation, you will be able to find a business problem that you can agree is worth solving. You'll then be able to offer them a productive challenge to solve that problem in a new way, while speaking with empathy to the feelings they are currently experiencing.

To be carefully clear, developing such an empathetic understanding doesn't mean *justifying* or *excusing* problematic behaviors by those in positions of power. It means being able to articulate an understanding of why someone might both feel and behave the way they do. An understanding which allows you to say: "What they're doing is wrong, but they are facing some genuine challenges, and I can see why it feels to them like they have no other options."

It can be tricky to find this way in. Let's bring it to life with an example of this kind of very human challenge you might find yourself facing:

You work at a B2B SaaS company.

Over the last several months, your head of product has started to insist on reviewing and adjusting every single detailed UX design before it ships.

This has, unsurprisingly, slowed the pace of delivery to an absolute crawl. The stalled-out delivery is starting to cause visible problems with the rest of the business. The head of product's behavior is also triggering some intense resentment among the designers and PM's, the best of whom are starting to look for new jobs.

Why might the head of product be demonstrating this (obviously!) problematic behavior?

Now, let's imagine that, through some magical power, we're able to understand their inner life, in perfect detail. How might this magical power help us to better understand the situation?

Let's start with a bare statement of feelings.

We discover, thanks to our magic power, that the head of product is struggling with an intense, somewhat overwhelming feeling of *fear*.

They wake up every morning, *knowing* that things at their job are on the verge of spinning completely out of their control. They rush through their their days in a haze of tension, desperately doing whatever they can to prevent the [impending?] failure which is clearly about to arrive. Their new habit of bottlenecking all design changes is fueled by this fear. Making those small changes *feels* good to them, because it soothes their fear. Making those small changes gives them brief moments of feeling *agency*.

They are not, of course, fully aware of this in themselves.

Is the above an empathetic statement of their feelings?

Not... quite.

It's useful, don't get me wrong. We might feel some *sympathy* for someone struggling with that feeling of impending disaster. But we haven't gotten to a full description of the *situation* that head of product perceives themselves to be in, nor to how, exactly, that situation is driving their behavior. And, crucially, we have not yet identified a meaningful business problem we can agree is worth solving with them.

Let's deploy our magic power once again. We'll wave a magic wand and understand what in their overall situation is leading to this behavior:

 - *A few months back, a confusing product change made it through to some important customers.*

   The largest customer, a notoriously thorny account, personally complained to the CEO  and threatened to delay their upcoming renewal.

   The CEO then chewed out the head of product in front of other executives. "How could you let this get out?" the CEO had demanded. "It was /obviously broken/. Do you not understand how important that renewal is?"

   Whenever the head of product thinks of that conversation, the back of their neck grows rigid with tension.

 - *The product team includes several new designers*

   And, unfortunately, the company's core product, which their largest customers depend on for high-stakes workflows, has grown quite complex over time.

   Naturally, some of the new designers don't fully understand the most complex workflows, nor the wide variety of ways customers have tweaked the product to meet their needs.

   Thus, there is a genuine risk of one of those new designers "breaking the product", and for that to be very disruptive to some customers.

 - *The head of product was only recently promoted to supervise multiple teams.*

   They have little experience of how to hold a high standard for their teams, when they're not immersed in the day-to-day flow of the work.

 - *The head of product started their career as a designer*

   Therefore, their comfort place, the thing that makes them feel like they're actually *doing something* is... adjusting details of a UX.

In this situation, we *can* identify a genuine challenge that the head of product is facing: finding a scalable way to ensure that design work doesn't break existing, complex workflows for customers.

This is a meaningful challenge *for the business*. If we had this (magic!) understanding of the situation, we could authentically commit to working with the head of product to tackle that challenge.

Unfortunately, they are currently reaching for the only tool they have in their existing kit: direct, final-say oversight over every single design change. In the past, exerting that kind of fine-grained oversight allowed them to heroically save at-risk projects. It is how they established control and prevented failure. Thus, it's completely unsurprising that they're reaching for it now. They are dimly aware that the team is growing frustrated with them, but part of the story in their head is that they have to be willing to piss their team off a bit, in order to get the details right.

Finally, ever since the CEO turned the emotional pressure up to eleven, the background fear is so strong, it feels impossible to even *imagine* any other options.

Given all of the above, the head of product's behavior is, well, a lot easier to understand.

To be clear: that behavior is *still* extremely problematic.

To build a healthy, fast-moving team that achieves real wins for the business, you would still need to find a way to help them change that behavior.[fn:: And, a boy can dream: to help the CEO change their behavior, too]

But, importantly, *beneath* the problematic behavior, and the surging emotions, you're now seeing a *valid business problem*, around ensuring stability in the product as it evolves. That's a problem you can authentically agree needs to be solved.

Your fuller, empathetic understanding will allow you to productively challenge your stakeholder to change.

Persuading humans to change their behavior works roughly a thousand times better if you can find a way to speak to their hearts as well as their minds.

Of course, the above posited the existence of the magic power of knowing someone's full emotional landscape and history. Back here in real life, we're going to need some way to understand what our stakeholders are feeling, without being able to wave a wand.

Let's dig in.

** Frustrations, Fears, Delights & Dreams

Fortunately, to help motivate change, you don't have to understand every single facet of your stakeholder's inner life. I recommend exploring four key emotions, by way of answering four distinct questions:

 - *Frustrations*

   What happens, day-to-day, that frustrates your stakeholder?

 - *Fears*

   What are they afraid might happen at some point in the future?

 - *Delights*

   What happens, day-to-day, that makes your stakeholder feel good?

 - *Dreams*

   What do they most fondly hope happens at some point in the future?

If you can come up with empathetic answers to these four questions, you can build an *extremely* compelling request to try something new. A request that the stakeholder will both *hear* and *feel* as worth taking a risk on.

Two focus on "negative" feelings (Frustrations & Fears), two on "positive" feelings (Delights & Dreams). Within each domain, we further split day-to-day experiences from longer-term motivations.

For the negative feelings, the Frustrations and the Fears, as you dig in, you'll want to be on the lookout for underlying business problems that you can agree to help solve. aka, looking for *valid concerns*.

For the Delights and Dreams, it's a bit different. Understanding those serves two purposes. First, that knowledge will enable you to offer your stakeholder new Good Feelings (and/or promise to avoid losing existing Good Feelings). That's an important way to motivate someone to take the risk of making a change.

Second, *many* problems are caused by stakeholders pursuing things that make them Feel Good, but that cause issues for others (e.g. the head of product doing detailed design work because it soothes their fears). If you're going to ask someone to change a behavior that currently makes them Feel Good, it's extremely valuable to be able to speak with genuine empathy to what they're going to have to give up.

What might these emotions look like for our Head of Product friend?

How might someone use their knowledge of these emotions to develop a persuasive case to change their problematic behavior?

To make it concrete, we'll assume the person who is gaining this knowledge of the head of product's emotions is someone they trust. Someone who would be able to offer them a productive challenge. Perhaps that's the head of engineering, who is their partner on the exec team. Perhaps it's their most senior PM, who has worked with them for years.

Let's go through our list of emotions, imagining for just a bit longer that we have our magic, perfect access to their inner life.

Let's see a few answers, and, for each, touch on how a trusted friend might leverage that understanding to help persuade the head of product to consider making a change.

** How To Use an Understanding of Feelings
*** Frustrations

/What happens, day-to-day, that frustrates your stakeholder?/

The head of product finds it very frustrating when the new designers don't understand the complexities of the existing product.

Although this isn't particularly odd on its face, our magic insight reveals a somewhat surprising underlying reason: the head of product created much of the existing design, and they feel somewhat *ashamed* of it. Every confusing screen reminds them of bad tradeoffs they had to make, and all the painful issues those tradeoffs caused. When the new designers get tripped up by one of the ambiguous workflows (or the endless, conflicting series of cryptic "settings" screens), the head of product is both upset because of the potential for customer confusion, but also because of the reminder of their own past failings.

It's obviously not okay to *act* on that feeling, but I would guess many of us can empathize with the shame of watching your own worst work come back to haunt you. Personally, I can effortlessly recall the moment, a full fifteen years ago, when a brilliant new engineer joined a team I led, and, in poking around the codebase, found the horrifying hack job of a deploy process I had kludged together. I felt a surge of shame that I can easily access, even right now as I type these words.

What might be a valid business problems beneath this frustration the head of product is feeling?

Well, the business needs to find a way to help new designers understand not just what the existing product *does*, but also which parts of it have proved to poorly meet customer needs. Only then can they develop effective new designs.

Given that understanding, the trusted friend could propose some new way to address this totally valid concern.

To make this concrete, perhaps they propose to the head of product that, when a new designer goes to work in some area of the product, they first spend real time doing a detailed walk through of that area with the head of product. That walk through would have an explicit goal of touching on all of:

 - What are the existing features /supposed/ to do

 - How do customers /actually/ use them

 - What would the head of product do /differently/ today

And then, once that walk through was done, the head of product would commit to staying off the critical path for deploying product changes.

Note how, by getting to the underlying feelings and valid concerns, the trusted friend can propose something *positive* (a new, useful thing to do), instead of merely insisting the head of product *stop doing their current behavior*. That's far more likely to work.

*** Fears

/What are they afraid might happen at some point in the future?/

More than anything, the head of product is afraid that the CEO will, once again, publicly shame them in front of their peers.

That fear should be straightforward to empathize with. Shame is a profoundly awful experience.

They also have a suite of fears that emanate from this, the most relevant of which is:

 - Important customers might being angered by imperfect, rough or confusing product changes

This is valid business problems. In fact, the full business problem is better stated as:

"How can the team continue to move quickly and learn, even though some important customers will be angered if the product changes in confusing ways?"

Now that we've gotten to this full, nuanced understanding of what's going on, the trusted friend sees a straightforward option: they could propose collecting a set of "beta-tolerant" customers, who are eager to see new changes, and willing to handle some confusion to do so. Once that customer group is in place, the head of product could step back and let the team  make some mistakes as they learn, confident that they won't could piss off the most important, change-resistant customers as they do so.

This pairs extremely well with the idea of the detailed walk throughs, above.

*** Delights

/What happens, day-to-day, that makes your stakeholder feel good?/

The Head of Product loves getting into the details of a UX and experimenting with alternatives.

This used to be central to their job, their new bad pattern of behavior is letting them return to this happy place. You're going to have to ask them to do a lot less of this. When you do so, it will be important to be able to speak with empathy to their experience. It will also be helpful if you can offer some non-disruptive ways that they can look forward to some related good feeling.

In our specific situation, what might the trusted friend say?

They could build on the walk through idea by saying: "Look, I know how good it can feel to get back into the details. But I think we'll be better off if we focus that on these deep dive periods of exploring the existing UX. And keep it off the critical path for deploys."

That's a direct challenge to change, while acknowledging the loss.

*** Dreams

/What do they most fondly hope happens at some point in the future?/

Early in their career, the head of product had a mentor who, well, changed their life. That person saw their potential and created space for them to take on more and more responsibility, and then supported them through some early stumbles. They still talk to that mentor, and every time they do so, it leaves them feeling energized and hopeful.

With their promotion to lead all of product, they started to dream about having that effect on someone else's life. But then they immediately got sucked into their own fears and the CEO's frustrations and have barely had a moment to look up, ever since.

Knowing this, a trusted friend could say: "I know how important it is for you to create a space where people can grow. I know how much that meant to you, early in your career. I think we need to find a new way for you to guide the teams, if people are going to have that kind of growth, here."

** Where Do The Magic Understanding and Trust Come From?

Hopefully you can see how powerful it is to deeply understand the situation a person perceives themselves to be in.

Without such an understanding, we're left with little option but to issue a blunt demand: "Please stop changing all the designs at the last minute. It's slowing everything down and pissing off the team." Such a demand gives the stakeholder *more things to be afraid of*. If they're *already* operating in a state of fear, the odds are extremely low that they'll respond to such a blunt request by changing their behavior.

With our magic understanding (and some trust), we can offer the stakeholder a new way to work, that will be better for the business *and* better for them. And we can speak to both their fears and their hopes as we do so.

Now we must turn to the question that we've been blithely ignoring.

How are going to come up with answers to these questions? How are we going to understand the inner emotional lives of our stakeholder?

We don't, sadly, have access to the magic power above.

Or... do we? /me raises eyebrows dramatically

In my next post, I'm going to share how you can, right here in the real world, develop an astonishing, near-magic ability to understand someone's fears and dreams.

We'll be exploring the profoundly valuable skills of Tactical Empathy.

Tune in next week...[fn:: Or, you know, however long it takes me to cobble the next section into shape! kthxbai!]
