* Intro / Purpose
For me to learn from you, and maybe see if any challenges can be helped by the ideas I'm working on.

Time check: 45 minutes?

Theme: challenges w/ stakeholders, maybe more broadly -- how to create value, solve business problems.

Home made ice cream

My background

* Good/Bad

* Context
** Where do you work
BookBub -- going on 10 years
** What is your team
Work on eBook -- predominantly on the consumer side. How to get better book recs in front of users. Site features, biulding some algorithms.
** Your role
Engineering lead -- overseeing the entire team. Working very closely with product. Sometimes stepping into. About 7 engineers, 3 product-ish. Some junior products.

30 engineers.

One layer between her and the head of engineering.

** What is your company trying to do?
At this point, her company were a startup. Want to exit. That's the big star.

it's not exactly, that the mandate is help us exit.

She thinks leadership is afraid of saying "We want to exit" and have people make decisions based on that. And there isn't a very firm timeline around that.

They're constantly trying to squeeze more revenue/value/users. Both grow and increase the value.

Does she know what will make them attractive to an acquirer.

Yes, profitable. But also having active, engaged, users.

Not clear who an acquirer would look like.

** How does your team fit into that?
More focused on the active/engaged.  She's been shifting a bit in teams of late. Primarily on the activation.

** What is frustrating about her job?

She feels good about pushing for tech debt.

The estimates. A brief recap.

They are often looking for short-term wins. For years. A bit of a lack of commitment to bigger, meaningful efforts. A few things at play there.

They are a conservative, profitable business -- they are

To prove something out -- a MVP, too perfectionist to launch embarrassed? But then can't do big bets because they want to be certain.

Even if product wants to do something, they end up splitting hairs, 3 weeks vs 4.

Because they don't have bigger ideas and plans -- they're not negotiating against something else.

Who are things being hashed out with.

She loves bookbub for a lot of reasons -- but the product team is a bit young, inexperienced. Most of her interactions are with that layer.

She'll then skip up to the GM, and they'll have more productive conversation. She, Lisa will get aligned with that GM, she, Lisa has to lean over and do their job.

Does she have a product peer -- also has been there as long as the org, has grown up in product, along with the company.

What are overall planning cycles. They do quarterly planning -- they're in the midst of an experiment right now, engineering driven.

Used to be in these weekly grooming splints. Planning was happening pretty close to each week. They've separate things now -- instead of, product would "run their teams". they'd be constantly worried about having enough work for people, all the tactical things.

Doing a project teaming thing. You have all the engineers to staff to your projects. Every two weeks they have a pitch meeting, then choosing them, and how to staff them.

That's been working better for getting planning.

** Her Ideas around better data around their users

** What layer slows it down the most
Her peer in product -- Conrad. He's extremely smart, but maybe to a fault. Wants to think through every edge case, possibility, wants to overly button things up for the GM.

She, Lisa doesn't think it's all coming down from the GM.

He's creating a really high bar for getting things to her.

He has not worked in product outside of BookBub. He came to them out of college, worked in a couple of different depts, and then landed in product.

What is he afraid of, what makes him feel good.

What afraid of -- failure. Which is: investing in something that doesn't show success in the top numbers. Not clear that he's

He will name -- this is okay, we learned.

What makes him look good with the GM -- hitting the goals, which are primarily incremental number goals. Certain levels -- book value.

He would also feel good if he "had a big idea" -- that would make him feel amazing.

A lower third one -- everyone around him being super excited and happy. Probably some praise.

They just went through a cycle for quarterly planning, the team is open.

Could they pitch a lot of experiments -- can they pitch a product pipeline, with decision makers.

Gave a similar pitch, but ending w/ pipeline of experiments, focusing on empowering product peer + GM to make decisions (and set those decisions as the milestones for the engineers).

Also, her situation was distinct, in that she had the product peer who was in stasis, and a GM she thinks she can align with.

The cultural value of taking care of users, not damaging them.

Also, using goals for good.

* Possible Topics
** Estimates/increments/milestones
** Building trust/alignment/rapport
** Advocating for important technical work

* Ice Cream

She loves White Mountain at Boston College -- a bit rundown, could use a coat of paint. Likes their ice cream a lot. Black raspberry chip, cookie dough w/ strong vanilla, little chocolate chips, they don't skimp

her fave black raspberry chip -- Gracie's in Somerville. Bubbling Brook in Westwood -- amazing black raspberry chip.
