* Email <2025-09-12 Fri>

** My response
Ryan,

I totally understand what you're saying, and honestly, you're in a tricky situation.

I would summarize as:

 - Your Head of Product (also GM?) has a different understanding of the product function than you do

 - She's not currently experiencing much in the way of obvious pains because of this

 - But that's true because you, Ryan, are actually doing a lot of the product function

 - But because you're not working directly with her on product things, it's not possible to even do the product function *well* (see game of telephone, etc).

I think there are maybe two key questions:

 - How "satisfied" is the Head of Product with the status quo?

 - Is the current situation bad enough for you, that you might seriously consider leaving your job?

I'm not recommending you doing so, but it's a key thing to think about.

If the Head of Product is mostly satisfied with how things work now, but you're growing more and more frustrated, you could run the game plan something as follows:

 - Pitch the increment to the Head of Product, not to your peer

 - Explicitly tell her that you think there's a different way for the PM role to work

   And that way of working will give her something she's not getting now (faster execution, more ideas explored, leverage, etc).

   But put the idea of changing her "interface" with product, directly on the table

   You can potentially create some urgency with some of the slowdowns due to game of telephone, etc.

 - Tell her that you'd like to explore working in a new way for a period of time (that will end with her decision, etc)

 - Tell her that, during this time, you, Ryan, will *temporarily* step fully into this new version of the product role, but you would want to "bring your peer along"

   This requires some nuance. You want to position this as something which isn't just directly undercutting your peer. Maybe you can lean on the fact that he has another responsibility -- so you're saying "Just for now, what if I play the lead, but keep him fully in the loop".

   More deeply, a key problem is that it's not clear if your peer can or wants to work in this new way.

   I suspect the only way things can change is if the Head of Product can *feel* how much better the new way is, and then be willing to push your peer to develop (and be ready to move on from them, if they can't).

   That's what I'm trying to work backwards from. I realize it may be an outside shot, but it's sort of the only real way I can see a change happening.

   If she's willing to do that, you can help her. If she's not willing to do that, there's no reason for your peer to change.

 - If you can them "earn a win", where she *feels* how much better things could be, you could then put on the table "I'm willing to help coach up my peer, if you, as their boss, direct them to learn this." And, depending on how frustrated you are, you could also say it as "I want to work as a product-minded engineer, not an actual product manager. I really want to understand how we can change things, so that's what I'm doing."

D



** His Email
Hey Dan,

I have to admit I haven't made any moves on it. Partially because teams have been a bit in flux and I wasn't quite sure how they were going to shake out. But I've also struggled to find the right incremental change to suggest - I'm finding that I'm not 100% confident in the problem or in what I would suggest is the solution.

Our original premise was that the Head of Product plays too active of a role in all product decisions, and that the Product Manager on my team isn't able to freely execute. They end up as a middle-man, and I deal with the various challenges that come with that such as not getting a clear vision to help me plan, having some information feel like a game of telephone, having to react as product decisions change or weren't fully communicated, etc. So the takeaway was finding a way to pitch an incremental change where the Head of Product lets us run more freely in order to solve their strategic intent (building new products quickly) and alleviate their fears (moving too slowly, not being able to vet ideas quickly enough).

As I thought through this, I got stuck on a couple fears/concerns:

 - I'm not confident that the PM is ready for more responsibility, for a couple reasons - they are new to the role, they actually (confusingly) have another non-PM role on another team that they balance along with this one. I'm not always confident that they know what a PM should be doing that they aren't.
 - I think the win that I really want is for the PM to learn how to step up and take more ownership, but I'm sure how to make that happen. I'm pitching this idea to their boss, but how do I know that I have buy-in from the PM? Maybe they are okay with how things are? They might not feel the pain that I feel. It feels like I need to actually pitch this idea to them first.
 - I worry that if the PM isn't really ready for this, then I end up carrying some of the weight (I already feel like I'm doing this a bit; I'm definitely doing some typical PM work in addition to my engineer role.) It sounds like this is the intent of your "clear the decks and stack the deck", but I worry that's the wrong strategy here. I don't actually want to do more of this work - I want to enable the PM to do more of the work. And if I carry more of that weight then the test might "succeed", but the goal won't.

What do you think? Am I missing the mark in any of this?

* Intro / Purpose
For me to learn from you, and maybe see if any challenges can be helped by the ideas I'm working on.

Time check: 45 minutes?

Theme: challenges w/ stakeholders, maybe more broadly -- how to create value, solve business problems.

My background -- spent a long time building, the move to product, back to building, then leading and managing, over both. Love the intersection of the two.
* Good/Bad

* Context
** Where do you work
BookBub -- based in Cambridge.

** What is your team
He's an engineer, he works on the "read worthy" team -- built a new product, called read worthy, for people who like buzzy, new full price books. The big publishers are eager to get more eye balls on that.

Been able to segmen

** Your role
He's the tech lead. Overseeing the technical direction -- he still ships a ton of code. There's one other engineer. He was originally the one engineer, Ryan mentors him, but is not his people manager. 80 percent of his time writing code, thinking long-term

Working closely with product.

He has one PM on the team -- the two ofthem are peers, "Doug". He's a new PM, as of last year. This was his irst time being a product guy, he was head of support.

This means the head of BookBub is also kind of the PM.

His boss is an engineering lead -- before this, she was just another tech lead. A layer above him, above her would be the head of eng.

Does she share any responsibility for the business outcomes in his area -- in theory, but not so much day to day.

** What does your company need to do, in the next 1-2 years?
We need to have enough growth so you can exit.

What does growth mean -- can be user growth, and users buying books (book value), how many dollars of books in sales they can grow.

** How does your team fit into that?
his team has become a spin up new products team -- read worthy was one example. Other ideas are becoming, how could we access other readers. Different segmentations.

His core success, at the moment, is how can he move fast and build ideas, so they can test them out. Ideas are coming from the head of the company.

** How long has he been working as an engineer
15 years

** What is frustrating about your job?
He'd suspect the third one, he's had pretty good success -- suggesting projects and getting them done.

They don't do a lot of estimating and timelines, they don't do them. So when they do have one it is a problem.

More the second one.

He's found succes in his role -- he can step across the line into product pretty well. He deeplys understands it, can step across that, into the product role.

That's been good, but it's created problems where he needs more detail out of stakeholder, but he can't get them to engage with the nuance.

He's missing the back and forth, the thoroughness at the product level.

Josh is not in the mix, it's more Doug and Katie, the head of bookbub product. But this is where stakeholder stuff gets complex. And if he doesn't know the expectations of Doug.

What has he tried -- has had some luck in asking Doug for deliverables. Identified a project for the other engineer to run

What he really wants is active thought partnership, and ownership. What are people responsible for understanding well enough.

Katie -- what is the bad ones, that's tricky. I'm not sure what she's even afraid of.

If things weren't delivering on time and without issues -- the bad would be. The new idea doesn't pay off. Don't find out soon enough that the ideas don't work. Or they overestimate the value early on.

He does worry that they don't validate things quite enough -- he worries that they jump into ideas without validating. A lot of their bets have paid off, but that tees them up.

Good = launching early tests, and doing them quickly.

The outcomes of rolling out a product aligns with early signal they're getting.

Going to Nova Scotia for 1.5 weeks, call after that.



* Possible Topics
** Estimates/increments/milestones
** Building trust/alignment/rapport
** Advocating for important technical work
