* Intro / Purpose
For me to learn from you, and maybe see if any challenges can be helped by the ideas I'm working on.

Time check: 45 minutes?

Theme: challenges w/ stakeholders, maybe more broadly -- how to create value, solve business problems.

My background -- spent a long time building, the move to product, back to building, then leading and managing, over both. Love the intersection of the two.
* Good/Bad

* Context
** Where do you work
BookBub -- based in Cambridge.

** What is your team
He's an engineer, he works on the "read worthy" team -- built a new product, called read worthy, for people who like buzzy, new full price books. The big publishers are eager to get more eye balls on that.

Been able to segmen

** Your role
He's the tech lead. Overseeing the technical direction -- he still ships a ton of code. There's one other engineer. He was originally the one engineer, Ryan mentors him, but is not his people manager. 80 percent of his time writing code, thinking long-term

Working closely with product.

He has one PM on the team -- the two ofthem are peers, "Doug". He's a new PM, as of last year. This was his irst time being a product guy, he was head of support.

This means the head of BookBub is also kind of the PM.

His boss is an engineering lead -- before this, she was just another tech lead. A layer above him, above her would be the head of eng.

Does she share any responsibility for the business outcomes in his area -- in theory, but not so much day to day.

** What does your company need to do, in the next 1-2 years?
We need to have enough growth so you can exit.

What does growth mean -- can be user growth, and users buying books (book value), how many dollars of books in sales they can grow.

** How does your team fit into that?
his team has become a spin up new products team -- read worthy was one example. Other ideas are becoming, how could we access other readers. Different segmentations.

His core success, at the moment, is how can he move fast and build ideas, so they can test them out. Ideas are coming from the head of the company.

** How long has he been working as an engineer
15 years

** What is frustrating about your job?
He'd suspect the third one, he's had pretty good success -- suggesting projects and getting them done.

They don't do a lot of estimating and timelines, they don't do them. So when they do have one it is a problem.

More the second one.

He's found succes in his role -- he can step across the line into product pretty well. He deeplys understands it, can step across that, into the product role.

That's been good, but it's created problems where he needs more detail out of stakeholder, but he can't get them to engage with the nuance.

He's missing the back and forth, the thoroughness at the product level.

Josh is not in the mix, it's more Doug and Katie, the head of bookbub product. But this is where stakeholder stuff gets complex. And if he doesn't know the expectations of Doug.

What has he tried -- has had some luck in asking Doug for deliverables. Identified a project for the other engineer to run

What he really wants is active thought partnership, and ownership. What are people responsible for understanding well enough.

Katie -- what is the bad ones, that's tricky. I'm not sure what she's even afraid of.

If things weren't delivering on time and without issues -- the bad would be. The new idea doesn't pay off. Don't find out soon enough that the ideas don't work. Or they overestimate the value early on.

He does worry that they don't validate things quite enough -- he worries that they jump into ideas without validating. A lot of their bets have paid off, but that tees them up.

Good = launching early tests, and doing them quickly.

The outcomes of rolling out a product aligns with early signal they're getting.

Going to Nova Scotia for 1.5 weeks, call after that.



* Possible Topics
** Estimates/increments/milestones
** Building trust/alignment/rapport
** Advocating for important technical work
